#lang rosette
(require rosette/lib/synthax)
(require rosette/lib/angelic)
(require racket/pretty)
(require data/bit-vector)
(require rosette/lib/destruct)
(require rosette/solver/smt/boolector)

(require hydride/utils/bvops)
(require hydride/utils/misc)


(require hydride/ir/hydride/semantics)
(require hydride/ir/hydride/definition)
(require hydride/ir/hydride/length)


(provide (all-defined-out))


;; ================================================================================
;;                                DSL Binder
;; ================================================================================
(define (bind-expr prog env)
 (destruct prog
	[(dim-x id) (dim-x id)]
	[(dim-y id) (dim-y id)]
	[(idx-i id) (idx-i id)]
	[(idx-j id) (idx-j id)]
	[(reg id) (vector-ref-bv env id)]
	[(lit v) (lit v)]
	[(nop v1) (nop (bind-expr v1 env))]
	[(idx-add i1 i2) (idx-add i1 i2)]
	[(idx-mul i1 i2) (idx-mul i1 i2)]
	[ (vector-two-input-swizzle_dsl v0 v1 num_2 prec_i_o num_4 num_5 num_6 num_7 num_8)
		(vector-two-input-swizzle_dsl (bind-expr v0 env) (bind-expr v1 env) (bind-expr num_2 env) 
		 (bind-expr prec_i_o env) (bind-expr num_4 env) (bind-expr num_5 env) 
		 (bind-expr num_6 env) (bind-expr num_7 env) (bind-expr num_8 env))
	]
	[ (interleave-vectors_dsl v0 v1 size_i_o prec_i_o)
		(interleave-vectors_dsl (bind-expr v0 env) (bind-expr v1 env) (bind-expr size_i_o env) 
		 (bind-expr prec_i_o env))
	]
	[ (interleave-vector_dsl v0 size_i_o prec_i_o)
		(interleave-vector_dsl (bind-expr v0 env) (bind-expr size_i_o env) (bind-expr prec_i_o env))
	]
	[ (deinterleave-vector_dsl v0 size_i_o prec_i_o)
		(deinterleave-vector_dsl (bind-expr v0 env) (bind-expr size_i_o env) (bind-expr prec_i_o env))
	]
	[ (llvm_shuffle_vectors_dsl v0 v1 num_2 prec_i_o v4 num_5)
		(llvm_shuffle_vectors_dsl (bind-expr v0 env) (bind-expr v1 env) (bind-expr num_2 env) 
		 (bind-expr prec_i_o env) (bind-expr v4 env) (bind-expr num_5 env))
	]
	[ (_mm512_rem_epu32_dsl v0 v1 size_i_o num_3 num_4 num_5 prec_i_o num_7 num_8)
		(_mm512_rem_epu32_dsl (bind-expr v0 env) (bind-expr v1 env) (bind-expr size_i_o env) 
		 (bind-expr num_3 env) (bind-expr num_4 env) (bind-expr num_5 env) 
		 (bind-expr prec_i_o env) (bind-expr num_7 env) (bind-expr num_8 env))
	]
	[ (_mm512_or_epi32_dsl v0 v1 size_i_o num_3 num_4 num_5 prec_i_o num_7)
		(_mm512_or_epi32_dsl (bind-expr v0 env) (bind-expr v1 env) (bind-expr size_i_o env) 
		 (bind-expr num_3 env) (bind-expr num_4 env) (bind-expr num_5 env) 
		 (bind-expr prec_i_o env) (bind-expr num_7 env))
	]
	[ (_mm256_mask_min_epi8_dsl v0 vc_1 v2 v3 v4 size_i_o num_6 num_7 num_8 prec_i_o num_10 num_11 num_12 num_13)
		(_mm256_mask_min_epi8_dsl (bind-expr v0 env) (bind-expr vc_1 env) (bind-expr v2 env) 
		 (bind-expr v3 env) (bind-expr v4 env) (bind-expr size_i_o env) 
		 (bind-expr num_6 env) (bind-expr num_7 env) (bind-expr num_8 env) 
		 (bind-expr prec_i_o env) (bind-expr num_10 env) (bind-expr num_11 env) 
		 (bind-expr num_12 env) (bind-expr num_13 env))
	]
	[ (_mm256_xor_epi32_dsl v0 v1 size_i_o num_3 num_4 num_5 prec_i_o num_7)
		(_mm256_xor_epi32_dsl (bind-expr v0 env) (bind-expr v1 env) (bind-expr size_i_o env) 
		 (bind-expr num_3 env) (bind-expr num_4 env) (bind-expr num_5 env) 
		 (bind-expr prec_i_o env) (bind-expr num_7 env))
	]
	[ (_mm_add_si64_dsl v0 v1 size_i_o num_3 num_4 num_5 prec_i_o num_7 num_8 num_9)
		(_mm_add_si64_dsl (bind-expr v0 env) (bind-expr v1 env) (bind-expr size_i_o env) 
		 (bind-expr num_3 env) (bind-expr num_4 env) (bind-expr num_5 env) 
		 (bind-expr prec_i_o env) (bind-expr num_7 env) (bind-expr num_8 env) 
		 (bind-expr num_9 env))
	]
	[ (_m_packssdw_dsl v0 v1 size_i_o num_3 num_4 num_5 num_6 num_7 num_8 prec_o num_10 num_11 num_12 num_13 prec_i num_15 num_16 num_17)
		(_m_packssdw_dsl (bind-expr v0 env) (bind-expr v1 env) (bind-expr size_i_o env) 
		 (bind-expr num_3 env) (bind-expr num_4 env) (bind-expr num_5 env) 
		 (bind-expr num_6 env) (bind-expr num_7 env) (bind-expr num_8 env) 
		 (bind-expr prec_o env) (bind-expr num_10 env) (bind-expr num_11 env) 
		 (bind-expr num_12 env) (bind-expr num_13 env) (bind-expr prec_i env) 
		 (bind-expr num_15 env) (bind-expr num_16 env) (bind-expr num_17 env))
	]
	[ (_mm512_maskz_packus_epi32_dsl v0 vc_1 vc_2 v3 v4 num_5 num_6 num_7 num_8 num_9 num_10 num_11 num_12 size_i_o num_14 num_15 num_16 prec_i_o num_18 num_19 num_20 num_21 num_22 num_23 num_24 num_25 num_26 num_27)
		(_mm512_maskz_packus_epi32_dsl (bind-expr v0 env) (bind-expr vc_1 env) (bind-expr vc_2 env) 
		 (bind-expr v3 env) (bind-expr v4 env) (bind-expr num_5 env) 
		 (bind-expr num_6 env) (bind-expr num_7 env) (bind-expr num_8 env) 
		 (bind-expr num_9 env) (bind-expr num_10 env) (bind-expr num_11 env) 
		 (bind-expr num_12 env) (bind-expr size_i_o env) (bind-expr num_14 env) 
		 (bind-expr num_15 env) (bind-expr num_16 env) (bind-expr prec_i_o env) 
		 (bind-expr num_18 env) (bind-expr num_19 env) (bind-expr num_20 env) 
		 (bind-expr num_21 env) (bind-expr num_22 env) (bind-expr num_23 env) 
		 (bind-expr num_24 env) (bind-expr num_25 env) (bind-expr num_26 env) 
		 (bind-expr num_27 env))
	]
	[ (_mm256_xor_si256_dsl v0 v1 size_i_o num_3 num_4 num_5 prec_i_o num_7 num_8)
		(_mm256_xor_si256_dsl (bind-expr v0 env) (bind-expr v1 env) (bind-expr size_i_o env) 
		 (bind-expr num_3 env) (bind-expr num_4 env) (bind-expr num_5 env) 
		 (bind-expr prec_i_o env) (bind-expr num_7 env) (bind-expr num_8 env))
	]
	[ (_mm_rolv_epi32_dsl vc_0 vc_1 v2 v3 size_i_o num_5 num_6 num_7 prec_i_o num_9 num_10)
		(_mm_rolv_epi32_dsl (bind-expr vc_0 env) (bind-expr vc_1 env) (bind-expr v2 env) 
		 (bind-expr v3 env) (bind-expr size_i_o env) (bind-expr num_5 env) 
		 (bind-expr num_6 env) (bind-expr num_7 env) (bind-expr prec_i_o env) 
		 (bind-expr num_9 env) (bind-expr num_10 env))
	]
	[ (_mm_maskz_srl_epi32_dsl v0 v1 vc_2 vc_3 vc_4 vc_5 v6 size_i_o num_8 num_9 num_10 num_11 num_12 num_13 num_14 num_15 num_16 prec_i_o num_18 num_19 num_20 num_21)
		(_mm_maskz_srl_epi32_dsl (bind-expr v0 env) (bind-expr v1 env) (bind-expr vc_2 env) 
		 (bind-expr vc_3 env) (bind-expr vc_4 env) (bind-expr vc_5 env) 
		 (bind-expr v6 env) (bind-expr size_i_o env) (bind-expr num_8 env) 
		 (bind-expr num_9 env) (bind-expr num_10 env) (bind-expr num_11 env) 
		 (bind-expr num_12 env) (bind-expr num_13 env) (bind-expr num_14 env) 
		 (bind-expr num_15 env) (bind-expr num_16 env) (bind-expr prec_i_o env) 
		 (bind-expr num_18 env) (bind-expr num_19 env) (bind-expr num_20 env) 
		 (bind-expr num_21 env))
	]
	[ (_mm512_maskz_avg_epu16_dsl v0 vc_1 vc_2 vc_3 vc_4 v5 v6 size_i_o num_8 num_9 num_10 prec_i_o num_12 num_13 num_14 num_15 num_16)
		(_mm512_maskz_avg_epu16_dsl (bind-expr v0 env) (bind-expr vc_1 env) (bind-expr vc_2 env) 
		 (bind-expr vc_3 env) (bind-expr vc_4 env) (bind-expr v5 env) 
		 (bind-expr v6 env) (bind-expr size_i_o env) (bind-expr num_8 env) 
		 (bind-expr num_9 env) (bind-expr num_10 env) (bind-expr prec_i_o env) 
		 (bind-expr num_12 env) (bind-expr num_13 env) (bind-expr num_14 env) 
		 (bind-expr num_15 env) (bind-expr num_16 env))
	]
	[ (_mm512_mask_rolv_epi32_dsl v0 vc_1 vc_2 vc_3 v4 v5 v6 size_i_o num_8 num_9 num_10 prec_i_o num_12 num_13 num_14 num_15)
		(_mm512_mask_rolv_epi32_dsl (bind-expr v0 env) (bind-expr vc_1 env) (bind-expr vc_2 env) 
		 (bind-expr vc_3 env) (bind-expr v4 env) (bind-expr v5 env) 
		 (bind-expr v6 env) (bind-expr size_i_o env) (bind-expr num_8 env) 
		 (bind-expr num_9 env) (bind-expr num_10 env) (bind-expr prec_i_o env) 
		 (bind-expr num_12 env) (bind-expr num_13 env) (bind-expr num_14 env) 
		 (bind-expr num_15 env))
	]
	[ (_mm_hadd_pi16_dsl v0 v1 size_i_o num_3 num_4 num_5 num_6 num_7 num_8 prec_i_o num_10 num_11 num_12 num_13 num_14 num_15 num_16 num_17)
		(_mm_hadd_pi16_dsl (bind-expr v0 env) (bind-expr v1 env) (bind-expr size_i_o env) 
		 (bind-expr num_3 env) (bind-expr num_4 env) (bind-expr num_5 env) 
		 (bind-expr num_6 env) (bind-expr num_7 env) (bind-expr num_8 env) 
		 (bind-expr prec_i_o env) (bind-expr num_10 env) (bind-expr num_11 env) 
		 (bind-expr num_12 env) (bind-expr num_13 env) (bind-expr num_14 env) 
		 (bind-expr num_15 env) (bind-expr num_16 env) (bind-expr num_17 env))
	]
	[ (_mm512_extracti64x4_epi64_dsl vc_0 vc_1 v2 v3 size_o num_5 num_6 num_7 prec_i_o num_9 num_10 num_11 num_12 num_13 num_14)
		(_mm512_extracti64x4_epi64_dsl (bind-expr vc_0 env) (bind-expr vc_1 env) (bind-expr v2 env) 
		 (bind-expr v3 env) (bind-expr size_o env) (bind-expr num_5 env) 
		 (bind-expr num_6 env) (bind-expr num_7 env) (bind-expr prec_i_o env) 
		 (bind-expr num_9 env) (bind-expr num_10 env) (bind-expr num_11 env) 
		 (bind-expr num_12 env) (bind-expr num_13 env) (bind-expr num_14 env))
	]
	[ (_mm512_unpacklo_epi64_dsl v0 v1 size_i_o num_3 num_4 num_5 prec_i_o num_7 num_8 num_9 num_10 num_11)
		(_mm512_unpacklo_epi64_dsl (bind-expr v0 env) (bind-expr v1 env) (bind-expr size_i_o env) 
		 (bind-expr num_3 env) (bind-expr num_4 env) (bind-expr num_5 env) 
		 (bind-expr prec_i_o env) (bind-expr num_7 env) (bind-expr num_8 env) 
		 (bind-expr num_9 env) (bind-expr num_10 env) (bind-expr num_11 env))
	]
	[ (_mm256_cvtepi64_epi32_dsl v0 size_i_o num_2 num_3 num_4 prec_o prec_i num_7 num_8)
		(_mm256_cvtepi64_epi32_dsl (bind-expr v0 env) (bind-expr size_i_o env) (bind-expr num_2 env) 
		 (bind-expr num_3 env) (bind-expr num_4 env) (bind-expr prec_o env) 
		 (bind-expr prec_i env) (bind-expr num_7 env) (bind-expr num_8 env))
	]
	[ (_mm256_max_epu64_dsl v0 v1 size_i_o num_3 num_4 num_5 prec_i_o num_7 num_8)
		(_mm256_max_epu64_dsl (bind-expr v0 env) (bind-expr v1 env) (bind-expr size_i_o env) 
		 (bind-expr num_3 env) (bind-expr num_4 env) (bind-expr num_5 env) 
		 (bind-expr prec_i_o env) (bind-expr num_7 env) (bind-expr num_8 env))
	]
	[ (_mm_broadcastmb_epi64_dsl v0 size_o num_2 num_3 num_4 prec_i prec_o num_7 num_8 num_9 num_10)
		(_mm_broadcastmb_epi64_dsl (bind-expr v0 env) (bind-expr size_o env) (bind-expr num_2 env) 
		 (bind-expr num_3 env) (bind-expr num_4 env) (bind-expr prec_i env) 
		 (bind-expr prec_o env) (bind-expr num_7 env) (bind-expr num_8 env) 
		 (bind-expr num_9 env) (bind-expr num_10 env))
	]
	[ (_mm_unpacklo_pi32_dsl v0 v1 size_i_o num_3 num_4 num_5 prec_i_o num_7 num_8 num_9)
		(_mm_unpacklo_pi32_dsl (bind-expr v0 env) (bind-expr v1 env) (bind-expr size_i_o env) 
		 (bind-expr num_3 env) (bind-expr num_4 env) (bind-expr num_5 env) 
		 (bind-expr prec_i_o env) (bind-expr num_7 env) (bind-expr num_8 env) 
		 (bind-expr num_9 env))
	]
	[ (_mm512_srav_epi16_dsl v0 vc_1 v2 vc_3 vc_4 vc_5 size_i_o num_7 num_8 num_9 num_10 num_11 num_12 prec_i_o num_14 num_15)
		(_mm512_srav_epi16_dsl (bind-expr v0 env) (bind-expr vc_1 env) (bind-expr v2 env) 
		 (bind-expr vc_3 env) (bind-expr vc_4 env) (bind-expr vc_5 env) 
		 (bind-expr size_i_o env) (bind-expr num_7 env) (bind-expr num_8 env) 
		 (bind-expr num_9 env) (bind-expr num_10 env) (bind-expr num_11 env) 
		 (bind-expr num_12 env) (bind-expr prec_i_o env) (bind-expr num_14 env) 
		 (bind-expr num_15 env))
	]
	[ (_mm_unpacklo_pi8_dsl v0 v1 size_i_o num_3 num_4 num_5 prec_i_o num_7 num_8 num_9 num_10)
		(_mm_unpacklo_pi8_dsl (bind-expr v0 env) (bind-expr v1 env) (bind-expr size_i_o env) 
		 (bind-expr num_3 env) (bind-expr num_4 env) (bind-expr num_5 env) 
		 (bind-expr prec_i_o env) (bind-expr num_7 env) (bind-expr num_8 env) 
		 (bind-expr num_9 env) (bind-expr num_10 env))
	]
	[ (_mm_mask_mul_epu32_dsl vc_0 v1 v2 v3 v4 size_i_o num_6 num_7 num_8 num_9 num_10 num_11 prec_i_o num_13 num_14 num_15 num_16 num_17)
		(_mm_mask_mul_epu32_dsl (bind-expr vc_0 env) (bind-expr v1 env) (bind-expr v2 env) 
		 (bind-expr v3 env) (bind-expr v4 env) (bind-expr size_i_o env) 
		 (bind-expr num_6 env) (bind-expr num_7 env) (bind-expr num_8 env) 
		 (bind-expr num_9 env) (bind-expr num_10 env) (bind-expr num_11 env) 
		 (bind-expr prec_i_o env) (bind-expr num_13 env) (bind-expr num_14 env) 
		 (bind-expr num_15 env) (bind-expr num_16 env) (bind-expr num_17 env))
	]
	[ (_mm256_mul_epi32_dsl v0 v1 size_i_o num_3 num_4 num_5 prec_i prec_o num_8 num_9 num_10 num_11)
		(_mm256_mul_epi32_dsl (bind-expr v0 env) (bind-expr v1 env) (bind-expr size_i_o env) 
		 (bind-expr num_3 env) (bind-expr num_4 env) (bind-expr num_5 env) 
		 (bind-expr prec_i env) (bind-expr prec_o env) (bind-expr num_8 env) 
		 (bind-expr num_9 env) (bind-expr num_10 env) (bind-expr num_11 env))
	]
	[ (_mm256_mask_testn_epi32_mask_dsl vc_0 v1 vc_2 vc_3 vc_4 v5 vc_6 v7 size_i_o num_9 num_10 num_11 prec_o num_13 prec_i num_15 num_16)
		(_mm256_mask_testn_epi32_mask_dsl (bind-expr vc_0 env) (bind-expr v1 env) (bind-expr vc_2 env) 
		 (bind-expr vc_3 env) (bind-expr vc_4 env) (bind-expr v5 env) 
		 (bind-expr vc_6 env) (bind-expr v7 env) (bind-expr size_i_o env) 
		 (bind-expr num_9 env) (bind-expr num_10 env) (bind-expr num_11 env) 
		 (bind-expr prec_o env) (bind-expr num_13 env) (bind-expr prec_i env) 
		 (bind-expr num_15 env) (bind-expr num_16 env))
	]
	[ (_mm_rorv_epi32_dsl vc_0 vc_1 v2 v3 size_i_o num_5 num_6 num_7 prec_i_o num_9 num_10)
		(_mm_rorv_epi32_dsl (bind-expr vc_0 env) (bind-expr vc_1 env) (bind-expr v2 env) 
		 (bind-expr v3 env) (bind-expr size_i_o env) (bind-expr num_5 env) 
		 (bind-expr num_6 env) (bind-expr num_7 env) (bind-expr prec_i_o env) 
		 (bind-expr num_9 env) (bind-expr num_10 env))
	]
	[ (_mm512_mulhi_epu16_dsl v0 v1 size_i_o num_3 num_4 num_5 prec_i_o num_7 num_8 num_9 num_10 num_11)
		(_mm512_mulhi_epu16_dsl (bind-expr v0 env) (bind-expr v1 env) (bind-expr size_i_o env) 
		 (bind-expr num_3 env) (bind-expr num_4 env) (bind-expr num_5 env) 
		 (bind-expr prec_i_o env) (bind-expr num_7 env) (bind-expr num_8 env) 
		 (bind-expr num_9 env) (bind-expr num_10 env) (bind-expr num_11 env))
	]
	[ (_mm_mul_su32_dsl v0 v1 size_i_o num_3 num_4 num_5 prec_i prec_o num_8 num_9 num_10 num_11)
		(_mm_mul_su32_dsl (bind-expr v0 env) (bind-expr v1 env) (bind-expr size_i_o env) 
		 (bind-expr num_3 env) (bind-expr num_4 env) (bind-expr num_5 env) 
		 (bind-expr prec_i env) (bind-expr prec_o env) (bind-expr num_8 env) 
		 (bind-expr num_9 env) (bind-expr num_10 env) (bind-expr num_11 env))
	]
	[ (_mm_broadcast_i32x2_dsl v0 size_i_o num_2 num_3 num_4 prec_i_o num_6 num_7 num_8)
		(_mm_broadcast_i32x2_dsl (bind-expr v0 env) (bind-expr size_i_o env) (bind-expr num_2 env) 
		 (bind-expr num_3 env) (bind-expr num_4 env) (bind-expr prec_i_o env) 
		 (bind-expr num_6 env) (bind-expr num_7 env) (bind-expr num_8 env))
	]
	[ (_mm_mask_ror_epi32_dsl vc_0 v1 vc_2 vc_3 v4 v5 v6 size_i_o num_8 num_9 num_10 num_11 num_12 num_13 prec_i_o num_15 num_16 num_17 num_18 num_19 num_20 num_21)
		(_mm_mask_ror_epi32_dsl (bind-expr vc_0 env) (bind-expr v1 env) (bind-expr vc_2 env) 
		 (bind-expr vc_3 env) (bind-expr v4 env) (bind-expr v5 env) 
		 (bind-expr v6 env) (bind-expr size_i_o env) (bind-expr num_8 env) 
		 (bind-expr num_9 env) (bind-expr num_10 env) (bind-expr num_11 env) 
		 (bind-expr num_12 env) (bind-expr num_13 env) (bind-expr prec_i_o env) 
		 (bind-expr num_15 env) (bind-expr num_16 env) (bind-expr num_17 env) 
		 (bind-expr num_18 env) (bind-expr num_19 env) (bind-expr num_20 env) 
		 (bind-expr num_21 env))
	]
	[ (_mm_mask_rol_epi32_dsl vc_0 v1 v2 vc_3 vc_4 v5 v6 size_i_o num_8 num_9 num_10 num_11 num_12 num_13 prec_i_o num_15 num_16 num_17 num_18 num_19 num_20 num_21)
		(_mm_mask_rol_epi32_dsl (bind-expr vc_0 env) (bind-expr v1 env) (bind-expr v2 env) 
		 (bind-expr vc_3 env) (bind-expr vc_4 env) (bind-expr v5 env) 
		 (bind-expr v6 env) (bind-expr size_i_o env) (bind-expr num_8 env) 
		 (bind-expr num_9 env) (bind-expr num_10 env) (bind-expr num_11 env) 
		 (bind-expr num_12 env) (bind-expr num_13 env) (bind-expr prec_i_o env) 
		 (bind-expr num_15 env) (bind-expr num_16 env) (bind-expr num_17 env) 
		 (bind-expr num_18 env) (bind-expr num_19 env) (bind-expr num_20 env) 
		 (bind-expr num_21 env))
	]
	[ (_mm_hadd_pi32_dsl v0 v1 size_i_o num_3 num_4 num_5 prec_i_o num_7 num_8 num_9 num_10 num_11)
		(_mm_hadd_pi32_dsl (bind-expr v0 env) (bind-expr v1 env) (bind-expr size_i_o env) 
		 (bind-expr num_3 env) (bind-expr num_4 env) (bind-expr num_5 env) 
		 (bind-expr prec_i_o env) (bind-expr num_7 env) (bind-expr num_8 env) 
		 (bind-expr num_9 env) (bind-expr num_10 env) (bind-expr num_11 env))
	]
	[ (_mm256_mask_cmpeq_epu8_mask_dsl v0 vc_1 v2 v3 vc_4 vc_5 vc_6 size_i_o num_8 num_9 num_10 prec_o num_12 prec_i num_14 num_15)
		(_mm256_mask_cmpeq_epu8_mask_dsl (bind-expr v0 env) (bind-expr vc_1 env) (bind-expr v2 env) 
		 (bind-expr v3 env) (bind-expr vc_4 env) (bind-expr vc_5 env) 
		 (bind-expr vc_6 env) (bind-expr size_i_o env) (bind-expr num_8 env) 
		 (bind-expr num_9 env) (bind-expr num_10 env) (bind-expr prec_o env) 
		 (bind-expr num_12 env) (bind-expr prec_i env) (bind-expr num_14 env) 
		 (bind-expr num_15 env))
	]
	[ (_mm_movemask_epi8_dsl v0 size_o num_2 num_3 num_4 prec_o num_6 num_7 num_8)
		(_mm_movemask_epi8_dsl (bind-expr v0 env) (bind-expr size_o env) (bind-expr num_2 env) 
		 (bind-expr num_3 env) (bind-expr num_4 env) (bind-expr prec_o env) 
		 (bind-expr num_6 env) (bind-expr num_7 env) (bind-expr num_8 env))
	]
	[ (_mm512_sll_epi64_dsl v0 vc_1 vc_2 v3 size_i_o num_5 num_6 num_7 num_8 num_9 num_10 num_11 prec_i_o num_13 num_14)
		(_mm512_sll_epi64_dsl (bind-expr v0 env) (bind-expr vc_1 env) (bind-expr vc_2 env) 
		 (bind-expr v3 env) (bind-expr size_i_o env) (bind-expr num_5 env) 
		 (bind-expr num_6 env) (bind-expr num_7 env) (bind-expr num_8 env) 
		 (bind-expr num_9 env) (bind-expr num_10 env) (bind-expr num_11 env) 
		 (bind-expr prec_i_o env) (bind-expr num_13 env) (bind-expr num_14 env))
	]
	[ (_mm_sign_pi16_dsl vc_0 v1 vc_2 vc_3 v4 size_i_o num_6 num_7 num_8 num_9 num_10 num_11 prec_i_o num_13 num_14)
		(_mm_sign_pi16_dsl (bind-expr vc_0 env) (bind-expr v1 env) (bind-expr vc_2 env) 
		 (bind-expr vc_3 env) (bind-expr v4 env) (bind-expr size_i_o env) 
		 (bind-expr num_6 env) (bind-expr num_7 env) (bind-expr num_8 env) 
		 (bind-expr num_9 env) (bind-expr num_10 env) (bind-expr num_11 env) 
		 (bind-expr prec_i_o env) (bind-expr num_13 env) (bind-expr num_14 env))
	]
	[ (_mm512_mask_sll_epi64_dsl v0 v1 vc_2 v3 vc_4 vc_5 v6 size_i_o num_8 num_9 num_10 num_11 num_12 num_13 num_14 num_15 num_16 prec_i_o num_18 num_19)
		(_mm512_mask_sll_epi64_dsl (bind-expr v0 env) (bind-expr v1 env) (bind-expr vc_2 env) 
		 (bind-expr v3 env) (bind-expr vc_4 env) (bind-expr vc_5 env) 
		 (bind-expr v6 env) (bind-expr size_i_o env) (bind-expr num_8 env) 
		 (bind-expr num_9 env) (bind-expr num_10 env) (bind-expr num_11 env) 
		 (bind-expr num_12 env) (bind-expr num_13 env) (bind-expr num_14 env) 
		 (bind-expr num_15 env) (bind-expr num_16 env) (bind-expr prec_i_o env) 
		 (bind-expr num_18 env) (bind-expr num_19 env))
	]
	[ (_mm_add_pi8_dsl v0 v1 size_i_o num_3 num_4 num_5 prec_i_o num_7 num_8)
		(_mm_add_pi8_dsl (bind-expr v0 env) (bind-expr v1 env) (bind-expr size_i_o env) 
		 (bind-expr num_3 env) (bind-expr num_4 env) (bind-expr num_5 env) 
		 (bind-expr prec_i_o env) (bind-expr num_7 env) (bind-expr num_8 env))
	]
	[ (_mm512_mask_srav_epi32_dsl v0 v1 vc_2 vc_3 vc_4 v5 vc_6 vc_7 v8 size_i_o num_10 num_11 num_12 num_13 num_14 num_15 num_16 num_17 prec_i_o num_19 num_20)
		(_mm512_mask_srav_epi32_dsl (bind-expr v0 env) (bind-expr v1 env) (bind-expr vc_2 env) 
		 (bind-expr vc_3 env) (bind-expr vc_4 env) (bind-expr v5 env) 
		 (bind-expr vc_6 env) (bind-expr vc_7 env) (bind-expr v8 env) 
		 (bind-expr size_i_o env) (bind-expr num_10 env) (bind-expr num_11 env) 
		 (bind-expr num_12 env) (bind-expr num_13 env) (bind-expr num_14 env) 
		 (bind-expr num_15 env) (bind-expr num_16 env) (bind-expr num_17 env) 
		 (bind-expr prec_i_o env) (bind-expr num_19 env) (bind-expr num_20 env))
	]
	[ (_mm_hsub_pi32_dsl v0 v1 size_i_o num_3 num_4 num_5 prec_i_o num_7 num_8 num_9 num_10 num_11)
		(_mm_hsub_pi32_dsl (bind-expr v0 env) (bind-expr v1 env) (bind-expr size_i_o env) 
		 (bind-expr num_3 env) (bind-expr num_4 env) (bind-expr num_5 env) 
		 (bind-expr prec_i_o env) (bind-expr num_7 env) (bind-expr num_8 env) 
		 (bind-expr num_9 env) (bind-expr num_10 env) (bind-expr num_11 env))
	]
	[ (_mm256_mulhrs_epi16_dsl vc_0 vc_1 v2 v3 size_i_o num_5 num_6 num_7 prec_i_o num_9 num_10 num_11 num_12 num_13 num_14)
		(_mm256_mulhrs_epi16_dsl (bind-expr vc_0 env) (bind-expr vc_1 env) (bind-expr v2 env) 
		 (bind-expr v3 env) (bind-expr size_i_o env) (bind-expr num_5 env) 
		 (bind-expr num_6 env) (bind-expr num_7 env) (bind-expr prec_i_o env) 
		 (bind-expr num_9 env) (bind-expr num_10 env) (bind-expr num_11 env) 
		 (bind-expr num_12 env) (bind-expr num_13 env) (bind-expr num_14 env))
	]
	[ (_mm256_mask_madd52hi_epu64_dsl vc_0 v1 v2 v3 v4 size_i_o num_6 num_7 num_8 num_9 num_10 num_11 prec_i_o num_13 num_14 num_15 num_16 num_17 num_18 num_19 num_20 num_21 num_22)
		(_mm256_mask_madd52hi_epu64_dsl (bind-expr vc_0 env) (bind-expr v1 env) (bind-expr v2 env) 
		 (bind-expr v3 env) (bind-expr v4 env) (bind-expr size_i_o env) 
		 (bind-expr num_6 env) (bind-expr num_7 env) (bind-expr num_8 env) 
		 (bind-expr num_9 env) (bind-expr num_10 env) (bind-expr num_11 env) 
		 (bind-expr prec_i_o env) (bind-expr num_13 env) (bind-expr num_14 env) 
		 (bind-expr num_15 env) (bind-expr num_16 env) (bind-expr num_17 env) 
		 (bind-expr num_18 env) (bind-expr num_19 env) (bind-expr num_20 env) 
		 (bind-expr num_21 env) (bind-expr num_22 env))
	]
	[ (_mm512_mask_extracti64x4_epi64_dsl v0 vc_1 vc_2 v3 vc_4 v5 v6 num_7 num_8 num_9 num_10 num_11 size_i_o num_13 num_14 num_15 prec_i_o num_17 num_18 num_19 num_20 num_21 num_22 num_23 num_24 num_25)
		(_mm512_mask_extracti64x4_epi64_dsl (bind-expr v0 env) (bind-expr vc_1 env) (bind-expr vc_2 env) 
		 (bind-expr v3 env) (bind-expr vc_4 env) (bind-expr v5 env) 
		 (bind-expr v6 env) (bind-expr num_7 env) (bind-expr num_8 env) 
		 (bind-expr num_9 env) (bind-expr num_10 env) (bind-expr num_11 env) 
		 (bind-expr size_i_o env) (bind-expr num_13 env) (bind-expr num_14 env) 
		 (bind-expr num_15 env) (bind-expr prec_i_o env) (bind-expr num_17 env) 
		 (bind-expr num_18 env) (bind-expr num_19 env) (bind-expr num_20 env) 
		 (bind-expr num_21 env) (bind-expr num_22 env) (bind-expr num_23 env) 
		 (bind-expr num_24 env) (bind-expr num_25 env))
	]
	[ (_mm512_extracti64x2_epi64_dsl vc_0 v1 vc_2 vc_3 vc_4 v5 size_o num_7 num_8 num_9 prec_i_o num_11 num_12 num_13 num_14 num_15 num_16 num_17 num_18 num_19 num_20 num_21)
		(_mm512_extracti64x2_epi64_dsl (bind-expr vc_0 env) (bind-expr v1 env) (bind-expr vc_2 env) 
		 (bind-expr vc_3 env) (bind-expr vc_4 env) (bind-expr v5 env) 
		 (bind-expr size_o env) (bind-expr num_7 env) (bind-expr num_8 env) 
		 (bind-expr num_9 env) (bind-expr prec_i_o env) (bind-expr num_11 env) 
		 (bind-expr num_12 env) (bind-expr num_13 env) (bind-expr num_14 env) 
		 (bind-expr num_15 env) (bind-expr num_16 env) (bind-expr num_17 env) 
		 (bind-expr num_18 env) (bind-expr num_19 env) (bind-expr num_20 env) 
		 (bind-expr num_21 env))
	]
	[ (_mm512_sra_epi64_dsl v0 vc_1 v2 vc_3 vc_4 vc_5 size_i_o num_7 num_8 num_9 num_10 num_11 num_12 num_13 prec_i_o num_15 num_16 num_17)
		(_mm512_sra_epi64_dsl (bind-expr v0 env) (bind-expr vc_1 env) (bind-expr v2 env) 
		 (bind-expr vc_3 env) (bind-expr vc_4 env) (bind-expr vc_5 env) 
		 (bind-expr size_i_o env) (bind-expr num_7 env) (bind-expr num_8 env) 
		 (bind-expr num_9 env) (bind-expr num_10 env) (bind-expr num_11 env) 
		 (bind-expr num_12 env) (bind-expr num_13 env) (bind-expr prec_i_o env) 
		 (bind-expr num_15 env) (bind-expr num_16 env) (bind-expr num_17 env))
	]
	[ (_mm256_maskz_max_epi32_dsl vc_0 v1 vc_2 v3 v4 size_i_o num_6 num_7 num_8 prec_i_o num_10 num_11 num_12 num_13)
		(_mm256_maskz_max_epi32_dsl (bind-expr vc_0 env) (bind-expr v1 env) (bind-expr vc_2 env) 
		 (bind-expr v3 env) (bind-expr v4 env) (bind-expr size_i_o env) 
		 (bind-expr num_6 env) (bind-expr num_7 env) (bind-expr num_8 env) 
		 (bind-expr prec_i_o env) (bind-expr num_10 env) (bind-expr num_11 env) 
		 (bind-expr num_12 env) (bind-expr num_13 env))
	]
	[ (_mm_abs_epi16_dsl v0 size_i_o num_2 num_3 num_4 prec_i_o num_6)
		(_mm_abs_epi16_dsl (bind-expr v0 env) (bind-expr size_i_o env) (bind-expr num_2 env) 
		 (bind-expr num_3 env) (bind-expr num_4 env) (bind-expr prec_i_o env) 
		 (bind-expr num_6 env))
	]
	[ (_mm512_unpacklo_epi16_dsl v0 v1 size_i_o num_3 num_4 num_5 prec_i_o num_7 num_8 num_9)
		(_mm512_unpacklo_epi16_dsl (bind-expr v0 env) (bind-expr v1 env) (bind-expr size_i_o env) 
		 (bind-expr num_3 env) (bind-expr num_4 env) (bind-expr num_5 env) 
		 (bind-expr prec_i_o env) (bind-expr num_7 env) (bind-expr num_8 env) 
		 (bind-expr num_9 env))
	]
	[ (_mm512_fmadd_epi32_dsl v0 v1 v2 size_i_o num_4 num_5 num_6 prec_i_o num_8 num_9 num_10 num_11 num_12 num_13 num_14)
		(_mm512_fmadd_epi32_dsl (bind-expr v0 env) (bind-expr v1 env) (bind-expr v2 env) 
		 (bind-expr size_i_o env) (bind-expr num_4 env) (bind-expr num_5 env) 
		 (bind-expr num_6 env) (bind-expr prec_i_o env) (bind-expr num_8 env) 
		 (bind-expr num_9 env) (bind-expr num_10 env) (bind-expr num_11 env) 
		 (bind-expr num_12 env) (bind-expr num_13 env) (bind-expr num_14 env))
	]
	[ (_mm_div_epi64_dsl v0 v1 size_i_o num_3 num_4 num_5 prec_i_o num_7 num_8 num_9 num_10 num_11 num_12)
		(_mm_div_epi64_dsl (bind-expr v0 env) (bind-expr v1 env) (bind-expr size_i_o env) 
		 (bind-expr num_3 env) (bind-expr num_4 env) (bind-expr num_5 env) 
		 (bind-expr prec_i_o env) (bind-expr num_7 env) (bind-expr num_8 env) 
		 (bind-expr num_9 env) (bind-expr num_10 env) (bind-expr num_11 env) 
		 (bind-expr num_12 env))
	]
	[ (_mm256_mask_sllv_epi16_dsl v0 v1 vc_2 v3 vc_4 vc_5 v6 size_i_o num_8 num_9 num_10 num_11 num_12 num_13 num_14 num_15 prec_i_o num_17)
		(_mm256_mask_sllv_epi16_dsl (bind-expr v0 env) (bind-expr v1 env) (bind-expr vc_2 env) 
		 (bind-expr v3 env) (bind-expr vc_4 env) (bind-expr vc_5 env) 
		 (bind-expr v6 env) (bind-expr size_i_o env) (bind-expr num_8 env) 
		 (bind-expr num_9 env) (bind-expr num_10 env) (bind-expr num_11 env) 
		 (bind-expr num_12 env) (bind-expr num_13 env) (bind-expr num_14 env) 
		 (bind-expr num_15 env) (bind-expr prec_i_o env) (bind-expr num_17 env))
	]
	[ (_mm256_mask_abs_epi16_dsl v0 vc_1 v2 v3 size_i_o num_5 num_6 num_7 prec_i_o num_9 num_10 num_11)
		(_mm256_mask_abs_epi16_dsl (bind-expr v0 env) (bind-expr vc_1 env) (bind-expr v2 env) 
		 (bind-expr v3 env) (bind-expr size_i_o env) (bind-expr num_5 env) 
		 (bind-expr num_6 env) (bind-expr num_7 env) (bind-expr prec_i_o env) 
		 (bind-expr num_9 env) (bind-expr num_10 env) (bind-expr num_11 env))
	]
	[ (_mm_cmpgt_epi16_dsl vc_0 vc_1 v2 v3 size_i_o num_5 num_6 num_7 prec_i_o num_9 num_10)
		(_mm_cmpgt_epi16_dsl (bind-expr vc_0 env) (bind-expr vc_1 env) (bind-expr v2 env) 
		 (bind-expr v3 env) (bind-expr size_i_o env) (bind-expr num_5 env) 
		 (bind-expr num_6 env) (bind-expr num_7 env) (bind-expr prec_i_o env) 
		 (bind-expr num_9 env) (bind-expr num_10 env))
	]
	[ (_mm256_unpackhi_epi16_dsl v0 v1 size_i_o num_3 num_4 num_5 prec_i_o num_7 num_8 num_9 num_10)
		(_mm256_unpackhi_epi16_dsl (bind-expr v0 env) (bind-expr v1 env) (bind-expr size_i_o env) 
		 (bind-expr num_3 env) (bind-expr num_4 env) (bind-expr num_5 env) 
		 (bind-expr prec_i_o env) (bind-expr num_7 env) (bind-expr num_8 env) 
		 (bind-expr num_9 env) (bind-expr num_10 env))
	]
	[ (_mm_mask_packs_epi16_dsl vc_0 v1 v2 v3 v4 num_5 num_6 num_7 num_8 num_9 num_10 num_11 num_12 size_i_o num_14 num_15 num_16 prec_i_o num_18 num_19 num_20 num_21 num_22 num_23 num_24 num_25 num_26 num_27)
		(_mm_mask_packs_epi16_dsl (bind-expr vc_0 env) (bind-expr v1 env) (bind-expr v2 env) 
		 (bind-expr v3 env) (bind-expr v4 env) (bind-expr num_5 env) 
		 (bind-expr num_6 env) (bind-expr num_7 env) (bind-expr num_8 env) 
		 (bind-expr num_9 env) (bind-expr num_10 env) (bind-expr num_11 env) 
		 (bind-expr num_12 env) (bind-expr size_i_o env) (bind-expr num_14 env) 
		 (bind-expr num_15 env) (bind-expr num_16 env) (bind-expr prec_i_o env) 
		 (bind-expr num_18 env) (bind-expr num_19 env) (bind-expr num_20 env) 
		 (bind-expr num_21 env) (bind-expr num_22 env) (bind-expr num_23 env) 
		 (bind-expr num_24 env) (bind-expr num_25 env) (bind-expr num_26 env) 
		 (bind-expr num_27 env))
	]
	[ (_mm512_maskz_xor_epi32_dsl v0 vc_1 vc_2 v3 v4 size_i_o num_6 num_7 num_8 prec_i_o num_10 num_11 num_12)
		(_mm512_maskz_xor_epi32_dsl (bind-expr v0 env) (bind-expr vc_1 env) (bind-expr vc_2 env) 
		 (bind-expr v3 env) (bind-expr v4 env) (bind-expr size_i_o env) 
		 (bind-expr num_6 env) (bind-expr num_7 env) (bind-expr num_8 env) 
		 (bind-expr prec_i_o env) (bind-expr num_10 env) (bind-expr num_11 env) 
		 (bind-expr num_12 env))
	]
	[ (_mm_mask_sra_epi64_dsl vc_0 v1 v2 vc_3 vc_4 v5 vc_6 vc_7 v8 size_i_o num_10 num_11 num_12 num_13 num_14 num_15 num_16 num_17 num_18 prec_i_o num_20 num_21 num_22)
		(_mm_mask_sra_epi64_dsl (bind-expr vc_0 env) (bind-expr v1 env) (bind-expr v2 env) 
		 (bind-expr vc_3 env) (bind-expr vc_4 env) (bind-expr v5 env) 
		 (bind-expr vc_6 env) (bind-expr vc_7 env) (bind-expr v8 env) 
		 (bind-expr size_i_o env) (bind-expr num_10 env) (bind-expr num_11 env) 
		 (bind-expr num_12 env) (bind-expr num_13 env) (bind-expr num_14 env) 
		 (bind-expr num_15 env) (bind-expr num_16 env) (bind-expr num_17 env) 
		 (bind-expr num_18 env) (bind-expr prec_i_o env) (bind-expr num_20 env) 
		 (bind-expr num_21 env) (bind-expr num_22 env))
	]
	[ (_mm_mask_or_epi64_dsl v0 vc_1 v2 v3 v4 size_i_o num_6 num_7 num_8 prec_i_o num_10 num_11 num_12)
		(_mm_mask_or_epi64_dsl (bind-expr v0 env) (bind-expr vc_1 env) (bind-expr v2 env) 
		 (bind-expr v3 env) (bind-expr v4 env) (bind-expr size_i_o env) 
		 (bind-expr num_6 env) (bind-expr num_7 env) (bind-expr num_8 env) 
		 (bind-expr prec_i_o env) (bind-expr num_10 env) (bind-expr num_11 env) 
		 (bind-expr num_12 env))
	]
	[ (_mm512_cmplt_epi32_mask_dsl vc_0 vc_1 v2 v3 size_i_o num_5 num_6 num_7 prec_o num_9 prec_i num_11 num_12)
		(_mm512_cmplt_epi32_mask_dsl (bind-expr vc_0 env) (bind-expr vc_1 env) (bind-expr v2 env) 
		 (bind-expr v3 env) (bind-expr size_i_o env) (bind-expr num_5 env) 
		 (bind-expr num_6 env) (bind-expr num_7 env) (bind-expr prec_o env) 
		 (bind-expr num_9 env) (bind-expr prec_i env) (bind-expr num_11 env) 
		 (bind-expr num_12 env))
	]
	[ (_mm512_sllv_epi16_dsl v0 vc_1 vc_2 v3 size_i_o num_5 num_6 num_7 num_8 num_9 num_10 prec_i_o num_12)
		(_mm512_sllv_epi16_dsl (bind-expr v0 env) (bind-expr vc_1 env) (bind-expr vc_2 env) 
		 (bind-expr v3 env) (bind-expr size_i_o env) (bind-expr num_5 env) 
		 (bind-expr num_6 env) (bind-expr num_7 env) (bind-expr num_8 env) 
		 (bind-expr num_9 env) (bind-expr num_10 env) (bind-expr prec_i_o env) 
		 (bind-expr num_12 env))
	]
	[ (_mm512_mask3_fmadd_epi32_dsl v0 vc_1 v2 v3 v4 size_i_o num_6 num_7 num_8 prec_i_o num_10 num_11 num_12 num_13 num_14 num_15 num_16 num_17 num_18)
		(_mm512_mask3_fmadd_epi32_dsl (bind-expr v0 env) (bind-expr vc_1 env) (bind-expr v2 env) 
		 (bind-expr v3 env) (bind-expr v4 env) (bind-expr size_i_o env) 
		 (bind-expr num_6 env) (bind-expr num_7 env) (bind-expr num_8 env) 
		 (bind-expr prec_i_o env) (bind-expr num_10 env) (bind-expr num_11 env) 
		 (bind-expr num_12 env) (bind-expr num_13 env) (bind-expr num_14 env) 
		 (bind-expr num_15 env) (bind-expr num_16 env) (bind-expr num_17 env) 
		 (bind-expr num_18 env))
	]
	[ (_mm_mask_unpackhi_epi32_dsl vc_0 v1 v2 v3 v4 num_5 num_6 num_7 num_8 num_9 size_i_o num_11 num_12 num_13 prec_i_o num_15 num_16 num_17 num_18 num_19 num_20 num_21 num_22)
		(_mm_mask_unpackhi_epi32_dsl (bind-expr vc_0 env) (bind-expr v1 env) (bind-expr v2 env) 
		 (bind-expr v3 env) (bind-expr v4 env) (bind-expr num_5 env) 
		 (bind-expr num_6 env) (bind-expr num_7 env) (bind-expr num_8 env) 
		 (bind-expr num_9 env) (bind-expr size_i_o env) (bind-expr num_11 env) 
		 (bind-expr num_12 env) (bind-expr num_13 env) (bind-expr prec_i_o env) 
		 (bind-expr num_15 env) (bind-expr num_16 env) (bind-expr num_17 env) 
		 (bind-expr num_18 env) (bind-expr num_19 env) (bind-expr num_20 env) 
		 (bind-expr num_21 env) (bind-expr num_22 env))
	]
	[ (_mm256_dpbusd_epi32_dsl v0 v1 v2 size_i prec_o num_5 num_6 prec_i num_8 num_9 num_10 num_11 num_12 num_13)
		(_mm256_dpbusd_epi32_dsl (bind-expr v0 env) (bind-expr v1 env) (bind-expr v2 env) 
		 (bind-expr size_i env) (bind-expr prec_o env) (bind-expr num_5 env) 
		 (bind-expr num_6 env) (bind-expr prec_i env) (bind-expr num_8 env) 
		 (bind-expr num_9 env) (bind-expr num_10 env) (bind-expr num_11 env) 
		 (bind-expr num_12 env) (bind-expr num_13 env))
	]
	[ (_mm_avg_epu8_dsl vc_0 vc_1 v2 v3 size_i_o num_5 num_6 num_7 prec_i_o num_9 num_10 num_11)
		(_mm_avg_epu8_dsl (bind-expr vc_0 env) (bind-expr vc_1 env) (bind-expr v2 env) 
		 (bind-expr v3 env) (bind-expr size_i_o env) (bind-expr num_5 env) 
		 (bind-expr num_6 env) (bind-expr num_7 env) (bind-expr prec_i_o env) 
		 (bind-expr num_9 env) (bind-expr num_10 env) (bind-expr num_11 env))
	]
	[ (_mm256_maskz_mulhrs_epi16_dsl vc_0 v1 vc_2 vc_3 vc_4 v5 v6 size_i_o num_8 num_9 num_10 prec_i_o num_12 num_13 num_14 num_15 num_16 num_17 num_18 num_19)
		(_mm256_maskz_mulhrs_epi16_dsl (bind-expr vc_0 env) (bind-expr v1 env) (bind-expr vc_2 env) 
		 (bind-expr vc_3 env) (bind-expr vc_4 env) (bind-expr v5 env) 
		 (bind-expr v6 env) (bind-expr size_i_o env) (bind-expr num_8 env) 
		 (bind-expr num_9 env) (bind-expr num_10 env) (bind-expr prec_i_o env) 
		 (bind-expr num_12 env) (bind-expr num_13 env) (bind-expr num_14 env) 
		 (bind-expr num_15 env) (bind-expr num_16 env) (bind-expr num_17 env) 
		 (bind-expr num_18 env) (bind-expr num_19 env))
	]
	[ (_mm256_hadd_epi32_dsl v0 v1 size_i_o num_3 num_4 num_5 num_6 num_7 num_8 prec_i_o num_10 num_11 num_12 num_13 num_14 num_15 num_16 num_17)
		(_mm256_hadd_epi32_dsl (bind-expr v0 env) (bind-expr v1 env) (bind-expr size_i_o env) 
		 (bind-expr num_3 env) (bind-expr num_4 env) (bind-expr num_5 env) 
		 (bind-expr num_6 env) (bind-expr num_7 env) (bind-expr num_8 env) 
		 (bind-expr prec_i_o env) (bind-expr num_10 env) (bind-expr num_11 env) 
		 (bind-expr num_12 env) (bind-expr num_13 env) (bind-expr num_14 env) 
		 (bind-expr num_15 env) (bind-expr num_16 env) (bind-expr num_17 env))
	]
	[ (_mm256_and_si256_dsl v0 v1 size_i_o num_3 num_4 num_5 prec_i_o num_7 num_8)
		(_mm256_and_si256_dsl (bind-expr v0 env) (bind-expr v1 env) (bind-expr size_i_o env) 
		 (bind-expr num_3 env) (bind-expr num_4 env) (bind-expr num_5 env) 
		 (bind-expr prec_i_o env) (bind-expr num_7 env) (bind-expr num_8 env))
	]
	[ (_mm256_cmpeq_epu64_mask_dsl vc_0 vc_1 v2 v3 size_i_o num_5 num_6 num_7 prec_o prec_i num_10 num_11)
		(_mm256_cmpeq_epu64_mask_dsl (bind-expr vc_0 env) (bind-expr vc_1 env) (bind-expr v2 env) 
		 (bind-expr v3 env) (bind-expr size_i_o env) (bind-expr num_5 env) 
		 (bind-expr num_6 env) (bind-expr num_7 env) (bind-expr prec_o env) 
		 (bind-expr prec_i env) (bind-expr num_10 env) (bind-expr num_11 env))
	]
	[ (_mm512_mask_cvtsepi16_epi8_dsl v0 vc_1 v2 v3 size_i_o num_5 num_6 num_7 prec_i_o num_9 num_10 num_11 num_12 num_13 num_14)
		(_mm512_mask_cvtsepi16_epi8_dsl (bind-expr v0 env) (bind-expr vc_1 env) (bind-expr v2 env) 
		 (bind-expr v3 env) (bind-expr size_i_o env) (bind-expr num_5 env) 
		 (bind-expr num_6 env) (bind-expr num_7 env) (bind-expr prec_i_o env) 
		 (bind-expr num_9 env) (bind-expr num_10 env) (bind-expr num_11 env) 
		 (bind-expr num_12 env) (bind-expr num_13 env) (bind-expr num_14 env))
	]
	[ (_mm512_mulhi_epu32_dsl vc_0 v1 v2 size_i_o num_4 num_5 num_6 prec_i_o num_8 num_9 num_10 num_11)
		(_mm512_mulhi_epu32_dsl (bind-expr vc_0 env) (bind-expr v1 env) (bind-expr v2 env) 
		 (bind-expr size_i_o env) (bind-expr num_4 env) (bind-expr num_5 env) 
		 (bind-expr num_6 env) (bind-expr prec_i_o env) (bind-expr num_8 env) 
		 (bind-expr num_9 env) (bind-expr num_10 env) (bind-expr num_11 env))
	]
	[ (_mm512_broadcastq_epi64_dsl v0 size_o num_2 num_3 num_4 prec_i_o num_6 num_7)
		(_mm512_broadcastq_epi64_dsl (bind-expr v0 env) (bind-expr size_o env) (bind-expr num_2 env) 
		 (bind-expr num_3 env) (bind-expr num_4 env) (bind-expr prec_i_o env) 
		 (bind-expr num_6 env) (bind-expr num_7 env))
	]
	[ (_mm_sub_si64_dsl v0 v1 size_i_o num_3 num_4 num_5 prec_i_o num_7 num_8 num_9)
		(_mm_sub_si64_dsl (bind-expr v0 env) (bind-expr v1 env) (bind-expr size_i_o env) 
		 (bind-expr num_3 env) (bind-expr num_4 env) (bind-expr num_5 env) 
		 (bind-expr prec_i_o env) (bind-expr num_7 env) (bind-expr num_8 env) 
		 (bind-expr num_9 env))
	]
	[ (_mm256_extract_epi8_dsl vc_0 v1 v2 size_i_o num_4 num_5 num_6 num_7 prec_o num_9 prec_i num_11 num_12)
		(_mm256_extract_epi8_dsl (bind-expr vc_0 env) (bind-expr v1 env) (bind-expr v2 env) 
		 (bind-expr size_i_o env) (bind-expr num_4 env) (bind-expr num_5 env) 
		 (bind-expr num_6 env) (bind-expr num_7 env) (bind-expr prec_o env) 
		 (bind-expr num_9 env) (bind-expr prec_i env) (bind-expr num_11 env) 
		 (bind-expr num_12 env))
	]
	[ (_mm_mask_srai_epi16_dsl vc_0 v1 v2 vc_3 v4 vc_5 vc_6 v7 vc_8 size_i_o num_10 num_11 num_12 num_13 num_14 num_15 num_16 num_17 num_18 prec_i_o num_20 num_21 num_22 num_23 num_24)
		(_mm_mask_srai_epi16_dsl (bind-expr vc_0 env) (bind-expr v1 env) (bind-expr v2 env) 
		 (bind-expr vc_3 env) (bind-expr v4 env) (bind-expr vc_5 env) 
		 (bind-expr vc_6 env) (bind-expr v7 env) (bind-expr vc_8 env) 
		 (bind-expr size_i_o env) (bind-expr num_10 env) (bind-expr num_11 env) 
		 (bind-expr num_12 env) (bind-expr num_13 env) (bind-expr num_14 env) 
		 (bind-expr num_15 env) (bind-expr num_16 env) (bind-expr num_17 env) 
		 (bind-expr num_18 env) (bind-expr prec_i_o env) (bind-expr num_20 env) 
		 (bind-expr num_21 env) (bind-expr num_22 env) (bind-expr num_23 env) 
		 (bind-expr num_24 env))
	]
	[ (_mm256_sra_epi32_dsl v0 vc_1 vc_2 v3 vc_4 vc_5 size_i_o num_7 num_8 num_9 num_10 num_11 num_12 num_13 prec_i_o num_15 num_16 num_17 num_18 num_19)
		(_mm256_sra_epi32_dsl (bind-expr v0 env) (bind-expr vc_1 env) (bind-expr vc_2 env) 
		 (bind-expr v3 env) (bind-expr vc_4 env) (bind-expr vc_5 env) 
		 (bind-expr size_i_o env) (bind-expr num_7 env) (bind-expr num_8 env) 
		 (bind-expr num_9 env) (bind-expr num_10 env) (bind-expr num_11 env) 
		 (bind-expr num_12 env) (bind-expr num_13 env) (bind-expr prec_i_o env) 
		 (bind-expr num_15 env) (bind-expr num_16 env) (bind-expr num_17 env) 
		 (bind-expr num_18 env) (bind-expr num_19 env))
	]
	[ (_m_psrawi_dsl v0 vc_1 v2 vc_3 vc_4 vc_5 size_i_o num_7 num_8 num_9 num_10 num_11 num_12 num_13 prec_i_o num_15 num_16 num_17 num_18 num_19 num_20 num_21)
		(_m_psrawi_dsl (bind-expr v0 env) (bind-expr vc_1 env) (bind-expr v2 env) 
		 (bind-expr vc_3 env) (bind-expr vc_4 env) (bind-expr vc_5 env) 
		 (bind-expr size_i_o env) (bind-expr num_7 env) (bind-expr num_8 env) 
		 (bind-expr num_9 env) (bind-expr num_10 env) (bind-expr num_11 env) 
		 (bind-expr num_12 env) (bind-expr num_13 env) (bind-expr prec_i_o env) 
		 (bind-expr num_15 env) (bind-expr num_16 env) (bind-expr num_17 env) 
		 (bind-expr num_18 env) (bind-expr num_19 env) (bind-expr num_20 env) 
		 (bind-expr num_21 env))
	]
	[ (_mm512_packs_epi32_dsl v0 v1 size_i_o num_3 num_4 num_5 num_6 num_7 num_8 prec_o num_10 num_11 num_12 num_13 prec_i num_15 num_16 num_17)
		(_mm512_packs_epi32_dsl (bind-expr v0 env) (bind-expr v1 env) (bind-expr size_i_o env) 
		 (bind-expr num_3 env) (bind-expr num_4 env) (bind-expr num_5 env) 
		 (bind-expr num_6 env) (bind-expr num_7 env) (bind-expr num_8 env) 
		 (bind-expr prec_o env) (bind-expr num_10 env) (bind-expr num_11 env) 
		 (bind-expr num_12 env) (bind-expr num_13 env) (bind-expr prec_i env) 
		 (bind-expr num_15 env) (bind-expr num_16 env) (bind-expr num_17 env))
	]
	[ (_mm256_mask_rorv_epi32_dsl v0 vc_1 vc_2 vc_3 v4 v5 v6 size_i_o num_8 num_9 num_10 prec_i_o num_12 num_13 num_14 num_15)
		(_mm256_mask_rorv_epi32_dsl (bind-expr v0 env) (bind-expr vc_1 env) (bind-expr vc_2 env) 
		 (bind-expr vc_3 env) (bind-expr v4 env) (bind-expr v5 env) 
		 (bind-expr v6 env) (bind-expr size_i_o env) (bind-expr num_8 env) 
		 (bind-expr num_9 env) (bind-expr num_10 env) (bind-expr prec_i_o env) 
		 (bind-expr num_12 env) (bind-expr num_13 env) (bind-expr num_14 env) 
		 (bind-expr num_15 env))
	]
	[ (_mm512_maskz_srl_epi64_dsl v0 vc_1 v2 vc_3 vc_4 vc_5 v6 size_i_o num_8 num_9 num_10 num_11 num_12 num_13 num_14 num_15 num_16 prec_i_o num_18 num_19)
		(_mm512_maskz_srl_epi64_dsl (bind-expr v0 env) (bind-expr vc_1 env) (bind-expr v2 env) 
		 (bind-expr vc_3 env) (bind-expr vc_4 env) (bind-expr vc_5 env) 
		 (bind-expr v6 env) (bind-expr size_i_o env) (bind-expr num_8 env) 
		 (bind-expr num_9 env) (bind-expr num_10 env) (bind-expr num_11 env) 
		 (bind-expr num_12 env) (bind-expr num_13 env) (bind-expr num_14 env) 
		 (bind-expr num_15 env) (bind-expr num_16 env) (bind-expr prec_i_o env) 
		 (bind-expr num_18 env) (bind-expr num_19 env))
	]
	[ (_mm512_mask_rem_epi32_dsl vc_0 v1 v2 v3 v4 size_i_o num_6 num_7 num_8 prec_i_o num_10 num_11 num_12 num_13)
		(_mm512_mask_rem_epi32_dsl (bind-expr vc_0 env) (bind-expr v1 env) (bind-expr v2 env) 
		 (bind-expr v3 env) (bind-expr v4 env) (bind-expr size_i_o env) 
		 (bind-expr num_6 env) (bind-expr num_7 env) (bind-expr num_8 env) 
		 (bind-expr prec_i_o env) (bind-expr num_10 env) (bind-expr num_11 env) 
		 (bind-expr num_12 env) (bind-expr num_13 env))
	]
	[ (_mm256_madd52hi_epu64_dsl v0 v1 v2 size_i_o num_4 num_5 num_6 prec_i prec_o num_9 num_10 num_11 num_12 num_13 num_14 num_15 num_16 num_17)
		(_mm256_madd52hi_epu64_dsl (bind-expr v0 env) (bind-expr v1 env) (bind-expr v2 env) 
		 (bind-expr size_i_o env) (bind-expr num_4 env) (bind-expr num_5 env) 
		 (bind-expr num_6 env) (bind-expr prec_i env) (bind-expr prec_o env) 
		 (bind-expr num_9 env) (bind-expr num_10 env) (bind-expr num_11 env) 
		 (bind-expr num_12 env) (bind-expr num_13 env) (bind-expr num_14 env) 
		 (bind-expr num_15 env) (bind-expr num_16 env) (bind-expr num_17 env))
	]
	[ (_mm_min_epu16_dsl v0 v1 size_i_o num_3 num_4 num_5 prec_i_o num_7 num_8)
		(_mm_min_epu16_dsl (bind-expr v0 env) (bind-expr v1 env) (bind-expr size_i_o env) 
		 (bind-expr num_3 env) (bind-expr num_4 env) (bind-expr num_5 env) 
		 (bind-expr prec_i_o env) (bind-expr num_7 env) (bind-expr num_8 env))
	]
	[ (_mm_andnot_si128_dsl v0 v1 size_i_o num_3 num_4 num_5 prec_i_o num_7 num_8)
		(_mm_andnot_si128_dsl (bind-expr v0 env) (bind-expr v1 env) (bind-expr size_i_o env) 
		 (bind-expr num_3 env) (bind-expr num_4 env) (bind-expr num_5 env) 
		 (bind-expr prec_i_o env) (bind-expr num_7 env) (bind-expr num_8 env))
	]
	[ (_mm256_maskz_cvtepi16_epi8_dsl v0 vc_1 vc_2 v3 size_i_o num_5 num_6 num_7 prec_i_o num_9 num_10 num_11 num_12 num_13)
		(_mm256_maskz_cvtepi16_epi8_dsl (bind-expr v0 env) (bind-expr vc_1 env) (bind-expr vc_2 env) 
		 (bind-expr v3 env) (bind-expr size_i_o env) (bind-expr num_5 env) 
		 (bind-expr num_6 env) (bind-expr num_7 env) (bind-expr prec_i_o env) 
		 (bind-expr num_9 env) (bind-expr num_10 env) (bind-expr num_11 env) 
		 (bind-expr num_12 env) (bind-expr num_13 env))
	]
	[ (_mm_test_epi64_mask_dsl vc_0 v1 vc_2 vc_3 v4 size_i_o num_6 num_7 num_8 prec_o prec_i num_11 num_12)
		(_mm_test_epi64_mask_dsl (bind-expr vc_0 env) (bind-expr v1 env) (bind-expr vc_2 env) 
		 (bind-expr vc_3 env) (bind-expr v4 env) (bind-expr size_i_o env) 
		 (bind-expr num_6 env) (bind-expr num_7 env) (bind-expr num_8 env) 
		 (bind-expr prec_o env) (bind-expr prec_i env) (bind-expr num_11 env) 
		 (bind-expr num_12 env))
	]
	[ (_mm512_cvtepu8_epi32_dsl v0 size_i_o num_2 num_3 num_4 prec_i prec_o num_7 num_8 num_9)
		(_mm512_cvtepu8_epi32_dsl (bind-expr v0 env) (bind-expr size_i_o env) (bind-expr num_2 env) 
		 (bind-expr num_3 env) (bind-expr num_4 env) (bind-expr prec_i env) 
		 (bind-expr prec_o env) (bind-expr num_7 env) (bind-expr num_8 env) 
		 (bind-expr num_9 env))
	]
	[ (_mm256_mask_cmpgt_epu64_mask_dsl v0 vc_1 vc_2 vc_3 vc_4 v5 v6 size_i_o num_8 num_9 num_10 prec_o num_12 num_13 prec_i num_15 num_16)
		(_mm256_mask_cmpgt_epu64_mask_dsl (bind-expr v0 env) (bind-expr vc_1 env) (bind-expr vc_2 env) 
		 (bind-expr vc_3 env) (bind-expr vc_4 env) (bind-expr v5 env) 
		 (bind-expr v6 env) (bind-expr size_i_o env) (bind-expr num_8 env) 
		 (bind-expr num_9 env) (bind-expr num_10 env) (bind-expr prec_o env) 
		 (bind-expr num_12 env) (bind-expr num_13 env) (bind-expr prec_i env) 
		 (bind-expr num_15 env) (bind-expr num_16 env))
	]
	[ (_mm_maskz_unpacklo_epi64_dsl v0 vc_1 vc_2 v3 v4 num_5 num_6 num_7 num_8 num_9 size_i_o num_11 num_12 num_13 prec_i_o num_15 num_16 num_17 num_18 num_19 num_20 num_21 num_22 num_23)
		(_mm_maskz_unpacklo_epi64_dsl (bind-expr v0 env) (bind-expr vc_1 env) (bind-expr vc_2 env) 
		 (bind-expr v3 env) (bind-expr v4 env) (bind-expr num_5 env) 
		 (bind-expr num_6 env) (bind-expr num_7 env) (bind-expr num_8 env) 
		 (bind-expr num_9 env) (bind-expr size_i_o env) (bind-expr num_11 env) 
		 (bind-expr num_12 env) (bind-expr num_13 env) (bind-expr prec_i_o env) 
		 (bind-expr num_15 env) (bind-expr num_16 env) (bind-expr num_17 env) 
		 (bind-expr num_18 env) (bind-expr num_19 env) (bind-expr num_20 env) 
		 (bind-expr num_21 env) (bind-expr num_22 env) (bind-expr num_23 env))
	]
	[ (_mm512_maskz_unpackhi_epi64_dsl vc_0 v1 vc_2 v3 v4 num_5 num_6 num_7 num_8 num_9 size_i_o num_11 num_12 num_13 prec_i_o num_15 num_16 num_17 num_18 num_19 num_20 num_21 num_22 num_23)
		(_mm512_maskz_unpackhi_epi64_dsl (bind-expr vc_0 env) (bind-expr v1 env) (bind-expr vc_2 env) 
		 (bind-expr v3 env) (bind-expr v4 env) (bind-expr num_5 env) 
		 (bind-expr num_6 env) (bind-expr num_7 env) (bind-expr num_8 env) 
		 (bind-expr num_9 env) (bind-expr size_i_o env) (bind-expr num_11 env) 
		 (bind-expr num_12 env) (bind-expr num_13 env) (bind-expr prec_i_o env) 
		 (bind-expr num_15 env) (bind-expr num_16 env) (bind-expr num_17 env) 
		 (bind-expr num_18 env) (bind-expr num_19 env) (bind-expr num_20 env) 
		 (bind-expr num_21 env) (bind-expr num_22 env) (bind-expr num_23 env))
	]
	[ (_mm512_mask_div_epi32_dsl vc_0 v1 v2 v3 v4 size_i_o num_6 num_7 num_8 prec_i_o num_10 num_11 num_12 num_13 num_14 num_15 num_16 num_17)
		(_mm512_mask_div_epi32_dsl (bind-expr vc_0 env) (bind-expr v1 env) (bind-expr v2 env) 
		 (bind-expr v3 env) (bind-expr v4 env) (bind-expr size_i_o env) 
		 (bind-expr num_6 env) (bind-expr num_7 env) (bind-expr num_8 env) 
		 (bind-expr prec_i_o env) (bind-expr num_10 env) (bind-expr num_11 env) 
		 (bind-expr num_12 env) (bind-expr num_13 env) (bind-expr num_14 env) 
		 (bind-expr num_15 env) (bind-expr num_16 env) (bind-expr num_17 env))
	]
	[ (_mm_maskz_sll_epi32_dsl v0 vc_1 v2 vc_3 vc_4 vc_5 v6 size_i_o num_8 num_9 num_10 num_11 num_12 num_13 num_14 num_15 num_16 prec_i_o num_18 num_19 num_20 num_21)
		(_mm_maskz_sll_epi32_dsl (bind-expr v0 env) (bind-expr vc_1 env) (bind-expr v2 env) 
		 (bind-expr vc_3 env) (bind-expr vc_4 env) (bind-expr vc_5 env) 
		 (bind-expr v6 env) (bind-expr size_i_o env) (bind-expr num_8 env) 
		 (bind-expr num_9 env) (bind-expr num_10 env) (bind-expr num_11 env) 
		 (bind-expr num_12 env) (bind-expr num_13 env) (bind-expr num_14 env) 
		 (bind-expr num_15 env) (bind-expr num_16 env) (bind-expr prec_i_o env) 
		 (bind-expr num_18 env) (bind-expr num_19 env) (bind-expr num_20 env) 
		 (bind-expr num_21 env))
	]
	[ (_mm512_and_epi32_dsl v0 v1 size_i_o num_3 num_4 num_5 prec_i_o num_7)
		(_mm512_and_epi32_dsl (bind-expr v0 env) (bind-expr v1 env) (bind-expr size_i_o env) 
		 (bind-expr num_3 env) (bind-expr num_4 env) (bind-expr num_5 env) 
		 (bind-expr prec_i_o env) (bind-expr num_7 env))
	]
	[ (_mm256_mask_dpbusd_epi32_dsl v0 vc_1 v2 v3 v4 size_i_o prec_i_o num_7 num_8 num_9 num_10 num_11 num_12 num_13 num_14 num_15 num_16 num_17 num_18 num_19 num_20)
		(_mm256_mask_dpbusd_epi32_dsl (bind-expr v0 env) (bind-expr vc_1 env) (bind-expr v2 env) 
		 (bind-expr v3 env) (bind-expr v4 env) (bind-expr size_i_o env) 
		 (bind-expr prec_i_o env) (bind-expr num_7 env) (bind-expr num_8 env) 
		 (bind-expr num_9 env) (bind-expr num_10 env) (bind-expr num_11 env) 
		 (bind-expr num_12 env) (bind-expr num_13 env) (bind-expr num_14 env) 
		 (bind-expr num_15 env) (bind-expr num_16 env) (bind-expr num_17 env) 
		 (bind-expr num_18 env) (bind-expr num_19 env) (bind-expr num_20 env))
	]
	[ (_m_pslld_dsl v0 vc_1 vc_2 v3 size_i_o num_5 num_6 num_7 num_8 num_9 num_10 num_11 prec_i_o num_13 num_14 num_15 num_16)
		(_m_pslld_dsl (bind-expr v0 env) (bind-expr vc_1 env) (bind-expr vc_2 env) 
		 (bind-expr v3 env) (bind-expr size_i_o env) (bind-expr num_5 env) 
		 (bind-expr num_6 env) (bind-expr num_7 env) (bind-expr num_8 env) 
		 (bind-expr num_9 env) (bind-expr num_10 env) (bind-expr num_11 env) 
		 (bind-expr prec_i_o env) (bind-expr num_13 env) (bind-expr num_14 env) 
		 (bind-expr num_15 env) (bind-expr num_16 env))
	]
	[ (_mm512_andnot_epi32_dsl v0 v1 size_i_o num_3 num_4 num_5 prec_i_o num_7)
		(_mm512_andnot_epi32_dsl (bind-expr v0 env) (bind-expr v1 env) (bind-expr size_i_o env) 
		 (bind-expr num_3 env) (bind-expr num_4 env) (bind-expr num_5 env) 
		 (bind-expr prec_i_o env) (bind-expr num_7 env))
	]
	[ (_mm512_mask_mulhi_epu32_dsl v0 vc_1 vc_2 v3 v4 v5 size_i_o num_7 num_8 num_9 prec_i_o num_11 num_12 num_13 num_14 num_15 num_16)
		(_mm512_mask_mulhi_epu32_dsl (bind-expr v0 env) (bind-expr vc_1 env) (bind-expr vc_2 env) 
		 (bind-expr v3 env) (bind-expr v4 env) (bind-expr v5 env) 
		 (bind-expr size_i_o env) (bind-expr num_7 env) (bind-expr num_8 env) 
		 (bind-expr num_9 env) (bind-expr prec_i_o env) (bind-expr num_11 env) 
		 (bind-expr num_12 env) (bind-expr num_13 env) (bind-expr num_14 env) 
		 (bind-expr num_15 env) (bind-expr num_16 env))
	]
	[ (_mm512_subs_epi8_dsl v0 v1 size_i_o num_3 num_4 num_5 prec_i_o num_7 num_8)
		(_mm512_subs_epi8_dsl (bind-expr v0 env) (bind-expr v1 env) (bind-expr size_i_o env) 
		 (bind-expr num_3 env) (bind-expr num_4 env) (bind-expr num_5 env) 
		 (bind-expr prec_i_o env) (bind-expr num_7 env) (bind-expr num_8 env))
	]
	[ (_mm256_rol_epi32_dsl vc_0 vc_1 v2 v3 size_i_o num_5 num_6 num_7 num_8 prec_i_o num_10 num_11 num_12 num_13 num_14 num_15)
		(_mm256_rol_epi32_dsl (bind-expr vc_0 env) (bind-expr vc_1 env) (bind-expr v2 env) 
		 (bind-expr v3 env) (bind-expr size_i_o env) (bind-expr num_5 env) 
		 (bind-expr num_6 env) (bind-expr num_7 env) (bind-expr num_8 env) 
		 (bind-expr prec_i_o env) (bind-expr num_10 env) (bind-expr num_11 env) 
		 (bind-expr num_12 env) (bind-expr num_13 env) (bind-expr num_14 env) 
		 (bind-expr num_15 env))
	]
	[ (_m_from_int_dsl v0 size_i_o num_2 num_3 num_4 prec_i_o num_6 num_7)
		(_m_from_int_dsl (bind-expr v0 env) (bind-expr size_i_o env) (bind-expr num_2 env) 
		 (bind-expr num_3 env) (bind-expr num_4 env) (bind-expr prec_i_o env) 
		 (bind-expr num_6 env) (bind-expr num_7 env))
	]
	[ (_m_psrld_dsl v0 vc_1 vc_2 v3 size_i_o num_5 num_6 num_7 num_8 num_9 num_10 num_11 prec_i_o num_13 num_14 num_15 num_16)
		(_m_psrld_dsl (bind-expr v0 env) (bind-expr vc_1 env) (bind-expr vc_2 env) 
		 (bind-expr v3 env) (bind-expr size_i_o env) (bind-expr num_5 env) 
		 (bind-expr num_6 env) (bind-expr num_7 env) (bind-expr num_8 env) 
		 (bind-expr num_9 env) (bind-expr num_10 env) (bind-expr num_11 env) 
		 (bind-expr prec_i_o env) (bind-expr num_13 env) (bind-expr num_14 env) 
		 (bind-expr num_15 env) (bind-expr num_16 env))
	]
	[ (_mm512_mask_fmadd_epi32_dsl v0 vc_1 v2 v3 v4 size_i_o num_6 num_7 num_8 prec_i_o num_10 num_11 num_12 num_13 num_14 num_15 num_16 num_17 num_18)
		(_mm512_mask_fmadd_epi32_dsl (bind-expr v0 env) (bind-expr vc_1 env) (bind-expr v2 env) 
		 (bind-expr v3 env) (bind-expr v4 env) (bind-expr size_i_o env) 
		 (bind-expr num_6 env) (bind-expr num_7 env) (bind-expr num_8 env) 
		 (bind-expr prec_i_o env) (bind-expr num_10 env) (bind-expr num_11 env) 
		 (bind-expr num_12 env) (bind-expr num_13 env) (bind-expr num_14 env) 
		 (bind-expr num_15 env) (bind-expr num_16 env) (bind-expr num_17 env) 
		 (bind-expr num_18 env))
	]
	[ (_mm512_srli_epi16_dsl v0 vc_1 vc_2 v3 size_i_o num_5 num_6 num_7 num_8 num_9 num_10 num_11 prec_i_o num_13 num_14 num_15 num_16 num_17 num_18)
		(_mm512_srli_epi16_dsl (bind-expr v0 env) (bind-expr vc_1 env) (bind-expr vc_2 env) 
		 (bind-expr v3 env) (bind-expr size_i_o env) (bind-expr num_5 env) 
		 (bind-expr num_6 env) (bind-expr num_7 env) (bind-expr num_8 env) 
		 (bind-expr num_9 env) (bind-expr num_10 env) (bind-expr num_11 env) 
		 (bind-expr prec_i_o env) (bind-expr num_13 env) (bind-expr num_14 env) 
		 (bind-expr num_15 env) (bind-expr num_16 env) (bind-expr num_17 env) 
		 (bind-expr num_18 env))
	]
	[ (_mm512_cmpneq_epu8_mask_dsl vc_0 v1 vc_2 v3 size_i_o num_5 num_6 num_7 prec_o prec_i num_10 num_11)
		(_mm512_cmpneq_epu8_mask_dsl (bind-expr vc_0 env) (bind-expr v1 env) (bind-expr vc_2 env) 
		 (bind-expr v3 env) (bind-expr size_i_o env) (bind-expr num_5 env) 
		 (bind-expr num_6 env) (bind-expr num_7 env) (bind-expr prec_o env) 
		 (bind-expr prec_i env) (bind-expr num_10 env) (bind-expr num_11 env))
	]
	[ (_mm512_mask_srlv_epi64_dsl vc_0 v1 v2 v3 vc_4 vc_5 v6 size_i_o num_8 num_9 num_10 num_11 num_12 num_13 num_14 num_15 prec_i_o num_17)
		(_mm512_mask_srlv_epi64_dsl (bind-expr vc_0 env) (bind-expr v1 env) (bind-expr v2 env) 
		 (bind-expr v3 env) (bind-expr vc_4 env) (bind-expr vc_5 env) 
		 (bind-expr v6 env) (bind-expr size_i_o env) (bind-expr num_8 env) 
		 (bind-expr num_9 env) (bind-expr num_10 env) (bind-expr num_11 env) 
		 (bind-expr num_12 env) (bind-expr num_13 env) (bind-expr num_14 env) 
		 (bind-expr num_15 env) (bind-expr prec_i_o env) (bind-expr num_17 env))
	]
	[ (_mm512_maskz_mulhi_epi16_dsl vc_0 v1 vc_2 v3 v4 size_i_o num_6 num_7 num_8 prec_i_o num_10 num_11 num_12 num_13 num_14 num_15 num_16)
		(_mm512_maskz_mulhi_epi16_dsl (bind-expr vc_0 env) (bind-expr v1 env) (bind-expr vc_2 env) 
		 (bind-expr v3 env) (bind-expr v4 env) (bind-expr size_i_o env) 
		 (bind-expr num_6 env) (bind-expr num_7 env) (bind-expr num_8 env) 
		 (bind-expr prec_i_o env) (bind-expr num_10 env) (bind-expr num_11 env) 
		 (bind-expr num_12 env) (bind-expr num_13 env) (bind-expr num_14 env) 
		 (bind-expr num_15 env) (bind-expr num_16 env))
	]
	[ (_mm512_cvtusepi64_epi32_dsl v0 size_i_o num_2 num_3 num_4 prec_o num_6 prec_i num_8 num_9)
		(_mm512_cvtusepi64_epi32_dsl (bind-expr v0 env) (bind-expr size_i_o env) (bind-expr num_2 env) 
		 (bind-expr num_3 env) (bind-expr num_4 env) (bind-expr prec_o env) 
		 (bind-expr num_6 env) (bind-expr prec_i env) (bind-expr num_8 env) 
		 (bind-expr num_9 env))
	]
	[ (_mm512_slli_epi16_dsl v0 vc_1 vc_2 v3 size_i_o num_5 num_6 num_7 num_8 num_9 num_10 num_11 prec_i_o num_13 num_14 num_15 num_16 num_17 num_18)
		(_mm512_slli_epi16_dsl (bind-expr v0 env) (bind-expr vc_1 env) (bind-expr vc_2 env) 
		 (bind-expr v3 env) (bind-expr size_i_o env) (bind-expr num_5 env) 
		 (bind-expr num_6 env) (bind-expr num_7 env) (bind-expr num_8 env) 
		 (bind-expr num_9 env) (bind-expr num_10 env) (bind-expr num_11 env) 
		 (bind-expr prec_i_o env) (bind-expr num_13 env) (bind-expr num_14 env) 
		 (bind-expr num_15 env) (bind-expr num_16 env) (bind-expr num_17 env) 
		 (bind-expr num_18 env))
	]
	[ (_mm256_mask_unpackhi_epi16_dsl vc_0 v1 v2 v3 v4 num_5 num_6 num_7 num_8 num_9 size_i_o num_11 num_12 num_13 prec_i_o num_15 num_16 num_17 num_18 num_19 num_20 num_21 num_22)
		(_mm256_mask_unpackhi_epi16_dsl (bind-expr vc_0 env) (bind-expr v1 env) (bind-expr v2 env) 
		 (bind-expr v3 env) (bind-expr v4 env) (bind-expr num_5 env) 
		 (bind-expr num_6 env) (bind-expr num_7 env) (bind-expr num_8 env) 
		 (bind-expr num_9 env) (bind-expr size_i_o env) (bind-expr num_11 env) 
		 (bind-expr num_12 env) (bind-expr num_13 env) (bind-expr prec_i_o env) 
		 (bind-expr num_15 env) (bind-expr num_16 env) (bind-expr num_17 env) 
		 (bind-expr num_18 env) (bind-expr num_19 env) (bind-expr num_20 env) 
		 (bind-expr num_21 env) (bind-expr num_22 env))
	]
	[ (_mm512_maskz_unpacklo_epi16_dsl vc_0 v1 vc_2 v3 v4 num_5 num_6 num_7 num_8 num_9 size_i_o num_11 num_12 num_13 prec_i_o num_15 num_16 num_17 num_18 num_19 num_20 num_21)
		(_mm512_maskz_unpacklo_epi16_dsl (bind-expr vc_0 env) (bind-expr v1 env) (bind-expr vc_2 env) 
		 (bind-expr v3 env) (bind-expr v4 env) (bind-expr num_5 env) 
		 (bind-expr num_6 env) (bind-expr num_7 env) (bind-expr num_8 env) 
		 (bind-expr num_9 env) (bind-expr size_i_o env) (bind-expr num_11 env) 
		 (bind-expr num_12 env) (bind-expr num_13 env) (bind-expr prec_i_o env) 
		 (bind-expr num_15 env) (bind-expr num_16 env) (bind-expr num_17 env) 
		 (bind-expr num_18 env) (bind-expr num_19 env) (bind-expr num_20 env) 
		 (bind-expr num_21 env))
	]
	[ (_mm256_maskz_dpwssd_epi32_dsl vc_0 v1 v2 vc_3 v4 v5 size_i_o prec_i_o num_8 num_9 num_10 num_11 num_12 num_13 num_14 num_15 num_16 num_17 num_18 num_19)
		(_mm256_maskz_dpwssd_epi32_dsl (bind-expr vc_0 env) (bind-expr v1 env) (bind-expr v2 env) 
		 (bind-expr vc_3 env) (bind-expr v4 env) (bind-expr v5 env) 
		 (bind-expr size_i_o env) (bind-expr prec_i_o env) (bind-expr num_8 env) 
		 (bind-expr num_9 env) (bind-expr num_10 env) (bind-expr num_11 env) 
		 (bind-expr num_12 env) (bind-expr num_13 env) (bind-expr num_14 env) 
		 (bind-expr num_15 env) (bind-expr num_16 env) (bind-expr num_17 env) 
		 (bind-expr num_18 env) (bind-expr num_19 env))
	]
	[ (_mm512_mask_extracti32x4_epi32_dsl v0 vc_1 vc_2 vc_3 vc_4 vc_5 v6 v7 v8 num_9 num_10 num_11 num_12 num_13 size_i_o num_15 num_16 num_17 prec_i_o num_19 num_20 num_21 num_22 num_23 num_24 num_25 num_26 num_27 num_28 num_29 num_30 num_31 num_32)
		(_mm512_mask_extracti32x4_epi32_dsl (bind-expr v0 env) (bind-expr vc_1 env) (bind-expr vc_2 env) 
		 (bind-expr vc_3 env) (bind-expr vc_4 env) (bind-expr vc_5 env) 
		 (bind-expr v6 env) (bind-expr v7 env) (bind-expr v8 env) 
		 (bind-expr num_9 env) (bind-expr num_10 env) (bind-expr num_11 env) 
		 (bind-expr num_12 env) (bind-expr num_13 env) (bind-expr size_i_o env) 
		 (bind-expr num_15 env) (bind-expr num_16 env) (bind-expr num_17 env) 
		 (bind-expr prec_i_o env) (bind-expr num_19 env) (bind-expr num_20 env) 
		 (bind-expr num_21 env) (bind-expr num_22 env) (bind-expr num_23 env) 
		 (bind-expr num_24 env) (bind-expr num_25 env) (bind-expr num_26 env) 
		 (bind-expr num_27 env) (bind-expr num_28 env) (bind-expr num_29 env) 
		 (bind-expr num_30 env) (bind-expr num_31 env) (bind-expr num_32 env))
	]
	[ (_mm512_mask_cvtepi16_epi64_dsl v0 vc_1 v2 v3 size_i_o num_5 num_6 num_7 num_8 num_9 num_10 prec_i_o num_12 num_13 num_14 num_15)
		(_mm512_mask_cvtepi16_epi64_dsl (bind-expr v0 env) (bind-expr vc_1 env) (bind-expr v2 env) 
		 (bind-expr v3 env) (bind-expr size_i_o env) (bind-expr num_5 env) 
		 (bind-expr num_6 env) (bind-expr num_7 env) (bind-expr num_8 env) 
		 (bind-expr num_9 env) (bind-expr num_10 env) (bind-expr prec_i_o env) 
		 (bind-expr num_12 env) (bind-expr num_13 env) (bind-expr num_14 env) 
		 (bind-expr num_15 env))
	]
	[ (_mm_movepi32_mask_dsl v0 vc_1 vc_2 vc_3 size_o num_5 num_6 num_7 prec_o num_9 num_10 num_11 num_12)
		(_mm_movepi32_mask_dsl (bind-expr v0 env) (bind-expr vc_1 env) (bind-expr vc_2 env) 
		 (bind-expr vc_3 env) (bind-expr size_o env) (bind-expr num_5 env) 
		 (bind-expr num_6 env) (bind-expr num_7 env) (bind-expr prec_o env) 
		 (bind-expr num_9 env) (bind-expr num_10 env) (bind-expr num_11 env) 
		 (bind-expr num_12 env))
	]
	[ (_m_por_dsl v0 v1 size_i_o num_3 num_4 num_5 prec_i_o num_7 num_8)
		(_m_por_dsl (bind-expr v0 env) (bind-expr v1 env) (bind-expr size_i_o env) 
		 (bind-expr num_3 env) (bind-expr num_4 env) (bind-expr num_5 env) 
		 (bind-expr prec_i_o env) (bind-expr num_7 env) (bind-expr num_8 env))
	]
	[ (_m_pcmpeqb_dsl vc_0 v1 v2 vc_3 size_i_o num_5 num_6 num_7 prec_i_o num_9)
		(_m_pcmpeqb_dsl (bind-expr vc_0 env) (bind-expr v1 env) (bind-expr v2 env) 
		 (bind-expr vc_3 env) (bind-expr size_i_o env) (bind-expr num_5 env) 
		 (bind-expr num_6 env) (bind-expr num_7 env) (bind-expr prec_i_o env) 
		 (bind-expr num_9 env))
	]
	[ (_mm_extract_pi16_dsl vc_0 v1 v2 size_i_o num_4 num_5 num_6 num_7 prec_o num_9 prec_i num_11 num_12 num_13 num_14)
		(_mm_extract_pi16_dsl (bind-expr vc_0 env) (bind-expr v1 env) (bind-expr v2 env) 
		 (bind-expr size_i_o env) (bind-expr num_4 env) (bind-expr num_5 env) 
		 (bind-expr num_6 env) (bind-expr num_7 env) (bind-expr prec_o env) 
		 (bind-expr num_9 env) (bind-expr prec_i env) (bind-expr num_11 env) 
		 (bind-expr num_12 env) (bind-expr num_13 env) (bind-expr num_14 env))
	]
	[ (_mm256_mask_broadcast_i64x2_dsl vc_0 v1 v2 v3 size_i_o num_5 num_6 num_7 prec_i_o num_9 num_10 num_11 num_12 num_13)
		(_mm256_mask_broadcast_i64x2_dsl (bind-expr vc_0 env) (bind-expr v1 env) (bind-expr v2 env) 
		 (bind-expr v3 env) (bind-expr size_i_o env) (bind-expr num_5 env) 
		 (bind-expr num_6 env) (bind-expr num_7 env) (bind-expr prec_i_o env) 
		 (bind-expr num_9 env) (bind-expr num_10 env) (bind-expr num_11 env) 
		 (bind-expr num_12 env) (bind-expr num_13 env))
	]
	[ (_mm256_hsub_epi32_dsl v0 v1 size_i_o num_3 num_4 num_5 num_6 num_7 num_8 prec_i_o num_10 num_11 num_12 num_13 num_14 num_15 num_16 num_17)
		(_mm256_hsub_epi32_dsl (bind-expr v0 env) (bind-expr v1 env) (bind-expr size_i_o env) 
		 (bind-expr num_3 env) (bind-expr num_4 env) (bind-expr num_5 env) 
		 (bind-expr num_6 env) (bind-expr num_7 env) (bind-expr num_8 env) 
		 (bind-expr prec_i_o env) (bind-expr num_10 env) (bind-expr num_11 env) 
		 (bind-expr num_12 env) (bind-expr num_13 env) (bind-expr num_14 env) 
		 (bind-expr num_15 env) (bind-expr num_16 env) (bind-expr num_17 env))
	]
	[ (_mm_hsub_epi16_dsl v0 v1 size_i_o num_3 num_4 num_5 num_6 num_7 num_8 prec_i_o num_10 num_11 num_12 num_13 num_14 num_15 num_16 num_17)
		(_mm_hsub_epi16_dsl (bind-expr v0 env) (bind-expr v1 env) (bind-expr size_i_o env) 
		 (bind-expr num_3 env) (bind-expr num_4 env) (bind-expr num_5 env) 
		 (bind-expr num_6 env) (bind-expr num_7 env) (bind-expr num_8 env) 
		 (bind-expr prec_i_o env) (bind-expr num_10 env) (bind-expr num_11 env) 
		 (bind-expr num_12 env) (bind-expr num_13 env) (bind-expr num_14 env) 
		 (bind-expr num_15 env) (bind-expr num_16 env) (bind-expr num_17 env))
	]
	[ (_mm512_mask_dpwssd_epi32_dsl vc_0 v1 v2 v3 v4 size_i_o prec_i_o num_7 num_8 num_9 num_10 num_11 num_12 num_13 num_14 num_15 num_16 num_17 num_18)
		(_mm512_mask_dpwssd_epi32_dsl (bind-expr vc_0 env) (bind-expr v1 env) (bind-expr v2 env) 
		 (bind-expr v3 env) (bind-expr v4 env) (bind-expr size_i_o env) 
		 (bind-expr prec_i_o env) (bind-expr num_7 env) (bind-expr num_8 env) 
		 (bind-expr num_9 env) (bind-expr num_10 env) (bind-expr num_11 env) 
		 (bind-expr num_12 env) (bind-expr num_13 env) (bind-expr num_14 env) 
		 (bind-expr num_15 env) (bind-expr num_16 env) (bind-expr num_17 env) 
		 (bind-expr num_18 env))
	]
	[ (_mm256_ror_epi32_dsl vc_0 vc_1 v2 v3 size_i_o num_5 num_6 num_7 num_8 prec_i_o num_10 num_11 num_12 num_13 num_14 num_15)
		(_mm256_ror_epi32_dsl (bind-expr vc_0 env) (bind-expr vc_1 env) (bind-expr v2 env) 
		 (bind-expr v3 env) (bind-expr size_i_o env) (bind-expr num_5 env) 
		 (bind-expr num_6 env) (bind-expr num_7 env) (bind-expr num_8 env) 
		 (bind-expr prec_i_o env) (bind-expr num_10 env) (bind-expr num_11 env) 
		 (bind-expr num_12 env) (bind-expr num_13 env) (bind-expr num_14 env) 
		 (bind-expr num_15 env))
	]
	[ (_mm256_mask_srli_epi32_dsl v0 vc_1 v2 v3 vc_4 vc_5 v6 size_i_o num_8 num_9 num_10 num_11 num_12 num_13 num_14 num_15 num_16 prec_i_o num_18 num_19 num_20 num_21)
		(_mm256_mask_srli_epi32_dsl (bind-expr v0 env) (bind-expr vc_1 env) (bind-expr v2 env) 
		 (bind-expr v3 env) (bind-expr vc_4 env) (bind-expr vc_5 env) 
		 (bind-expr v6 env) (bind-expr size_i_o env) (bind-expr num_8 env) 
		 (bind-expr num_9 env) (bind-expr num_10 env) (bind-expr num_11 env) 
		 (bind-expr num_12 env) (bind-expr num_13 env) (bind-expr num_14 env) 
		 (bind-expr num_15 env) (bind-expr num_16 env) (bind-expr prec_i_o env) 
		 (bind-expr num_18 env) (bind-expr num_19 env) (bind-expr num_20 env) 
		 (bind-expr num_21 env))
	]
	[ (_mm_mask_broadcastd_epi32_dsl vc_0 v1 v2 v3 size_i_o num_5 num_6 num_7 prec_i_o num_9 num_10 num_11 num_12)
		(_mm_mask_broadcastd_epi32_dsl (bind-expr vc_0 env) (bind-expr v1 env) (bind-expr v2 env) 
		 (bind-expr v3 env) (bind-expr size_i_o env) (bind-expr num_5 env) 
		 (bind-expr num_6 env) (bind-expr num_7 env) (bind-expr prec_i_o env) 
		 (bind-expr num_9 env) (bind-expr num_10 env) (bind-expr num_11 env) 
		 (bind-expr num_12 env))
	]
	[ (_mm_maskz_madd52lo_epu64_dsl vc_0 v1 vc_2 v3 v4 v5 size_i_o num_7 num_8 num_9 num_10 num_11 num_12 prec_i_o num_14 num_15 num_16 num_17 num_18 num_19 num_20 num_21 num_22 num_23)
		(_mm_maskz_madd52lo_epu64_dsl (bind-expr vc_0 env) (bind-expr v1 env) (bind-expr vc_2 env) 
		 (bind-expr v3 env) (bind-expr v4 env) (bind-expr v5 env) 
		 (bind-expr size_i_o env) (bind-expr num_7 env) (bind-expr num_8 env) 
		 (bind-expr num_9 env) (bind-expr num_10 env) (bind-expr num_11 env) 
		 (bind-expr num_12 env) (bind-expr prec_i_o env) (bind-expr num_14 env) 
		 (bind-expr num_15 env) (bind-expr num_16 env) (bind-expr num_17 env) 
		 (bind-expr num_18 env) (bind-expr num_19 env) (bind-expr num_20 env) 
		 (bind-expr num_21 env) (bind-expr num_22 env) (bind-expr num_23 env))
	]
	[ (_mm256_blendv_epi8_dsl vc_0 v1 v2 v3 size_i_o num_5 num_6 num_7 prec_i_o num_9 num_10 num_11)
		(_mm256_blendv_epi8_dsl (bind-expr vc_0 env) (bind-expr v1 env) (bind-expr v2 env) 
		 (bind-expr v3 env) (bind-expr size_i_o env) (bind-expr num_5 env) 
		 (bind-expr num_6 env) (bind-expr num_7 env) (bind-expr prec_i_o env) 
		 (bind-expr num_9 env) (bind-expr num_10 env) (bind-expr num_11 env))
	]
	[ (_mm512_srl_epi64_dsl v0 vc_1 vc_2 v3 size_i_o num_5 num_6 num_7 num_8 num_9 num_10 num_11 prec_i_o num_13 num_14)
		(_mm512_srl_epi64_dsl (bind-expr v0 env) (bind-expr vc_1 env) (bind-expr vc_2 env) 
		 (bind-expr v3 env) (bind-expr size_i_o env) (bind-expr num_5 env) 
		 (bind-expr num_6 env) (bind-expr num_7 env) (bind-expr num_8 env) 
		 (bind-expr num_9 env) (bind-expr num_10 env) (bind-expr num_11 env) 
		 (bind-expr prec_i_o env) (bind-expr num_13 env) (bind-expr num_14 env))
	]
	[ (_mm256_blend_epi16_dsl v0 vc_1 v2 v3 size_i_o num_5 num_6 num_7 prec_i_o num_9 num_10 num_11 num_12)
		(_mm256_blend_epi16_dsl (bind-expr v0 env) (bind-expr vc_1 env) (bind-expr v2 env) 
		 (bind-expr v3 env) (bind-expr size_i_o env) (bind-expr num_5 env) 
		 (bind-expr num_6 env) (bind-expr num_7 env) (bind-expr prec_i_o env) 
		 (bind-expr num_9 env) (bind-expr num_10 env) (bind-expr num_11 env) 
		 (bind-expr num_12 env))
	]
	[ (_mm_mask_sra_epi32_dsl v0 vc_1 v2 vc_3 vc_4 vc_5 v6 v7 vc_8 size_i_o num_10 num_11 num_12 num_13 num_14 num_15 num_16 num_17 num_18 prec_i_o num_20 num_21 num_22 num_23 num_24)
		(_mm_mask_sra_epi32_dsl (bind-expr v0 env) (bind-expr vc_1 env) (bind-expr v2 env) 
		 (bind-expr vc_3 env) (bind-expr vc_4 env) (bind-expr vc_5 env) 
		 (bind-expr v6 env) (bind-expr v7 env) (bind-expr vc_8 env) 
		 (bind-expr size_i_o env) (bind-expr num_10 env) (bind-expr num_11 env) 
		 (bind-expr num_12 env) (bind-expr num_13 env) (bind-expr num_14 env) 
		 (bind-expr num_15 env) (bind-expr num_16 env) (bind-expr num_17 env) 
		 (bind-expr num_18 env) (bind-expr prec_i_o env) (bind-expr num_20 env) 
		 (bind-expr num_21 env) (bind-expr num_22 env) (bind-expr num_23 env) 
		 (bind-expr num_24 env))
	]
	[ (_mm_movm_epi8_dsl v0 vc_1 vc_2 vc_3 size_i_o num_5 num_6 num_7 prec_i_o num_9 num_10 num_11)
		(_mm_movm_epi8_dsl (bind-expr v0 env) (bind-expr vc_1 env) (bind-expr vc_2 env) 
		 (bind-expr vc_3 env) (bind-expr size_i_o env) (bind-expr num_5 env) 
		 (bind-expr num_6 env) (bind-expr num_7 env) (bind-expr prec_i_o env) 
		 (bind-expr num_9 env) (bind-expr num_10 env) (bind-expr num_11 env))
	]
	[ (_mm_maskz_sub_epi8_dsl vc_0 v1 vc_2 v3 v4 size_i_o num_6 num_7 num_8 prec_i_o num_10 num_11 num_12 num_13)
		(_mm_maskz_sub_epi8_dsl (bind-expr vc_0 env) (bind-expr v1 env) (bind-expr vc_2 env) 
		 (bind-expr v3 env) (bind-expr v4 env) (bind-expr size_i_o env) 
		 (bind-expr num_6 env) (bind-expr num_7 env) (bind-expr num_8 env) 
		 (bind-expr prec_i_o env) (bind-expr num_10 env) (bind-expr num_11 env) 
		 (bind-expr num_12 env) (bind-expr num_13 env))
	]
	[ (_mm512_maskz_andnot_epi64_dsl v0 vc_1 vc_2 v3 v4 size_i_o num_6 num_7 num_8 prec_i_o num_10 num_11 num_12)
		(_mm512_maskz_andnot_epi64_dsl (bind-expr v0 env) (bind-expr vc_1 env) (bind-expr vc_2 env) 
		 (bind-expr v3 env) (bind-expr v4 env) (bind-expr size_i_o env) 
		 (bind-expr num_6 env) (bind-expr num_7 env) (bind-expr num_8 env) 
		 (bind-expr prec_i_o env) (bind-expr num_10 env) (bind-expr num_11 env) 
		 (bind-expr num_12 env))
	]
	[ (_mm512_mask_add_epi32_dsl vc_0 v1 v2 v3 v4 size_i_o num_6 num_7 num_8 prec_i_o num_10 num_11 num_12 num_13)
		(_mm512_mask_add_epi32_dsl (bind-expr vc_0 env) (bind-expr v1 env) (bind-expr v2 env) 
		 (bind-expr v3 env) (bind-expr v4 env) (bind-expr size_i_o env) 
		 (bind-expr num_6 env) (bind-expr num_7 env) (bind-expr num_8 env) 
		 (bind-expr prec_i_o env) (bind-expr num_10 env) (bind-expr num_11 env) 
		 (bind-expr num_12 env) (bind-expr num_13 env))
	]
	[ (_mm256_mask_and_epi32_dsl v0 vc_1 v2 v3 v4 size_i_o num_6 num_7 num_8 prec_i_o num_10 num_11 num_12)
		(_mm256_mask_and_epi32_dsl (bind-expr v0 env) (bind-expr vc_1 env) (bind-expr v2 env) 
		 (bind-expr v3 env) (bind-expr v4 env) (bind-expr size_i_o env) 
		 (bind-expr num_6 env) (bind-expr num_7 env) (bind-expr num_8 env) 
		 (bind-expr prec_i_o env) (bind-expr num_10 env) (bind-expr num_11 env) 
		 (bind-expr num_12 env))
	]
	[ (_mm_maskz_slli_epi32_dsl v0 v1 vc_2 vc_3 vc_4 vc_5 v6 size_i_o num_8 num_9 num_10 num_11 num_12 num_13 num_14 num_15 num_16 prec_i_o num_18 num_19 num_20 num_21)
		(_mm_maskz_slli_epi32_dsl (bind-expr v0 env) (bind-expr v1 env) (bind-expr vc_2 env) 
		 (bind-expr vc_3 env) (bind-expr vc_4 env) (bind-expr vc_5 env) 
		 (bind-expr v6 env) (bind-expr size_i_o env) (bind-expr num_8 env) 
		 (bind-expr num_9 env) (bind-expr num_10 env) (bind-expr num_11 env) 
		 (bind-expr num_12 env) (bind-expr num_13 env) (bind-expr num_14 env) 
		 (bind-expr num_15 env) (bind-expr num_16 env) (bind-expr prec_i_o env) 
		 (bind-expr num_18 env) (bind-expr num_19 env) (bind-expr num_20 env) 
		 (bind-expr num_21 env))
	]
	[ (_mm256_maddubs_epi16_dsl vc_0 v1 v2 size_i prec_o num_5 num_6 prec_i num_8 num_9 num_10 num_11)
		(_mm256_maddubs_epi16_dsl (bind-expr vc_0 env) (bind-expr v1 env) (bind-expr v2 env) 
		 (bind-expr size_i env) (bind-expr prec_o env) (bind-expr num_5 env) 
		 (bind-expr num_6 env) (bind-expr prec_i env) (bind-expr num_8 env) 
		 (bind-expr num_9 env) (bind-expr num_10 env) (bind-expr num_11 env))
	]
	[ (_mm_maskz_dpbusds_epi32_dsl v0 vc_1 vc_2 v3 v4 v5 size_i_o prec_i_o num_8 num_9 num_10 num_11 num_12 num_13 num_14 num_15 num_16 num_17 num_18 num_19 num_20 num_21)
		(_mm_maskz_dpbusds_epi32_dsl (bind-expr v0 env) (bind-expr vc_1 env) (bind-expr vc_2 env) 
		 (bind-expr v3 env) (bind-expr v4 env) (bind-expr v5 env) 
		 (bind-expr size_i_o env) (bind-expr prec_i_o env) (bind-expr num_8 env) 
		 (bind-expr num_9 env) (bind-expr num_10 env) (bind-expr num_11 env) 
		 (bind-expr num_12 env) (bind-expr num_13 env) (bind-expr num_14 env) 
		 (bind-expr num_15 env) (bind-expr num_16 env) (bind-expr num_17 env) 
		 (bind-expr num_18 env) (bind-expr num_19 env) (bind-expr num_20 env) 
		 (bind-expr num_21 env))
	]
	[ (_mm_srlv_epi32_dsl v0 vc_1 vc_2 v3 size_i_o num_5 num_6 num_7 num_8 num_9 num_10 prec_i_o num_12)
		(_mm_srlv_epi32_dsl (bind-expr v0 env) (bind-expr vc_1 env) (bind-expr vc_2 env) 
		 (bind-expr v3 env) (bind-expr size_i_o env) (bind-expr num_5 env) 
		 (bind-expr num_6 env) (bind-expr num_7 env) (bind-expr num_8 env) 
		 (bind-expr num_9 env) (bind-expr num_10 env) (bind-expr prec_i_o env) 
		 (bind-expr num_12 env))
	]
	[v v]
 )
)

;; ================================================================================
