#lang rosette
(require rosette/lib/synthax)
(require rosette/lib/angelic)
(require racket/pretty)
(require data/bit-vector)
(require rosette/lib/destruct)
(require rosette/solver/smt/boolector)

(require hydride/utils/bvops)
(require hydride/utils/misc)


(require hydride/ir/hydride/semantics)
(require hydride/ir/hydride/definition)
(require hydride/ir/hydride/length)


(provide (all-defined-out))


;; ================================================================================
;;                                DSL Binder
;; ================================================================================
(define (bind-expr prog env)
 (destruct prog
	[(dim-x id) (dim-x id)]
	[(dim-y id) (dim-y id)]
	[(idx-i id) (idx-i id)]
	[(idx-j id) (idx-j id)]
	[(reg id) (vector-ref env id)]
	[(lit v) (lit v)]
	[(nop v1) (nop (bind-expr v1 env))]
	[(idx-add i1 i2) (idx-add i1 i2)]
	[(idx-mul i1 i2) (idx-mul i1 i2)]
	[ (vector-load_dsl v0 size_i_o num_2 num_3 prec_i_o)
		(vector-load_dsl (bind-expr v0 env) (bind-expr size_i_o env) (bind-expr num_2 env) 
		 (bind-expr num_3 env) (bind-expr prec_i_o env))
	]
	[ (vector-two-input-swizzle_dsl v0 v1 num_2 prec_i_o num_4 lane_size num_6 num_7 num_8)
		(vector-two-input-swizzle_dsl (bind-expr v0 env) (bind-expr v1 env) (bind-expr num_2 env) 
		 (bind-expr prec_i_o env) (bind-expr num_4 env) (bind-expr lane_size env) 
		 (bind-expr num_6 env) (bind-expr num_7 env) (bind-expr num_8 env))
	]
	[ (interleave-vectors_dsl v0 v1 size_i_o prec_i_o)
		(interleave-vectors_dsl (bind-expr v0 env) (bind-expr v1 env) (bind-expr size_i_o env) 
		 (bind-expr prec_i_o env))
	]
	[ (interleave-vector_dsl v0 size_i_o prec_i_o)
		(interleave-vector_dsl (bind-expr v0 env) (bind-expr size_i_o env) (bind-expr prec_i_o env))
	]
	[ (deinterleave-vector_dsl v0 size_i_o prec_i_o)
		(deinterleave-vector_dsl (bind-expr v0 env) (bind-expr size_i_o env) (bind-expr prec_i_o env))
	]
	[ (_mm512_mulhi_epi16_dsl v0 v1 size_i_o lane_size num_4 prec_i_o num_6 num_7 num_8 num_9)
		(_mm512_mulhi_epi16_dsl (bind-expr v0 env) (bind-expr v1 env) (bind-expr size_i_o env) 
		 (bind-expr lane_size env) (bind-expr num_4 env) (bind-expr prec_i_o env) 
		 (bind-expr num_6 env) (bind-expr num_7 env) (bind-expr num_8 env) 
		 (bind-expr num_9 env))
	]
	[ (_m_from_int_dsl v0 size_o lane_size num_3 prec_i_o num_5 num_6 num_7 num_8)
		(_m_from_int_dsl (bind-expr v0 env) (bind-expr size_o env) (bind-expr lane_size env) 
		 (bind-expr num_3 env) (bind-expr prec_i_o env) (bind-expr num_5 env) 
		 (bind-expr num_6 env) (bind-expr num_7 env) (bind-expr num_8 env))
	]
	[ (_mm_hsubs_pi16_dsl v0 v1 size_i_o lane_size num_4 num_5 num_6 prec_i_o num_8 num_9 num_10 num_11 num_12 num_13 num_14)
		(_mm_hsubs_pi16_dsl (bind-expr v0 env) (bind-expr v1 env) (bind-expr size_i_o env) 
		 (bind-expr lane_size env) (bind-expr num_4 env) (bind-expr num_5 env) 
		 (bind-expr num_6 env) (bind-expr prec_i_o env) (bind-expr num_8 env) 
		 (bind-expr num_9 env) (bind-expr num_10 env) (bind-expr num_11 env) 
		 (bind-expr num_12 env) (bind-expr num_13 env) (bind-expr num_14 env))
	]
	[ (_mm256_maskz_sllv_epi32_dsl vc_0 vc_1 v2 v3 v4 size_i_o lane_size num_7 num_8 num_9 vc_10 prec_i_o num_12)
		(_mm256_maskz_sllv_epi32_dsl (bind-expr vc_0 env) (bind-expr vc_1 env) (bind-expr v2 env) 
		 (bind-expr v3 env) (bind-expr v4 env) (bind-expr size_i_o env) 
		 (bind-expr lane_size env) (bind-expr num_7 env) (bind-expr num_8 env) 
		 (bind-expr num_9 env) (bind-expr vc_10 env) (bind-expr prec_i_o env) 
		 (bind-expr num_12 env))
	]
	[ (_mm256_mask_dpbusd_epi32_dsl v0 v1 v2 v3 size_i_o lane_size num_6 num_7 num_8 num_9 num_10 num_11 num_12 num_13)
		(_mm256_mask_dpbusd_epi32_dsl (bind-expr v0 env) (bind-expr v1 env) (bind-expr v2 env) 
		 (bind-expr v3 env) (bind-expr size_i_o env) (bind-expr lane_size env) 
		 (bind-expr num_6 env) (bind-expr num_7 env) (bind-expr num_8 env) 
		 (bind-expr num_9 env) (bind-expr num_10 env) (bind-expr num_11 env) 
		 (bind-expr num_12 env) (bind-expr num_13 env))
	]
	[ (_mm256_maskz_sra_epi32_dsl vc_0 v1 v2 v3 size_i_o lane_size num_6 num_7 num_8 vc_9 num_10 num_11 prec_i_o vc_13 vc_14 num_15 num_16 num_17)
		(_mm256_maskz_sra_epi32_dsl (bind-expr vc_0 env) (bind-expr v1 env) (bind-expr v2 env) 
		 (bind-expr v3 env) (bind-expr size_i_o env) (bind-expr lane_size env) 
		 (bind-expr num_6 env) (bind-expr num_7 env) (bind-expr num_8 env) 
		 (bind-expr vc_9 env) (bind-expr num_10 env) (bind-expr num_11 env) 
		 (bind-expr prec_i_o env) (bind-expr vc_13 env) (bind-expr vc_14 env) 
		 (bind-expr num_15 env) (bind-expr num_16 env) (bind-expr num_17 env))
	]
	[ (_mm512_xor_epi64_dsl v0 v1 size_i_o lane_size num_4 prec_i_o num_6 num_7)
		(_mm512_xor_epi64_dsl (bind-expr v0 env) (bind-expr v1 env) (bind-expr size_i_o env) 
		 (bind-expr lane_size env) (bind-expr num_4 env) (bind-expr prec_i_o env) 
		 (bind-expr num_6 env) (bind-expr num_7 env))
	]
	[ (_mm512_broadcast_i64x4_dsl v0 size_i_o lane_size num_3 prec_i_o num_5 num_6 num_7)
		(_mm512_broadcast_i64x4_dsl (bind-expr v0 env) (bind-expr size_i_o env) (bind-expr lane_size env) 
		 (bind-expr num_3 env) (bind-expr prec_i_o env) (bind-expr num_5 env) 
		 (bind-expr num_6 env) (bind-expr num_7 env))
	]
	[ (_mm512_and_epi32_dsl v0 v1 size_i_o lane_size num_4 prec_i_o num_6 num_7)
		(_mm512_and_epi32_dsl (bind-expr v0 env) (bind-expr v1 env) (bind-expr size_i_o env) 
		 (bind-expr lane_size env) (bind-expr num_4 env) (bind-expr prec_i_o env) 
		 (bind-expr num_6 env) (bind-expr num_7 env))
	]
	[ (_mm512_subs_epu16_dsl v0 v1 size_i_o lane_size num_4 prec_i_o num_6 num_7)
		(_mm512_subs_epu16_dsl (bind-expr v0 env) (bind-expr v1 env) (bind-expr size_i_o env) 
		 (bind-expr lane_size env) (bind-expr num_4 env) (bind-expr prec_i_o env) 
		 (bind-expr num_6 env) (bind-expr num_7 env))
	]
	[ (_mm256_maskz_packus_epi16_dsl vc_0 v1 v2 v3 size_i prec_i num_6 num_7 num_8 num_9 num_10 num_11 num_12 num_13 num_14)
		(_mm256_maskz_packus_epi16_dsl (bind-expr vc_0 env) (bind-expr v1 env) (bind-expr v2 env) 
		 (bind-expr v3 env) (bind-expr size_i env) (bind-expr prec_i env) 
		 (bind-expr num_6 env) (bind-expr num_7 env) (bind-expr num_8 env) 
		 (bind-expr num_9 env) (bind-expr num_10 env) (bind-expr num_11 env) 
		 (bind-expr num_12 env) (bind-expr num_13 env) (bind-expr num_14 env))
	]
	[ (_mm512_maskz_packus_epi32_dsl vc_0 v1 v2 v3 size_i prec_i num_6 num_7 num_8 num_9 num_10 num_11 num_12)
		(_mm512_maskz_packus_epi32_dsl (bind-expr vc_0 env) (bind-expr v1 env) (bind-expr v2 env) 
		 (bind-expr v3 env) (bind-expr size_i env) (bind-expr prec_i env) 
		 (bind-expr num_6 env) (bind-expr num_7 env) (bind-expr num_8 env) 
		 (bind-expr num_9 env) (bind-expr num_10 env) (bind-expr num_11 env) 
		 (bind-expr num_12 env))
	]
	[ (_mm512_maskz_srl_epi64_dsl vc_0 vc_1 v2 v3 v4 size_i_o lane_size num_7 num_8 num_9 vc_10 num_11 prec_i_o num_13 num_14)
		(_mm512_maskz_srl_epi64_dsl (bind-expr vc_0 env) (bind-expr vc_1 env) (bind-expr v2 env) 
		 (bind-expr v3 env) (bind-expr v4 env) (bind-expr size_i_o env) 
		 (bind-expr lane_size env) (bind-expr num_7 env) (bind-expr num_8 env) 
		 (bind-expr num_9 env) (bind-expr vc_10 env) (bind-expr num_11 env) 
		 (bind-expr prec_i_o env) (bind-expr num_13 env) (bind-expr num_14 env))
	]
	[ (_mm_maskz_packus_epi32_dsl vc_0 v1 v2 v3 size_i_o lane_size num_6 prec_i num_8 num_9 num_10 num_11 num_12)
		(_mm_maskz_packus_epi32_dsl (bind-expr vc_0 env) (bind-expr v1 env) (bind-expr v2 env) 
		 (bind-expr v3 env) (bind-expr size_i_o env) (bind-expr lane_size env) 
		 (bind-expr num_6 env) (bind-expr prec_i env) (bind-expr num_8 env) 
		 (bind-expr num_9 env) (bind-expr num_10 env) (bind-expr num_11 env) 
		 (bind-expr num_12 env))
	]
	[ (_mm256_maskz_adds_epu16_dsl vc_0 v1 v2 v3 size_i_o lane_size num_6 prec_i_o num_8 num_9)
		(_mm256_maskz_adds_epu16_dsl (bind-expr vc_0 env) (bind-expr v1 env) (bind-expr v2 env) 
		 (bind-expr v3 env) (bind-expr size_i_o env) (bind-expr lane_size env) 
		 (bind-expr num_6 env) (bind-expr prec_i_o env) (bind-expr num_8 env) 
		 (bind-expr num_9 env))
	]
	[ (_mm512_maskz_packs_epi16_dsl vc_0 v1 v2 v3 size_i prec_i num_6 num_7 num_8 num_9 num_10 num_11 num_12)
		(_mm512_maskz_packs_epi16_dsl (bind-expr vc_0 env) (bind-expr v1 env) (bind-expr v2 env) 
		 (bind-expr v3 env) (bind-expr size_i env) (bind-expr prec_i env) 
		 (bind-expr num_6 env) (bind-expr num_7 env) (bind-expr num_8 env) 
		 (bind-expr num_9 env) (bind-expr num_10 env) (bind-expr num_11 env) 
		 (bind-expr num_12 env))
	]
	[ (_mm_maskz_xor_epi64_dsl vc_0 v1 v2 v3 size_i_o lane_size num_6 prec_i_o num_8 num_9)
		(_mm_maskz_xor_epi64_dsl (bind-expr vc_0 env) (bind-expr v1 env) (bind-expr v2 env) 
		 (bind-expr v3 env) (bind-expr size_i_o env) (bind-expr lane_size env) 
		 (bind-expr num_6 env) (bind-expr prec_i_o env) (bind-expr num_8 env) 
		 (bind-expr num_9 env))
	]
	[ (_mm256_min_epi8_dsl v0 v1 size_i_o lane_size num_4 prec_i_o num_6 num_7)
		(_mm256_min_epi8_dsl (bind-expr v0 env) (bind-expr v1 env) (bind-expr size_i_o env) 
		 (bind-expr lane_size env) (bind-expr num_4 env) (bind-expr prec_i_o env) 
		 (bind-expr num_6 env) (bind-expr num_7 env))
	]
	[ (_mm256_cvtepi16_epi8_dsl v0 size_i_o lane_size num_3 prec_o num_5 prec_i num_7)
		(_mm256_cvtepi16_epi8_dsl (bind-expr v0 env) (bind-expr size_i_o env) (bind-expr lane_size env) 
		 (bind-expr num_3 env) (bind-expr prec_o env) (bind-expr num_5 env) 
		 (bind-expr prec_i env) (bind-expr num_7 env))
	]
	[ (_mm_extract_epi32_dsl v0 v1 size_o lane_size num_4 num_5 num_6 prec_o num_8 num_9 prec_i vc_11 num_12 num_13 num_14 num_15)
		(_mm_extract_epi32_dsl (bind-expr v0 env) (bind-expr v1 env) (bind-expr size_o env) 
		 (bind-expr lane_size env) (bind-expr num_4 env) (bind-expr num_5 env) 
		 (bind-expr num_6 env) (bind-expr prec_o env) (bind-expr num_8 env) 
		 (bind-expr num_9 env) (bind-expr prec_i env) (bind-expr vc_11 env) 
		 (bind-expr num_12 env) (bind-expr num_13 env) (bind-expr num_14 env) 
		 (bind-expr num_15 env))
	]
	[ (_mm256_hsub_epi32_dsl v0 v1 size_i_o lane_size num_4 num_5 num_6 prec_i_o num_8 num_9 num_10 num_11 num_12 num_13 num_14 num_15)
		(_mm256_hsub_epi32_dsl (bind-expr v0 env) (bind-expr v1 env) (bind-expr size_i_o env) 
		 (bind-expr lane_size env) (bind-expr num_4 env) (bind-expr num_5 env) 
		 (bind-expr num_6 env) (bind-expr prec_i_o env) (bind-expr num_8 env) 
		 (bind-expr num_9 env) (bind-expr num_10 env) (bind-expr num_11 env) 
		 (bind-expr num_12 env) (bind-expr num_13 env) (bind-expr num_14 env) 
		 (bind-expr num_15 env))
	]
	[ (_mm_maskz_packs_epi32_dsl vc_0 v1 v2 v3 size_i_o lane_size num_6 prec_i num_8 num_9 num_10 num_11 num_12)
		(_mm_maskz_packs_epi32_dsl (bind-expr vc_0 env) (bind-expr v1 env) (bind-expr v2 env) 
		 (bind-expr v3 env) (bind-expr size_i_o env) (bind-expr lane_size env) 
		 (bind-expr num_6 env) (bind-expr prec_i env) (bind-expr num_8 env) 
		 (bind-expr num_9 env) (bind-expr num_10 env) (bind-expr num_11 env) 
		 (bind-expr num_12 env))
	]
	[ (_mm256_maskz_packus_epi32_dsl vc_0 v1 v2 v3 size_i prec_i num_6 num_7 num_8 num_9 num_10 num_11 num_12 num_13 num_14)
		(_mm256_maskz_packus_epi32_dsl (bind-expr vc_0 env) (bind-expr v1 env) (bind-expr v2 env) 
		 (bind-expr v3 env) (bind-expr size_i env) (bind-expr prec_i env) 
		 (bind-expr num_6 env) (bind-expr num_7 env) (bind-expr num_8 env) 
		 (bind-expr num_9 env) (bind-expr num_10 env) (bind-expr num_11 env) 
		 (bind-expr num_12 env) (bind-expr num_13 env) (bind-expr num_14 env))
	]
	[ (_m_psrldi_dsl vc_0 v1 v2 size_i_o lane_size num_5 num_6 num_7 vc_8 num_9 prec_i_o num_11 num_12 num_13)
		(_m_psrldi_dsl (bind-expr vc_0 env) (bind-expr v1 env) (bind-expr v2 env) 
		 (bind-expr size_i_o env) (bind-expr lane_size env) (bind-expr num_5 env) 
		 (bind-expr num_6 env) (bind-expr num_7 env) (bind-expr vc_8 env) 
		 (bind-expr num_9 env) (bind-expr prec_i_o env) (bind-expr num_11 env) 
		 (bind-expr num_12 env) (bind-expr num_13 env))
	]
	[ (_mm256_mask_slli_epi64_dsl vc_0 v1 v2 v3 v4 size_i_o lane_size num_7 num_8 num_9 vc_10 num_11 prec_i_o num_13 num_14 num_15)
		(_mm256_mask_slli_epi64_dsl (bind-expr vc_0 env) (bind-expr v1 env) (bind-expr v2 env) 
		 (bind-expr v3 env) (bind-expr v4 env) (bind-expr size_i_o env) 
		 (bind-expr lane_size env) (bind-expr num_7 env) (bind-expr num_8 env) 
		 (bind-expr num_9 env) (bind-expr vc_10 env) (bind-expr num_11 env) 
		 (bind-expr prec_i_o env) (bind-expr num_13 env) (bind-expr num_14 env) 
		 (bind-expr num_15 env))
	]
	[ (_mm512_xor_si512_dsl v0 v1 size_o lane_size num_4 prec_i_o num_6 num_7 num_8 num_9 num_10)
		(_mm512_xor_si512_dsl (bind-expr v0 env) (bind-expr v1 env) (bind-expr size_o env) 
		 (bind-expr lane_size env) (bind-expr num_4 env) (bind-expr prec_i_o env) 
		 (bind-expr num_6 env) (bind-expr num_7 env) (bind-expr num_8 env) 
		 (bind-expr num_9 env) (bind-expr num_10 env))
	]
	[ (_mm256_srl_epi16_dsl vc_0 v1 v2 size_i_o lane_size num_5 num_6 num_7 vc_8 num_9 num_10 prec_i_o num_12 num_13 num_14)
		(_mm256_srl_epi16_dsl (bind-expr vc_0 env) (bind-expr v1 env) (bind-expr v2 env) 
		 (bind-expr size_i_o env) (bind-expr lane_size env) (bind-expr num_5 env) 
		 (bind-expr num_6 env) (bind-expr num_7 env) (bind-expr vc_8 env) 
		 (bind-expr num_9 env) (bind-expr num_10 env) (bind-expr prec_i_o env) 
		 (bind-expr num_12 env) (bind-expr num_13 env) (bind-expr num_14 env))
	]
	[ (_mm_maskz_cvtepu8_epi64_dsl vc_0 v1 v2 size_i_o lane_size num_5 num_6 num_7 prec_i_o num_9)
		(_mm_maskz_cvtepu8_epi64_dsl (bind-expr vc_0 env) (bind-expr v1 env) (bind-expr v2 env) 
		 (bind-expr size_i_o env) (bind-expr lane_size env) (bind-expr num_5 env) 
		 (bind-expr num_6 env) (bind-expr num_7 env) (bind-expr prec_i_o env) 
		 (bind-expr num_9 env))
	]
	[ (_mm512_srai_epi64_dsl v0 v1 size_i_o lane_size num_4 num_5 num_6 vc_7 num_8 prec_i_o vc_10 vc_11 num_12 num_13 num_14)
		(_mm512_srai_epi64_dsl (bind-expr v0 env) (bind-expr v1 env) (bind-expr size_i_o env) 
		 (bind-expr lane_size env) (bind-expr num_4 env) (bind-expr num_5 env) 
		 (bind-expr num_6 env) (bind-expr vc_7 env) (bind-expr num_8 env) 
		 (bind-expr prec_i_o env) (bind-expr vc_10 env) (bind-expr vc_11 env) 
		 (bind-expr num_12 env) (bind-expr num_13 env) (bind-expr num_14 env))
	]
	[ (_m_paddd_dsl v0 v1 size_i_o lane_size num_4 prec_i_o num_6 num_7)
		(_m_paddd_dsl (bind-expr v0 env) (bind-expr v1 env) (bind-expr size_i_o env) 
		 (bind-expr lane_size env) (bind-expr num_4 env) (bind-expr prec_i_o env) 
		 (bind-expr num_6 env) (bind-expr num_7 env))
	]
	[ (_mm512_subr_epi32_dsl v0 v1 size_i_o lane_size num_4 prec_i_o num_6 num_7)
		(_mm512_subr_epi32_dsl (bind-expr v0 env) (bind-expr v1 env) (bind-expr size_i_o env) 
		 (bind-expr lane_size env) (bind-expr num_4 env) (bind-expr prec_i_o env) 
		 (bind-expr num_6 env) (bind-expr num_7 env))
	]
	[ (_mm256_cvtsepi32_epi8_dsl v0 size_i_o lane_size num_3 prec_o num_5 prec_i num_7)
		(_mm256_cvtsepi32_epi8_dsl (bind-expr v0 env) (bind-expr size_i_o env) (bind-expr lane_size env) 
		 (bind-expr num_3 env) (bind-expr prec_o env) (bind-expr num_5 env) 
		 (bind-expr prec_i env) (bind-expr num_7 env))
	]
	[ (_mm512_mulhi_epu32_dsl v0 v1 size_i_o lane_size num_4 prec_i_o num_6 vc_7 num_8 num_9)
		(_mm512_mulhi_epu32_dsl (bind-expr v0 env) (bind-expr v1 env) (bind-expr size_i_o env) 
		 (bind-expr lane_size env) (bind-expr num_4 env) (bind-expr prec_i_o env) 
		 (bind-expr num_6 env) (bind-expr vc_7 env) (bind-expr num_8 env) 
		 (bind-expr num_9 env))
	]
	[ (_mm256_mask_srav_epi16_dsl v0 v1 v2 v3 size_i_o lane_size num_6 num_7 num_8 vc_9 prec_i_o vc_11 vc_12 num_13)
		(_mm256_mask_srav_epi16_dsl (bind-expr v0 env) (bind-expr v1 env) (bind-expr v2 env) 
		 (bind-expr v3 env) (bind-expr size_i_o env) (bind-expr lane_size env) 
		 (bind-expr num_6 env) (bind-expr num_7 env) (bind-expr num_8 env) 
		 (bind-expr vc_9 env) (bind-expr prec_i_o env) (bind-expr vc_11 env) 
		 (bind-expr vc_12 env) (bind-expr num_13 env))
	]
	[ (_mm512_mask3_fmadd_epi32_dsl v0 v1 v2 v3 size_i_o lane_size num_6 prec_i_o num_8 num_9 num_10)
		(_mm512_mask3_fmadd_epi32_dsl (bind-expr v0 env) (bind-expr v1 env) (bind-expr v2 env) 
		 (bind-expr v3 env) (bind-expr size_i_o env) (bind-expr lane_size env) 
		 (bind-expr num_6 env) (bind-expr prec_i_o env) (bind-expr num_8 env) 
		 (bind-expr num_9 env) (bind-expr num_10 env))
	]
	[ (_mm_mask_sra_epi64_dsl v0 v1 v2 v3 size_i_o lane_size num_6 num_7 num_8 vc_9 num_10 prec_i_o vc_12 vc_13 num_14 num_15)
		(_mm_mask_sra_epi64_dsl (bind-expr v0 env) (bind-expr v1 env) (bind-expr v2 env) 
		 (bind-expr v3 env) (bind-expr size_i_o env) (bind-expr lane_size env) 
		 (bind-expr num_6 env) (bind-expr num_7 env) (bind-expr num_8 env) 
		 (bind-expr vc_9 env) (bind-expr num_10 env) (bind-expr prec_i_o env) 
		 (bind-expr vc_12 env) (bind-expr vc_13 env) (bind-expr num_14 env) 
		 (bind-expr num_15 env))
	]
	[ (_mm_srav_epi64_dsl v0 v1 size_i_o lane_size num_4 num_5 num_6 vc_7 prec_i_o vc_9 vc_10 num_11)
		(_mm_srav_epi64_dsl (bind-expr v0 env) (bind-expr v1 env) (bind-expr size_i_o env) 
		 (bind-expr lane_size env) (bind-expr num_4 env) (bind-expr num_5 env) 
		 (bind-expr num_6 env) (bind-expr vc_7 env) (bind-expr prec_i_o env) 
		 (bind-expr vc_9 env) (bind-expr vc_10 env) (bind-expr num_11 env))
	]
	[ (_mm_mask_min_epi8_dsl v0 v1 v2 v3 size_i_o lane_size num_6 prec_i_o num_8 num_9)
		(_mm_mask_min_epi8_dsl (bind-expr v0 env) (bind-expr v1 env) (bind-expr v2 env) 
		 (bind-expr v3 env) (bind-expr size_i_o env) (bind-expr lane_size env) 
		 (bind-expr num_6 env) (bind-expr prec_i_o env) (bind-expr num_8 env) 
		 (bind-expr num_9 env))
	]
	[ (_mm_mask_min_epu16_dsl v0 v1 v2 v3 size_i_o lane_size num_6 prec_i_o num_8 num_9)
		(_mm_mask_min_epu16_dsl (bind-expr v0 env) (bind-expr v1 env) (bind-expr v2 env) 
		 (bind-expr v3 env) (bind-expr size_i_o env) (bind-expr lane_size env) 
		 (bind-expr num_6 env) (bind-expr prec_i_o env) (bind-expr num_8 env) 
		 (bind-expr num_9 env))
	]
	[ (_m_punpckhdq_dsl v0 v1 size_o lane_size num_4 prec_i_o num_6 num_7 num_8 num_9 num_10 num_11)
		(_m_punpckhdq_dsl (bind-expr v0 env) (bind-expr v1 env) (bind-expr size_o env) 
		 (bind-expr lane_size env) (bind-expr num_4 env) (bind-expr prec_i_o env) 
		 (bind-expr num_6 env) (bind-expr num_7 env) (bind-expr num_8 env) 
		 (bind-expr num_9 env) (bind-expr num_10 env) (bind-expr num_11 env))
	]
	[ (_mm256_maskz_packs_epi16_dsl vc_0 v1 v2 v3 size_i prec_i num_6 num_7 num_8 num_9 num_10 num_11 num_12 num_13 num_14)
		(_mm256_maskz_packs_epi16_dsl (bind-expr vc_0 env) (bind-expr v1 env) (bind-expr v2 env) 
		 (bind-expr v3 env) (bind-expr size_i env) (bind-expr prec_i env) 
		 (bind-expr num_6 env) (bind-expr num_7 env) (bind-expr num_8 env) 
		 (bind-expr num_9 env) (bind-expr num_10 env) (bind-expr num_11 env) 
		 (bind-expr num_12 env) (bind-expr num_13 env) (bind-expr num_14 env))
	]
	[ (_mm_cmplt_epu16_mask_dsl v0 v1 size_i_o lane_size num_4 prec_o num_6 vc_7 vc_8 prec_i num_10)
		(_mm_cmplt_epu16_mask_dsl (bind-expr v0 env) (bind-expr v1 env) (bind-expr size_i_o env) 
		 (bind-expr lane_size env) (bind-expr num_4 env) (bind-expr prec_o env) 
		 (bind-expr num_6 env) (bind-expr vc_7 env) (bind-expr vc_8 env) 
		 (bind-expr prec_i env) (bind-expr num_10 env))
	]
	[ (_mm512_mask_srl_epi32_dsl vc_0 v1 v2 v3 v4 size_i_o lane_size num_7 num_8 num_9 vc_10 num_11 num_12 prec_i_o num_14 num_15 num_16)
		(_mm512_mask_srl_epi32_dsl (bind-expr vc_0 env) (bind-expr v1 env) (bind-expr v2 env) 
		 (bind-expr v3 env) (bind-expr v4 env) (bind-expr size_i_o env) 
		 (bind-expr lane_size env) (bind-expr num_7 env) (bind-expr num_8 env) 
		 (bind-expr num_9 env) (bind-expr vc_10 env) (bind-expr num_11 env) 
		 (bind-expr num_12 env) (bind-expr prec_i_o env) (bind-expr num_14 env) 
		 (bind-expr num_15 env) (bind-expr num_16 env))
	]
	[ (_mm256_mask_cvtepi32_epi8_dsl v0 v1 v2 size_i_o lane_size num_5 prec_i_o num_7 num_8 num_9)
		(_mm256_mask_cvtepi32_epi8_dsl (bind-expr v0 env) (bind-expr v1 env) (bind-expr v2 env) 
		 (bind-expr size_i_o env) (bind-expr lane_size env) (bind-expr num_5 env) 
		 (bind-expr prec_i_o env) (bind-expr num_7 env) (bind-expr num_8 env) 
		 (bind-expr num_9 env))
	]
	[ (_mm_mask_cmpeq_epi8_mask_dsl vc_0 v1 v2 v3 size_i_o lane_size num_6 prec_o num_8 vc_9 vc_10 prec_i num_12)
		(_mm_mask_cmpeq_epi8_mask_dsl (bind-expr vc_0 env) (bind-expr v1 env) (bind-expr v2 env) 
		 (bind-expr v3 env) (bind-expr size_i_o env) (bind-expr lane_size env) 
		 (bind-expr num_6 env) (bind-expr prec_o env) (bind-expr num_8 env) 
		 (bind-expr vc_9 env) (bind-expr vc_10 env) (bind-expr prec_i env) 
		 (bind-expr num_12 env))
	]
	[ (_mm256_adds_epu16_dsl v0 v1 size_i_o lane_size num_4 prec_i_o num_6 num_7)
		(_mm256_adds_epu16_dsl (bind-expr v0 env) (bind-expr v1 env) (bind-expr size_i_o env) 
		 (bind-expr lane_size env) (bind-expr num_4 env) (bind-expr prec_i_o env) 
		 (bind-expr num_6 env) (bind-expr num_7 env))
	]
	[ (_mm_maskz_mulhi_epi16_dsl vc_0 v1 v2 v3 size_i_o lane_size num_6 prec_i_o num_8 num_9 num_10 num_11)
		(_mm_maskz_mulhi_epi16_dsl (bind-expr vc_0 env) (bind-expr v1 env) (bind-expr v2 env) 
		 (bind-expr v3 env) (bind-expr size_i_o env) (bind-expr lane_size env) 
		 (bind-expr num_6 env) (bind-expr prec_i_o env) (bind-expr num_8 env) 
		 (bind-expr num_9 env) (bind-expr num_10 env) (bind-expr num_11 env))
	]
	[ (_mm256_mul_epu32_dsl v0 v1 size_i_o lane_size num_4 prec_i num_6 prec_o num_8)
		(_mm256_mul_epu32_dsl (bind-expr v0 env) (bind-expr v1 env) (bind-expr size_i_o env) 
		 (bind-expr lane_size env) (bind-expr num_4 env) (bind-expr prec_i env) 
		 (bind-expr num_6 env) (bind-expr prec_o env) (bind-expr num_8 env))
	]
	[ (_mm_maskz_dpwssd_epi32_dsl vc_0 v1 v2 v3 v4 size_i_o lane_size num_7 num_8 num_9 num_10 num_11 num_12 num_13)
		(_mm_maskz_dpwssd_epi32_dsl (bind-expr vc_0 env) (bind-expr v1 env) (bind-expr v2 env) 
		 (bind-expr v3 env) (bind-expr v4 env) (bind-expr size_i_o env) 
		 (bind-expr lane_size env) (bind-expr num_7 env) (bind-expr num_8 env) 
		 (bind-expr num_9 env) (bind-expr num_10 env) (bind-expr num_11 env) 
		 (bind-expr num_12 env) (bind-expr num_13 env))
	]
	[ (_mm512_mask_cmpgt_epi8_mask_dsl vc_0 v1 v2 v3 size_i_o lane_size num_6 prec_o num_8 vc_9 vc_10 prec_i num_12)
		(_mm512_mask_cmpgt_epi8_mask_dsl (bind-expr vc_0 env) (bind-expr v1 env) (bind-expr v2 env) 
		 (bind-expr v3 env) (bind-expr size_i_o env) (bind-expr lane_size env) 
		 (bind-expr num_6 env) (bind-expr prec_o env) (bind-expr num_8 env) 
		 (bind-expr vc_9 env) (bind-expr vc_10 env) (bind-expr prec_i env) 
		 (bind-expr num_12 env))
	]
	[ (_mm256_mask_blend_epi32_dsl v0 v1 v2 size_i_o lane_size num_5 prec_i_o num_7 num_8)
		(_mm256_mask_blend_epi32_dsl (bind-expr v0 env) (bind-expr v1 env) (bind-expr v2 env) 
		 (bind-expr size_i_o env) (bind-expr lane_size env) (bind-expr num_5 env) 
		 (bind-expr prec_i_o env) (bind-expr num_7 env) (bind-expr num_8 env))
	]
	[ (_mm512_srlv_epi64_dsl vc_0 v1 v2 size_i_o lane_size num_5 num_6 num_7 vc_8 prec_i_o num_10)
		(_mm512_srlv_epi64_dsl (bind-expr vc_0 env) (bind-expr v1 env) (bind-expr v2 env) 
		 (bind-expr size_i_o env) (bind-expr lane_size env) (bind-expr num_5 env) 
		 (bind-expr num_6 env) (bind-expr num_7 env) (bind-expr vc_8 env) 
		 (bind-expr prec_i_o env) (bind-expr num_10 env))
	]
	[ (_mm256_hsubs_epi16_dsl v0 v1 size_i_o lane_size num_4 num_5 num_6 prec_i_o num_8 num_9 num_10 num_11 num_12 num_13 num_14 num_15)
		(_mm256_hsubs_epi16_dsl (bind-expr v0 env) (bind-expr v1 env) (bind-expr size_i_o env) 
		 (bind-expr lane_size env) (bind-expr num_4 env) (bind-expr num_5 env) 
		 (bind-expr num_6 env) (bind-expr prec_i_o env) (bind-expr num_8 env) 
		 (bind-expr num_9 env) (bind-expr num_10 env) (bind-expr num_11 env) 
		 (bind-expr num_12 env) (bind-expr num_13 env) (bind-expr num_14 env) 
		 (bind-expr num_15 env))
	]
	[ (_mm512_or_si512_dsl v0 v1 size_o lane_size num_4 prec_i_o num_6 num_7 num_8 num_9 num_10)
		(_mm512_or_si512_dsl (bind-expr v0 env) (bind-expr v1 env) (bind-expr size_o env) 
		 (bind-expr lane_size env) (bind-expr num_4 env) (bind-expr prec_i_o env) 
		 (bind-expr num_6 env) (bind-expr num_7 env) (bind-expr num_8 env) 
		 (bind-expr num_9 env) (bind-expr num_10 env))
	]
	[ (_mm_broadcastmb_epi64_dsl v0 size_o lane_size num_3 prec_i num_5 prec_o num_7 num_8)
		(_mm_broadcastmb_epi64_dsl (bind-expr v0 env) (bind-expr size_o env) (bind-expr lane_size env) 
		 (bind-expr num_3 env) (bind-expr prec_i env) (bind-expr num_5 env) 
		 (bind-expr prec_o env) (bind-expr num_7 env) (bind-expr num_8 env))
	]
	[ (_mm512_maskz_cvtusepi16_epi8_dsl vc_0 v1 v2 size_i_o lane_size num_5 prec_i_o num_7 num_8 num_9)
		(_mm512_maskz_cvtusepi16_epi8_dsl (bind-expr vc_0 env) (bind-expr v1 env) (bind-expr v2 env) 
		 (bind-expr size_i_o env) (bind-expr lane_size env) (bind-expr num_5 env) 
		 (bind-expr prec_i_o env) (bind-expr num_7 env) (bind-expr num_8 env) 
		 (bind-expr num_9 env))
	]
	[ (_mm512_maskz_srli_epi64_dsl vc_0 vc_1 v2 v3 v4 size_i_o lane_size num_7 num_8 num_9 vc_10 num_11 prec_i_o num_13 num_14 num_15)
		(_mm512_maskz_srli_epi64_dsl (bind-expr vc_0 env) (bind-expr vc_1 env) (bind-expr v2 env) 
		 (bind-expr v3 env) (bind-expr v4 env) (bind-expr size_i_o env) 
		 (bind-expr lane_size env) (bind-expr num_7 env) (bind-expr num_8 env) 
		 (bind-expr num_9 env) (bind-expr vc_10 env) (bind-expr num_11 env) 
		 (bind-expr prec_i_o env) (bind-expr num_13 env) (bind-expr num_14 env) 
		 (bind-expr num_15 env))
	]
	[ (_mm_extract_epi8_dsl v0 v1 size_o lane_size num_4 num_5 num_6 prec_o num_8 num_9 prec_i vc_11 num_12 num_13 num_14)
		(_mm_extract_epi8_dsl (bind-expr v0 env) (bind-expr v1 env) (bind-expr size_o env) 
		 (bind-expr lane_size env) (bind-expr num_4 env) (bind-expr num_5 env) 
		 (bind-expr num_6 env) (bind-expr prec_o env) (bind-expr num_8 env) 
		 (bind-expr num_9 env) (bind-expr prec_i env) (bind-expr vc_11 env) 
		 (bind-expr num_12 env) (bind-expr num_13 env) (bind-expr num_14 env))
	]
	[ (_mm_cmpeq_epu8_mask_dsl v0 v1 size_i_o lane_size num_4 prec_o num_6 vc_7 vc_8 prec_i num_10)
		(_mm_cmpeq_epu8_mask_dsl (bind-expr v0 env) (bind-expr v1 env) (bind-expr size_i_o env) 
		 (bind-expr lane_size env) (bind-expr num_4 env) (bind-expr prec_o env) 
		 (bind-expr num_6 env) (bind-expr vc_7 env) (bind-expr vc_8 env) 
		 (bind-expr prec_i env) (bind-expr num_10 env))
	]
	[ (_mm_maskz_srlv_epi32_dsl vc_0 vc_1 v2 v3 v4 size_i_o lane_size num_7 num_8 num_9 vc_10 prec_i_o num_12)
		(_mm_maskz_srlv_epi32_dsl (bind-expr vc_0 env) (bind-expr vc_1 env) (bind-expr v2 env) 
		 (bind-expr v3 env) (bind-expr v4 env) (bind-expr size_i_o env) 
		 (bind-expr lane_size env) (bind-expr num_7 env) (bind-expr num_8 env) 
		 (bind-expr num_9 env) (bind-expr vc_10 env) (bind-expr prec_i_o env) 
		 (bind-expr num_12 env))
	]
	[ (_mm512_max_epu32_dsl v0 v1 size_i_o lane_size num_4 prec_i_o num_6 num_7)
		(_mm512_max_epu32_dsl (bind-expr v0 env) (bind-expr v1 env) (bind-expr size_i_o env) 
		 (bind-expr lane_size env) (bind-expr num_4 env) (bind-expr prec_i_o env) 
		 (bind-expr num_6 env) (bind-expr num_7 env))
	]
	[ (_mm_maskz_dpwssds_epi32_dsl vc_0 v1 v2 v3 v4 size_i_o lane_size num_7 num_8 num_9 num_10 num_11 num_12 num_13)
		(_mm_maskz_dpwssds_epi32_dsl (bind-expr vc_0 env) (bind-expr v1 env) (bind-expr v2 env) 
		 (bind-expr v3 env) (bind-expr v4 env) (bind-expr size_i_o env) 
		 (bind-expr lane_size env) (bind-expr num_7 env) (bind-expr num_8 env) 
		 (bind-expr num_9 env) (bind-expr num_10 env) (bind-expr num_11 env) 
		 (bind-expr num_12 env) (bind-expr num_13 env))
	]
	[ (_mm_maskz_sll_epi64_dsl vc_0 vc_1 v2 v3 v4 size_i_o lane_size num_7 num_8 num_9 vc_10 num_11 prec_i_o num_13 num_14)
		(_mm_maskz_sll_epi64_dsl (bind-expr vc_0 env) (bind-expr vc_1 env) (bind-expr v2 env) 
		 (bind-expr v3 env) (bind-expr v4 env) (bind-expr size_i_o env) 
		 (bind-expr lane_size env) (bind-expr num_7 env) (bind-expr num_8 env) 
		 (bind-expr num_9 env) (bind-expr vc_10 env) (bind-expr num_11 env) 
		 (bind-expr prec_i_o env) (bind-expr num_13 env) (bind-expr num_14 env))
	]
	[ (_mm_movpi64_epi64_dsl v0 size_o lane_size num_3 prec_i_o num_5 num_6 num_7 num_8)
		(_mm_movpi64_epi64_dsl (bind-expr v0 env) (bind-expr size_o env) (bind-expr lane_size env) 
		 (bind-expr num_3 env) (bind-expr prec_i_o env) (bind-expr num_5 env) 
		 (bind-expr num_6 env) (bind-expr num_7 env) (bind-expr num_8 env))
	]
	[ (_mm256_mask_packus_epi16_dsl v0 v1 v2 v3 size_i num_5 num_6 prec_i num_8 num_9 num_10 num_11 num_12 num_13 num_14)
		(_mm256_mask_packus_epi16_dsl (bind-expr v0 env) (bind-expr v1 env) (bind-expr v2 env) 
		 (bind-expr v3 env) (bind-expr size_i env) (bind-expr num_5 env) 
		 (bind-expr num_6 env) (bind-expr prec_i env) (bind-expr num_8 env) 
		 (bind-expr num_9 env) (bind-expr num_10 env) (bind-expr num_11 env) 
		 (bind-expr num_12 env) (bind-expr num_13 env) (bind-expr num_14 env))
	]
	[ (_mm512_fmadd_epi32_dsl v0 v1 v2 size_i_o lane_size num_5 prec_i_o num_7 num_8 num_9)
		(_mm512_fmadd_epi32_dsl (bind-expr v0 env) (bind-expr v1 env) (bind-expr v2 env) 
		 (bind-expr size_i_o env) (bind-expr lane_size env) (bind-expr num_5 env) 
		 (bind-expr prec_i_o env) (bind-expr num_7 env) (bind-expr num_8 env) 
		 (bind-expr num_9 env))
	]
	[ (_mm_mask_add_epi32_dsl v0 v1 v2 v3 size_i_o lane_size num_6 prec_i_o num_8 num_9)
		(_mm_mask_add_epi32_dsl (bind-expr v0 env) (bind-expr v1 env) (bind-expr v2 env) 
		 (bind-expr v3 env) (bind-expr size_i_o env) (bind-expr lane_size env) 
		 (bind-expr num_6 env) (bind-expr prec_i_o env) (bind-expr num_8 env) 
		 (bind-expr num_9 env))
	]
	[ (_mm_mul_su32_dsl v0 v1 size_o lane_size num_4 prec_i num_6 prec_o num_8 num_9 num_10 num_11)
		(_mm_mul_su32_dsl (bind-expr v0 env) (bind-expr v1 env) (bind-expr size_o env) 
		 (bind-expr lane_size env) (bind-expr num_4 env) (bind-expr prec_i env) 
		 (bind-expr num_6 env) (bind-expr prec_o env) (bind-expr num_8 env) 
		 (bind-expr num_9 env) (bind-expr num_10 env) (bind-expr num_11 env))
	]
	[ (_mm_mask_cmpge_epi64_mask_dsl vc_0 v1 v2 v3 size_i_o lane_size num_6 prec_o num_8 vc_9 vc_10 prec_i num_12)
		(_mm_mask_cmpge_epi64_mask_dsl (bind-expr vc_0 env) (bind-expr v1 env) (bind-expr v2 env) 
		 (bind-expr v3 env) (bind-expr size_i_o env) (bind-expr lane_size env) 
		 (bind-expr num_6 env) (bind-expr prec_o env) (bind-expr num_8 env) 
		 (bind-expr vc_9 env) (bind-expr vc_10 env) (bind-expr prec_i env) 
		 (bind-expr num_12 env))
	]
	[ (_mm256_cmple_epu32_mask_dsl v0 v1 size_i_o lane_size num_4 prec_o num_6 vc_7 vc_8 prec_i num_10)
		(_mm256_cmple_epu32_mask_dsl (bind-expr v0 env) (bind-expr v1 env) (bind-expr size_i_o env) 
		 (bind-expr lane_size env) (bind-expr num_4 env) (bind-expr prec_o env) 
		 (bind-expr num_6 env) (bind-expr vc_7 env) (bind-expr vc_8 env) 
		 (bind-expr prec_i env) (bind-expr num_10 env))
	]
	[ (_mm512_test_epi32_mask_dsl v0 v1 size_i_o lane_size num_4 prec_o num_6 vc_7 vc_8 vc_9 prec_i num_11)
		(_mm512_test_epi32_mask_dsl (bind-expr v0 env) (bind-expr v1 env) (bind-expr size_i_o env) 
		 (bind-expr lane_size env) (bind-expr num_4 env) (bind-expr prec_o env) 
		 (bind-expr num_6 env) (bind-expr vc_7 env) (bind-expr vc_8 env) 
		 (bind-expr vc_9 env) (bind-expr prec_i env) (bind-expr num_11 env))
	]
	[ (_m_packuswb_dsl v0 v1 size_i_o lane_size num_4 num_5 num_6 prec_o num_8 num_9 num_10 prec_i num_12 num_13 num_14)
		(_m_packuswb_dsl (bind-expr v0 env) (bind-expr v1 env) (bind-expr size_i_o env) 
		 (bind-expr lane_size env) (bind-expr num_4 env) (bind-expr num_5 env) 
		 (bind-expr num_6 env) (bind-expr prec_o env) (bind-expr num_8 env) 
		 (bind-expr num_9 env) (bind-expr num_10 env) (bind-expr prec_i env) 
		 (bind-expr num_12 env) (bind-expr num_13 env) (bind-expr num_14 env))
	]
	[ (_mm_hsub_pi32_dsl v0 v1 size_o lane_size num_4 prec_i_o num_6 num_7 num_8 num_9 num_10 num_11 num_12 num_13)
		(_mm_hsub_pi32_dsl (bind-expr v0 env) (bind-expr v1 env) (bind-expr size_o env) 
		 (bind-expr lane_size env) (bind-expr num_4 env) (bind-expr prec_i_o env) 
		 (bind-expr num_6 env) (bind-expr num_7 env) (bind-expr num_8 env) 
		 (bind-expr num_9 env) (bind-expr num_10 env) (bind-expr num_11 env) 
		 (bind-expr num_12 env) (bind-expr num_13 env))
	]
	[ (_mm_maskz_subs_epu8_dsl vc_0 v1 v2 v3 size_i_o lane_size num_6 prec_i_o num_8 num_9)
		(_mm_maskz_subs_epu8_dsl (bind-expr vc_0 env) (bind-expr v1 env) (bind-expr v2 env) 
		 (bind-expr v3 env) (bind-expr size_i_o env) (bind-expr lane_size env) 
		 (bind-expr num_6 env) (bind-expr prec_i_o env) (bind-expr num_8 env) 
		 (bind-expr num_9 env))
	]
	[ (_mm_subs_pi8_dsl v0 v1 size_i_o lane_size num_4 prec_i_o num_6 num_7)
		(_mm_subs_pi8_dsl (bind-expr v0 env) (bind-expr v1 env) (bind-expr size_i_o env) 
		 (bind-expr lane_size env) (bind-expr num_4 env) (bind-expr prec_i_o env) 
		 (bind-expr num_6 env) (bind-expr num_7 env))
	]
	[ (_mm512_mask_srli_epi64_dsl vc_0 v1 v2 v3 v4 size_i_o lane_size num_7 num_8 num_9 vc_10 num_11 prec_i_o num_13 num_14 num_15)
		(_mm512_mask_srli_epi64_dsl (bind-expr vc_0 env) (bind-expr v1 env) (bind-expr v2 env) 
		 (bind-expr v3 env) (bind-expr v4 env) (bind-expr size_i_o env) 
		 (bind-expr lane_size env) (bind-expr num_7 env) (bind-expr num_8 env) 
		 (bind-expr num_9 env) (bind-expr vc_10 env) (bind-expr num_11 env) 
		 (bind-expr prec_i_o env) (bind-expr num_13 env) (bind-expr num_14 env) 
		 (bind-expr num_15 env))
	]
	[ (_mm256_cmpgt_epu64_mask_dsl v0 v1 size_i_o lane_size num_4 prec_o num_6 vc_7 vc_8 prec_i num_10)
		(_mm256_cmpgt_epu64_mask_dsl (bind-expr v0 env) (bind-expr v1 env) (bind-expr size_i_o env) 
		 (bind-expr lane_size env) (bind-expr num_4 env) (bind-expr prec_o env) 
		 (bind-expr num_6 env) (bind-expr vc_7 env) (bind-expr vc_8 env) 
		 (bind-expr prec_i env) (bind-expr num_10 env))
	]
	[ (_mm_cmpeq_epi32_dsl v0 v1 size_i_o lane_size num_4 prec_i_o num_6 vc_7 vc_8 num_9)
		(_mm_cmpeq_epi32_dsl (bind-expr v0 env) (bind-expr v1 env) (bind-expr size_i_o env) 
		 (bind-expr lane_size env) (bind-expr num_4 env) (bind-expr prec_i_o env) 
		 (bind-expr num_6 env) (bind-expr vc_7 env) (bind-expr vc_8 env) 
		 (bind-expr num_9 env))
	]
	[ (_mm256_mask_sll_epi64_dsl vc_0 v1 v2 v3 v4 size_i_o lane_size num_7 num_8 num_9 vc_10 num_11 prec_i_o num_13 num_14)
		(_mm256_mask_sll_epi64_dsl (bind-expr vc_0 env) (bind-expr v1 env) (bind-expr v2 env) 
		 (bind-expr v3 env) (bind-expr v4 env) (bind-expr size_i_o env) 
		 (bind-expr lane_size env) (bind-expr num_7 env) (bind-expr num_8 env) 
		 (bind-expr num_9 env) (bind-expr vc_10 env) (bind-expr num_11 env) 
		 (bind-expr prec_i_o env) (bind-expr num_13 env) (bind-expr num_14 env))
	]
	[ (_mm_maskz_packs_epi16_dsl vc_0 v1 v2 v3 size_i_o lane_size num_6 prec_i num_8 num_9 num_10 num_11 num_12)
		(_mm_maskz_packs_epi16_dsl (bind-expr vc_0 env) (bind-expr v1 env) (bind-expr v2 env) 
		 (bind-expr v3 env) (bind-expr size_i_o env) (bind-expr lane_size env) 
		 (bind-expr num_6 env) (bind-expr prec_i env) (bind-expr num_8 env) 
		 (bind-expr num_9 env) (bind-expr num_10 env) (bind-expr num_11 env) 
		 (bind-expr num_12 env))
	]
	[ (_mm256_mask_cvtepi16_epi64_dsl v0 v1 v2 size_i_o lane_size num_5 num_6 num_7 prec_i_o num_9)
		(_mm256_mask_cvtepi16_epi64_dsl (bind-expr v0 env) (bind-expr v1 env) (bind-expr v2 env) 
		 (bind-expr size_i_o env) (bind-expr lane_size env) (bind-expr num_5 env) 
		 (bind-expr num_6 env) (bind-expr num_7 env) (bind-expr prec_i_o env) 
		 (bind-expr num_9 env))
	]
	[ (_mm_cvtsi64_si128_dsl v0 size_o lane_size num_3 prec_i_o num_5 num_6 num_7 num_8)
		(_mm_cvtsi64_si128_dsl (bind-expr v0 env) (bind-expr size_o env) (bind-expr lane_size env) 
		 (bind-expr num_3 env) (bind-expr prec_i_o env) (bind-expr num_5 env) 
		 (bind-expr num_6 env) (bind-expr num_7 env) (bind-expr num_8 env))
	]
	[ (_mm_rorv_epi32_dsl v0 v1 size_i_o lane_size num_4 prec_i_o num_6 vc_7 vc_8 num_9)
		(_mm_rorv_epi32_dsl (bind-expr v0 env) (bind-expr v1 env) (bind-expr size_i_o env) 
		 (bind-expr lane_size env) (bind-expr num_4 env) (bind-expr prec_i_o env) 
		 (bind-expr num_6 env) (bind-expr vc_7 env) (bind-expr vc_8 env) 
		 (bind-expr num_9 env))
	]
	[ (_mm512_sra_epi64_dsl v0 v1 size_i_o lane_size num_4 num_5 num_6 vc_7 num_8 prec_i_o vc_10 vc_11 num_12 num_13)
		(_mm512_sra_epi64_dsl (bind-expr v0 env) (bind-expr v1 env) (bind-expr size_i_o env) 
		 (bind-expr lane_size env) (bind-expr num_4 env) (bind-expr num_5 env) 
		 (bind-expr num_6 env) (bind-expr vc_7 env) (bind-expr num_8 env) 
		 (bind-expr prec_i_o env) (bind-expr vc_10 env) (bind-expr vc_11 env) 
		 (bind-expr num_12 env) (bind-expr num_13 env))
	]
	[ (_mm_mask_cvtsepi16_epi8_dsl v0 v1 v2 size_i_o lane_size num_5 prec_i_o num_7 num_8 num_9)
		(_mm_mask_cvtsepi16_epi8_dsl (bind-expr v0 env) (bind-expr v1 env) (bind-expr v2 env) 
		 (bind-expr size_i_o env) (bind-expr lane_size env) (bind-expr num_5 env) 
		 (bind-expr prec_i_o env) (bind-expr num_7 env) (bind-expr num_8 env) 
		 (bind-expr num_9 env))
	]
	[ (_mm_maskz_dpbusds_epi32_dsl vc_0 v1 v2 v3 v4 size_i_o lane_size num_7 num_8 num_9 num_10 num_11 num_12 num_13 num_14)
		(_mm_maskz_dpbusds_epi32_dsl (bind-expr vc_0 env) (bind-expr v1 env) (bind-expr v2 env) 
		 (bind-expr v3 env) (bind-expr v4 env) (bind-expr size_i_o env) 
		 (bind-expr lane_size env) (bind-expr num_7 env) (bind-expr num_8 env) 
		 (bind-expr num_9 env) (bind-expr num_10 env) (bind-expr num_11 env) 
		 (bind-expr num_12 env) (bind-expr num_13 env) (bind-expr num_14 env))
	]
	[ (_mm512_min_epu64_dsl v0 v1 size_i_o lane_size num_4 prec_i_o num_6 num_7)
		(_mm512_min_epu64_dsl (bind-expr v0 env) (bind-expr v1 env) (bind-expr size_i_o env) 
		 (bind-expr lane_size env) (bind-expr num_4 env) (bind-expr prec_i_o env) 
		 (bind-expr num_6 env) (bind-expr num_7 env))
	]
	[ (_mm_mask_max_epi32_dsl v0 v1 v2 v3 size_i_o lane_size num_6 prec_i_o num_8 num_9)
		(_mm_mask_max_epi32_dsl (bind-expr v0 env) (bind-expr v1 env) (bind-expr v2 env) 
		 (bind-expr v3 env) (bind-expr size_i_o env) (bind-expr lane_size env) 
		 (bind-expr num_6 env) (bind-expr prec_i_o env) (bind-expr num_8 env) 
		 (bind-expr num_9 env))
	]
	[ (_mm256_mask_packs_epi16_dsl v0 v1 v2 v3 size_i num_5 num_6 prec_i num_8 num_9 num_10 num_11 num_12 num_13 num_14)
		(_mm256_mask_packs_epi16_dsl (bind-expr v0 env) (bind-expr v1 env) (bind-expr v2 env) 
		 (bind-expr v3 env) (bind-expr size_i env) (bind-expr num_5 env) 
		 (bind-expr num_6 env) (bind-expr prec_i env) (bind-expr num_8 env) 
		 (bind-expr num_9 env) (bind-expr num_10 env) (bind-expr num_11 env) 
		 (bind-expr num_12 env) (bind-expr num_13 env) (bind-expr num_14 env))
	]
	[ (_mm256_mask_srl_epi64_dsl vc_0 v1 v2 v3 v4 size_i_o lane_size num_7 num_8 num_9 vc_10 num_11 prec_i_o num_13 num_14)
		(_mm256_mask_srl_epi64_dsl (bind-expr vc_0 env) (bind-expr v1 env) (bind-expr v2 env) 
		 (bind-expr v3 env) (bind-expr v4 env) (bind-expr size_i_o env) 
		 (bind-expr lane_size env) (bind-expr num_7 env) (bind-expr num_8 env) 
		 (bind-expr num_9 env) (bind-expr vc_10 env) (bind-expr num_11 env) 
		 (bind-expr prec_i_o env) (bind-expr num_13 env) (bind-expr num_14 env))
	]
	[ (_mm256_mulhrs_epi16_dsl v0 v1 size_i_o lane_size num_4 prec_i_o num_6 num_7 vc_8 vc_9 num_10 num_11)
		(_mm256_mulhrs_epi16_dsl (bind-expr v0 env) (bind-expr v1 env) (bind-expr size_i_o env) 
		 (bind-expr lane_size env) (bind-expr num_4 env) (bind-expr prec_i_o env) 
		 (bind-expr num_6 env) (bind-expr num_7 env) (bind-expr vc_8 env) 
		 (bind-expr vc_9 env) (bind-expr num_10 env) (bind-expr num_11 env))
	]
	[ (_mm_cvtm64_si64_dsl v0 size_o lane_size num_3 prec_i_o num_5 num_6 num_7 num_8)
		(_mm_cvtm64_si64_dsl (bind-expr v0 env) (bind-expr size_o env) (bind-expr lane_size env) 
		 (bind-expr num_3 env) (bind-expr prec_i_o env) (bind-expr num_5 env) 
		 (bind-expr num_6 env) (bind-expr num_7 env) (bind-expr num_8 env))
	]
	[ (_mm_extract_epi16_dsl v0 v1 size_o lane_size num_4 num_5 num_6 prec_o num_8 num_9 prec_i vc_11 num_12 num_13 num_14 num_15)
		(_mm_extract_epi16_dsl (bind-expr v0 env) (bind-expr v1 env) (bind-expr size_o env) 
		 (bind-expr lane_size env) (bind-expr num_4 env) (bind-expr num_5 env) 
		 (bind-expr num_6 env) (bind-expr prec_o env) (bind-expr num_8 env) 
		 (bind-expr num_9 env) (bind-expr prec_i env) (bind-expr vc_11 env) 
		 (bind-expr num_12 env) (bind-expr num_13 env) (bind-expr num_14 env) 
		 (bind-expr num_15 env))
	]
	[ (_mm256_cvtepu8_epi16_dsl v0 size_i_o lane_size num_3 prec_i num_5 prec_o num_7)
		(_mm256_cvtepu8_epi16_dsl (bind-expr v0 env) (bind-expr size_i_o env) (bind-expr lane_size env) 
		 (bind-expr num_3 env) (bind-expr prec_i env) (bind-expr num_5 env) 
		 (bind-expr prec_o env) (bind-expr num_7 env))
	]
	[ (_mm256_mask_srlv_epi64_dsl vc_0 v1 v2 v3 v4 size_i_o lane_size num_7 num_8 num_9 vc_10 prec_i_o num_12)
		(_mm256_mask_srlv_epi64_dsl (bind-expr vc_0 env) (bind-expr v1 env) (bind-expr v2 env) 
		 (bind-expr v3 env) (bind-expr v4 env) (bind-expr size_i_o env) 
		 (bind-expr lane_size env) (bind-expr num_7 env) (bind-expr num_8 env) 
		 (bind-expr num_9 env) (bind-expr vc_10 env) (bind-expr prec_i_o env) 
		 (bind-expr num_12 env))
	]
	[ (_mm_hsub_pi16_dsl v0 v1 size_i_o lane_size num_4 num_5 num_6 prec_i_o num_8 num_9 num_10 num_11 num_12 num_13 num_14)
		(_mm_hsub_pi16_dsl (bind-expr v0 env) (bind-expr v1 env) (bind-expr size_i_o env) 
		 (bind-expr lane_size env) (bind-expr num_4 env) (bind-expr num_5 env) 
		 (bind-expr num_6 env) (bind-expr prec_i_o env) (bind-expr num_8 env) 
		 (bind-expr num_9 env) (bind-expr num_10 env) (bind-expr num_11 env) 
		 (bind-expr num_12 env) (bind-expr num_13 env) (bind-expr num_14 env))
	]
	[ (_mm512_maskz_rorv_epi64_dsl vc_0 v1 v2 v3 size_i_o lane_size num_6 prec_i_o num_8 vc_9 vc_10 num_11)
		(_mm512_maskz_rorv_epi64_dsl (bind-expr vc_0 env) (bind-expr v1 env) (bind-expr v2 env) 
		 (bind-expr v3 env) (bind-expr size_i_o env) (bind-expr lane_size env) 
		 (bind-expr num_6 env) (bind-expr prec_i_o env) (bind-expr num_8 env) 
		 (bind-expr vc_9 env) (bind-expr vc_10 env) (bind-expr num_11 env))
	]
	[ (_mm256_mask_test_epi64_mask_dsl vc_0 v1 v2 v3 size_i_o lane_size num_6 prec_o num_8 vc_9 vc_10 vc_11 prec_i num_13)
		(_mm256_mask_test_epi64_mask_dsl (bind-expr vc_0 env) (bind-expr v1 env) (bind-expr v2 env) 
		 (bind-expr v3 env) (bind-expr size_i_o env) (bind-expr lane_size env) 
		 (bind-expr num_6 env) (bind-expr prec_o env) (bind-expr num_8 env) 
		 (bind-expr vc_9 env) (bind-expr vc_10 env) (bind-expr vc_11 env) 
		 (bind-expr prec_i env) (bind-expr num_13 env))
	]
	[ (_mm_maskz_avg_epu8_dsl vc_0 v1 v2 v3 size_i_o lane_size num_6 prec_i_o num_8 vc_9 vc_10 num_11)
		(_mm_maskz_avg_epu8_dsl (bind-expr vc_0 env) (bind-expr v1 env) (bind-expr v2 env) 
		 (bind-expr v3 env) (bind-expr size_i_o env) (bind-expr lane_size env) 
		 (bind-expr num_6 env) (bind-expr prec_i_o env) (bind-expr num_8 env) 
		 (bind-expr vc_9 env) (bind-expr vc_10 env) (bind-expr num_11 env))
	]
	[ (_mm512_ror_epi64_dsl v0 v1 size_i_o lane_size num_4 num_5 num_6 prec_i_o vc_8 vc_9 num_10 num_11)
		(_mm512_ror_epi64_dsl (bind-expr v0 env) (bind-expr v1 env) (bind-expr size_i_o env) 
		 (bind-expr lane_size env) (bind-expr num_4 env) (bind-expr num_5 env) 
		 (bind-expr num_6 env) (bind-expr prec_i_o env) (bind-expr vc_8 env) 
		 (bind-expr vc_9 env) (bind-expr num_10 env) (bind-expr num_11 env))
	]
	[ (_mm512_mask_packus_epi16_dsl v0 v1 v2 v3 size_i num_5 num_6 prec_i num_8 num_9 num_10 num_11 num_12)
		(_mm512_mask_packus_epi16_dsl (bind-expr v0 env) (bind-expr v1 env) (bind-expr v2 env) 
		 (bind-expr v3 env) (bind-expr size_i env) (bind-expr num_5 env) 
		 (bind-expr num_6 env) (bind-expr prec_i env) (bind-expr num_8 env) 
		 (bind-expr num_9 env) (bind-expr num_10 env) (bind-expr num_11 env) 
		 (bind-expr num_12 env))
	]
	[ (_mm_mask_sub_epi32_dsl v0 v1 v2 v3 size_i_o lane_size num_6 prec_i_o num_8 num_9)
		(_mm_mask_sub_epi32_dsl (bind-expr v0 env) (bind-expr v1 env) (bind-expr v2 env) 
		 (bind-expr v3 env) (bind-expr size_i_o env) (bind-expr lane_size env) 
		 (bind-expr num_6 env) (bind-expr prec_i_o env) (bind-expr num_8 env) 
		 (bind-expr num_9 env))
	]
	[ (_mm_mask_packs_epi32_dsl v0 v1 v2 v3 size_i_o lane_size num_6 prec_i num_8 num_9 num_10 num_11 num_12)
		(_mm_mask_packs_epi32_dsl (bind-expr v0 env) (bind-expr v1 env) (bind-expr v2 env) 
		 (bind-expr v3 env) (bind-expr size_i_o env) (bind-expr lane_size env) 
		 (bind-expr num_6 env) (bind-expr prec_i env) (bind-expr num_8 env) 
		 (bind-expr num_9 env) (bind-expr num_10 env) (bind-expr num_11 env) 
		 (bind-expr num_12 env))
	]
	[ (_mm256_mask_cmplt_epu64_mask_dsl vc_0 v1 v2 v3 size_i_o lane_size num_6 prec_o num_8 vc_9 vc_10 prec_i num_12)
		(_mm256_mask_cmplt_epu64_mask_dsl (bind-expr vc_0 env) (bind-expr v1 env) (bind-expr v2 env) 
		 (bind-expr v3 env) (bind-expr size_i_o env) (bind-expr lane_size env) 
		 (bind-expr num_6 env) (bind-expr prec_o env) (bind-expr num_8 env) 
		 (bind-expr vc_9 env) (bind-expr vc_10 env) (bind-expr prec_i env) 
		 (bind-expr num_12 env))
	]
	[ (_mm256_maskz_packs_epi32_dsl vc_0 v1 v2 v3 size_i prec_i num_6 num_7 num_8 num_9 num_10 num_11 num_12 num_13 num_14)
		(_mm256_maskz_packs_epi32_dsl (bind-expr vc_0 env) (bind-expr v1 env) (bind-expr v2 env) 
		 (bind-expr v3 env) (bind-expr size_i env) (bind-expr prec_i env) 
		 (bind-expr num_6 env) (bind-expr num_7 env) (bind-expr num_8 env) 
		 (bind-expr num_9 env) (bind-expr num_10 env) (bind-expr num_11 env) 
		 (bind-expr num_12 env) (bind-expr num_13 env) (bind-expr num_14 env))
	]
	[ (_m_psllwi_dsl vc_0 v1 v2 size_i_o lane_size num_5 num_6 num_7 vc_8 num_9 prec_i_o num_11 num_12 num_13)
		(_m_psllwi_dsl (bind-expr vc_0 env) (bind-expr v1 env) (bind-expr v2 env) 
		 (bind-expr size_i_o env) (bind-expr lane_size env) (bind-expr num_5 env) 
		 (bind-expr num_6 env) (bind-expr num_7 env) (bind-expr vc_8 env) 
		 (bind-expr num_9 env) (bind-expr prec_i_o env) (bind-expr num_11 env) 
		 (bind-expr num_12 env) (bind-expr num_13 env))
	]
	[ (_mm256_max_epi64_dsl v0 v1 size_i_o lane_size num_4 prec_i_o num_6 num_7)
		(_mm256_max_epi64_dsl (bind-expr v0 env) (bind-expr v1 env) (bind-expr size_i_o env) 
		 (bind-expr lane_size env) (bind-expr num_4 env) (bind-expr prec_i_o env) 
		 (bind-expr num_6 env) (bind-expr num_7 env))
	]
	[ (_mm_sub_epi8_dsl v0 v1 size_i_o lane_size num_4 prec_i_o num_6 num_7)
		(_mm_sub_epi8_dsl (bind-expr v0 env) (bind-expr v1 env) (bind-expr size_i_o env) 
		 (bind-expr lane_size env) (bind-expr num_4 env) (bind-expr prec_i_o env) 
		 (bind-expr num_6 env) (bind-expr num_7 env))
	]
	[ (_mm_cvtsi32_si64_dsl v0 size_o lane_size num_3 prec_i_o num_5 num_6 num_7 num_8)
		(_mm_cvtsi32_si64_dsl (bind-expr v0 env) (bind-expr size_o env) (bind-expr lane_size env) 
		 (bind-expr num_3 env) (bind-expr prec_i_o env) (bind-expr num_5 env) 
		 (bind-expr num_6 env) (bind-expr num_7 env) (bind-expr num_8 env))
	]
	[ (_mm_maskz_adds_epi16_dsl vc_0 v1 v2 v3 size_i_o lane_size num_6 prec_i_o num_8 num_9)
		(_mm_maskz_adds_epi16_dsl (bind-expr vc_0 env) (bind-expr v1 env) (bind-expr v2 env) 
		 (bind-expr v3 env) (bind-expr size_i_o env) (bind-expr lane_size env) 
		 (bind-expr num_6 env) (bind-expr prec_i_o env) (bind-expr num_8 env) 
		 (bind-expr num_9 env))
	]
	[ (_mm_unpackhi_pi32_dsl v0 v1 size_o lane_size num_4 prec_i_o num_6 num_7 num_8 num_9 num_10 num_11)
		(_mm_unpackhi_pi32_dsl (bind-expr v0 env) (bind-expr v1 env) (bind-expr size_o env) 
		 (bind-expr lane_size env) (bind-expr num_4 env) (bind-expr prec_i_o env) 
		 (bind-expr num_6 env) (bind-expr num_7 env) (bind-expr num_8 env) 
		 (bind-expr num_9 env) (bind-expr num_10 env) (bind-expr num_11 env))
	]
	[ (_mm256_mask_cmple_epu32_mask_dsl vc_0 v1 v2 v3 size_i_o lane_size num_6 prec_o num_8 vc_9 vc_10 prec_i num_12)
		(_mm256_mask_cmple_epu32_mask_dsl (bind-expr vc_0 env) (bind-expr v1 env) (bind-expr v2 env) 
		 (bind-expr v3 env) (bind-expr size_i_o env) (bind-expr lane_size env) 
		 (bind-expr num_6 env) (bind-expr prec_o env) (bind-expr num_8 env) 
		 (bind-expr vc_9 env) (bind-expr vc_10 env) (bind-expr prec_i env) 
		 (bind-expr num_12 env))
	]
	[ (_mm512_andnot_epi32_dsl v0 v1 size_i_o lane_size num_4 prec_i_o num_6 num_7)
		(_mm512_andnot_epi32_dsl (bind-expr v0 env) (bind-expr v1 env) (bind-expr size_i_o env) 
		 (bind-expr lane_size env) (bind-expr num_4 env) (bind-expr prec_i_o env) 
		 (bind-expr num_6 env) (bind-expr num_7 env))
	]
	[ (_mm512_dpwssd_epi32_dsl v0 v1 v2 size_i_o lane_size num_5 prec_i num_7 num_8)
		(_mm512_dpwssd_epi32_dsl (bind-expr v0 env) (bind-expr v1 env) (bind-expr v2 env) 
		 (bind-expr size_i_o env) (bind-expr lane_size env) (bind-expr num_5 env) 
		 (bind-expr prec_i env) (bind-expr num_7 env) (bind-expr num_8 env))
	]
	[ (_mm_mask_packs_epi16_dsl v0 v1 v2 v3 size_i_o lane_size num_6 prec_i num_8 num_9 num_10 num_11 num_12)
		(_mm_mask_packs_epi16_dsl (bind-expr v0 env) (bind-expr v1 env) (bind-expr v2 env) 
		 (bind-expr v3 env) (bind-expr size_i_o env) (bind-expr lane_size env) 
		 (bind-expr num_6 env) (bind-expr prec_i env) (bind-expr num_8 env) 
		 (bind-expr num_9 env) (bind-expr num_10 env) (bind-expr num_11 env) 
		 (bind-expr num_12 env))
	]
	[ (_mm512_mask_mulhi_epu32_dsl v0 v1 v2 v3 size_i_o lane_size num_6 prec_i_o num_8 vc_9 num_10 num_11)
		(_mm512_mask_mulhi_epu32_dsl (bind-expr v0 env) (bind-expr v1 env) (bind-expr v2 env) 
		 (bind-expr v3 env) (bind-expr size_i_o env) (bind-expr lane_size env) 
		 (bind-expr num_6 env) (bind-expr prec_i_o env) (bind-expr num_8 env) 
		 (bind-expr vc_9 env) (bind-expr num_10 env) (bind-expr num_11 env))
	]
	[ (_mm_abs_epi8_dsl v0 size_i_o lane_size num_3 prec_i_o num_5 num_6)
		(_mm_abs_epi8_dsl (bind-expr v0 env) (bind-expr size_i_o env) (bind-expr lane_size env) 
		 (bind-expr num_3 env) (bind-expr prec_i_o env) (bind-expr num_5 env) 
		 (bind-expr num_6 env))
	]
	[ (_mm512_mask_packus_epi32_dsl v0 v1 v2 v3 size_i num_5 num_6 prec_i num_8 num_9 num_10 num_11 num_12)
		(_mm512_mask_packus_epi32_dsl (bind-expr v0 env) (bind-expr v1 env) (bind-expr v2 env) 
		 (bind-expr v3 env) (bind-expr size_i env) (bind-expr num_5 env) 
		 (bind-expr num_6 env) (bind-expr prec_i env) (bind-expr num_8 env) 
		 (bind-expr num_9 env) (bind-expr num_10 env) (bind-expr num_11 env) 
		 (bind-expr num_12 env))
	]
	[ (_mm512_mask_packs_epi16_dsl v0 v1 v2 v3 size_i num_5 num_6 prec_i num_8 num_9 num_10 num_11 num_12)
		(_mm512_mask_packs_epi16_dsl (bind-expr v0 env) (bind-expr v1 env) (bind-expr v2 env) 
		 (bind-expr v3 env) (bind-expr size_i env) (bind-expr num_5 env) 
		 (bind-expr num_6 env) (bind-expr prec_i env) (bind-expr num_8 env) 
		 (bind-expr num_9 env) (bind-expr num_10 env) (bind-expr num_11 env) 
		 (bind-expr num_12 env))
	]
	[ (_mm256_sll_epi64_dsl vc_0 v1 v2 size_i_o lane_size num_5 num_6 num_7 vc_8 num_9 prec_i_o num_11 num_12)
		(_mm256_sll_epi64_dsl (bind-expr vc_0 env) (bind-expr v1 env) (bind-expr v2 env) 
		 (bind-expr size_i_o env) (bind-expr lane_size env) (bind-expr num_5 env) 
		 (bind-expr num_6 env) (bind-expr num_7 env) (bind-expr vc_8 env) 
		 (bind-expr num_9 env) (bind-expr prec_i_o env) (bind-expr num_11 env) 
		 (bind-expr num_12 env))
	]
	[ (_mm256_cvtepi8_epi16_dsl v0 size_i_o lane_size num_3 prec_i num_5 prec_o num_7)
		(_mm256_cvtepi8_epi16_dsl (bind-expr v0 env) (bind-expr size_i_o env) (bind-expr lane_size env) 
		 (bind-expr num_3 env) (bind-expr prec_i env) (bind-expr num_5 env) 
		 (bind-expr prec_o env) (bind-expr num_7 env))
	]
	[ (_mm256_mask_testn_epi16_mask_dsl vc_0 v1 v2 v3 size_i_o lane_size num_6 prec_o num_8 vc_9 vc_10 vc_11 prec_i num_13)
		(_mm256_mask_testn_epi16_mask_dsl (bind-expr vc_0 env) (bind-expr v1 env) (bind-expr v2 env) 
		 (bind-expr v3 env) (bind-expr size_i_o env) (bind-expr lane_size env) 
		 (bind-expr num_6 env) (bind-expr prec_o env) (bind-expr num_8 env) 
		 (bind-expr vc_9 env) (bind-expr vc_10 env) (bind-expr vc_11 env) 
		 (bind-expr prec_i env) (bind-expr num_13 env))
	]
	[ (_mm512_cmpgt_epi32_mask_dsl v0 v1 size_i_o lane_size num_4 prec_o num_6 vc_7 vc_8 prec_i num_10)
		(_mm512_cmpgt_epi32_mask_dsl (bind-expr v0 env) (bind-expr v1 env) (bind-expr size_i_o env) 
		 (bind-expr lane_size env) (bind-expr num_4 env) (bind-expr prec_o env) 
		 (bind-expr num_6 env) (bind-expr vc_7 env) (bind-expr vc_8 env) 
		 (bind-expr prec_i env) (bind-expr num_10 env))
	]
	[ (_mm512_mul_epi32_dsl v0 v1 size_i_o lane_size num_4 prec_i num_6 prec_o num_8)
		(_mm512_mul_epi32_dsl (bind-expr v0 env) (bind-expr v1 env) (bind-expr size_i_o env) 
		 (bind-expr lane_size env) (bind-expr num_4 env) (bind-expr prec_i env) 
		 (bind-expr num_6 env) (bind-expr prec_o env) (bind-expr num_8 env))
	]
	[ (_mm256_mask_cmple_epi32_mask_dsl vc_0 v1 v2 v3 size_i_o lane_size num_6 prec_o num_8 vc_9 vc_10 prec_i num_12)
		(_mm256_mask_cmple_epi32_mask_dsl (bind-expr vc_0 env) (bind-expr v1 env) (bind-expr v2 env) 
		 (bind-expr v3 env) (bind-expr size_i_o env) (bind-expr lane_size env) 
		 (bind-expr num_6 env) (bind-expr prec_o env) (bind-expr num_8 env) 
		 (bind-expr vc_9 env) (bind-expr vc_10 env) (bind-expr prec_i env) 
		 (bind-expr num_12 env))
	]
	[ (_mm_maskz_dpbusd_epi32_dsl vc_0 v1 v2 v3 v4 size_i_o lane_size num_7 num_8 num_9 num_10 num_11 num_12 num_13 num_14)
		(_mm_maskz_dpbusd_epi32_dsl (bind-expr vc_0 env) (bind-expr v1 env) (bind-expr v2 env) 
		 (bind-expr v3 env) (bind-expr v4 env) (bind-expr size_i_o env) 
		 (bind-expr lane_size env) (bind-expr num_7 env) (bind-expr num_8 env) 
		 (bind-expr num_9 env) (bind-expr num_10 env) (bind-expr num_11 env) 
		 (bind-expr num_12 env) (bind-expr num_13 env) (bind-expr num_14 env))
	]
	[ (_mm_movm_epi8_dsl vc_0 vc_1 v2 size_i_o lane_size num_5 prec_i_o num_7 num_8)
		(_mm_movm_epi8_dsl (bind-expr vc_0 env) (bind-expr vc_1 env) (bind-expr v2 env) 
		 (bind-expr size_i_o env) (bind-expr lane_size env) (bind-expr num_5 env) 
		 (bind-expr prec_i_o env) (bind-expr num_7 env) (bind-expr num_8 env))
	]
	[ (_mm_sub_si64_dsl v0 v1 size_o lane_size num_4 prec_i_o num_6 num_7 num_8 num_9 num_10)
		(_mm_sub_si64_dsl (bind-expr v0 env) (bind-expr v1 env) (bind-expr size_o env) 
		 (bind-expr lane_size env) (bind-expr num_4 env) (bind-expr prec_i_o env) 
		 (bind-expr num_6 env) (bind-expr num_7 env) (bind-expr num_8 env) 
		 (bind-expr num_9 env) (bind-expr num_10 env))
	]
	[ (_mm512_maskz_srai_epi16_dsl vc_0 v1 v2 v3 size_i_o lane_size num_6 num_7 num_8 vc_9 num_10 prec_i_o vc_12 vc_13 num_14 num_15 num_16)
		(_mm512_maskz_srai_epi16_dsl (bind-expr vc_0 env) (bind-expr v1 env) (bind-expr v2 env) 
		 (bind-expr v3 env) (bind-expr size_i_o env) (bind-expr lane_size env) 
		 (bind-expr num_6 env) (bind-expr num_7 env) (bind-expr num_8 env) 
		 (bind-expr vc_9 env) (bind-expr num_10 env) (bind-expr prec_i_o env) 
		 (bind-expr vc_12 env) (bind-expr vc_13 env) (bind-expr num_14 env) 
		 (bind-expr num_15 env) (bind-expr num_16 env))
	]
	[ (_mm512_maskz_and_epi64_dsl vc_0 v1 v2 v3 size_i_o lane_size num_6 prec_i_o num_8 num_9)
		(_mm512_maskz_and_epi64_dsl (bind-expr vc_0 env) (bind-expr v1 env) (bind-expr v2 env) 
		 (bind-expr v3 env) (bind-expr size_i_o env) (bind-expr lane_size env) 
		 (bind-expr num_6 env) (bind-expr prec_i_o env) (bind-expr num_8 env) 
		 (bind-expr num_9 env))
	]
	[ (_mm256_mask_abs_epi16_dsl v0 v1 v2 size_i_o lane_size num_5 prec_i_o num_7 num_8)
		(_mm256_mask_abs_epi16_dsl (bind-expr v0 env) (bind-expr v1 env) (bind-expr v2 env) 
		 (bind-expr size_i_o env) (bind-expr lane_size env) (bind-expr num_5 env) 
		 (bind-expr prec_i_o env) (bind-expr num_7 env) (bind-expr num_8 env))
	]
	[ (_mm256_mask_rolv_epi32_dsl v0 v1 v2 v3 size_i_o lane_size num_6 prec_i_o num_8 vc_9 vc_10 num_11)
		(_mm256_mask_rolv_epi32_dsl (bind-expr v0 env) (bind-expr v1 env) (bind-expr v2 env) 
		 (bind-expr v3 env) (bind-expr size_i_o env) (bind-expr lane_size env) 
		 (bind-expr num_6 env) (bind-expr prec_i_o env) (bind-expr num_8 env) 
		 (bind-expr vc_9 env) (bind-expr vc_10 env) (bind-expr num_11 env))
	]
	[ (_mm256_movepi16_mask_dsl vc_0 vc_1 v2 size_o lane_size num_5 prec_o num_7 num_8 num_9)
		(_mm256_movepi16_mask_dsl (bind-expr vc_0 env) (bind-expr vc_1 env) (bind-expr v2 env) 
		 (bind-expr size_o env) (bind-expr lane_size env) (bind-expr num_5 env) 
		 (bind-expr prec_o env) (bind-expr num_7 env) (bind-expr num_8 env) 
		 (bind-expr num_9 env))
	]
	[ (_mm512_mask_subr_epi32_dsl v0 v1 v2 v3 size_i_o lane_size num_6 prec_i_o num_8 num_9)
		(_mm512_mask_subr_epi32_dsl (bind-expr v0 env) (bind-expr v1 env) (bind-expr v2 env) 
		 (bind-expr v3 env) (bind-expr size_i_o env) (bind-expr lane_size env) 
		 (bind-expr num_6 env) (bind-expr prec_i_o env) (bind-expr num_8 env) 
		 (bind-expr num_9 env))
	]
	[ (_mm_mask_dpwssd_epi32_dsl v0 v1 v2 v3 size_i_o lane_size num_6 num_7 num_8 num_9 num_10 num_11 num_12)
		(_mm_mask_dpwssd_epi32_dsl (bind-expr v0 env) (bind-expr v1 env) (bind-expr v2 env) 
		 (bind-expr v3 env) (bind-expr size_i_o env) (bind-expr lane_size env) 
		 (bind-expr num_6 env) (bind-expr num_7 env) (bind-expr num_8 env) 
		 (bind-expr num_9 env) (bind-expr num_10 env) (bind-expr num_11 env) 
		 (bind-expr num_12 env))
	]
	[ (_mm_movemask_epi8_dsl v0 size_o lane_size num_3 prec_o num_5 num_6 num_7 num_8)
		(_mm_movemask_epi8_dsl (bind-expr v0 env) (bind-expr size_o env) (bind-expr lane_size env) 
		 (bind-expr num_3 env) (bind-expr prec_o env) (bind-expr num_5 env) 
		 (bind-expr num_6 env) (bind-expr num_7 env) (bind-expr num_8 env))
	]
	[ (_mm512_mask_cmpge_epu32_mask_dsl vc_0 v1 v2 v3 size_i_o lane_size num_6 prec_o num_8 vc_9 vc_10 prec_i num_12)
		(_mm512_mask_cmpge_epu32_mask_dsl (bind-expr vc_0 env) (bind-expr v1 env) (bind-expr v2 env) 
		 (bind-expr v3 env) (bind-expr size_i_o env) (bind-expr lane_size env) 
		 (bind-expr num_6 env) (bind-expr prec_o env) (bind-expr num_8 env) 
		 (bind-expr vc_9 env) (bind-expr vc_10 env) (bind-expr prec_i env) 
		 (bind-expr num_12 env))
	]
	[ (_mm_cvtsi64x_si128_dsl v0 size_o lane_size num_3 prec_i_o num_5 num_6 num_7 num_8)
		(_mm_cvtsi64x_si128_dsl (bind-expr v0 env) (bind-expr size_o env) (bind-expr lane_size env) 
		 (bind-expr num_3 env) (bind-expr prec_i_o env) (bind-expr num_5 env) 
		 (bind-expr num_6 env) (bind-expr num_7 env) (bind-expr num_8 env))
	]
	[ (_mm_sllv_epi64_dsl vc_0 v1 v2 size_i_o lane_size num_5 num_6 num_7 vc_8 prec_i_o num_10)
		(_mm_sllv_epi64_dsl (bind-expr vc_0 env) (bind-expr v1 env) (bind-expr v2 env) 
		 (bind-expr size_i_o env) (bind-expr lane_size env) (bind-expr num_5 env) 
		 (bind-expr num_6 env) (bind-expr num_7 env) (bind-expr vc_8 env) 
		 (bind-expr prec_i_o env) (bind-expr num_10 env))
	]
	[ (_mm_extract_pi16_dsl v0 v1 size_o lane_size num_4 num_5 num_6 prec_o num_8 num_9 prec_i vc_11 num_12 num_13 num_14 num_15)
		(_mm_extract_pi16_dsl (bind-expr v0 env) (bind-expr v1 env) (bind-expr size_o env) 
		 (bind-expr lane_size env) (bind-expr num_4 env) (bind-expr num_5 env) 
		 (bind-expr num_6 env) (bind-expr prec_o env) (bind-expr num_8 env) 
		 (bind-expr num_9 env) (bind-expr prec_i env) (bind-expr vc_11 env) 
		 (bind-expr num_12 env) (bind-expr num_13 env) (bind-expr num_14 env) 
		 (bind-expr num_15 env))
	]
	[ (_mm512_maskz_srl_epi16_dsl vc_0 vc_1 v2 v3 v4 size_i_o lane_size num_7 num_8 num_9 vc_10 num_11 num_12 prec_i_o num_14 num_15 num_16)
		(_mm512_maskz_srl_epi16_dsl (bind-expr vc_0 env) (bind-expr vc_1 env) (bind-expr v2 env) 
		 (bind-expr v3 env) (bind-expr v4 env) (bind-expr size_i_o env) 
		 (bind-expr lane_size env) (bind-expr num_7 env) (bind-expr num_8 env) 
		 (bind-expr num_9 env) (bind-expr vc_10 env) (bind-expr num_11 env) 
		 (bind-expr num_12 env) (bind-expr prec_i_o env) (bind-expr num_14 env) 
		 (bind-expr num_15 env) (bind-expr num_16 env))
	]
	[ (_mm_dpwssds_epi32_dsl v0 v1 v2 size_i_o lane_size num_5 prec_i num_7 num_8)
		(_mm_dpwssds_epi32_dsl (bind-expr v0 env) (bind-expr v1 env) (bind-expr v2 env) 
		 (bind-expr size_i_o env) (bind-expr lane_size env) (bind-expr num_5 env) 
		 (bind-expr prec_i env) (bind-expr num_7 env) (bind-expr num_8 env))
	]
	[ (_mm256_maskz_or_epi32_dsl vc_0 v1 v2 v3 size_i_o lane_size num_6 prec_i_o num_8 num_9)
		(_mm256_maskz_or_epi32_dsl (bind-expr vc_0 env) (bind-expr v1 env) (bind-expr v2 env) 
		 (bind-expr v3 env) (bind-expr size_i_o env) (bind-expr lane_size env) 
		 (bind-expr num_6 env) (bind-expr prec_i_o env) (bind-expr num_8 env) 
		 (bind-expr num_9 env))
	]
	[ (_mm_mask_packus_epi32_dsl v0 v1 v2 v3 size_i_o lane_size num_6 prec_i num_8 num_9 num_10 num_11 num_12)
		(_mm_mask_packus_epi32_dsl (bind-expr v0 env) (bind-expr v1 env) (bind-expr v2 env) 
		 (bind-expr v3 env) (bind-expr size_i_o env) (bind-expr lane_size env) 
		 (bind-expr num_6 env) (bind-expr prec_i env) (bind-expr num_8 env) 
		 (bind-expr num_9 env) (bind-expr num_10 env) (bind-expr num_11 env) 
		 (bind-expr num_12 env))
	]
	[ (_mm256_rolv_epi32_dsl v0 v1 size_i_o lane_size num_4 prec_i_o num_6 vc_7 vc_8 num_9)
		(_mm256_rolv_epi32_dsl (bind-expr v0 env) (bind-expr v1 env) (bind-expr size_i_o env) 
		 (bind-expr lane_size env) (bind-expr num_4 env) (bind-expr prec_i_o env) 
		 (bind-expr num_6 env) (bind-expr vc_7 env) (bind-expr vc_8 env) 
		 (bind-expr num_9 env))
	]
	[ (_mm_blendv_epi8_dsl v0 v1 v2 size_i_o lane_size num_5 prec_i_o num_7 num_8)
		(_mm_blendv_epi8_dsl (bind-expr v0 env) (bind-expr v1 env) (bind-expr v2 env) 
		 (bind-expr size_i_o env) (bind-expr lane_size env) (bind-expr num_5 env) 
		 (bind-expr prec_i_o env) (bind-expr num_7 env) (bind-expr num_8 env))
	]
	[ (_mm256_setr_m128i_dsl v0 v1 size_o lane_size num_4 prec_i_o num_6 num_7 num_8 num_9 num_10 num_11)
		(_mm256_setr_m128i_dsl (bind-expr v0 env) (bind-expr v1 env) (bind-expr size_o env) 
		 (bind-expr lane_size env) (bind-expr num_4 env) (bind-expr prec_i_o env) 
		 (bind-expr num_6 env) (bind-expr num_7 env) (bind-expr num_8 env) 
		 (bind-expr num_9 env) (bind-expr num_10 env) (bind-expr num_11 env))
	]
	[ (_mm256_mask_cmpneq_epi16_mask_dsl vc_0 v1 v2 v3 size_i_o lane_size num_6 prec_o num_8 vc_9 vc_10 prec_i num_12)
		(_mm256_mask_cmpneq_epi16_mask_dsl (bind-expr vc_0 env) (bind-expr v1 env) (bind-expr v2 env) 
		 (bind-expr v3 env) (bind-expr size_i_o env) (bind-expr lane_size env) 
		 (bind-expr num_6 env) (bind-expr prec_o env) (bind-expr num_8 env) 
		 (bind-expr vc_9 env) (bind-expr vc_10 env) (bind-expr prec_i env) 
		 (bind-expr num_12 env))
	]
	[ (_mm256_testn_epi32_mask_dsl v0 v1 size_i_o lane_size num_4 prec_o num_6 vc_7 vc_8 vc_9 prec_i num_11)
		(_mm256_testn_epi32_mask_dsl (bind-expr v0 env) (bind-expr v1 env) (bind-expr size_i_o env) 
		 (bind-expr lane_size env) (bind-expr num_4 env) (bind-expr prec_o env) 
		 (bind-expr num_6 env) (bind-expr vc_7 env) (bind-expr vc_8 env) 
		 (bind-expr vc_9 env) (bind-expr prec_i env) (bind-expr num_11 env))
	]
	[ (_mm256_blend_epi16_dsl v0 v1 v2 size_i_o lane_size num_5 prec_i_o num_7 num_8 num_9)
		(_mm256_blend_epi16_dsl (bind-expr v0 env) (bind-expr v1 env) (bind-expr v2 env) 
		 (bind-expr size_i_o env) (bind-expr lane_size env) (bind-expr num_5 env) 
		 (bind-expr prec_i_o env) (bind-expr num_7 env) (bind-expr num_8 env) 
		 (bind-expr num_9 env))
	]
	[ (_mm256_maskz_rol_epi64_dsl vc_0 v1 v2 v3 size_i_o lane_size num_6 num_7 num_8 prec_i_o vc_10 vc_11 num_12 num_13)
		(_mm256_maskz_rol_epi64_dsl (bind-expr vc_0 env) (bind-expr v1 env) (bind-expr v2 env) 
		 (bind-expr v3 env) (bind-expr size_i_o env) (bind-expr lane_size env) 
		 (bind-expr num_6 env) (bind-expr num_7 env) (bind-expr num_8 env) 
		 (bind-expr prec_i_o env) (bind-expr vc_10 env) (bind-expr vc_11 env) 
		 (bind-expr num_12 env) (bind-expr num_13 env))
	]
	[ (_mm256_mask_subs_epi8_dsl v0 v1 v2 v3 size_i_o lane_size num_6 prec_i_o num_8 num_9)
		(_mm256_mask_subs_epi8_dsl (bind-expr v0 env) (bind-expr v1 env) (bind-expr v2 env) 
		 (bind-expr v3 env) (bind-expr size_i_o env) (bind-expr lane_size env) 
		 (bind-expr num_6 env) (bind-expr prec_i_o env) (bind-expr num_8 env) 
		 (bind-expr num_9 env))
	]
	[ (_mm256_or_epi32_dsl v0 v1 size_i_o lane_size num_4 prec_i_o num_6 num_7)
		(_mm256_or_epi32_dsl (bind-expr v0 env) (bind-expr v1 env) (bind-expr size_i_o env) 
		 (bind-expr lane_size env) (bind-expr num_4 env) (bind-expr prec_i_o env) 
		 (bind-expr num_6 env) (bind-expr num_7 env))
	]
	[ (_m_packsswb_dsl v0 v1 size_i_o lane_size num_4 num_5 num_6 prec_o num_8 num_9 num_10 prec_i num_12 num_13 num_14)
		(_m_packsswb_dsl (bind-expr v0 env) (bind-expr v1 env) (bind-expr size_i_o env) 
		 (bind-expr lane_size env) (bind-expr num_4 env) (bind-expr num_5 env) 
		 (bind-expr num_6 env) (bind-expr prec_o env) (bind-expr num_8 env) 
		 (bind-expr num_9 env) (bind-expr num_10 env) (bind-expr prec_i env) 
		 (bind-expr num_12 env) (bind-expr num_13 env) (bind-expr num_14 env))
	]
	[ (_mm512_broadcastd_epi32_dsl v0 size_o lane_size num_3 prec_i_o num_5 num_6 num_7)
		(_mm512_broadcastd_epi32_dsl (bind-expr v0 env) (bind-expr size_o env) (bind-expr lane_size env) 
		 (bind-expr num_3 env) (bind-expr prec_i_o env) (bind-expr num_5 env) 
		 (bind-expr num_6 env) (bind-expr num_7 env))
	]
	[ (_mm512_and_si512_dsl v0 v1 size_o lane_size num_4 prec_i_o num_6 num_7 num_8 num_9 num_10)
		(_mm512_and_si512_dsl (bind-expr v0 env) (bind-expr v1 env) (bind-expr size_o env) 
		 (bind-expr lane_size env) (bind-expr num_4 env) (bind-expr prec_i_o env) 
		 (bind-expr num_6 env) (bind-expr num_7 env) (bind-expr num_8 env) 
		 (bind-expr num_9 env) (bind-expr num_10 env))
	]
	[ (_mm256_maskz_slli_epi16_dsl vc_0 vc_1 v2 v3 v4 size_i_o lane_size num_7 num_8 num_9 vc_10 num_11 prec_i_o num_13 num_14 num_15)
		(_mm256_maskz_slli_epi16_dsl (bind-expr vc_0 env) (bind-expr vc_1 env) (bind-expr v2 env) 
		 (bind-expr v3 env) (bind-expr v4 env) (bind-expr size_i_o env) 
		 (bind-expr lane_size env) (bind-expr num_7 env) (bind-expr num_8 env) 
		 (bind-expr num_9 env) (bind-expr vc_10 env) (bind-expr num_11 env) 
		 (bind-expr prec_i_o env) (bind-expr num_13 env) (bind-expr num_14 env) 
		 (bind-expr num_15 env))
	]
	[ (_mm512_cmplt_epi64_mask_dsl v0 v1 size_i_o lane_size num_4 prec_o num_6 vc_7 vc_8 prec_i num_10)
		(_mm512_cmplt_epi64_mask_dsl (bind-expr v0 env) (bind-expr v1 env) (bind-expr size_i_o env) 
		 (bind-expr lane_size env) (bind-expr num_4 env) (bind-expr prec_o env) 
		 (bind-expr num_6 env) (bind-expr vc_7 env) (bind-expr vc_8 env) 
		 (bind-expr prec_i env) (bind-expr num_10 env))
	]
	[ (_mm256_mask_packus_epi32_dsl v0 v1 v2 v3 size_i num_5 num_6 prec_i num_8 num_9 num_10 num_11 num_12 num_13 num_14)
		(_mm256_mask_packus_epi32_dsl (bind-expr v0 env) (bind-expr v1 env) (bind-expr v2 env) 
		 (bind-expr v3 env) (bind-expr size_i env) (bind-expr num_5 env) 
		 (bind-expr num_6 env) (bind-expr prec_i env) (bind-expr num_8 env) 
		 (bind-expr num_9 env) (bind-expr num_10 env) (bind-expr num_11 env) 
		 (bind-expr num_12 env) (bind-expr num_13 env) (bind-expr num_14 env))
	]
	[ (_mm_cmpneq_epi32_mask_dsl v0 v1 size_i_o lane_size num_4 prec_o num_6 vc_7 vc_8 prec_i num_10)
		(_mm_cmpneq_epi32_mask_dsl (bind-expr v0 env) (bind-expr v1 env) (bind-expr size_i_o env) 
		 (bind-expr lane_size env) (bind-expr num_4 env) (bind-expr prec_o env) 
		 (bind-expr num_6 env) (bind-expr vc_7 env) (bind-expr vc_8 env) 
		 (bind-expr prec_i env) (bind-expr num_10 env))
	]
	[ (_mm256_mask_packs_epi32_dsl v0 v1 v2 v3 size_i num_5 num_6 prec_i num_8 num_9 num_10 num_11 num_12 num_13 num_14)
		(_mm256_mask_packs_epi32_dsl (bind-expr v0 env) (bind-expr v1 env) (bind-expr v2 env) 
		 (bind-expr v3 env) (bind-expr size_i env) (bind-expr num_5 env) 
		 (bind-expr num_6 env) (bind-expr prec_i env) (bind-expr num_8 env) 
		 (bind-expr num_9 env) (bind-expr num_10 env) (bind-expr num_11 env) 
		 (bind-expr num_12 env) (bind-expr num_13 env) (bind-expr num_14 env))
	]
	[ (_mm_maskz_ror_epi32_dsl vc_0 v1 v2 v3 size_i_o lane_size num_6 num_7 num_8 prec_i_o vc_10 vc_11 num_12 num_13)
		(_mm_maskz_ror_epi32_dsl (bind-expr vc_0 env) (bind-expr v1 env) (bind-expr v2 env) 
		 (bind-expr v3 env) (bind-expr size_i_o env) (bind-expr lane_size env) 
		 (bind-expr num_6 env) (bind-expr num_7 env) (bind-expr num_8 env) 
		 (bind-expr prec_i_o env) (bind-expr vc_10 env) (bind-expr vc_11 env) 
		 (bind-expr num_12 env) (bind-expr num_13 env))
	]
	[ (_mm512_maskz_packs_epi32_dsl vc_0 v1 v2 v3 size_i prec_i num_6 num_7 num_8 num_9 num_10 num_11 num_12)
		(_mm512_maskz_packs_epi32_dsl (bind-expr vc_0 env) (bind-expr v1 env) (bind-expr v2 env) 
		 (bind-expr v3 env) (bind-expr size_i env) (bind-expr prec_i env) 
		 (bind-expr num_6 env) (bind-expr num_7 env) (bind-expr num_8 env) 
		 (bind-expr num_9 env) (bind-expr num_10 env) (bind-expr num_11 env) 
		 (bind-expr num_12 env))
	]
	[ (_mm512_cmpge_epu64_mask_dsl v0 v1 size_i_o lane_size num_4 prec_o num_6 vc_7 vc_8 prec_i num_10)
		(_mm512_cmpge_epu64_mask_dsl (bind-expr v0 env) (bind-expr v1 env) (bind-expr size_i_o env) 
		 (bind-expr lane_size env) (bind-expr num_4 env) (bind-expr prec_o env) 
		 (bind-expr num_6 env) (bind-expr vc_7 env) (bind-expr vc_8 env) 
		 (bind-expr prec_i env) (bind-expr num_10 env))
	]
	[ (_mm256_mask_dpbusds_epi32_dsl v0 v1 v2 v3 size_i_o lane_size num_6 num_7 num_8 num_9 num_10 num_11 num_12 num_13)
		(_mm256_mask_dpbusds_epi32_dsl (bind-expr v0 env) (bind-expr v1 env) (bind-expr v2 env) 
		 (bind-expr v3 env) (bind-expr size_i_o env) (bind-expr lane_size env) 
		 (bind-expr num_6 env) (bind-expr num_7 env) (bind-expr num_8 env) 
		 (bind-expr num_9 env) (bind-expr num_10 env) (bind-expr num_11 env) 
		 (bind-expr num_12 env) (bind-expr num_13 env))
	]
	[ (_mm_cmplt_epi16_dsl v0 v1 size_i_o lane_size num_4 prec_i_o num_6 vc_7 vc_8 num_9)
		(_mm_cmplt_epi16_dsl (bind-expr v0 env) (bind-expr v1 env) (bind-expr size_i_o env) 
		 (bind-expr lane_size env) (bind-expr num_4 env) (bind-expr prec_i_o env) 
		 (bind-expr num_6 env) (bind-expr vc_7 env) (bind-expr vc_8 env) 
		 (bind-expr num_9 env))
	]
	[ (_mm512_cvtusepi32_epi8_dsl v0 size_i_o lane_size num_3 prec_o num_5 prec_i num_7)
		(_mm512_cvtusepi32_epi8_dsl (bind-expr v0 env) (bind-expr size_i_o env) (bind-expr lane_size env) 
		 (bind-expr num_3 env) (bind-expr prec_o env) (bind-expr num_5 env) 
		 (bind-expr prec_i env) (bind-expr num_7 env))
	]
	[ (_mm_mask_sllv_epi64_dsl vc_0 v1 v2 v3 v4 size_i_o lane_size num_7 num_8 num_9 vc_10 prec_i_o num_12)
		(_mm_mask_sllv_epi64_dsl (bind-expr vc_0 env) (bind-expr v1 env) (bind-expr v2 env) 
		 (bind-expr v3 env) (bind-expr v4 env) (bind-expr size_i_o env) 
		 (bind-expr lane_size env) (bind-expr num_7 env) (bind-expr num_8 env) 
		 (bind-expr num_9 env) (bind-expr vc_10 env) (bind-expr prec_i_o env) 
		 (bind-expr num_12 env))
	]
	[ (_mm256_cmpgt_epi64_dsl v0 v1 size_i_o lane_size num_4 prec_i_o num_6 vc_7 vc_8 num_9)
		(_mm256_cmpgt_epi64_dsl (bind-expr v0 env) (bind-expr v1 env) (bind-expr size_i_o env) 
		 (bind-expr lane_size env) (bind-expr num_4 env) (bind-expr prec_i_o env) 
		 (bind-expr num_6 env) (bind-expr vc_7 env) (bind-expr vc_8 env) 
		 (bind-expr num_9 env))
	]
	[ (_mm_cmpge_epi32_mask_dsl v0 v1 size_i_o lane_size num_4 prec_o num_6 vc_7 vc_8 prec_i num_10)
		(_mm_cmpge_epi32_mask_dsl (bind-expr v0 env) (bind-expr v1 env) (bind-expr size_i_o env) 
		 (bind-expr lane_size env) (bind-expr num_4 env) (bind-expr prec_o env) 
		 (bind-expr num_6 env) (bind-expr vc_7 env) (bind-expr vc_8 env) 
		 (bind-expr prec_i env) (bind-expr num_10 env))
	]
	[ (_mm_mask_dpwssds_epi32_dsl v0 v1 v2 v3 size_i_o lane_size num_6 num_7 num_8 num_9 num_10 num_11 num_12)
		(_mm_mask_dpwssds_epi32_dsl (bind-expr v0 env) (bind-expr v1 env) (bind-expr v2 env) 
		 (bind-expr v3 env) (bind-expr size_i_o env) (bind-expr lane_size env) 
		 (bind-expr num_6 env) (bind-expr num_7 env) (bind-expr num_8 env) 
		 (bind-expr num_9 env) (bind-expr num_10 env) (bind-expr num_11 env) 
		 (bind-expr num_12 env))
	]
	[ (_mm256_srl_epi64_dsl vc_0 v1 v2 size_i_o lane_size num_5 num_6 num_7 vc_8 num_9 prec_i_o num_11 num_12)
		(_mm256_srl_epi64_dsl (bind-expr vc_0 env) (bind-expr v1 env) (bind-expr v2 env) 
		 (bind-expr size_i_o env) (bind-expr lane_size env) (bind-expr num_5 env) 
		 (bind-expr num_6 env) (bind-expr num_7 env) (bind-expr vc_8 env) 
		 (bind-expr num_9 env) (bind-expr prec_i_o env) (bind-expr num_11 env) 
		 (bind-expr num_12 env))
	]
	[ (_mm_maskz_packus_epi16_dsl vc_0 v1 v2 v3 size_i_o lane_size num_6 prec_i num_8 num_9 num_10 num_11 num_12)
		(_mm_maskz_packus_epi16_dsl (bind-expr vc_0 env) (bind-expr v1 env) (bind-expr v2 env) 
		 (bind-expr v3 env) (bind-expr size_i_o env) (bind-expr lane_size env) 
		 (bind-expr num_6 env) (bind-expr prec_i env) (bind-expr num_8 env) 
		 (bind-expr num_9 env) (bind-expr num_10 env) (bind-expr num_11 env) 
		 (bind-expr num_12 env))
	]
	[ (_mm_avg_pu8_dsl v0 v1 size_i_o lane_size num_4 prec_i_o num_6 vc_7 vc_8 num_9)
		(_mm_avg_pu8_dsl (bind-expr v0 env) (bind-expr v1 env) (bind-expr size_i_o env) 
		 (bind-expr lane_size env) (bind-expr num_4 env) (bind-expr prec_i_o env) 
		 (bind-expr num_6 env) (bind-expr vc_7 env) (bind-expr vc_8 env) 
		 (bind-expr num_9 env))
	]
	[ (_mm512_andnot_si512_dsl v0 v1 size_o lane_size num_4 prec_i_o num_6 num_7 num_8 num_9 num_10)
		(_mm512_andnot_si512_dsl (bind-expr v0 env) (bind-expr v1 env) (bind-expr size_o env) 
		 (bind-expr lane_size env) (bind-expr num_4 env) (bind-expr prec_i_o env) 
		 (bind-expr num_6 env) (bind-expr num_7 env) (bind-expr num_8 env) 
		 (bind-expr num_9 env) (bind-expr num_10 env))
	]
	[ (_mm512_cmple_epi16_mask_dsl v0 v1 size_i_o lane_size num_4 prec_o num_6 vc_7 vc_8 prec_i num_10)
		(_mm512_cmple_epi16_mask_dsl (bind-expr v0 env) (bind-expr v1 env) (bind-expr size_i_o env) 
		 (bind-expr lane_size env) (bind-expr num_4 env) (bind-expr prec_o env) 
		 (bind-expr num_6 env) (bind-expr vc_7 env) (bind-expr vc_8 env) 
		 (bind-expr prec_i env) (bind-expr num_10 env))
	]
	[ (_mm256_mask_cmpgt_epu32_mask_dsl vc_0 v1 v2 v3 size_i_o lane_size num_6 prec_o num_8 vc_9 vc_10 prec_i num_12)
		(_mm256_mask_cmpgt_epu32_mask_dsl (bind-expr vc_0 env) (bind-expr v1 env) (bind-expr v2 env) 
		 (bind-expr v3 env) (bind-expr size_i_o env) (bind-expr lane_size env) 
		 (bind-expr num_6 env) (bind-expr prec_o env) (bind-expr num_8 env) 
		 (bind-expr vc_9 env) (bind-expr vc_10 env) (bind-expr prec_i env) 
		 (bind-expr num_12 env))
	]
	[ (_mm512_maskz_mulhrs_epi16_dsl vc_0 v1 v2 v3 size_i_o lane_size num_6 prec_i_o num_8 num_9 vc_10 vc_11 num_12 num_13)
		(_mm512_maskz_mulhrs_epi16_dsl (bind-expr vc_0 env) (bind-expr v1 env) (bind-expr v2 env) 
		 (bind-expr v3 env) (bind-expr size_i_o env) (bind-expr lane_size env) 
		 (bind-expr num_6 env) (bind-expr prec_i_o env) (bind-expr num_8 env) 
		 (bind-expr num_9 env) (bind-expr vc_10 env) (bind-expr vc_11 env) 
		 (bind-expr num_12 env) (bind-expr num_13 env))
	]
	[ (_mm256_set_m128i_dsl v0 v1 size_o lane_size num_4 prec_i_o num_6 num_7 num_8 num_9 num_10 num_11)
		(_mm256_set_m128i_dsl (bind-expr v0 env) (bind-expr v1 env) (bind-expr size_o env) 
		 (bind-expr lane_size env) (bind-expr num_4 env) (bind-expr prec_i_o env) 
		 (bind-expr num_6 env) (bind-expr num_7 env) (bind-expr num_8 env) 
		 (bind-expr num_9 env) (bind-expr num_10 env) (bind-expr num_11 env))
	]
	[ (_mm256_packs_epi16_dsl v0 v1 size_i_o lane_size num_4 num_5 num_6 prec_o num_8 num_9 num_10 num_11 prec_i num_13 num_14 num_15)
		(_mm256_packs_epi16_dsl (bind-expr v0 env) (bind-expr v1 env) (bind-expr size_i_o env) 
		 (bind-expr lane_size env) (bind-expr num_4 env) (bind-expr num_5 env) 
		 (bind-expr num_6 env) (bind-expr prec_o env) (bind-expr num_8 env) 
		 (bind-expr num_9 env) (bind-expr num_10 env) (bind-expr num_11 env) 
		 (bind-expr prec_i env) (bind-expr num_13 env) (bind-expr num_14 env) 
		 (bind-expr num_15 env))
	]
	[ (_mm_mask_packus_epi16_dsl v0 v1 v2 v3 size_i_o lane_size num_6 prec_i num_8 num_9 num_10 num_11 num_12)
		(_mm_mask_packus_epi16_dsl (bind-expr v0 env) (bind-expr v1 env) (bind-expr v2 env) 
		 (bind-expr v3 env) (bind-expr size_i_o env) (bind-expr lane_size env) 
		 (bind-expr num_6 env) (bind-expr prec_i env) (bind-expr num_8 env) 
		 (bind-expr num_9 env) (bind-expr num_10 env) (bind-expr num_11 env) 
		 (bind-expr num_12 env))
	]
	[ (_mm512_mask_fmadd_epi32_dsl v0 v1 v2 v3 size_i_o lane_size num_6 prec_i_o num_8 num_9 num_10)
		(_mm512_mask_fmadd_epi32_dsl (bind-expr v0 env) (bind-expr v1 env) (bind-expr v2 env) 
		 (bind-expr v3 env) (bind-expr size_i_o env) (bind-expr lane_size env) 
		 (bind-expr num_6 env) (bind-expr prec_i_o env) (bind-expr num_8 env) 
		 (bind-expr num_9 env) (bind-expr num_10 env))
	]
	[ (_mm512_dpbusd_epi32_dsl v0 v1 v2 size_i_o lane_size num_5 prec_i num_7 num_8 num_9)
		(_mm512_dpbusd_epi32_dsl (bind-expr v0 env) (bind-expr v1 env) (bind-expr v2 env) 
		 (bind-expr size_i_o env) (bind-expr lane_size env) (bind-expr num_5 env) 
		 (bind-expr prec_i env) (bind-expr num_7 env) (bind-expr num_8 env) 
		 (bind-expr num_9 env))
	]
	[ (_mm256_mask_mul_epi32_dsl v0 v1 v2 v3 size_i_o lane_size num_6 num_7 num_8 prec_i_o num_10)
		(_mm256_mask_mul_epi32_dsl (bind-expr v0 env) (bind-expr v1 env) (bind-expr v2 env) 
		 (bind-expr v3 env) (bind-expr size_i_o env) (bind-expr lane_size env) 
		 (bind-expr num_6 env) (bind-expr num_7 env) (bind-expr num_8 env) 
		 (bind-expr prec_i_o env) (bind-expr num_10 env))
	]
	[ (_mm_unpacklo_pi32_dsl v0 v1 size_o lane_size num_4 prec_i_o num_6 num_7 num_8 num_9 num_10 num_11)
		(_mm_unpacklo_pi32_dsl (bind-expr v0 env) (bind-expr v1 env) (bind-expr size_o env) 
		 (bind-expr lane_size env) (bind-expr num_4 env) (bind-expr prec_i_o env) 
		 (bind-expr num_6 env) (bind-expr num_7 env) (bind-expr num_8 env) 
		 (bind-expr num_9 env) (bind-expr num_10 env) (bind-expr num_11 env))
	]
	[ (_mm512_mask_max_epu16_dsl v0 v1 v2 v3 size_i_o lane_size num_6 prec_i_o num_8 num_9)
		(_mm512_mask_max_epu16_dsl (bind-expr v0 env) (bind-expr v1 env) (bind-expr v2 env) 
		 (bind-expr v3 env) (bind-expr size_i_o env) (bind-expr lane_size env) 
		 (bind-expr num_6 env) (bind-expr prec_i_o env) (bind-expr num_8 env) 
		 (bind-expr num_9 env))
	]
	[ (_mm512_mask_andnot_epi64_dsl v0 v1 v2 v3 size_i_o lane_size num_6 prec_i_o num_8 num_9)
		(_mm512_mask_andnot_epi64_dsl (bind-expr v0 env) (bind-expr v1 env) (bind-expr v2 env) 
		 (bind-expr v3 env) (bind-expr size_i_o env) (bind-expr lane_size env) 
		 (bind-expr num_6 env) (bind-expr prec_i_o env) (bind-expr num_8 env) 
		 (bind-expr num_9 env))
	]
	[ (_mm256_adds_epi16_dsl v0 v1 size_i_o lane_size num_4 prec_i_o num_6 num_7)
		(_mm256_adds_epi16_dsl (bind-expr v0 env) (bind-expr v1 env) (bind-expr size_i_o env) 
		 (bind-expr lane_size env) (bind-expr num_4 env) (bind-expr prec_i_o env) 
		 (bind-expr num_6 env) (bind-expr num_7 env))
	]
	[ (_mm256_maskz_mullo_epi32_dsl vc_0 v1 v2 v3 size_i_o lane_size num_6 prec_i_o num_8 num_9 num_10 num_11)
		(_mm256_maskz_mullo_epi32_dsl (bind-expr vc_0 env) (bind-expr v1 env) (bind-expr v2 env) 
		 (bind-expr v3 env) (bind-expr size_i_o env) (bind-expr lane_size env) 
		 (bind-expr num_6 env) (bind-expr prec_i_o env) (bind-expr num_8 env) 
		 (bind-expr num_9 env) (bind-expr num_10 env) (bind-expr num_11 env))
	]
	[ (_mm512_maskz_broadcast_i64x4_dsl vc_0 v1 v2 size_i_o lane_size num_5 prec_i_o num_7 num_8 num_9)
		(_mm512_maskz_broadcast_i64x4_dsl (bind-expr vc_0 env) (bind-expr v1 env) (bind-expr v2 env) 
		 (bind-expr size_i_o env) (bind-expr lane_size env) (bind-expr num_5 env) 
		 (bind-expr prec_i_o env) (bind-expr num_7 env) (bind-expr num_8 env) 
		 (bind-expr num_9 env))
	]
	[ (_mm_dpbusds_epi32_dsl v0 v1 v2 size_i_o lane_size num_5 prec_i num_7 num_8 num_9)
		(_mm_dpbusds_epi32_dsl (bind-expr v0 env) (bind-expr v1 env) (bind-expr v2 env) 
		 (bind-expr size_i_o env) (bind-expr lane_size env) (bind-expr num_5 env) 
		 (bind-expr prec_i env) (bind-expr num_7 env) (bind-expr num_8 env) 
		 (bind-expr num_9 env))
	]
	[ (_mm_sign_pi8_dsl vc_0 v1 v2 size_i_o lane_size num_5 num_6 num_7 vc_8 prec_i_o vc_10 num_11 num_12)
		(_mm_sign_pi8_dsl (bind-expr vc_0 env) (bind-expr v1 env) (bind-expr v2 env) 
		 (bind-expr size_i_o env) (bind-expr lane_size env) (bind-expr num_5 env) 
		 (bind-expr num_6 env) (bind-expr num_7 env) (bind-expr vc_8 env) 
		 (bind-expr prec_i_o env) (bind-expr vc_10 env) (bind-expr num_11 env) 
		 (bind-expr num_12 env))
	]
	[ (_mm_cvtsi32_si128_dsl v0 size_o lane_size num_3 prec_i_o num_5 num_6 num_7 num_8)
		(_mm_cvtsi32_si128_dsl (bind-expr v0 env) (bind-expr size_o env) (bind-expr lane_size env) 
		 (bind-expr num_3 env) (bind-expr prec_i_o env) (bind-expr num_5 env) 
		 (bind-expr num_6 env) (bind-expr num_7 env) (bind-expr num_8 env))
	]
	[ (_mm_mulhi_epu16_dsl v0 v1 size_i_o lane_size num_4 prec_i_o num_6 num_7 num_8 num_9)
		(_mm_mulhi_epu16_dsl (bind-expr v0 env) (bind-expr v1 env) (bind-expr size_i_o env) 
		 (bind-expr lane_size env) (bind-expr num_4 env) (bind-expr prec_i_o env) 
		 (bind-expr num_6 env) (bind-expr num_7 env) (bind-expr num_8 env) 
		 (bind-expr num_9 env))
	]
	[ (_mm_add_si64_dsl v0 v1 size_o lane_size num_4 prec_i_o num_6 num_7 num_8 num_9 num_10)
		(_mm_add_si64_dsl (bind-expr v0 env) (bind-expr v1 env) (bind-expr size_o env) 
		 (bind-expr lane_size env) (bind-expr num_4 env) (bind-expr prec_i_o env) 
		 (bind-expr num_6 env) (bind-expr num_7 env) (bind-expr num_8 env) 
		 (bind-expr num_9 env) (bind-expr num_10 env))
	]
	[ (_mm256_mask_mov_epi32_dsl v0 v1 v2 size_i_o lane_size num_5 prec_i_o num_7 num_8)
		(_mm256_mask_mov_epi32_dsl (bind-expr v0 env) (bind-expr v1 env) (bind-expr v2 env) 
		 (bind-expr size_i_o env) (bind-expr lane_size env) (bind-expr num_5 env) 
		 (bind-expr prec_i_o env) (bind-expr num_7 env) (bind-expr num_8 env))
	]
	[ (_mm_extract_epi64_dsl v0 v1 size_i_o lane_size num_4 num_5 num_6 prec_o num_8 num_9 prec_i vc_11 num_12 num_13 num_14)
		(_mm_extract_epi64_dsl (bind-expr v0 env) (bind-expr v1 env) (bind-expr size_i_o env) 
		 (bind-expr lane_size env) (bind-expr num_4 env) (bind-expr num_5 env) 
		 (bind-expr num_6 env) (bind-expr prec_o env) (bind-expr num_8 env) 
		 (bind-expr num_9 env) (bind-expr prec_i env) (bind-expr vc_11 env) 
		 (bind-expr num_12 env) (bind-expr num_13 env) (bind-expr num_14 env))
	]
	[ (_mm512_mask_packs_epi32_dsl v0 v1 v2 v3 size_i num_5 num_6 prec_i num_8 num_9 num_10 num_11 num_12)
		(_mm512_mask_packs_epi32_dsl (bind-expr v0 env) (bind-expr v1 env) (bind-expr v2 env) 
		 (bind-expr v3 env) (bind-expr size_i env) (bind-expr num_5 env) 
		 (bind-expr num_6 env) (bind-expr prec_i env) (bind-expr num_8 env) 
		 (bind-expr num_9 env) (bind-expr num_10 env) (bind-expr num_11 env) 
		 (bind-expr num_12 env))
	]
	[ (_mm256_maskz_set1_epi16_dsl vc_0 v1 v2 size_i_o lane_size num_5 prec_i_o num_7 num_8 num_9)
		(_mm256_maskz_set1_epi16_dsl (bind-expr vc_0 env) (bind-expr v1 env) (bind-expr v2 env) 
		 (bind-expr size_i_o env) (bind-expr lane_size env) (bind-expr num_5 env) 
		 (bind-expr prec_i_o env) (bind-expr num_7 env) (bind-expr num_8 env) 
		 (bind-expr num_9 env))
	]
	[ (_mm_sra_pi32_dsl v0 v1 size_i_o lane_size num_4 num_5 num_6 vc_7 num_8 num_9 prec_i_o vc_11 vc_12 num_13 num_14 num_15)
		(_mm_sra_pi32_dsl (bind-expr v0 env) (bind-expr v1 env) (bind-expr size_i_o env) 
		 (bind-expr lane_size env) (bind-expr num_4 env) (bind-expr num_5 env) 
		 (bind-expr num_6 env) (bind-expr vc_7 env) (bind-expr num_8 env) 
		 (bind-expr num_9 env) (bind-expr prec_i_o env) (bind-expr vc_11 env) 
		 (bind-expr vc_12 env) (bind-expr num_13 env) (bind-expr num_14 env) 
		 (bind-expr num_15 env))
	]
	[ (_mm512_maskz_packus_epi16_dsl vc_0 v1 v2 v3 size_i prec_i num_6 num_7 num_8 num_9 num_10 num_11 num_12)
		(_mm512_maskz_packus_epi16_dsl (bind-expr vc_0 env) (bind-expr v1 env) (bind-expr v2 env) 
		 (bind-expr v3 env) (bind-expr size_i env) (bind-expr prec_i env) 
		 (bind-expr num_6 env) (bind-expr num_7 env) (bind-expr num_8 env) 
		 (bind-expr num_9 env) (bind-expr num_10 env) (bind-expr num_11 env) 
		 (bind-expr num_12 env))
	]
	[ (_mm512_mask_cmplt_epi8_mask_dsl vc_0 v1 v2 v3 size_i_o lane_size num_6 prec_o num_8 vc_9 vc_10 prec_i num_12)
		(_mm512_mask_cmplt_epi8_mask_dsl (bind-expr vc_0 env) (bind-expr v1 env) (bind-expr v2 env) 
		 (bind-expr v3 env) (bind-expr size_i_o env) (bind-expr lane_size env) 
		 (bind-expr num_6 env) (bind-expr prec_o env) (bind-expr num_8 env) 
		 (bind-expr vc_9 env) (bind-expr vc_10 env) (bind-expr prec_i env) 
		 (bind-expr num_12 env))
	]
	[ (_m_pextrw_dsl v0 v1 size_o lane_size num_4 num_5 num_6 prec_o num_8 num_9 prec_i vc_11 num_12 num_13 num_14 num_15)
		(_m_pextrw_dsl (bind-expr v0 env) (bind-expr v1 env) (bind-expr size_o env) 
		 (bind-expr lane_size env) (bind-expr num_4 env) (bind-expr num_5 env) 
		 (bind-expr num_6 env) (bind-expr prec_o env) (bind-expr num_8 env) 
		 (bind-expr num_9 env) (bind-expr prec_i env) (bind-expr vc_11 env) 
		 (bind-expr num_12 env) (bind-expr num_13 env) (bind-expr num_14 env) 
		 (bind-expr num_15 env))
	]
	[ (_mm512_maskz_mul_epu32_dsl vc_0 v1 v2 v3 size_i_o lane_size num_6 num_7 num_8 prec_i_o num_10)
		(_mm512_maskz_mul_epu32_dsl (bind-expr vc_0 env) (bind-expr v1 env) (bind-expr v2 env) 
		 (bind-expr v3 env) (bind-expr size_i_o env) (bind-expr lane_size env) 
		 (bind-expr num_6 env) (bind-expr num_7 env) (bind-expr num_8 env) 
		 (bind-expr prec_i_o env) (bind-expr num_10 env))
	]
	[ (_mm_rol_epi64_dsl v0 v1 size_i_o lane_size num_4 num_5 num_6 prec_i_o vc_8 vc_9 num_10 num_11)
		(_mm_rol_epi64_dsl (bind-expr v0 env) (bind-expr v1 env) (bind-expr size_i_o env) 
		 (bind-expr lane_size env) (bind-expr num_4 env) (bind-expr num_5 env) 
		 (bind-expr num_6 env) (bind-expr prec_i_o env) (bind-expr vc_8 env) 
		 (bind-expr vc_9 env) (bind-expr num_10 env) (bind-expr num_11 env))
	]
	[ (_mm256_packus_epi32_dsl v0 v1 size_i_o lane_size num_4 num_5 num_6 prec_o num_8 num_9 num_10 num_11 prec_i num_13 num_14 num_15)
		(_mm256_packus_epi32_dsl (bind-expr v0 env) (bind-expr v1 env) (bind-expr size_i_o env) 
		 (bind-expr lane_size env) (bind-expr num_4 env) (bind-expr num_5 env) 
		 (bind-expr num_6 env) (bind-expr prec_o env) (bind-expr num_8 env) 
		 (bind-expr num_9 env) (bind-expr num_10 env) (bind-expr num_11 env) 
		 (bind-expr prec_i env) (bind-expr num_13 env) (bind-expr num_14 env) 
		 (bind-expr num_15 env))
	]
	[v v]
 )
)

;; ================================================================================
