#lang rosette
(require rosette/lib/synthax)
(require rosette/lib/angelic)
(require racket/pretty)
(require data/bit-vector)
(require rosette/lib/destruct)
(require rosette/solver/smt/boolector)

(require hydride/utils/bvops)
(require hydride/utils/misc)


(require hydride/ir/hydride/semantics)
(require hydride/ir/hydride/definition)
(require hydride/ir/hydride/length)


(provide (all-defined-out))


;; ================================================================================
;;                                DSL Interpreter
;; ================================================================================
(define (interpret prog env)
 (destruct prog
	[(dim-x id) (vector-ref env (- (vector-length env) 2))]
	[(dim-y id) (vector-ref env (- (vector-length env) 1))]
	[(idx-i id) (vector-ref env (- (vector-length env) 4))]
	[(idx-j id) (vector-ref env (- (vector-length env) 3))]
	[(reg id) (vector-ref env id)]
	[(lit v) v]
	[(nop v1) (interpret v1 env)]
	[(idx-add i1 i2) (+ (interpret i1 env) (interpret i2 env))]
	[(idx-mul i1 i2) (* (interpret i1 env) (interpret i2 env))]
	
	[ (vector-choose_dsl  num_elems)
        (define random-regs (for/list ([i (range (vector-length env))])  (reg i)))
        (apply concat
         (for/list ([i (range num_elems)])
                  (interpret (apply choose* random-regs) env)
            )
         )
	]
	[ (vector-load_dsl v0 size_i_o num_2 num_3 prec_i_o)
		(assert (equal? size_i_o (get-length v0 env)))
		(vector-load (interpret v0 env) (interpret size_i_o env) (interpret num_2 env) 
		 (interpret num_3 env) (interpret prec_i_o env))
	]
	[ (vector-two-input-swizzle_dsl v0 v1 num_2 prec_i_o num_4 lane_size num_6 num_7 num_8)
		(vector-two-input-swizzle (interpret v0 env) (interpret v1 env) (interpret num_2 env) 
		 (interpret prec_i_o env) (interpret num_4 env) (interpret lane_size env) 
		 (interpret num_6 env) (interpret num_7 env) (interpret num_8 env))
	]
	[ (_mm512_mask_testn_epi64_mask_dsl vc_0 v1 v2 v3 size_i_o lane_size num_6 prec_o num_8 vc_9 vc_10 vc_11 prec_i)
		(assert (equal? (get-length v2 env) (get-length v3 env)))
		(assert (equal? size_i_o (get-length v1 env)))
		(_mm512_mask_testn_epi64_mask (interpret vc_0 env) (interpret v1 env) (interpret v2 env) 
		 (interpret v3 env) (interpret size_i_o env) (interpret lane_size env) 
		 (interpret num_6 env) (interpret prec_o env) (interpret num_8 env) 
		 (interpret vc_9 env) (interpret vc_10 env) (interpret vc_11 env) 
		 (interpret prec_i env))
	]
	[ (_mm512_maskz_mulhi_epu16_dsl vc_0 v1 v2 v3 size_i_o lane_size num_6 prec_i_o num_8 num_9 num_10)
		(assert (equal? (get-length v2 env) (get-length v3 env)))
		(assert (equal? size_i_o (get-length v2 env)))
		(assert (equal? size_i_o (get-length v3 env)))
		(_mm512_maskz_mulhi_epu16 (interpret vc_0 env) (interpret v1 env) (interpret v2 env) 
		 (interpret v3 env) (interpret size_i_o env) (interpret lane_size env) 
		 (interpret num_6 env) (interpret prec_i_o env) (interpret num_8 env) 
		 (interpret num_9 env) (interpret num_10 env))
	]
	[ (_mm_cmpge_epi16_mask_dsl v0 v1 size_i_o lane_size num_4 prec_o num_6 vc_7 vc_8 prec_i)
		(assert (equal? (get-length v0 env) (get-length v1 env)))
		(_mm_cmpge_epi16_mask (interpret v0 env) (interpret v1 env) (interpret size_i_o env) 
		 (interpret lane_size env) (interpret num_4 env) (interpret prec_o env) 
		 (interpret num_6 env) (interpret vc_7 env) (interpret vc_8 env) 
		 (interpret prec_i env))
	]
	[ (_mm512_mask_cmpge_epu8_mask_dsl vc_0 v1 v2 v3 size_i_o lane_size num_6 prec_o num_8 vc_9 vc_10 prec_i)
		(assert (equal? (get-length v2 env) (get-length v3 env)))
		(assert (equal? size_i_o (get-length v1 env)))
		(_mm512_mask_cmpge_epu8_mask (interpret vc_0 env) (interpret v1 env) (interpret v2 env) 
		 (interpret v3 env) (interpret size_i_o env) (interpret lane_size env) 
		 (interpret num_6 env) (interpret prec_o env) (interpret num_8 env) 
		 (interpret vc_9 env) (interpret vc_10 env) (interpret prec_i env))
	]
	[ (_mm512_dpbusd_epi32_dsl v0 v1 v2 size_i lane_size num_5 prec_i num_7 num_8)
		(assert (equal? size_i (get-length v0 env)))
		(assert (equal? (get-length v0 env) (get-length v1 env)))
		(assert (equal? (get-length v0 env) (get-length v2 env)))
		(assert (equal? (get-length v1 env) (get-length v2 env)))
		(assert (equal? size_i (get-length v1 env)))
		(assert (equal? size_i (get-length v2 env)))
		(_mm512_dpbusd_epi32 (interpret v0 env) (interpret v1 env) (interpret v2 env) 
		 (interpret size_i env) (interpret lane_size env) (interpret num_5 env) 
		 (interpret prec_i env) (interpret num_7 env) (interpret num_8 env))
	]
	[ (_mm512_maskz_broadcast_i64x2_dsl vc_0 v1 v2 size_i_o lane_size num_5 prec_i_o num_7 num_8)
		(_mm512_maskz_broadcast_i64x2 (interpret vc_0 env) (interpret v1 env) (interpret v2 env) 
		 (interpret size_i_o env) (interpret lane_size env) (interpret num_5 env) 
		 (interpret prec_i_o env) (interpret num_7 env) (interpret num_8 env))
	]
	[ (_mm256_blend_epi16_dsl v0 v1 v2 size_i_o lane_size num_5 prec_i_o num_7 num_8)
		(assert (equal? (get-length v0 env) (get-length v1 env)))
		(assert (equal? size_i_o (get-length v0 env)))
		(assert (equal? size_i_o (get-length v1 env)))
		(_mm256_blend_epi16 (interpret v0 env) (interpret v1 env) (interpret v2 env) 
		 (interpret size_i_o env) (interpret lane_size env) (interpret num_5 env) 
		 (interpret prec_i_o env) (interpret num_7 env) (interpret num_8 env))
	]
	[ (_mm_maddubs_pi16_dsl v0 v1 size_i_o lane_size num_4 prec_i num_6 prec_o num_8)
		(assert (equal? (get-length v0 env) (get-length v1 env)))
		(assert (equal? size_i_o (get-length v0 env)))
		(assert (equal? size_i_o (get-length v1 env)))
		(_mm_maddubs_pi16 (interpret v0 env) (interpret v1 env) (interpret size_i_o env) 
		 (interpret lane_size env) (interpret num_4 env) (interpret prec_i env) 
		 (interpret num_6 env) (interpret prec_o env) (interpret num_8 env))
	]
	[ (_mm256_mask_min_epi16_dsl v0 v1 v2 v3 size_i_o lane_size num_6 prec_i_o num_8)
		(assert (equal? (get-length v0 env) (get-length v2 env)))
		(assert (equal? (get-length v0 env) (get-length v3 env)))
		(assert (equal? (get-length v2 env) (get-length v3 env)))
		(assert (equal? size_i_o (get-length v0 env)))
		(assert (equal? size_i_o (get-length v2 env)))
		(assert (equal? size_i_o (get-length v3 env)))
		(_mm256_mask_min_epi16 (interpret v0 env) (interpret v1 env) (interpret v2 env) 
		 (interpret v3 env) (interpret size_i_o env) (interpret lane_size env) 
		 (interpret num_6 env) (interpret prec_i_o env) (interpret num_8 env))
	]
	[ (_mm256_avg_epu16_dsl v0 v1 size_i_o lane_size num_4 prec_i_o num_6 vc_7 vc_8)
		(assert (equal? (get-length v0 env) (get-length v1 env)))
		(assert (equal? size_i_o (get-length v0 env)))
		(assert (equal? size_i_o (get-length v1 env)))
		(_mm256_avg_epu16 (interpret v0 env) (interpret v1 env) (interpret size_i_o env) 
		 (interpret lane_size env) (interpret num_4 env) (interpret prec_i_o env) 
		 (interpret num_6 env) (interpret vc_7 env) (interpret vc_8 env))
	]
	[ (_mm256_mask_cmpgt_epi16_mask_dsl vc_0 v1 v2 v3 size_i_o lane_size num_6 prec_o num_8 vc_9 vc_10 prec_i)
		(assert (equal? (get-length v2 env) (get-length v3 env)))
		(assert (equal? size_i_o (get-length v1 env)))
		(_mm256_mask_cmpgt_epi16_mask (interpret vc_0 env) (interpret v1 env) (interpret v2 env) 
		 (interpret v3 env) (interpret size_i_o env) (interpret lane_size env) 
		 (interpret num_6 env) (interpret prec_o env) (interpret num_8 env) 
		 (interpret vc_9 env) (interpret vc_10 env) (interpret prec_i env))
	]
	[ (_mm512_maskz_dpbusd_epi32_dsl vc_0 v1 v2 v3 v4 size_i_o lane_size num_7 num_8 num_9 num_10 num_11 num_12 num_13)
		(assert (equal? (get-length v2 env) (get-length v3 env)))
		(assert (equal? (get-length v2 env) (get-length v4 env)))
		(assert (equal? (get-length v3 env) (get-length v4 env)))
		(assert (equal? size_i_o (get-length v2 env)))
		(assert (equal? size_i_o (get-length v3 env)))
		(assert (equal? size_i_o (get-length v4 env)))
		(_mm512_maskz_dpbusd_epi32 (interpret vc_0 env) (interpret v1 env) (interpret v2 env) 
		 (interpret v3 env) (interpret v4 env) (interpret size_i_o env) 
		 (interpret lane_size env) (interpret num_7 env) (interpret num_8 env) 
		 (interpret num_9 env) (interpret num_10 env) (interpret num_11 env) 
		 (interpret num_12 env) (interpret num_13 env))
	]
	[ (_mm512_mask_cvtsepi32_epi16_dsl v0 v1 v2 size_i_o lane_size num_5 prec_i_o num_7 num_8)
		(assert (equal? size_i_o (get-length v0 env)))
		(_mm512_mask_cvtsepi32_epi16 (interpret v0 env) (interpret v1 env) (interpret v2 env) 
		 (interpret size_i_o env) (interpret lane_size env) (interpret num_5 env) 
		 (interpret prec_i_o env) (interpret num_7 env) (interpret num_8 env))
	]
	[ (_mm_mul_epi32_dsl v0 v1 size_i_o lane_size num_4 prec_i num_6 prec_o)
		(assert (equal? (get-length v0 env) (get-length v1 env)))
		(assert (equal? size_i_o (get-length v0 env)))
		(assert (equal? size_i_o (get-length v1 env)))
		(_mm_mul_epi32 (interpret v0 env) (interpret v1 env) (interpret size_i_o env) 
		 (interpret lane_size env) (interpret num_4 env) (interpret prec_i env) 
		 (interpret num_6 env) (interpret prec_o env))
	]
	[ (_mm_maskz_sub_epi16_dsl vc_0 v1 v2 v3 size_i_o lane_size num_6 prec_i_o num_8)
		(assert (equal? (get-length v2 env) (get-length v3 env)))
		(assert (equal? size_i_o (get-length v2 env)))
		(assert (equal? size_i_o (get-length v3 env)))
		(_mm_maskz_sub_epi16 (interpret vc_0 env) (interpret v1 env) (interpret v2 env) 
		 (interpret v3 env) (interpret size_i_o env) (interpret lane_size env) 
		 (interpret num_6 env) (interpret prec_i_o env) (interpret num_8 env))
	]
	[ (_mm512_mask_div_epu32_dsl v0 v1 v2 v3 size_i_o lane_size num_6 prec_i_o num_8 num_9 num_10)
		(assert (equal? (get-length v0 env) (get-length v2 env)))
		(assert (equal? (get-length v0 env) (get-length v3 env)))
		(assert (equal? (get-length v2 env) (get-length v3 env)))
		(assert (equal? size_i_o (get-length v0 env)))
		(assert (equal? size_i_o (get-length v2 env)))
		(assert (equal? size_i_o (get-length v3 env)))
		(_mm512_mask_div_epu32 (interpret v0 env) (interpret v1 env) (interpret v2 env) 
		 (interpret v3 env) (interpret size_i_o env) (interpret lane_size env) 
		 (interpret num_6 env) (interpret prec_i_o env) (interpret num_8 env) 
		 (interpret num_9 env) (interpret num_10 env))
	]
	[ (_mm512_sub_epi8_dsl v0 v1 size_i_o lane_size num_4 prec_i_o num_6)
		(assert (equal? (get-length v0 env) (get-length v1 env)))
		(assert (equal? size_i_o (get-length v0 env)))
		(assert (equal? size_i_o (get-length v1 env)))
		(_mm512_sub_epi8 (interpret v0 env) (interpret v1 env) (interpret size_i_o env) 
		 (interpret lane_size env) (interpret num_4 env) (interpret prec_i_o env) 
		 (interpret num_6 env))
	]
	[ (_mm512_madd52hi_epu64_dsl v0 v1 v2 size_i_o lane_size num_5 prec_i num_7 prec_o num_9 num_10 num_11)
		(assert (equal? (get-length v0 env) (get-length v1 env)))
		(assert (equal? (get-length v0 env) (get-length v2 env)))
		(assert (equal? (get-length v1 env) (get-length v2 env)))
		(assert (equal? size_i_o (get-length v0 env)))
		(assert (equal? size_i_o (get-length v1 env)))
		(assert (equal? size_i_o (get-length v2 env)))
		(_mm512_madd52hi_epu64 (interpret v0 env) (interpret v1 env) (interpret v2 env) 
		 (interpret size_i_o env) (interpret lane_size env) (interpret num_5 env) 
		 (interpret prec_i env) (interpret num_7 env) (interpret prec_o env) 
		 (interpret num_9 env) (interpret num_10 env) (interpret num_11 env))
	]
	[ (_mm256_cvtepi64_epi8_dsl v0 size_i_o lane_size num_3 prec_o num_5 prec_i)
		(_mm256_cvtepi64_epi8 (interpret v0 env) (interpret size_i_o env) (interpret lane_size env) 
		 (interpret num_3 env) (interpret prec_o env) (interpret num_5 env) 
		 (interpret prec_i env))
	]
	[ (_mm512_mullo_epi16_dsl v0 v1 size_i_o lane_size num_4 prec_i_o num_6 num_7 num_8)
		(assert (equal? (get-length v0 env) (get-length v1 env)))
		(assert (equal? size_i_o (get-length v0 env)))
		(assert (equal? size_i_o (get-length v1 env)))
		(_mm512_mullo_epi16 (interpret v0 env) (interpret v1 env) (interpret size_i_o env) 
		 (interpret lane_size env) (interpret num_4 env) (interpret prec_i_o env) 
		 (interpret num_6 env) (interpret num_7 env) (interpret num_8 env))
	]
	[ (_mm256_mask_cmpneq_epu32_mask_dsl vc_0 v1 v2 v3 size_i_o lane_size num_6 prec_o num_8 vc_9 vc_10 prec_i)
		(assert (equal? (get-length v2 env) (get-length v3 env)))
		(assert (equal? size_i_o (get-length v1 env)))
		(_mm256_mask_cmpneq_epu32_mask (interpret vc_0 env) (interpret v1 env) (interpret v2 env) 
		 (interpret v3 env) (interpret size_i_o env) (interpret lane_size env) 
		 (interpret num_6 env) (interpret prec_o env) (interpret num_8 env) 
		 (interpret vc_9 env) (interpret vc_10 env) (interpret prec_i env))
	]
	[ (_mm512_mask_reduce_add_epi64_dsl vc_0 v1 v2 size_i_o lane_size num_5 prec_i_o num_7 num_8)
		(assert (equal? size_i_o (get-length v2 env)))
		(_mm512_mask_reduce_add_epi64 (interpret vc_0 env) (interpret v1 env) (interpret v2 env) 
		 (interpret size_i_o env) (interpret lane_size env) (interpret num_5 env) 
		 (interpret prec_i_o env) (interpret num_7 env) (interpret num_8 env))
	]
	[ (_mm512_subr_epi32_dsl v0 v1 size_i_o lane_size num_4 prec_i_o num_6)
		(assert (equal? (get-length v0 env) (get-length v1 env)))
		(assert (equal? size_i_o (get-length v0 env)))
		(assert (equal? size_i_o (get-length v1 env)))
		(_mm512_subr_epi32 (interpret v0 env) (interpret v1 env) (interpret size_i_o env) 
		 (interpret lane_size env) (interpret num_4 env) (interpret prec_i_o env) 
		 (interpret num_6 env))
	]
	[ (_mm256_subs_epu8_dsl v0 v1 size_i_o lane_size num_4 prec_i_o num_6)
		(assert (equal? (get-length v0 env) (get-length v1 env)))
		(assert (equal? size_i_o (get-length v0 env)))
		(assert (equal? size_i_o (get-length v1 env)))
		(_mm256_subs_epu8 (interpret v0 env) (interpret v1 env) (interpret size_i_o env) 
		 (interpret lane_size env) (interpret num_4 env) (interpret prec_i_o env) 
		 (interpret num_6 env))
	]
	[ (_mm512_abs_epi64_dsl v0 size_i_o lane_size num_3 prec_i_o num_5)
		(assert (equal? size_i_o (get-length v0 env)))
		(_mm512_abs_epi64 (interpret v0 env) (interpret size_i_o env) (interpret lane_size env) 
		 (interpret num_3 env) (interpret prec_i_o env) (interpret num_5 env))
	]
	[ (_mm_urem_epi32_dsl v0 v1 size_i_o lane_size num_4 prec_i_o num_6)
		(assert (equal? (get-length v0 env) (get-length v1 env)))
		(assert (equal? size_i_o (get-length v0 env)))
		(assert (equal? size_i_o (get-length v1 env)))
		(_mm_urem_epi32 (interpret v0 env) (interpret v1 env) (interpret size_i_o env) 
		 (interpret lane_size env) (interpret num_4 env) (interpret prec_i_o env) 
		 (interpret num_6 env))
	]
	[ (_mm512_mask_cmple_epi32_mask_dsl vc_0 v1 v2 v3 size_i_o lane_size num_6 prec_o num_8 vc_9 vc_10 prec_i)
		(assert (equal? (get-length v2 env) (get-length v3 env)))
		(assert (equal? size_i_o (get-length v1 env)))
		(_mm512_mask_cmple_epi32_mask (interpret vc_0 env) (interpret v1 env) (interpret v2 env) 
		 (interpret v3 env) (interpret size_i_o env) (interpret lane_size env) 
		 (interpret num_6 env) (interpret prec_o env) (interpret num_8 env) 
		 (interpret vc_9 env) (interpret vc_10 env) (interpret prec_i env))
	]
	[ (_mm_cmpeq_epi32_dsl v0 v1 size_i_o lane_size num_4 prec_i_o num_6 vc_7 vc_8)
		(assert (equal? (get-length v0 env) (get-length v1 env)))
		(assert (equal? size_i_o (get-length v0 env)))
		(assert (equal? size_i_o (get-length v1 env)))
		(_mm_cmpeq_epi32 (interpret v0 env) (interpret v1 env) (interpret size_i_o env) 
		 (interpret lane_size env) (interpret num_4 env) (interpret prec_i_o env) 
		 (interpret num_6 env) (interpret vc_7 env) (interpret vc_8 env))
	]
	[ (_mm_maskz_adds_epu16_dsl vc_0 v1 v2 v3 size_i_o lane_size num_6 prec_i_o num_8)
		(assert (equal? (get-length v2 env) (get-length v3 env)))
		(assert (equal? size_i_o (get-length v2 env)))
		(assert (equal? size_i_o (get-length v3 env)))
		(_mm_maskz_adds_epu16 (interpret vc_0 env) (interpret v1 env) (interpret v2 env) 
		 (interpret v3 env) (interpret size_i_o env) (interpret lane_size env) 
		 (interpret num_6 env) (interpret prec_i_o env) (interpret num_8 env))
	]
	[ (_mm_maskz_dpbusds_epi32_dsl vc_0 v1 v2 v3 v4 size_i_o lane_size num_7 num_8 num_9 num_10 num_11 num_12 num_13)
		(assert (equal? (get-length v2 env) (get-length v3 env)))
		(assert (equal? (get-length v2 env) (get-length v4 env)))
		(assert (equal? (get-length v3 env) (get-length v4 env)))
		(assert (equal? size_i_o (get-length v2 env)))
		(assert (equal? size_i_o (get-length v3 env)))
		(assert (equal? size_i_o (get-length v4 env)))
		(_mm_maskz_dpbusds_epi32 (interpret vc_0 env) (interpret v1 env) (interpret v2 env) 
		 (interpret v3 env) (interpret v4 env) (interpret size_i_o env) 
		 (interpret lane_size env) (interpret num_7 env) (interpret num_8 env) 
		 (interpret num_9 env) (interpret num_10 env) (interpret num_11 env) 
		 (interpret num_12 env) (interpret num_13 env))
	]
	[ (_mm256_maskz_andnot_epi32_dsl vc_0 v1 v2 v3 size_i_o lane_size num_6 prec_i_o num_8)
		(assert (equal? (get-length v2 env) (get-length v3 env)))
		(assert (equal? size_i_o (get-length v2 env)))
		(assert (equal? size_i_o (get-length v3 env)))
		(_mm256_maskz_andnot_epi32 (interpret vc_0 env) (interpret v1 env) (interpret v2 env) 
		 (interpret v3 env) (interpret size_i_o env) (interpret lane_size env) 
		 (interpret num_6 env) (interpret prec_i_o env) (interpret num_8 env))
	]
	[ (_mm256_maskz_cvtepu32_epi64_dsl vc_0 v1 v2 size_i_o lane_size num_5 num_6 num_7 prec_i_o)
		(assert (equal? size_i_o (get-length v2 env)))
		(_mm256_maskz_cvtepu32_epi64 (interpret vc_0 env) (interpret v1 env) (interpret v2 env) 
		 (interpret size_i_o env) (interpret lane_size env) (interpret num_5 env) 
		 (interpret num_6 env) (interpret num_7 env) (interpret prec_i_o env))
	]
	[ (_mm256_mask_xor_epi64_dsl v0 v1 v2 v3 size_i_o lane_size num_6 prec_i_o num_8)
		(assert (equal? (get-length v0 env) (get-length v2 env)))
		(assert (equal? (get-length v0 env) (get-length v3 env)))
		(assert (equal? (get-length v2 env) (get-length v3 env)))
		(assert (equal? size_i_o (get-length v0 env)))
		(assert (equal? size_i_o (get-length v2 env)))
		(assert (equal? size_i_o (get-length v3 env)))
		(_mm256_mask_xor_epi64 (interpret v0 env) (interpret v1 env) (interpret v2 env) 
		 (interpret v3 env) (interpret size_i_o env) (interpret lane_size env) 
		 (interpret num_6 env) (interpret prec_i_o env) (interpret num_8 env))
	]
	[ (_mm512_mask_rem_epu32_dsl v0 v1 v2 v3 size_i_o lane_size num_6 prec_i_o num_8)
		(assert (equal? (get-length v0 env) (get-length v2 env)))
		(assert (equal? (get-length v0 env) (get-length v3 env)))
		(assert (equal? (get-length v2 env) (get-length v3 env)))
		(assert (equal? size_i_o (get-length v0 env)))
		(assert (equal? size_i_o (get-length v2 env)))
		(assert (equal? size_i_o (get-length v3 env)))
		(_mm512_mask_rem_epu32 (interpret v0 env) (interpret v1 env) (interpret v2 env) 
		 (interpret v3 env) (interpret size_i_o env) (interpret lane_size env) 
		 (interpret num_6 env) (interpret prec_i_o env) (interpret num_8 env))
	]
	[ (_mm_mask_cvtepi32_epi64_dsl v0 v1 v2 size_i_o lane_size num_5 num_6 num_7 prec_i_o)
		(assert (equal? (get-length v0 env) (get-length v2 env)))
		(assert (equal? size_i_o (get-length v2 env)))
		(_mm_mask_cvtepi32_epi64 (interpret v0 env) (interpret v1 env) (interpret v2 env) 
		 (interpret size_i_o env) (interpret lane_size env) (interpret num_5 env) 
		 (interpret num_6 env) (interpret num_7 env) (interpret prec_i_o env))
	]
	[ (_mm512_testn_epi32_mask_dsl v0 v1 size_i_o lane_size num_4 prec_o num_6 vc_7 vc_8 vc_9 prec_i)
		(assert (equal? (get-length v0 env) (get-length v1 env)))
		(_mm512_testn_epi32_mask (interpret v0 env) (interpret v1 env) (interpret size_i_o env) 
		 (interpret lane_size env) (interpret num_4 env) (interpret prec_o env) 
		 (interpret num_6 env) (interpret vc_7 env) (interpret vc_8 env) 
		 (interpret vc_9 env) (interpret prec_i env))
	]
	[ (_mm512_reduce_add_epi64_dsl vc_0 v1 size_i lane_size num_4 prec_i_o num_6 num_7)
		(assert (equal? size_i (get-length v1 env)))
		(_mm512_reduce_add_epi64 (interpret vc_0 env) (interpret v1 env) (interpret size_i env) 
		 (interpret lane_size env) (interpret num_4 env) (interpret prec_i_o env) 
		 (interpret num_6 env) (interpret num_7 env))
	]
	[ (_mm256_blendv_epi8_dsl v0 v1 v2 size_i_o lane_size num_5 prec_i_o num_7)
		(assert (equal? (get-length v0 env) (get-length v1 env)))
		(assert (equal? (get-length v0 env) (get-length v2 env)))
		(assert (equal? (get-length v1 env) (get-length v2 env)))
		(assert (equal? size_i_o (get-length v0 env)))
		(assert (equal? size_i_o (get-length v1 env)))
		(assert (equal? size_i_o (get-length v2 env)))
		(_mm256_blendv_epi8 (interpret v0 env) (interpret v1 env) (interpret v2 env) 
		 (interpret size_i_o env) (interpret lane_size env) (interpret num_5 env) 
		 (interpret prec_i_o env) (interpret num_7 env))
	]
	[ (_mm512_maskz_and_epi64_dsl vc_0 v1 v2 v3 size_i_o lane_size num_6 prec_i_o num_8)
		(assert (equal? (get-length v2 env) (get-length v3 env)))
		(assert (equal? size_i_o (get-length v2 env)))
		(assert (equal? size_i_o (get-length v3 env)))
		(_mm512_maskz_and_epi64 (interpret vc_0 env) (interpret v1 env) (interpret v2 env) 
		 (interpret v3 env) (interpret size_i_o env) (interpret lane_size env) 
		 (interpret num_6 env) (interpret prec_i_o env) (interpret num_8 env))
	]
	[ (_mm_mask_cmplt_epi64_mask_dsl vc_0 v1 v2 v3 size_i_o lane_size num_6 prec_o num_8 vc_9 vc_10 prec_i)
		(assert (equal? (get-length v2 env) (get-length v3 env)))
		(assert (equal? size_i_o (get-length v1 env)))
		(_mm_mask_cmplt_epi64_mask (interpret vc_0 env) (interpret v1 env) (interpret v2 env) 
		 (interpret v3 env) (interpret size_i_o env) (interpret lane_size env) 
		 (interpret num_6 env) (interpret prec_o env) (interpret num_8 env) 
		 (interpret vc_9 env) (interpret vc_10 env) (interpret prec_i env))
	]
	[ (_mm_maskz_dpwssds_epi32_dsl vc_0 v1 v2 v3 v4 size_i_o lane_size num_7 num_8 num_9 num_10 num_11 num_12)
		(assert (equal? (get-length v2 env) (get-length v3 env)))
		(assert (equal? (get-length v2 env) (get-length v4 env)))
		(assert (equal? (get-length v3 env) (get-length v4 env)))
		(assert (equal? size_i_o (get-length v2 env)))
		(assert (equal? size_i_o (get-length v3 env)))
		(assert (equal? size_i_o (get-length v4 env)))
		(_mm_maskz_dpwssds_epi32 (interpret vc_0 env) (interpret v1 env) (interpret v2 env) 
		 (interpret v3 env) (interpret v4 env) (interpret size_i_o env) 
		 (interpret lane_size env) (interpret num_7 env) (interpret num_8 env) 
		 (interpret num_9 env) (interpret num_10 env) (interpret num_11 env) 
		 (interpret num_12 env))
	]
	[ (_mm512_andnot_epi32_dsl v0 v1 size_i_o lane_size num_4 prec_i_o num_6)
		(assert (equal? (get-length v0 env) (get-length v1 env)))
		(assert (equal? size_i_o (get-length v0 env)))
		(assert (equal? size_i_o (get-length v1 env)))
		(_mm512_andnot_epi32 (interpret v0 env) (interpret v1 env) (interpret size_i_o env) 
		 (interpret lane_size env) (interpret num_4 env) (interpret prec_i_o env) 
		 (interpret num_6 env))
	]
	[ (_mm512_reduce_and_epi64_dsl vc_0 v1 size_i lane_size num_4 prec_i_o num_6 num_7)
		(assert (equal? size_i (get-length v1 env)))
		(_mm512_reduce_and_epi64 (interpret vc_0 env) (interpret v1 env) (interpret size_i env) 
		 (interpret lane_size env) (interpret num_4 env) (interpret prec_i_o env) 
		 (interpret num_6 env) (interpret num_7 env))
	]
	[ (_m_paddw_dsl v0 v1 size_i_o lane_size num_4 prec_i_o num_6)
		(assert (equal? (get-length v0 env) (get-length v1 env)))
		(assert (equal? size_i_o (get-length v0 env)))
		(assert (equal? size_i_o (get-length v1 env)))
		(_m_paddw (interpret v0 env) (interpret v1 env) (interpret size_i_o env) 
		 (interpret lane_size env) (interpret num_4 env) (interpret prec_i_o env) 
		 (interpret num_6 env))
	]
	[ (_mm256_max_epi8_dsl v0 v1 size_i_o lane_size num_4 prec_i_o num_6)
		(assert (equal? (get-length v0 env) (get-length v1 env)))
		(assert (equal? size_i_o (get-length v0 env)))
		(assert (equal? size_i_o (get-length v1 env)))
		(_mm256_max_epi8 (interpret v0 env) (interpret v1 env) (interpret size_i_o env) 
		 (interpret lane_size env) (interpret num_4 env) (interpret prec_i_o env) 
		 (interpret num_6 env))
	]
	[ (_mm256_mask_dpbusds_epi32_dsl v0 v1 v2 v3 size_i_o lane_size num_6 num_7 num_8 num_9 num_10 num_11 num_12)
		(assert (equal? (get-length v0 env) (get-length v2 env)))
		(assert (equal? (get-length v0 env) (get-length v3 env)))
		(assert (equal? (get-length v2 env) (get-length v3 env)))
		(assert (equal? size_i_o (get-length v0 env)))
		(assert (equal? size_i_o (get-length v2 env)))
		(assert (equal? size_i_o (get-length v3 env)))
		(_mm256_mask_dpbusds_epi32 (interpret v0 env) (interpret v1 env) (interpret v2 env) 
		 (interpret v3 env) (interpret size_i_o env) (interpret lane_size env) 
		 (interpret num_6 env) (interpret num_7 env) (interpret num_8 env) 
		 (interpret num_9 env) (interpret num_10 env) (interpret num_11 env) 
		 (interpret num_12 env))
	]
	[ (_mm256_mask_madd52lo_epu64_dsl v0 v1 v2 v3 size_i_o lane_size num_6 num_7 num_8 prec_i_o num_10 num_11 num_12)
		(assert (equal? (get-length v0 env) (get-length v2 env)))
		(assert (equal? (get-length v0 env) (get-length v3 env)))
		(assert (equal? (get-length v2 env) (get-length v3 env)))
		(assert (equal? size_i_o (get-length v0 env)))
		(assert (equal? size_i_o (get-length v2 env)))
		(assert (equal? size_i_o (get-length v3 env)))
		(_mm256_mask_madd52lo_epu64 (interpret v0 env) (interpret v1 env) (interpret v2 env) 
		 (interpret v3 env) (interpret size_i_o env) (interpret lane_size env) 
		 (interpret num_6 env) (interpret num_7 env) (interpret num_8 env) 
		 (interpret prec_i_o env) (interpret num_10 env) (interpret num_11 env) 
		 (interpret num_12 env))
	]
	[ (_mm256_test_epi8_mask_dsl v0 v1 size_i_o lane_size num_4 prec_o num_6 vc_7 vc_8 vc_9 prec_i)
		(assert (equal? (get-length v0 env) (get-length v1 env)))
		(_mm256_test_epi8_mask (interpret v0 env) (interpret v1 env) (interpret size_i_o env) 
		 (interpret lane_size env) (interpret num_4 env) (interpret prec_o env) 
		 (interpret num_6 env) (interpret vc_7 env) (interpret vc_8 env) 
		 (interpret vc_9 env) (interpret prec_i env))
	]
	[ (_mm256_xor_epi32_dsl v0 v1 size_i_o lane_size num_4 prec_i_o num_6)
		(assert (equal? (get-length v0 env) (get-length v1 env)))
		(assert (equal? size_i_o (get-length v0 env)))
		(assert (equal? size_i_o (get-length v1 env)))
		(_mm256_xor_epi32 (interpret v0 env) (interpret v1 env) (interpret size_i_o env) 
		 (interpret lane_size env) (interpret num_4 env) (interpret prec_i_o env) 
		 (interpret num_6 env))
	]
	[ (_mm512_cmpeq_epi64_mask_dsl v0 v1 size_i_o lane_size num_4 prec_o num_6 vc_7 vc_8 prec_i)
		(assert (equal? (get-length v0 env) (get-length v1 env)))
		(_mm512_cmpeq_epi64_mask (interpret v0 env) (interpret v1 env) (interpret size_i_o env) 
		 (interpret lane_size env) (interpret num_4 env) (interpret prec_o env) 
		 (interpret num_6 env) (interpret vc_7 env) (interpret vc_8 env) 
		 (interpret prec_i env))
	]
	[ (_mm512_maskz_subs_epi8_dsl vc_0 v1 v2 v3 size_i_o lane_size num_6 prec_i_o num_8)
		(assert (equal? (get-length v2 env) (get-length v3 env)))
		(assert (equal? size_i_o (get-length v2 env)))
		(assert (equal? size_i_o (get-length v3 env)))
		(_mm512_maskz_subs_epi8 (interpret vc_0 env) (interpret v1 env) (interpret v2 env) 
		 (interpret v3 env) (interpret size_i_o env) (interpret lane_size env) 
		 (interpret num_6 env) (interpret prec_i_o env) (interpret num_8 env))
	]
	[ (_mm_cmple_epu32_mask_dsl v0 v1 size_i_o lane_size num_4 prec_o num_6 vc_7 vc_8 prec_i)
		(assert (equal? (get-length v0 env) (get-length v1 env)))
		(_mm_cmple_epu32_mask (interpret v0 env) (interpret v1 env) (interpret size_i_o env) 
		 (interpret lane_size env) (interpret num_4 env) (interpret prec_o env) 
		 (interpret num_6 env) (interpret vc_7 env) (interpret vc_8 env) 
		 (interpret prec_i env))
	]
	[ (_mm_maskz_mul_epi32_dsl vc_0 v1 v2 v3 size_i_o lane_size num_6 num_7 num_8 prec_i_o)
		(assert (equal? (get-length v2 env) (get-length v3 env)))
		(assert (equal? size_i_o (get-length v2 env)))
		(assert (equal? size_i_o (get-length v3 env)))
		(_mm_maskz_mul_epi32 (interpret vc_0 env) (interpret v1 env) (interpret v2 env) 
		 (interpret v3 env) (interpret size_i_o env) (interpret lane_size env) 
		 (interpret num_6 env) (interpret num_7 env) (interpret num_8 env) 
		 (interpret prec_i_o env))
	]
	[ (_mm_mulhi_pi16_dsl v0 v1 size_i_o lane_size num_4 prec_i_o num_6 num_7 num_8)
		(assert (equal? (get-length v0 env) (get-length v1 env)))
		(assert (equal? size_i_o (get-length v0 env)))
		(assert (equal? size_i_o (get-length v1 env)))
		(_mm_mulhi_pi16 (interpret v0 env) (interpret v1 env) (interpret size_i_o env) 
		 (interpret lane_size env) (interpret num_4 env) (interpret prec_i_o env) 
		 (interpret num_6 env) (interpret num_7 env) (interpret num_8 env))
	]
	[ (_mm512_mask_cmpgt_epu32_mask_dsl vc_0 v1 v2 v3 size_i_o lane_size num_6 prec_o num_8 vc_9 vc_10 prec_i)
		(assert (equal? (get-length v2 env) (get-length v3 env)))
		(assert (equal? size_i_o (get-length v1 env)))
		(_mm512_mask_cmpgt_epu32_mask (interpret vc_0 env) (interpret v1 env) (interpret v2 env) 
		 (interpret v3 env) (interpret size_i_o env) (interpret lane_size env) 
		 (interpret num_6 env) (interpret prec_o env) (interpret num_8 env) 
		 (interpret vc_9 env) (interpret vc_10 env) (interpret prec_i env))
	]
	[ (_mm256_maskz_min_epu16_dsl vc_0 v1 v2 v3 size_i_o lane_size num_6 prec_i_o num_8)
		(assert (equal? (get-length v2 env) (get-length v3 env)))
		(assert (equal? size_i_o (get-length v2 env)))
		(assert (equal? size_i_o (get-length v3 env)))
		(_mm256_maskz_min_epu16 (interpret vc_0 env) (interpret v1 env) (interpret v2 env) 
		 (interpret v3 env) (interpret size_i_o env) (interpret lane_size env) 
		 (interpret num_6 env) (interpret prec_i_o env) (interpret num_8 env))
	]
	[ (_mm_mask_dpwssd_epi32_dsl v0 v1 v2 v3 size_i_o lane_size num_6 num_7 num_8 num_9 num_10 num_11)
		(assert (equal? (get-length v0 env) (get-length v2 env)))
		(assert (equal? (get-length v0 env) (get-length v3 env)))
		(assert (equal? (get-length v2 env) (get-length v3 env)))
		(assert (equal? size_i_o (get-length v0 env)))
		(assert (equal? size_i_o (get-length v2 env)))
		(assert (equal? size_i_o (get-length v3 env)))
		(_mm_mask_dpwssd_epi32 (interpret v0 env) (interpret v1 env) (interpret v2 env) 
		 (interpret v3 env) (interpret size_i_o env) (interpret lane_size env) 
		 (interpret num_6 env) (interpret num_7 env) (interpret num_8 env) 
		 (interpret num_9 env) (interpret num_10 env) (interpret num_11 env))
	]
	[ (_mm256_adds_epi16_dsl v0 v1 size_i_o lane_size num_4 prec_i_o num_6)
		(assert (equal? (get-length v0 env) (get-length v1 env)))
		(assert (equal? size_i_o (get-length v0 env)))
		(assert (equal? size_i_o (get-length v1 env)))
		(_mm256_adds_epi16 (interpret v0 env) (interpret v1 env) (interpret size_i_o env) 
		 (interpret lane_size env) (interpret num_4 env) (interpret prec_i_o env) 
		 (interpret num_6 env))
	]
	[ (_mm_dpbusds_epi32_dsl v0 v1 v2 size_i lane_size num_5 prec_i num_7 num_8)
		(assert (equal? size_i (get-length v0 env)))
		(assert (equal? (get-length v0 env) (get-length v1 env)))
		(assert (equal? (get-length v0 env) (get-length v2 env)))
		(assert (equal? (get-length v1 env) (get-length v2 env)))
		(assert (equal? size_i (get-length v1 env)))
		(assert (equal? size_i (get-length v2 env)))
		(_mm_dpbusds_epi32 (interpret v0 env) (interpret v1 env) (interpret v2 env) 
		 (interpret size_i env) (interpret lane_size env) (interpret num_5 env) 
		 (interpret prec_i env) (interpret num_7 env) (interpret num_8 env))
	]
	[ (_mm256_cmpneq_epi8_mask_dsl v0 v1 size_i_o lane_size num_4 prec_o num_6 vc_7 vc_8 prec_i)
		(assert (equal? (get-length v0 env) (get-length v1 env)))
		(_mm256_cmpneq_epi8_mask (interpret v0 env) (interpret v1 env) (interpret size_i_o env) 
		 (interpret lane_size env) (interpret num_4 env) (interpret prec_o env) 
		 (interpret num_6 env) (interpret vc_7 env) (interpret vc_8 env) 
		 (interpret prec_i env))
	]
	[ (_m_pmovmskb_dsl v0 size_o lane_size num_3 prec_o num_5 num_6)
		(_m_pmovmskb (interpret v0 env) (interpret size_o env) (interpret lane_size env) 
		 (interpret num_3 env) (interpret prec_o env) (interpret num_5 env) 
		 (interpret num_6 env))
	]
	[ (_mm512_mask_cvtepi32_epi8_dsl v0 v1 v2 size_i_o lane_size num_5 prec_i_o num_7 num_8)
		(assert (equal? size_i_o (get-length v0 env)))
		(_mm512_mask_cvtepi32_epi8 (interpret v0 env) (interpret v1 env) (interpret v2 env) 
		 (interpret size_i_o env) (interpret lane_size env) (interpret num_5 env) 
		 (interpret prec_i_o env) (interpret num_7 env) (interpret num_8 env))
	]
	[ (_mm_mask_mul_epu32_dsl v0 v1 v2 v3 size_i_o lane_size num_6 num_7 num_8 prec_i_o)
		(assert (equal? (get-length v0 env) (get-length v2 env)))
		(assert (equal? (get-length v0 env) (get-length v3 env)))
		(assert (equal? (get-length v2 env) (get-length v3 env)))
		(assert (equal? size_i_o (get-length v0 env)))
		(assert (equal? size_i_o (get-length v2 env)))
		(assert (equal? size_i_o (get-length v3 env)))
		(_mm_mask_mul_epu32 (interpret v0 env) (interpret v1 env) (interpret v2 env) 
		 (interpret v3 env) (interpret size_i_o env) (interpret lane_size env) 
		 (interpret num_6 env) (interpret num_7 env) (interpret num_8 env) 
		 (interpret prec_i_o env))
	]
	[ (_mm_cmpgt_epi8_mask_dsl v0 v1 size_i_o lane_size num_4 prec_o num_6 vc_7 vc_8 prec_i)
		(assert (equal? (get-length v0 env) (get-length v1 env)))
		(_mm_cmpgt_epi8_mask (interpret v0 env) (interpret v1 env) (interpret size_i_o env) 
		 (interpret lane_size env) (interpret num_4 env) (interpret prec_o env) 
		 (interpret num_6 env) (interpret vc_7 env) (interpret vc_8 env) 
		 (interpret prec_i env))
	]
	[ (_mm512_mask_cmplt_epu64_mask_dsl vc_0 v1 v2 v3 size_i_o lane_size num_6 prec_o num_8 vc_9 vc_10 prec_i)
		(assert (equal? (get-length v2 env) (get-length v3 env)))
		(assert (equal? size_i_o (get-length v1 env)))
		(_mm512_mask_cmplt_epu64_mask (interpret vc_0 env) (interpret v1 env) (interpret v2 env) 
		 (interpret v3 env) (interpret size_i_o env) (interpret lane_size env) 
		 (interpret num_6 env) (interpret prec_o env) (interpret num_8 env) 
		 (interpret vc_9 env) (interpret vc_10 env) (interpret prec_i env))
	]
	[ (_mm512_mask_reduce_and_epi64_dsl vc_0 v1 v2 size_i_o lane_size num_5 prec_i_o num_7 num_8)
		(assert (equal? size_i_o (get-length v2 env)))
		(_mm512_mask_reduce_and_epi64 (interpret vc_0 env) (interpret v1 env) (interpret v2 env) 
		 (interpret size_i_o env) (interpret lane_size env) (interpret num_5 env) 
		 (interpret prec_i_o env) (interpret num_7 env) (interpret num_8 env))
	]
	[ (_mm256_mask_dpwssds_epi32_dsl v0 v1 v2 v3 size_i_o lane_size num_6 num_7 num_8 num_9 num_10 num_11)
		(assert (equal? (get-length v0 env) (get-length v2 env)))
		(assert (equal? (get-length v0 env) (get-length v3 env)))
		(assert (equal? (get-length v2 env) (get-length v3 env)))
		(assert (equal? size_i_o (get-length v0 env)))
		(assert (equal? size_i_o (get-length v2 env)))
		(assert (equal? size_i_o (get-length v3 env)))
		(_mm256_mask_dpwssds_epi32 (interpret v0 env) (interpret v1 env) (interpret v2 env) 
		 (interpret v3 env) (interpret size_i_o env) (interpret lane_size env) 
		 (interpret num_6 env) (interpret num_7 env) (interpret num_8 env) 
		 (interpret num_9 env) (interpret num_10 env) (interpret num_11 env))
	]
	[ (_mm_cvtepi16_epi64_dsl v0 size_i_o lane_size num_3 prec_i num_5 prec_o)
		(assert (equal? size_i_o (get-length v0 env)))
		(_mm_cvtepi16_epi64 (interpret v0 env) (interpret size_i_o env) (interpret lane_size env) 
		 (interpret num_3 env) (interpret prec_i env) (interpret num_5 env) 
		 (interpret prec_o env))
	]
	[ (_mm_mask_blend_epi64_dsl v0 v1 v2 size_i_o lane_size num_5 prec_i_o num_7)
		(assert (equal? (get-length v1 env) (get-length v2 env)))
		(assert (equal? size_i_o (get-length v1 env)))
		(assert (equal? size_i_o (get-length v2 env)))
		(_mm_mask_blend_epi64 (interpret v0 env) (interpret v1 env) (interpret v2 env) 
		 (interpret size_i_o env) (interpret lane_size env) (interpret num_5 env) 
		 (interpret prec_i_o env) (interpret num_7 env))
	]
	[ (_mm256_mask_cmple_epu32_mask_dsl vc_0 v1 v2 v3 size_i_o lane_size num_6 prec_o num_8 vc_9 vc_10 prec_i)
		(assert (equal? (get-length v2 env) (get-length v3 env)))
		(assert (equal? size_i_o (get-length v1 env)))
		(_mm256_mask_cmple_epu32_mask (interpret vc_0 env) (interpret v1 env) (interpret v2 env) 
		 (interpret v3 env) (interpret size_i_o env) (interpret lane_size env) 
		 (interpret num_6 env) (interpret prec_o env) (interpret num_8 env) 
		 (interpret vc_9 env) (interpret vc_10 env) (interpret prec_i env))
	]
	[ (_mm512_maskz_mov_epi64_dsl vc_0 v1 v2 size_i_o lane_size num_5 prec_i_o num_7)
		(assert (equal? size_i_o (get-length v2 env)))
		(_mm512_maskz_mov_epi64 (interpret vc_0 env) (interpret v1 env) (interpret v2 env) 
		 (interpret size_i_o env) (interpret lane_size env) (interpret num_5 env) 
		 (interpret prec_i_o env) (interpret num_7 env))
	]
	[ (_mm_cvtepu16_epi32_dsl v0 size_i_o lane_size num_3 prec_i num_5 prec_o)
		(assert (equal? size_i_o (get-length v0 env)))
		(_mm_cvtepu16_epi32 (interpret v0 env) (interpret size_i_o env) (interpret lane_size env) 
		 (interpret num_3 env) (interpret prec_i env) (interpret num_5 env) 
		 (interpret prec_o env))
	]
	[ (_mm256_broadcastmw_epi32_dsl v0 size_o lane_size num_3 prec_i num_5 prec_o num_7)
		(_mm256_broadcastmw_epi32 (interpret v0 env) (interpret size_o env) (interpret lane_size env) 
		 (interpret num_3 env) (interpret prec_i env) (interpret num_5 env) 
		 (interpret prec_o env) (interpret num_7 env))
	]
	[ (_mm512_mask_div_epi32_dsl v0 v1 v2 v3 size_i_o lane_size num_6 prec_i_o num_8 num_9 num_10)
		(assert (equal? (get-length v0 env) (get-length v2 env)))
		(assert (equal? (get-length v0 env) (get-length v3 env)))
		(assert (equal? (get-length v2 env) (get-length v3 env)))
		(assert (equal? size_i_o (get-length v0 env)))
		(assert (equal? size_i_o (get-length v2 env)))
		(assert (equal? size_i_o (get-length v3 env)))
		(_mm512_mask_div_epi32 (interpret v0 env) (interpret v1 env) (interpret v2 env) 
		 (interpret v3 env) (interpret size_i_o env) (interpret lane_size env) 
		 (interpret num_6 env) (interpret prec_i_o env) (interpret num_8 env) 
		 (interpret num_9 env) (interpret num_10 env))
	]
	[ (_mm512_maskz_maddubs_epi16_dsl vc_0 v1 v2 v3 size_i_o lane_size num_6 num_7 num_8 prec_i_o num_10)
		(assert (equal? (get-length v2 env) (get-length v3 env)))
		(assert (equal? size_i_o (get-length v2 env)))
		(assert (equal? size_i_o (get-length v3 env)))
		(_mm512_maskz_maddubs_epi16 (interpret vc_0 env) (interpret v1 env) (interpret v2 env) 
		 (interpret v3 env) (interpret size_i_o env) (interpret lane_size env) 
		 (interpret num_6 env) (interpret num_7 env) (interpret num_8 env) 
		 (interpret prec_i_o env) (interpret num_10 env))
	]
	[ (_mm256_maskz_dpwssd_epi32_dsl vc_0 v1 v2 v3 v4 size_i_o lane_size num_7 num_8 num_9 num_10 num_11 num_12)
		(assert (equal? (get-length v2 env) (get-length v3 env)))
		(assert (equal? (get-length v2 env) (get-length v4 env)))
		(assert (equal? (get-length v3 env) (get-length v4 env)))
		(assert (equal? size_i_o (get-length v2 env)))
		(assert (equal? size_i_o (get-length v3 env)))
		(assert (equal? size_i_o (get-length v4 env)))
		(_mm256_maskz_dpwssd_epi32 (interpret vc_0 env) (interpret v1 env) (interpret v2 env) 
		 (interpret v3 env) (interpret v4 env) (interpret size_i_o env) 
		 (interpret lane_size env) (interpret num_7 env) (interpret num_8 env) 
		 (interpret num_9 env) (interpret num_10 env) (interpret num_11 env) 
		 (interpret num_12 env))
	]
	[ (_mm_cmplt_epi32_mask_dsl v0 v1 size_i_o lane_size num_4 prec_o num_6 vc_7 vc_8 prec_i)
		(assert (equal? (get-length v0 env) (get-length v1 env)))
		(_mm_cmplt_epi32_mask (interpret v0 env) (interpret v1 env) (interpret size_i_o env) 
		 (interpret lane_size env) (interpret num_4 env) (interpret prec_o env) 
		 (interpret num_6 env) (interpret vc_7 env) (interpret vc_8 env) 
		 (interpret prec_i env))
	]
	[ (_mm512_mask_cmpge_epi16_mask_dsl vc_0 v1 v2 v3 size_i_o lane_size num_6 prec_o num_8 vc_9 vc_10 prec_i)
		(assert (equal? (get-length v2 env) (get-length v3 env)))
		(assert (equal? size_i_o (get-length v1 env)))
		(_mm512_mask_cmpge_epi16_mask (interpret vc_0 env) (interpret v1 env) (interpret v2 env) 
		 (interpret v3 env) (interpret size_i_o env) (interpret lane_size env) 
		 (interpret num_6 env) (interpret prec_o env) (interpret num_8 env) 
		 (interpret vc_9 env) (interpret vc_10 env) (interpret prec_i env))
	]
	[ (_mm_dpwssds_epi32_dsl v0 v1 v2 size_i lane_size num_5 prec_i num_7)
		(assert (equal? size_i (get-length v0 env)))
		(assert (equal? (get-length v0 env) (get-length v1 env)))
		(assert (equal? (get-length v0 env) (get-length v2 env)))
		(assert (equal? (get-length v1 env) (get-length v2 env)))
		(assert (equal? size_i (get-length v1 env)))
		(assert (equal? size_i (get-length v2 env)))
		(_mm_dpwssds_epi32 (interpret v0 env) (interpret v1 env) (interpret v2 env) 
		 (interpret size_i env) (interpret lane_size env) (interpret num_5 env) 
		 (interpret prec_i env) (interpret num_7 env))
	]
	[ (_mm_or_epi32_dsl v0 v1 size_i_o lane_size num_4 prec_i_o num_6)
		(assert (equal? (get-length v0 env) (get-length v1 env)))
		(assert (equal? size_i_o (get-length v0 env)))
		(assert (equal? size_i_o (get-length v1 env)))
		(_mm_or_epi32 (interpret v0 env) (interpret v1 env) (interpret size_i_o env) 
		 (interpret lane_size env) (interpret num_4 env) (interpret prec_i_o env) 
		 (interpret num_6 env))
	]
	[ (_mm_dpwssd_epi32_dsl v0 v1 v2 size_i lane_size num_5 prec_i num_7)
		(assert (equal? size_i (get-length v0 env)))
		(assert (equal? (get-length v0 env) (get-length v1 env)))
		(assert (equal? (get-length v0 env) (get-length v2 env)))
		(assert (equal? (get-length v1 env) (get-length v2 env)))
		(assert (equal? size_i (get-length v1 env)))
		(assert (equal? size_i (get-length v2 env)))
		(_mm_dpwssd_epi32 (interpret v0 env) (interpret v1 env) (interpret v2 env) 
		 (interpret size_i env) (interpret lane_size env) (interpret num_5 env) 
		 (interpret prec_i env) (interpret num_7 env))
	]
	[ (_mm256_maskz_mulhrs_epi16_dsl vc_0 v1 v2 v3 size_i_o lane_size num_6 prec_i_o num_8 num_9 vc_10 vc_11 num_12)
		(assert (equal? (get-length v2 env) (get-length v3 env)))
		(assert (equal? size_i_o (get-length v2 env)))
		(assert (equal? size_i_o (get-length v3 env)))
		(_mm256_maskz_mulhrs_epi16 (interpret vc_0 env) (interpret v1 env) (interpret v2 env) 
		 (interpret v3 env) (interpret size_i_o env) (interpret lane_size env) 
		 (interpret num_6 env) (interpret prec_i_o env) (interpret num_8 env) 
		 (interpret num_9 env) (interpret vc_10 env) (interpret vc_11 env) 
		 (interpret num_12 env))
	]
	[ (_mm512_subs_epi16_dsl v0 v1 size_i_o lane_size num_4 prec_i_o num_6)
		(assert (equal? (get-length v0 env) (get-length v1 env)))
		(assert (equal? size_i_o (get-length v0 env)))
		(assert (equal? size_i_o (get-length v1 env)))
		(_mm512_subs_epi16 (interpret v0 env) (interpret v1 env) (interpret size_i_o env) 
		 (interpret lane_size env) (interpret num_4 env) (interpret prec_i_o env) 
		 (interpret num_6 env))
	]
	[ (_mm256_mul_epu32_dsl v0 v1 size_i_o lane_size num_4 prec_i num_6 prec_o)
		(assert (equal? (get-length v0 env) (get-length v1 env)))
		(assert (equal? size_i_o (get-length v0 env)))
		(assert (equal? size_i_o (get-length v1 env)))
		(_mm256_mul_epu32 (interpret v0 env) (interpret v1 env) (interpret size_i_o env) 
		 (interpret lane_size env) (interpret num_4 env) (interpret prec_i env) 
		 (interpret num_6 env) (interpret prec_o env))
	]
	[ (_mm512_min_epu64_dsl v0 v1 size_i_o lane_size num_4 prec_i_o num_6)
		(assert (equal? (get-length v0 env) (get-length v1 env)))
		(assert (equal? size_i_o (get-length v0 env)))
		(assert (equal? size_i_o (get-length v1 env)))
		(_mm512_min_epu64 (interpret v0 env) (interpret v1 env) (interpret size_i_o env) 
		 (interpret lane_size env) (interpret num_4 env) (interpret prec_i_o env) 
		 (interpret num_6 env))
	]
	[ (_mm512_mask_reduce_or_epi64_dsl vc_0 v1 v2 size_i_o lane_size num_5 prec_i_o num_7 num_8)
		(assert (equal? size_i_o (get-length v2 env)))
		(_mm512_mask_reduce_or_epi64 (interpret vc_0 env) (interpret v1 env) (interpret v2 env) 
		 (interpret size_i_o env) (interpret lane_size env) (interpret num_5 env) 
		 (interpret prec_i_o env) (interpret num_7 env) (interpret num_8 env))
	]
	[ (_mm256_cmpgt_epi8_dsl v0 v1 size_i_o lane_size num_4 prec_i_o num_6 vc_7 vc_8)
		(assert (equal? (get-length v0 env) (get-length v1 env)))
		(assert (equal? size_i_o (get-length v0 env)))
		(assert (equal? size_i_o (get-length v1 env)))
		(_mm256_cmpgt_epi8 (interpret v0 env) (interpret v1 env) (interpret size_i_o env) 
		 (interpret lane_size env) (interpret num_4 env) (interpret prec_i_o env) 
		 (interpret num_6 env) (interpret vc_7 env) (interpret vc_8 env))
	]
	[ (_mm256_cmplt_epu16_mask_dsl v0 v1 size_i_o lane_size num_4 prec_o num_6 vc_7 vc_8 prec_i)
		(assert (equal? (get-length v0 env) (get-length v1 env)))
		(_mm256_cmplt_epu16_mask (interpret v0 env) (interpret v1 env) (interpret size_i_o env) 
		 (interpret lane_size env) (interpret num_4 env) (interpret prec_o env) 
		 (interpret num_6 env) (interpret vc_7 env) (interpret vc_8 env) 
		 (interpret prec_i env))
	]
	[ (_mm256_mulhrs_epi16_dsl v0 v1 size_i_o lane_size num_4 prec_i_o num_6 num_7 vc_8 vc_9 num_10)
		(assert (equal? (get-length v0 env) (get-length v1 env)))
		(assert (equal? size_i_o (get-length v0 env)))
		(assert (equal? size_i_o (get-length v1 env)))
		(_mm256_mulhrs_epi16 (interpret v0 env) (interpret v1 env) (interpret size_i_o env) 
		 (interpret lane_size env) (interpret num_4 env) (interpret prec_i_o env) 
		 (interpret num_6 env) (interpret num_7 env) (interpret vc_8 env) 
		 (interpret vc_9 env) (interpret num_10 env))
	]
	[ (_mm512_min_epi8_dsl v0 v1 size_i_o lane_size num_4 prec_i_o num_6)
		(assert (equal? (get-length v0 env) (get-length v1 env)))
		(assert (equal? size_i_o (get-length v0 env)))
		(assert (equal? size_i_o (get-length v1 env)))
		(_mm512_min_epi8 (interpret v0 env) (interpret v1 env) (interpret size_i_o env) 
		 (interpret lane_size env) (interpret num_4 env) (interpret prec_i_o env) 
		 (interpret num_6 env))
	]
	[ (_mm_cvtusepi64_epi32_dsl v0 size_i_o lane_size num_3 prec_o num_5 prec_i)
		(_mm_cvtusepi64_epi32 (interpret v0 env) (interpret size_i_o env) (interpret lane_size env) 
		 (interpret num_3 env) (interpret prec_o env) (interpret num_5 env) 
		 (interpret prec_i env))
	]
	[ (_mm512_reduce_or_epi64_dsl vc_0 v1 size_i lane_size num_4 prec_i_o num_6 num_7)
		(assert (equal? size_i (get-length v1 env)))
		(_mm512_reduce_or_epi64 (interpret vc_0 env) (interpret v1 env) (interpret size_i env) 
		 (interpret lane_size env) (interpret num_4 env) (interpret prec_i_o env) 
		 (interpret num_6 env) (interpret num_7 env))
	]
	[ (_mm_blend_epi16_dsl v0 v1 v2 size_i_o lane_size num_5 prec_i_o num_7)
		(assert (equal? (get-length v0 env) (get-length v1 env)))
		(assert (equal? size_i_o (get-length v0 env)))
		(assert (equal? size_i_o (get-length v1 env)))
		(_mm_blend_epi16 (interpret v0 env) (interpret v1 env) (interpret v2 env) 
		 (interpret size_i_o env) (interpret lane_size env) (interpret num_5 env) 
		 (interpret prec_i_o env) (interpret num_7 env))
	]
	[ (_mm256_movm_epi64_dsl v0 size_o lane_size num_3 prec_o num_5 vc_6 vc_7)
		(_mm256_movm_epi64 (interpret v0 env) (interpret size_o env) (interpret lane_size env) 
		 (interpret num_3 env) (interpret prec_o env) (interpret num_5 env) 
		 (interpret vc_6 env) (interpret vc_7 env))
	]
	[ (_mm256_maskz_madd_epi16_dsl vc_0 v1 v2 v3 size_i_o lane_size num_6 num_7 num_8 prec_i_o num_10)
		(assert (equal? (get-length v2 env) (get-length v3 env)))
		(assert (equal? size_i_o (get-length v2 env)))
		(assert (equal? size_i_o (get-length v3 env)))
		(_mm256_maskz_madd_epi16 (interpret vc_0 env) (interpret v1 env) (interpret v2 env) 
		 (interpret v3 env) (interpret size_i_o env) (interpret lane_size env) 
		 (interpret num_6 env) (interpret num_7 env) (interpret num_8 env) 
		 (interpret prec_i_o env) (interpret num_10 env))
	]
	[ (_mm512_mask_adds_epi16_dsl v0 v1 v2 v3 size_i_o lane_size num_6 prec_i_o num_8)
		(assert (equal? (get-length v0 env) (get-length v2 env)))
		(assert (equal? (get-length v0 env) (get-length v3 env)))
		(assert (equal? (get-length v2 env) (get-length v3 env)))
		(assert (equal? size_i_o (get-length v0 env)))
		(assert (equal? size_i_o (get-length v2 env)))
		(assert (equal? size_i_o (get-length v3 env)))
		(_mm512_mask_adds_epi16 (interpret v0 env) (interpret v1 env) (interpret v2 env) 
		 (interpret v3 env) (interpret size_i_o env) (interpret lane_size env) 
		 (interpret num_6 env) (interpret prec_i_o env) (interpret num_8 env))
	]
	[ (_mm_maskz_avg_epu16_dsl vc_0 v1 v2 v3 size_i_o lane_size num_6 prec_i_o num_8 vc_9 vc_10)
		(assert (equal? (get-length v2 env) (get-length v3 env)))
		(assert (equal? size_i_o (get-length v2 env)))
		(assert (equal? size_i_o (get-length v3 env)))
		(_mm_maskz_avg_epu16 (interpret vc_0 env) (interpret v1 env) (interpret v2 env) 
		 (interpret v3 env) (interpret size_i_o env) (interpret lane_size env) 
		 (interpret num_6 env) (interpret prec_i_o env) (interpret num_8 env) 
		 (interpret vc_9 env) (interpret vc_10 env))
	]
	[ (_mm_mask_or_epi32_dsl v0 v1 v2 v3 size_i_o lane_size num_6 prec_i_o num_8)
		(assert (equal? (get-length v0 env) (get-length v2 env)))
		(assert (equal? (get-length v0 env) (get-length v3 env)))
		(assert (equal? (get-length v2 env) (get-length v3 env)))
		(assert (equal? size_i_o (get-length v0 env)))
		(assert (equal? size_i_o (get-length v2 env)))
		(assert (equal? size_i_o (get-length v3 env)))
		(_mm_mask_or_epi32 (interpret v0 env) (interpret v1 env) (interpret v2 env) 
		 (interpret v3 env) (interpret size_i_o env) (interpret lane_size env) 
		 (interpret num_6 env) (interpret prec_i_o env) (interpret num_8 env))
	]
	[ (_mm_maskz_abs_epi16_dsl vc_0 v1 v2 size_i_o lane_size num_5 prec_i_o num_7)
		(assert (equal? size_i_o (get-length v2 env)))
		(_mm_maskz_abs_epi16 (interpret vc_0 env) (interpret v1 env) (interpret v2 env) 
		 (interpret size_i_o env) (interpret lane_size env) (interpret num_5 env) 
		 (interpret prec_i_o env) (interpret num_7 env))
	]
	[ (_mm512_and_epi32_dsl v0 v1 size_i_o lane_size num_4 prec_i_o num_6)
		(assert (equal? (get-length v0 env) (get-length v1 env)))
		(assert (equal? size_i_o (get-length v0 env)))
		(assert (equal? size_i_o (get-length v1 env)))
		(_mm512_and_epi32 (interpret v0 env) (interpret v1 env) (interpret size_i_o env) 
		 (interpret lane_size env) (interpret num_4 env) (interpret prec_i_o env) 
		 (interpret num_6 env))
	]
	[ (_mm256_cmpgt_epu32_mask_dsl v0 v1 size_i_o lane_size num_4 prec_o num_6 vc_7 vc_8 prec_i)
		(assert (equal? (get-length v0 env) (get-length v1 env)))
		(_mm256_cmpgt_epu32_mask (interpret v0 env) (interpret v1 env) (interpret size_i_o env) 
		 (interpret lane_size env) (interpret num_4 env) (interpret prec_o env) 
		 (interpret num_6 env) (interpret vc_7 env) (interpret vc_8 env) 
		 (interpret prec_i env))
	]
	[ (_mm_cmpge_epu64_mask_dsl v0 v1 size_i_o lane_size num_4 prec_o num_6 vc_7 vc_8 prec_i)
		(assert (equal? (get-length v0 env) (get-length v1 env)))
		(_mm_cmpge_epu64_mask (interpret v0 env) (interpret v1 env) (interpret size_i_o env) 
		 (interpret lane_size env) (interpret num_4 env) (interpret prec_o env) 
		 (interpret num_6 env) (interpret vc_7 env) (interpret vc_8 env) 
		 (interpret prec_i env))
	]
	[ (_mm512_mask_subs_epu16_dsl v0 v1 v2 v3 size_i_o lane_size num_6 prec_i_o num_8)
		(assert (equal? (get-length v0 env) (get-length v2 env)))
		(assert (equal? (get-length v0 env) (get-length v3 env)))
		(assert (equal? (get-length v2 env) (get-length v3 env)))
		(assert (equal? size_i_o (get-length v0 env)))
		(assert (equal? size_i_o (get-length v2 env)))
		(assert (equal? size_i_o (get-length v3 env)))
		(_mm512_mask_subs_epu16 (interpret v0 env) (interpret v1 env) (interpret v2 env) 
		 (interpret v3 env) (interpret size_i_o env) (interpret lane_size env) 
		 (interpret num_6 env) (interpret prec_i_o env) (interpret num_8 env))
	]
	[ (_mm_cmplt_epi32_dsl v0 v1 size_i_o lane_size num_4 prec_i_o num_6 vc_7 vc_8)
		(assert (equal? (get-length v0 env) (get-length v1 env)))
		(assert (equal? size_i_o (get-length v0 env)))
		(assert (equal? size_i_o (get-length v1 env)))
		(_mm_cmplt_epi32 (interpret v0 env) (interpret v1 env) (interpret size_i_o env) 
		 (interpret lane_size env) (interpret num_4 env) (interpret prec_i_o env) 
		 (interpret num_6 env) (interpret vc_7 env) (interpret vc_8 env))
	]
	[ (_mm256_maskz_set1_epi8_dsl vc_0 v1 v2 size_i_o lane_size num_5 prec_i_o num_7 num_8)
		(_mm256_maskz_set1_epi8 (interpret vc_0 env) (interpret v1 env) (interpret v2 env) 
		 (interpret size_i_o env) (interpret lane_size env) (interpret num_5 env) 
		 (interpret prec_i_o env) (interpret num_7 env) (interpret num_8 env))
	]
	[ (_mm_adds_pu16_dsl v0 v1 size_i_o lane_size num_4 prec_i_o num_6)
		(assert (equal? (get-length v0 env) (get-length v1 env)))
		(assert (equal? size_i_o (get-length v0 env)))
		(assert (equal? size_i_o (get-length v1 env)))
		(_mm_adds_pu16 (interpret v0 env) (interpret v1 env) (interpret size_i_o env) 
		 (interpret lane_size env) (interpret num_4 env) (interpret prec_i_o env) 
		 (interpret num_6 env))
	]
	[ (_mm256_mask_cmpeq_epi32_mask_dsl vc_0 v1 v2 v3 size_i_o lane_size num_6 prec_o num_8 vc_9 vc_10 prec_i)
		(assert (equal? (get-length v2 env) (get-length v3 env)))
		(assert (equal? size_i_o (get-length v1 env)))
		(_mm256_mask_cmpeq_epi32_mask (interpret vc_0 env) (interpret v1 env) (interpret v2 env) 
		 (interpret v3 env) (interpret size_i_o env) (interpret lane_size env) 
		 (interpret num_6 env) (interpret prec_o env) (interpret num_8 env) 
		 (interpret vc_9 env) (interpret vc_10 env) (interpret prec_i env))
	]
	[ (_mm_maskz_add_epi16_dsl vc_0 v1 v2 v3 size_i_o lane_size num_6 prec_i_o num_8)
		(assert (equal? (get-length v2 env) (get-length v3 env)))
		(assert (equal? size_i_o (get-length v2 env)))
		(assert (equal? size_i_o (get-length v3 env)))
		(_mm_maskz_add_epi16 (interpret vc_0 env) (interpret v1 env) (interpret v2 env) 
		 (interpret v3 env) (interpret size_i_o env) (interpret lane_size env) 
		 (interpret num_6 env) (interpret prec_i_o env) (interpret num_8 env))
	]
	[ (_mm256_maskz_mulhi_epi16_dsl vc_0 v1 v2 v3 size_i_o lane_size num_6 prec_i_o num_8 num_9 num_10)
		(assert (equal? (get-length v2 env) (get-length v3 env)))
		(assert (equal? size_i_o (get-length v2 env)))
		(assert (equal? size_i_o (get-length v3 env)))
		(_mm256_maskz_mulhi_epi16 (interpret vc_0 env) (interpret v1 env) (interpret v2 env) 
		 (interpret v3 env) (interpret size_i_o env) (interpret lane_size env) 
		 (interpret num_6 env) (interpret prec_i_o env) (interpret num_8 env) 
		 (interpret num_9 env) (interpret num_10 env))
	]
	[ (_m_pmaxub_dsl v0 v1 size_i_o lane_size num_4 prec_i_o num_6)
		(assert (equal? (get-length v0 env) (get-length v1 env)))
		(assert (equal? size_i_o (get-length v0 env)))
		(assert (equal? size_i_o (get-length v1 env)))
		(_m_pmaxub (interpret v0 env) (interpret v1 env) (interpret size_i_o env) 
		 (interpret lane_size env) (interpret num_4 env) (interpret prec_i_o env) 
		 (interpret num_6 env))
	]
	[ (_mm512_broadcast_i64x2_dsl v0 size_i_o lane_size num_3 prec_i_o num_5 num_6)
		(_mm512_broadcast_i64x2 (interpret v0 env) (interpret size_i_o env) (interpret lane_size env) 
		 (interpret num_3 env) (interpret prec_i_o env) (interpret num_5 env) 
		 (interpret num_6 env))
	]
	[ (_mm512_cmple_epi32_mask_dsl v0 v1 size_i_o lane_size num_4 prec_o num_6 vc_7 vc_8 prec_i)
		(assert (equal? (get-length v0 env) (get-length v1 env)))
		(_mm512_cmple_epi32_mask (interpret v0 env) (interpret v1 env) (interpret size_i_o env) 
		 (interpret lane_size env) (interpret num_4 env) (interpret prec_o env) 
		 (interpret num_6 env) (interpret vc_7 env) (interpret vc_8 env) 
		 (interpret prec_i env))
	]
	[ (_mm256_maskz_max_epu16_dsl vc_0 v1 v2 v3 size_i_o lane_size num_6 prec_i_o num_8)
		(assert (equal? (get-length v2 env) (get-length v3 env)))
		(assert (equal? size_i_o (get-length v2 env)))
		(assert (equal? size_i_o (get-length v3 env)))
		(_mm256_maskz_max_epu16 (interpret vc_0 env) (interpret v1 env) (interpret v2 env) 
		 (interpret v3 env) (interpret size_i_o env) (interpret lane_size env) 
		 (interpret num_6 env) (interpret prec_i_o env) (interpret num_8 env))
	]
	[ (_mm512_maskz_madd52lo_epu64_dsl vc_0 v1 v2 v3 v4 size_i_o lane_size num_7 num_8 num_9 prec_i_o num_11 num_12 num_13)
		(assert (equal? (get-length v2 env) (get-length v3 env)))
		(assert (equal? (get-length v2 env) (get-length v4 env)))
		(assert (equal? (get-length v3 env) (get-length v4 env)))
		(assert (equal? size_i_o (get-length v2 env)))
		(assert (equal? size_i_o (get-length v3 env)))
		(assert (equal? size_i_o (get-length v4 env)))
		(_mm512_maskz_madd52lo_epu64 (interpret vc_0 env) (interpret v1 env) (interpret v2 env) 
		 (interpret v3 env) (interpret v4 env) (interpret size_i_o env) 
		 (interpret lane_size env) (interpret num_7 env) (interpret num_8 env) 
		 (interpret num_9 env) (interpret prec_i_o env) (interpret num_11 env) 
		 (interpret num_12 env) (interpret num_13 env))
	]
	[ (_mm_mask_dpbusd_epi32_dsl v0 v1 v2 v3 size_i_o lane_size num_6 num_7 num_8 num_9 num_10 num_11 num_12)
		(assert (equal? (get-length v0 env) (get-length v2 env)))
		(assert (equal? (get-length v0 env) (get-length v3 env)))
		(assert (equal? (get-length v2 env) (get-length v3 env)))
		(assert (equal? size_i_o (get-length v0 env)))
		(assert (equal? size_i_o (get-length v2 env)))
		(assert (equal? size_i_o (get-length v3 env)))
		(_mm_mask_dpbusd_epi32 (interpret v0 env) (interpret v1 env) (interpret v2 env) 
		 (interpret v3 env) (interpret size_i_o env) (interpret lane_size env) 
		 (interpret num_6 env) (interpret num_7 env) (interpret num_8 env) 
		 (interpret num_9 env) (interpret num_10 env) (interpret num_11 env) 
		 (interpret num_12 env))
	]
	[ (_mm256_broadcastq_epi64_dsl v0 size_o lane_size num_3 prec_i_o num_5 num_6)
		(_mm256_broadcastq_epi64 (interpret v0 env) (interpret size_o env) (interpret lane_size env) 
		 (interpret num_3 env) (interpret prec_i_o env) (interpret num_5 env) 
		 (interpret num_6 env))
	]
	[ (_mm_movepi16_mask_dsl v0 size_o lane_size num_3 prec_o num_5 num_6 vc_7 vc_8)
		(_mm_movepi16_mask (interpret v0 env) (interpret size_o env) (interpret lane_size env) 
		 (interpret num_3 env) (interpret prec_o env) (interpret num_5 env) 
		 (interpret num_6 env) (interpret vc_7 env) (interpret vc_8 env))
	]
	[ (_mm256_mask_test_epi16_mask_dsl vc_0 v1 v2 v3 size_i_o lane_size num_6 prec_o num_8 vc_9 vc_10 vc_11 prec_i)
		(assert (equal? (get-length v2 env) (get-length v3 env)))
		(assert (equal? size_i_o (get-length v1 env)))
		(_mm256_mask_test_epi16_mask (interpret vc_0 env) (interpret v1 env) (interpret v2 env) 
		 (interpret v3 env) (interpret size_i_o env) (interpret lane_size env) 
		 (interpret num_6 env) (interpret prec_o env) (interpret num_8 env) 
		 (interpret vc_9 env) (interpret vc_10 env) (interpret vc_11 env) 
		 (interpret prec_i env))
	]
	[ (_mm256_mask_max_epi8_dsl v0 v1 v2 v3 size_i_o lane_size num_6 prec_i_o num_8)
		(assert (equal? (get-length v0 env) (get-length v2 env)))
		(assert (equal? (get-length v0 env) (get-length v3 env)))
		(assert (equal? (get-length v2 env) (get-length v3 env)))
		(assert (equal? size_i_o (get-length v0 env)))
		(assert (equal? size_i_o (get-length v2 env)))
		(assert (equal? size_i_o (get-length v3 env)))
		(_mm256_mask_max_epi8 (interpret v0 env) (interpret v1 env) (interpret v2 env) 
		 (interpret v3 env) (interpret size_i_o env) (interpret lane_size env) 
		 (interpret num_6 env) (interpret prec_i_o env) (interpret num_8 env))
	]
	[ (_mm_madd_epi16_dsl v0 v1 size_i_o lane_size num_4 prec_i num_6 prec_o num_8)
		(assert (equal? (get-length v0 env) (get-length v1 env)))
		(assert (equal? size_i_o (get-length v0 env)))
		(assert (equal? size_i_o (get-length v1 env)))
		(_mm_madd_epi16 (interpret v0 env) (interpret v1 env) (interpret size_i_o env) 
		 (interpret lane_size env) (interpret num_4 env) (interpret prec_i env) 
		 (interpret num_6 env) (interpret prec_o env) (interpret num_8 env))
	]
	[ (_mm512_mask_subr_epi32_dsl v0 v1 v2 v3 size_i_o lane_size num_6 prec_i_o num_8)
		(assert (equal? (get-length v0 env) (get-length v2 env)))
		(assert (equal? (get-length v0 env) (get-length v3 env)))
		(assert (equal? (get-length v2 env) (get-length v3 env)))
		(assert (equal? size_i_o (get-length v0 env)))
		(assert (equal? size_i_o (get-length v2 env)))
		(assert (equal? size_i_o (get-length v3 env)))
		(_mm512_mask_subr_epi32 (interpret v0 env) (interpret v1 env) (interpret v2 env) 
		 (interpret v3 env) (interpret size_i_o env) (interpret lane_size env) 
		 (interpret num_6 env) (interpret prec_i_o env) (interpret num_8 env))
	]
	[ (_mm_div_epi8_dsl v0 v1 size_i_o lane_size num_4 prec_i_o num_6 num_7 num_8)
		(assert (equal? (get-length v0 env) (get-length v1 env)))
		(assert (equal? size_i_o (get-length v0 env)))
		(assert (equal? size_i_o (get-length v1 env)))
		(_mm_div_epi8 (interpret v0 env) (interpret v1 env) (interpret size_i_o env) 
		 (interpret lane_size env) (interpret num_4 env) (interpret prec_i_o env) 
		 (interpret num_6 env) (interpret num_7 env) (interpret num_8 env))
	]
	[ (_mm256_idiv_epi32_dsl v0 v1 size_i_o lane_size num_4 prec_i_o num_6 num_7 num_8)
		(assert (equal? (get-length v0 env) (get-length v1 env)))
		(assert (equal? size_i_o (get-length v0 env)))
		(assert (equal? size_i_o (get-length v1 env)))
		(_mm256_idiv_epi32 (interpret v0 env) (interpret v1 env) (interpret size_i_o env) 
		 (interpret lane_size env) (interpret num_4 env) (interpret prec_i_o env) 
		 (interpret num_6 env) (interpret num_7 env) (interpret num_8 env))
	]
	[v v]
 )
)
;; ================================================================================
