# ============================== Hydride File =================================
#
# Part of the Hydride Compiler Infrastructure.
# <Placeholder for license information>
#
# =============================================================================
#
# Do NOT modify this file. It is automatically generated.
#
# =============================================================================


semantcs = {
    #           "_mm256_max_epu64" : {
    #         "target_instructions" : {
    #           "_mm256_max_epu64" : {
    #               "args" : ["SYMBOLIC_BV_256","SYMBOLIC_BV_256","256","256","0","256","64","0","0"],
    #               "in_vectsize" : 256,
    #               "out_vectsize" : 256,
    #               "lanesize" : 256,
    #               "in_precision" : 64,
    #               "out_precision" : 64,
    #               "in_vectsize_index" : 2,
    #               "out_vectsize_index" : 2,
    #               "in_lanesize_index" : 5,
    #               "out_lanesize_index" : 3,
    #               "in_precision_index" : 6,
    #               "out_precision_index" : 6,
    #               "arg_permute_map" : [0,1,-1,-1,-1,-1,-1,-1,-1],
    #               "Signedness" : 0,
    #               "Cost" : "[{'Icelake': {'l': '3', 't': '1'}}, {'Skylake': {'l': '3', 't': '1'}}]",
    #               "SIMD" : "True",
    #               "Extensions" : "['avx512vl', 'avx512f']",
    #   },

    #           "_mm512_max_epu64" : {
    #               "args" : ["SYMBOLIC_BV_512","SYMBOLIC_BV_512","512","512","0","512","64","0","0"],
    #               "in_vectsize" : 512,
    #               "out_vectsize" : 512,
    #               "lanesize" : 512,
    #               "in_precision" : 64,
    #               "out_precision" : 64,
    #               "in_vectsize_index" : 2,
    #               "out_vectsize_index" : 2,
    #               "in_lanesize_index" : 5,
    #               "out_lanesize_index" : 3,
    #               "in_precision_index" : 6,
    #               "out_precision_index" : 6,
    #               "arg_permute_map" : [0,1,-1,-1,-1,-1,-1,-1,-1],
    #               "Signedness" : 0,
    #               "Cost" : "[{'Icelake': {'l': '3', 't': '1'}}, {'Skylake': {'l': '3', 't': '1'}}]",
    #               "SIMD" : "True",
    #               "Extensions" : "['avx512f']",
    #   },

    #           "_mm_max_epi64" : {
    #               "args" : ["SYMBOLIC_BV_128","SYMBOLIC_BV_128","128","128","0","128","64","1","0"],
    #               "in_vectsize" : 128,
    #               "out_vectsize" : 128,
    #               "lanesize" : 128,
    #               "in_precision" : 64,
    #               "out_precision" : 64,
    #               "in_vectsize_index" : 2,
    #               "out_vectsize_index" : 2,
    #               "in_lanesize_index" : 5,
    #               "out_lanesize_index" : 3,
    #               "in_precision_index" : 6,
    #               "out_precision_index" : 6,
    #               "arg_permute_map" : [0,1,-1,-1,-1,-1,-1,-1,-1],
    #               "Signedness" : 1,
    #               "Cost" : "[{'Icelake': {'l': '3', 't': '1'}}, {'Skylake': {'l': '3', 't': '1'}}]",
    #               "SIMD" : "True",
    #               "Extensions" : "['avx512vl', 'avx512f']",
    #   },

    #           "_mm_max_epu8" : {
    #               "args" : ["SYMBOLIC_BV_128","SYMBOLIC_BV_128","128","128","0","128","8","0","0"],
    #               "in_vectsize" : 128,
    #               "out_vectsize" : 128,
    #               "lanesize" : 128,
    #               "in_precision" : 8,
    #               "out_precision" : 8,
    #               "in_vectsize_index" : 2,
    #               "out_vectsize_index" : 2,
    #               "in_lanesize_index" : 5,
    #               "out_lanesize_index" : 3,
    #               "in_precision_index" : 6,
    #               "out_precision_index" : 6,
    #               "arg_permute_map" : [0,1,-1,-1,-1,-1,-1,-1,-1],
    #               "Signedness" : 0,
    #               "Cost" : "[{'Skylake': {'l': '1', 't': '0.5'}}]",
    #               "SIMD" : "True",
    #               "Extensions" : "['sse2']",
    #   },

    #           "_mm512_max_epi16" : {
    #               "args" : ["SYMBOLIC_BV_512","SYMBOLIC_BV_512","512","512","0","512","16","1","0"],
    #               "in_vectsize" : 512,
    #               "out_vectsize" : 512,
    #               "lanesize" : 512,
    #               "in_precision" : 16,
    #               "out_precision" : 16,
    #               "in_vectsize_index" : 2,
    #               "out_vectsize_index" : 2,
    #               "in_lanesize_index" : 5,
    #               "out_lanesize_index" : 3,
    #               "in_precision_index" : 6,
    #               "out_precision_index" : 6,
    #               "arg_permute_map" : [0,1,-1,-1,-1,-1,-1,-1,-1],
    #               "Signedness" : 1,
    #               "Cost" : "[{'Icelake': {'l': '', 't': '1'}}, {'Skylake': {'l': '1', 't': '1'}}]",
    #               "SIMD" : "True",
    #               "Extensions" : "['avx512bw']",
    #   },

    #           "_mm256_max_epu32" : {
    #               "args" : ["SYMBOLIC_BV_256","SYMBOLIC_BV_256","256","256","0","256","32","0","0"],
    #               "in_vectsize" : 256,
    #               "out_vectsize" : 256,
    #               "lanesize" : 256,
    #               "in_precision" : 32,
    #               "out_precision" : 32,
    #               "in_vectsize_index" : 2,
    #               "out_vectsize_index" : 2,
    #               "in_lanesize_index" : 5,
    #               "out_lanesize_index" : 3,
    #               "in_precision_index" : 6,
    #               "out_precision_index" : 6,
    #               "arg_permute_map" : [0,1,-1,-1,-1,-1,-1,-1,-1],
    #               "Signedness" : 0,
    #               "Cost" : "[{'Icelake': {'l': '1', 't': '0.5'}}, {'Skylake': {'l': '1', 't': '0.5'}}]",
    #               "SIMD" : "True",
    #               "Extensions" : "['avx2']",
    #   },

    #           "_mm256_max_epu8" : {
    #               "args" : ["SYMBOLIC_BV_256","SYMBOLIC_BV_256","256","256","0","256","8","0","0"],
    #               "in_vectsize" : 256,
    #               "out_vectsize" : 256,
    #               "lanesize" : 256,
    #               "in_precision" : 8,
    #               "out_precision" : 8,
    #               "in_vectsize_index" : 2,
    #               "out_vectsize_index" : 2,
    #               "in_lanesize_index" : 5,
    #               "out_lanesize_index" : 3,
    #               "in_precision_index" : 6,
    #               "out_precision_index" : 6,
    #               "arg_permute_map" : [0,1,-1,-1,-1,-1,-1,-1,-1],
    #               "Signedness" : 0,
    #               "Cost" : "[{'Icelake': {'l': '1', 't': '0.5'}}, {'Skylake': {'l': '1', 't': '0.5'}}]",
    #               "SIMD" : "True",
    #               "Extensions" : "['avx2']",
    #   },

    #           "_mm256_max_epi64" : {
    #               "args" : ["SYMBOLIC_BV_256","SYMBOLIC_BV_256","256","256","0","256","64","1","0"],
    #               "in_vectsize" : 256,
    #               "out_vectsize" : 256,
    #               "lanesize" : 256,
    #               "in_precision" : 64,
    #               "out_precision" : 64,
    #               "in_vectsize_index" : 2,
    #               "out_vectsize_index" : 2,
    #               "in_lanesize_index" : 5,
    #               "out_lanesize_index" : 3,
    #               "in_precision_index" : 6,
    #               "out_precision_index" : 6,
    #               "arg_permute_map" : [0,1,-1,-1,-1,-1,-1,-1,-1],
    #               "Signedness" : 1,
    #               "Cost" : "[{'Icelake': {'l': '3', 't': '1'}}, {'Skylake': {'l': '3', 't': '1'}}]",
    #               "SIMD" : "True",
    #               "Extensions" : "['avx512vl', 'avx512f']",
    #   },

    #           "_mm_max_epi16" : {
    #               "args" : ["SYMBOLIC_BV_128","SYMBOLIC_BV_128","128","128","0","128","16","1","0"],
    #               "in_vectsize" : 128,
    #               "out_vectsize" : 128,
    #               "lanesize" : 128,
    #               "in_precision" : 16,
    #               "out_precision" : 16,
    #               "in_vectsize_index" : 2,
    #               "out_vectsize_index" : 2,
    #               "in_lanesize_index" : 5,
    #               "out_lanesize_index" : 3,
    #               "in_precision_index" : 6,
    #               "out_precision_index" : 6,
    #               "arg_permute_map" : [0,1,-1,-1,-1,-1,-1,-1,-1],
    #               "Signedness" : 1,
    #               "Cost" : "[{'Skylake': {'l': '1', 't': '0.5'}}]",
    #               "SIMD" : "True",
    #               "Extensions" : "['sse2']",
    #   },

    #           "_m_pmaxsw" : {
    #               "args" : ["SYMBOLIC_BV_64","SYMBOLIC_BV_64","64","64","0","64","16","1","0"],
    #               "in_vectsize" : 64,
    #               "out_vectsize" : 64,
    #               "lanesize" : 64,
    #               "in_precision" : 16,
    #               "out_precision" : 16,
    #               "in_vectsize_index" : 2,
    #               "out_vectsize_index" : 2,
    #               "in_lanesize_index" : 5,
    #               "out_lanesize_index" : 3,
    #               "in_precision_index" : 6,
    #               "out_precision_index" : 6,
    #               "arg_permute_map" : [0,1,-1,-1,-1,-1,-1,-1,-1],
    #               "Signedness" : 1,
    #               "Cost" : "[{'Icelake': {'l': '1', 't': '1'}}, {'Skylake': {'l': '1', 't': '1'}}]",
    #               "SIMD" : "True",
    #               "Extensions" : "['sse']",
    #   },

    #           "_mm_max_pu8" : {
    #               "args" : ["SYMBOLIC_BV_64","SYMBOLIC_BV_64","64","64","0","64","8","0","0"],
    #               "in_vectsize" : 64,
    #               "out_vectsize" : 64,
    #               "lanesize" : 64,
    #               "in_precision" : 8,
    #               "out_precision" : 8,
    #               "in_vectsize_index" : 2,
    #               "out_vectsize_index" : 2,
    #               "in_lanesize_index" : 5,
    #               "out_lanesize_index" : 3,
    #               "in_precision_index" : 6,
    #               "out_precision_index" : 6,
    #               "arg_permute_map" : [0,1,-1,-1,-1,-1,-1,-1,-1],
    #               "Signedness" : 0,
    #               "Cost" : "[{'Icelake': {'l': '1', 't': '1'}}, {'Skylake': {'l': '1', 't': '1'}}]",
    #               "SIMD" : "True",
    #               "Extensions" : "['sse']",
    #   },

    #           "_mm_max_epi32" : {
    #               "args" : ["SYMBOLIC_BV_128","SYMBOLIC_BV_128","128","128","0","128","32","1","0"],
    #               "in_vectsize" : 128,
    #               "out_vectsize" : 128,
    #               "lanesize" : 128,
    #               "in_precision" : 32,
    #               "out_precision" : 32,
    #               "in_vectsize_index" : 2,
    #               "out_vectsize_index" : 2,
    #               "in_lanesize_index" : 5,
    #               "out_lanesize_index" : 3,
    #               "in_precision_index" : 6,
    #               "out_precision_index" : 6,
    #               "arg_permute_map" : [0,1,-1,-1,-1,-1,-1,-1,-1],
    #               "Signedness" : 1,
    #               "Cost" : "[{'Skylake': {'l': '1', 't': '0.5'}}]",
    #               "SIMD" : "True",
    #               "Extensions" : "['sse4.1']",
    #   },

    #           "_mm256_max_epu16" : {
    #               "args" : ["SYMBOLIC_BV_256","SYMBOLIC_BV_256","256","256","0","256","16","0","0"],
    #               "in_vectsize" : 256,
    #               "out_vectsize" : 256,
    #               "lanesize" : 256,
    #               "in_precision" : 16,
    #               "out_precision" : 16,
    #               "in_vectsize_index" : 2,
    #               "out_vectsize_index" : 2,
    #               "in_lanesize_index" : 5,
    #               "out_lanesize_index" : 3,
    #               "in_precision_index" : 6,
    #               "out_precision_index" : 6,
    #               "arg_permute_map" : [0,1,-1,-1,-1,-1,-1,-1,-1],
    #               "Signedness" : 0,
    #               "Cost" : "[{'Icelake': {'l': '1', 't': '0.5'}}, {'Skylake': {'l': '1', 't': '0.5'}}]",
    #               "SIMD" : "True",
    #               "Extensions" : "['avx2']",
    #   },

    #           "_mm_max_epu32" : {
    #               "args" : ["SYMBOLIC_BV_128","SYMBOLIC_BV_128","128","128","0","128","32","0","0"],
    #               "in_vectsize" : 128,
    #               "out_vectsize" : 128,
    #               "lanesize" : 128,
    #               "in_precision" : 32,
    #               "out_precision" : 32,
    #               "in_vectsize_index" : 2,
    #               "out_vectsize_index" : 2,
    #               "in_lanesize_index" : 5,
    #               "out_lanesize_index" : 3,
    #               "in_precision_index" : 6,
    #               "out_precision_index" : 6,
    #               "arg_permute_map" : [0,1,-1,-1,-1,-1,-1,-1,-1],
    #               "Signedness" : 0,
    #               "Cost" : "[{'Skylake': {'l': '1', 't': '0.5'}}]",
    #               "SIMD" : "True",
    #               "Extensions" : "['sse4.1']",
    #   },

    #           "_mm512_max_epi64" : {
    #               "args" : ["SYMBOLIC_BV_512","SYMBOLIC_BV_512","512","512","0","512","64","1","0"],
    #               "in_vectsize" : 512,
    #               "out_vectsize" : 512,
    #               "lanesize" : 512,
    #               "in_precision" : 64,
    #               "out_precision" : 64,
    #               "in_vectsize_index" : 2,
    #               "out_vectsize_index" : 2,
    #               "in_lanesize_index" : 5,
    #               "out_lanesize_index" : 3,
    #               "in_precision_index" : 6,
    #               "out_precision_index" : 6,
    #               "arg_permute_map" : [0,1,-1,-1,-1,-1,-1,-1,-1],
    #               "Signedness" : 1,
    #               "Cost" : "[{'Icelake': {'l': '3', 't': '1'}}, {'Skylake': {'l': '3', 't': '1'}}]",
    #               "SIMD" : "True",
    #               "Extensions" : "['avx512f']",
    #   },

    #           "_mm256_max_epi32" : {
    #               "args" : ["SYMBOLIC_BV_256","SYMBOLIC_BV_256","256","256","0","256","32","1","0"],
    #               "in_vectsize" : 256,
    #               "out_vectsize" : 256,
    #               "lanesize" : 256,
    #               "in_precision" : 32,
    #               "out_precision" : 32,
    #               "in_vectsize_index" : 2,
    #               "out_vectsize_index" : 2,
    #               "in_lanesize_index" : 5,
    #               "out_lanesize_index" : 3,
    #               "in_precision_index" : 6,
    #               "out_precision_index" : 6,
    #               "arg_permute_map" : [0,1,-1,-1,-1,-1,-1,-1,-1],
    #               "Signedness" : 1,
    #               "Cost" : "[{'Icelake': {'l': '1', 't': '0.5'}}, {'Skylake': {'l': '1', 't': '0.5'}}]",
    #               "SIMD" : "True",
    #               "Extensions" : "['avx2']",
    #   },

    #           "_mm512_max_epi8" : {
    #               "args" : ["SYMBOLIC_BV_512","SYMBOLIC_BV_512","512","512","0","512","8","1","0"],
    #               "in_vectsize" : 512,
    #               "out_vectsize" : 512,
    #               "lanesize" : 512,
    #               "in_precision" : 8,
    #               "out_precision" : 8,
    #               "in_vectsize_index" : 2,
    #               "out_vectsize_index" : 2,
    #               "in_lanesize_index" : 5,
    #               "out_lanesize_index" : 3,
    #               "in_precision_index" : 6,
    #               "out_precision_index" : 6,
    #               "arg_permute_map" : [0,1,-1,-1,-1,-1,-1,-1,-1],
    #               "Signedness" : 1,
    #               "Cost" : "[{'Icelake': {'l': '', 't': '1'}}, {'Skylake': {'l': '1', 't': '1'}}]",
    #               "SIMD" : "True",
    #               "Extensions" : "['avx512bw']",
    #   },

    #           "_mm_max_epi8" : {
    #               "args" : ["SYMBOLIC_BV_128","SYMBOLIC_BV_128","128","128","0","128","8","1","0"],
    #               "in_vectsize" : 128,
    #               "out_vectsize" : 128,
    #               "lanesize" : 128,
    #               "in_precision" : 8,
    #               "out_precision" : 8,
    #               "in_vectsize_index" : 2,
    #               "out_vectsize_index" : 2,
    #               "in_lanesize_index" : 5,
    #               "out_lanesize_index" : 3,
    #               "in_precision_index" : 6,
    #               "out_precision_index" : 6,
    #               "arg_permute_map" : [0,1,-1,-1,-1,-1,-1,-1,-1],
    #               "Signedness" : 1,
    #               "Cost" : "[{'Skylake': {'l': '1', 't': '0.5'}}]",
    #               "SIMD" : "True",
    #               "Extensions" : "['sse4.1']",
    #   },

    #           "_mm256_max_epi8" : {
    #               "args" : ["SYMBOLIC_BV_256","SYMBOLIC_BV_256","256","256","0","256","8","1","0"],
    #               "in_vectsize" : 256,
    #               "out_vectsize" : 256,
    #               "lanesize" : 256,
    #               "in_precision" : 8,
    #               "out_precision" : 8,
    #               "in_vectsize_index" : 2,
    #               "out_vectsize_index" : 2,
    #               "in_lanesize_index" : 5,
    #               "out_lanesize_index" : 3,
    #               "in_precision_index" : 6,
    #               "out_precision_index" : 6,
    #               "arg_permute_map" : [0,1,-1,-1,-1,-1,-1,-1,-1],
    #               "Signedness" : 1,
    #               "Cost" : "[{'Icelake': {'l': '1', 't': '0.5'}}, {'Skylake': {'l': '1', 't': '0.5'}}]",
    #               "SIMD" : "True",
    #               "Extensions" : "['avx2']",
    #   },

    #           "_mm_max_epu64" : {
    #               "args" : ["SYMBOLIC_BV_128","SYMBOLIC_BV_128","128","128","0","128","64","0","0"],
    #               "in_vectsize" : 128,
    #               "out_vectsize" : 128,
    #               "lanesize" : 128,
    #               "in_precision" : 64,
    #               "out_precision" : 64,
    #               "in_vectsize_index" : 2,
    #               "out_vectsize_index" : 2,
    #               "in_lanesize_index" : 5,
    #               "out_lanesize_index" : 3,
    #               "in_precision_index" : 6,
    #               "out_precision_index" : 6,
    #               "arg_permute_map" : [0,1,-1,-1,-1,-1,-1,-1,-1],
    #               "Signedness" : 0,
    #               "Cost" : "[{'Icelake': {'l': '3', 't': '1'}}, {'Skylake': {'l': '3', 't': '1'}}]",
    #               "SIMD" : "True",
    #               "Extensions" : "['avx512vl', 'avx512f']",
    #   },

    #           "_mm_max_epu16" : {
    #               "args" : ["SYMBOLIC_BV_128","SYMBOLIC_BV_128","128","128","0","128","16","0","0"],
    #               "in_vectsize" : 128,
    #               "out_vectsize" : 128,
    #               "lanesize" : 128,
    #               "in_precision" : 16,
    #               "out_precision" : 16,
    #               "in_vectsize_index" : 2,
    #               "out_vectsize_index" : 2,
    #               "in_lanesize_index" : 5,
    #               "out_lanesize_index" : 3,
    #               "in_precision_index" : 6,
    #               "out_precision_index" : 6,
    #               "arg_permute_map" : [0,1,-1,-1,-1,-1,-1,-1,-1],
    #               "Signedness" : 0,
    #               "Cost" : "[{'Skylake': {'l': '1', 't': '0.5'}}]",
    #               "SIMD" : "True",
    #               "Extensions" : "['sse4.1']",
    #   },

    #           "_mm512_max_epi32" : {
    #               "args" : ["SYMBOLIC_BV_512","SYMBOLIC_BV_512","512","512","0","512","32","1","0"],
    #               "in_vectsize" : 512,
    #               "out_vectsize" : 512,
    #               "lanesize" : 512,
    #               "in_precision" : 32,
    #               "out_precision" : 32,
    #               "in_vectsize_index" : 2,
    #               "out_vectsize_index" : 2,
    #               "in_lanesize_index" : 5,
    #               "out_lanesize_index" : 3,
    #               "in_precision_index" : 6,
    #               "out_precision_index" : 6,
    #               "arg_permute_map" : [0,1,-1,-1,-1,-1,-1,-1,-1],
    #               "Signedness" : 1,
    #               "Cost" : "[{'Icelake': {'l': '1', 't': '1'}}, {'Skylake': {'l': '1', 't': '1'}}]",
    #               "SIMD" : "True",
    #               "Extensions" : "['avx512f']",
    #   },

    #           "_mm_max_pi16" : {
    #               "args" : ["SYMBOLIC_BV_64","SYMBOLIC_BV_64","64","64","0","64","16","1","0"],
    #               "in_vectsize" : 64,
    #               "out_vectsize" : 64,
    #               "lanesize" : 64,
    #               "in_precision" : 16,
    #               "out_precision" : 16,
    #               "in_vectsize_index" : 2,
    #               "out_vectsize_index" : 2,
    #               "in_lanesize_index" : 5,
    #               "out_lanesize_index" : 3,
    #               "in_precision_index" : 6,
    #               "out_precision_index" : 6,
    #               "arg_permute_map" : [0,1,-1,-1,-1,-1,-1,-1,-1],
    #               "Signedness" : 1,
    #               "Cost" : "[{'Icelake': {'l': '1', 't': '1'}}, {'Skylake': {'l': '1', 't': '1'}}]",
    #               "SIMD" : "True",
    #               "Extensions" : "['sse']",
    #   },

    #           "_mm512_max_epu32" : {
    #               "args" : ["SYMBOLIC_BV_512","SYMBOLIC_BV_512","512","512","0","512","32","0","0"],
    #               "in_vectsize" : 512,
    #               "out_vectsize" : 512,
    #               "lanesize" : 512,
    #               "in_precision" : 32,
    #               "out_precision" : 32,
    #               "in_vectsize_index" : 2,
    #               "out_vectsize_index" : 2,
    #               "in_lanesize_index" : 5,
    #               "out_lanesize_index" : 3,
    #               "in_precision_index" : 6,
    #               "out_precision_index" : 6,
    #               "arg_permute_map" : [0,1,-1,-1,-1,-1,-1,-1,-1],
    #               "Signedness" : 0,
    #               "Cost" : "[{'Icelake': {'l': '1', 't': '1'}}, {'Skylake': {'l': '1', 't': '1'}}]",
    #               "SIMD" : "True",
    #               "Extensions" : "['avx512f']",
    #   },

    #           "_m_pmaxub" : {
    #               "args" : ["SYMBOLIC_BV_64","SYMBOLIC_BV_64","64","64","0","64","8","0","0"],
    #               "in_vectsize" : 64,
    #               "out_vectsize" : 64,
    #               "lanesize" : 64,
    #               "in_precision" : 8,
    #               "out_precision" : 8,
    #               "in_vectsize_index" : 2,
    #               "out_vectsize_index" : 2,
    #               "in_lanesize_index" : 5,
    #               "out_lanesize_index" : 3,
    #               "in_precision_index" : 6,
    #               "out_precision_index" : 6,
    #               "arg_permute_map" : [0,1,-1,-1,-1,-1,-1,-1,-1],
    #               "Signedness" : 0,
    #               "Cost" : "[{'Icelake': {'l': '1', 't': '1'}}, {'Skylake': {'l': '1', 't': '1'}}]",
    #               "SIMD" : "True",
    #               "Extensions" : "['sse']",
    #   },

    #           "_mm256_max_epi16" : {
    #               "args" : ["SYMBOLIC_BV_256","SYMBOLIC_BV_256","256","256","0","256","16","1","0"],
    #               "in_vectsize" : 256,
    #               "out_vectsize" : 256,
    #               "lanesize" : 256,
    #               "in_precision" : 16,
    #               "out_precision" : 16,
    #               "in_vectsize_index" : 2,
    #               "out_vectsize_index" : 2,
    #               "in_lanesize_index" : 5,
    #               "out_lanesize_index" : 3,
    #               "in_precision_index" : 6,
    #               "out_precision_index" : 6,
    #               "arg_permute_map" : [0,1,-1,-1,-1,-1,-1,-1,-1],
    #               "Signedness" : 1,
    #               "Cost" : "[{'Icelake': {'l': '1', 't': '0.5'}}, {'Skylake': {'l': '1', 't': '0.5'}}]",
    #               "SIMD" : "True",
    #               "Extensions" : "['avx2']",
    #   },

    #           "_mm512_max_epu8" : {
    #               "args" : ["SYMBOLIC_BV_512","SYMBOLIC_BV_512","512","512","0","512","8","0","0"],
    #               "in_vectsize" : 512,
    #               "out_vectsize" : 512,
    #               "lanesize" : 512,
    #               "in_precision" : 8,
    #               "out_precision" : 8,
    #               "in_vectsize_index" : 2,
    #               "out_vectsize_index" : 2,
    #               "in_lanesize_index" : 5,
    #               "out_lanesize_index" : 3,
    #               "in_precision_index" : 6,
    #               "out_precision_index" : 6,
    #               "arg_permute_map" : [0,1,-1,-1,-1,-1,-1,-1,-1],
    #               "Signedness" : 0,
    #               "Cost" : "[{'Icelake': {'l': '', 't': '1'}}, {'Skylake': {'l': '1', 't': '1'}}]",
    #               "SIMD" : "True",
    #               "Extensions" : "['avx512bw']",
    #   },

    #           "_mm512_max_epu16" : {
    #               "args" : ["SYMBOLIC_BV_512","SYMBOLIC_BV_512","512","512","0","512","16","0","0"],
    #               "in_vectsize" : 512,
    #               "out_vectsize" : 512,
    #               "lanesize" : 512,
    #               "in_precision" : 16,
    #               "out_precision" : 16,
    #               "in_vectsize_index" : 2,
    #               "out_vectsize_index" : 2,
    #               "in_lanesize_index" : 5,
    #               "out_lanesize_index" : 3,
    #               "in_precision_index" : 6,
    #               "out_precision_index" : 6,
    #               "arg_permute_map" : [0,1,-1,-1,-1,-1,-1,-1,-1],
    #               "Signedness" : 0,
    #               "Cost" : "[{'Icelake': {'l': '', 't': '1'}}, {'Skylake': {'l': '1', 't': '1'}}]",
    #               "SIMD" : "True",
    #               "Extensions" : "['avx512bw']",
    #   },
    #     },
    #         "semantics" : ['"(define (_mm256_max_epu64  a b %vectsize0 %outerlanesize0 %innerlaneoffset0 %innerlanesize0 %elemsize0 %arg0 %arg1 )"', '"(define dst"', '"(apply"', '"concat"', '"(for/list ([%outer.it (reverse (range 0 %vectsize0 %outerlanesize0))])"', '" (apply"', '" concat"', '" (for/list ([j0.new (reverse (range %innerlaneoffset0 %innerlanesize0 %elemsize0))])"', '"  (define %lastidx0 (-  %elemsize0  1))"', '"  (define %1 (+  j0.new  %lastidx0))"', '"  (define %2 (extract  %1 j0.new a))"', '"  (define %4 (extract  %1 j0.new b))"', '"  (define %5.ab0 (bvmax %2 %4 %arg0 ))"', '"  %5.ab0"', '" )"', '" )"', '")"', '")"', '")"', '"(bvpadhighbits  dst %arg1)"', '")"', '""'],
    #   },

    "_tile_dpbssd": {
        "target_instructions": {
            "_tile_dpbssd": {
                "args": ["SYMBOLIC_BV_8192", "SYMBOLIC_BV_8192", "SYMBOLIC_BV_8192", "16", "64", "64"],
                "in_vectsize": 8192,
                "out_vectsize": 8192,
                "lanesize": 8192,
                "in_precision": 8,
                "out_precision": 32,
                "in_vectsize_index": [3,4,5],
                "out_vectsize_index": [3,4],
                "in_lanesize_index": 0,
                "out_lanesize_index": 0,
                "in_precision_index": 0,
                "out_precision_index": 0,
                "arg_permute_map": [0, 1, 2, 3, 4, 5],
                "Signedness": 1,
                "Cost": "[{'Sapphire Rapids': {'l': '1', 't': '8'}}]",
                "SIMD": "True",
                "Extensions": "['amx-int8']",
            },
        },
        "semantics": [
"            (define (_tile_dpbssd dst a b dst_rows dst_colsb a_colsb)",
"  (define (DPBD x y)",
"    (define %0 (* 8 0))",
"    (define %1 (+ %0 7))",
"    (define %2 (extract %1 %0 x))",
"    (define %3 (sign-extend %2 (bitvector 32)))",
"    (define %4 (* 8 0))",
"    (define %5 (+ %4 7))",
"    (define %6 (extract %5 %4 y))",
"    (define %7 (sign-extend %6 (bitvector 32)))",
"    (define %8 (bvmul %3 %7))",
"    (define %9 (* 8 1))",
"    (define %10 (+ %9 7))",
"    (define %11 (extract %10 %9 x))",
"    (define %12 (sign-extend %11 (bitvector 32)))",
"    (define %13 (* 8 1))",
"    (define %14 (+ %13 7))",
"    (define %15 (extract %14 %13 y))",
"    (define %16 (sign-extend %15 (bitvector 32)))",
"    (define %17 (bvmul %12 %16))",
"    (define %18 (* 8 2))",
"    (define %19 (+ %18 7))",
"    (define %20 (extract %19 %18 x))",
"    (define %21 (sign-extend %20 (bitvector 32)))",
"    (define %22 (* 8 2))",
"    (define %23 (+ %22 7))",
"    (define %24 (extract %23 %22 y))",
"    (define %25 (sign-extend %24 (bitvector 32)))",
"    (define %26 (bvmul %21 %25))",
"    (define %27 (* 8 3))",
"    (define %28 (+ %27 7))",
"    (define %29 (extract %28 %27 x))",
"    (define %30 (sign-extend %29 (bitvector 32)))",
"    (define %31 (* 8 3))",
"    (define %32 (+ %31 7))",
"    (define %33 (extract %32 %31 y))",
"    (define %34 (sign-extend %33 (bitvector 32)))",
"    (define %35 (bvmul %30 %34))",
"    (define %36 %8)",
"    (define %37 (bvadd %36 %17))",
"    (define %38 (bvadd %37 %26))",
"    (define %39 (bvadd %38 %35))",
"    %39)",
"  (define %0 (- dst_rows 1))",
"  (define %1 (+ %0 1))",
"  (define %2",
"    (apply concat",
"           (for/list ([m0 (reverse (range 0 %1 1))])",
"             (define row_bits (* 8 dst_colsb))",
"             (define %2 (extract (+ (* m0 row_bits) (- row_bits 1)) (* m0 row_bits) dst))",
"             (define %3 (/ dst_colsb 4))",
"             (define %4 (- %3 1))",
"             (define %5 (+ %4 1))",
"             (apply concat",
"                    (for/list ([n0 (reverse (range 0 %5 1))])",
"                      (define %6 (/ a_colsb 4))",
"                      (define %7 (- %6 1))",
"                      (define %8 (+ %7 1))",
"                      (define %9 (* 32 n0))",
"                      (define %10 (+ %9 31))",
"                      (define %11 (extract %10 %9 %2))",
"                      (bvadd %11",
"                             (apply bvadd",
"                                    (for/list ([k0 (reverse (range 0 %8 1))])",
"                                      (define %12 (* 32 k0))",
"                                      (define %13 (extract (+ (* m0 row_bits) (- row_bits 1)) (* m0 row_bits) ","a))",
"                                      (define %14 (+ %12 31))",
"                                      (define %15 (extract %14 %12 %13))",
"                                      (define %16 (* 32 n0))",
"                                      (define %17 (extract (+ (* k0 row_bits) (- row_bits 1)) (* k0 row_bits) ","b))",
"                                      (define %18 (+ %16 31))",
"                                      (define %19 (extract %18 %16 %17))",
"                                      (define %20 (DPBD %15 %19))",
"                                      %20)))))",
"             ;;;  (define %24 (* dst_colsb 8))",
"             ;;;  (define %25 (- row_bits %24))",
"             ;;;  (define %26 (bvpadlowbits %2 %25))",
"             ;;;  %26",
"             )))",
"  %2)",
        ]},
}
