# ============================== Hydride File =================================
# Part of the Hydride Compiler Infrastructure.
# ============================== Hydride File =================================
aie_sema = {
    "concat_v16int16": {
        "target_instructions": {
            "concat_v16int16": {
                "args": ["SYMBOLIC_BV_256", "SYMBOLIC_BV_256", "16", "32", "16", "16"],
                "in_vectsize": 256,
                "out_vectsize": 512,
                "lanesize": 256,
                "in_precision": 16,
                "out_precision": 32,
                "in_vectsize_index": 2,
                "out_vectsize_index": 3,
                "in_lanesize_index": 2,
                "out_lanesize_index": 3,
                "in_precision_index": 4,
                "out_precision_index": 5,
                "arg_permute_map": [0, 1, -1, -1, -1, -1],
                "Signedness": 1,
                "Cost": "None",
                "SIMD": "True",
                "Extensions": "[]",
            },
            "concat_v32int8": {
                "args": ["SYMBOLIC_BV_256", "SYMBOLIC_BV_256", "32", "64", "8", "8"],
                "in_vectsize": 256,
                "out_vectsize": 512,
                "lanesize": 256,
                "in_precision": 8,
                "out_precision": 8,
                "in_vectsize_index": 2,
                "out_vectsize_index": 3,
                "in_lanesize_index": 2,
                "out_lanesize_index": 3,
                "in_precision_index": 4,
                "out_precision_index": 5,
                "arg_permute_map": [0, 1, -1, -1, -1, -1],
                "Signedness": 1,
                "Cost": "None",
                "SIMD": "True",
                "Extensions": "[]",
            },
        },
        "semantics": [
            '"(define (concat_v16int16 vecA vecB %inlanesize %outlanesize %inprec %outprec)"',
            '"(concat vecA vecB)"',
            '")"',
        ],
    },
    "ups_to_v16acc32": {
        "target_instructions": {
            "ups_to_v16acc32": {
                "args": ["SYMBOLIC_BV_256"],
                "in_vectsize": 256,
                "out_vectsize": 512,
                "lanesize": 256,
                "in_precision": 16,
                "out_precision": 32,
                "in_vectsize_index": None,
                "out_vectsize_index": None,
                "in_lanesize_index": None,
                "out_lanesize_index": None,
                "in_precision_index": None,
                "out_precision_index": None,
                "arg_permute_map": [0],
                "Signedness": 1,
                "Cost": "None",
                "SIMD": "True",
                "Extensions": "[]",
            },
        },
        "semantics": [
            '"(define (ups_to_v16acc32 vec)"',
            '"(define dst"',
            '"(apply concat"',
            '"(for/list ([%i (reverse (range 0 16 1))])"',
            '"(define %low1 (* 16 %i))"',
            '"(define %high1 (+ %low1 (- 16 1)))"',
            '"(define %o (sign-extend (extract %high1 %low1 vec) (bitvector 32)))"',
            '"%o"',
            '")"',
            '")"',
            '")"',
            '"dst"',
            '")"',
        ],
    },
    "ups_to_v32acc32": {
        "target_instructions": {
            "ups_to_v32acc32": {
                "args": ["SYMBOLIC_BV_512"],
                "in_vectsize": 512,
                "out_vectsize": 1024,
                "lanesize": 512,
                "in_precision": 16,
                "out_precision": 32,
                "in_vectsize_index": None,
                "out_vectsize_index": None,
                "in_lanesize_index": None,
                "out_lanesize_index": None,
                "in_precision_index": None,
                "out_precision_index": None,
                "arg_permute_map": [0],
                "Signedness": 1,
                "Cost": "None",
                "SIMD": "True",
                "Extensions": "[]",
            },
        },
        "semantics": [
            '"(define (ups_to_v32acc32 vec)"',
            '"(define dst"',
            '"(apply concat"',
            '"(for/list ([%i (reverse (range 0 32 1))])"',
            '"(define %low1 (* 16 %i))"',
            '"(define %high1 (+ %low1 (- 16 1)))"',
            '"(define %o (sign-extend (extract %high1 %low1 vec) (bitvector 32)))"',
            '"%o"',
            '")"',
            '")"',
            '")"',
            '"dst"',
            '")"',
        ],
    },
    "srs_to_v16int16": {
        "target_instructions": {
            "srs_to_v16int16": {
                "args": ["SYMBOLIC_BV_1024"],
                "in_vectsize": 1024,
                "out_vectsize": 256,
                "lanesize": 1024,
                "in_precision": 64,
                "out_precision": 16,
                "in_vectsize_index": None,
                "out_vectsize_index": None,
                "in_lanesize_index": None,
                "out_lanesize_index": None,
                "in_precision_index": None,
                "out_precision_index": None,
                "arg_permute_map": [0],
                "Signedness": 1,
                "Cost": "None",
                "SIMD": "True",
                "Extensions": "[]",
            },
        },
        "semantics": [
            '"(define (srs_to_v16int16 acc)"',
            '"(define dst"',
            '"(apply concat"',
            '"(for/list ([%i (reverse (range 0 16 1))])"',
            '"(define %low1 (* 64 %i))"',
            '"(define %high1 (+ %low1 (- 64 1)))"',
            '"(define %o (extract 15 0 (extract %high1 %low1 acc)))"',
            '"%o"',
            '")"',
            '")"',
            '")"',
            '"dst "',
            '")"',
        ],
    },
    "srs_to_v32int16": {
        "target_instructions": {
            "srs_to_v32int16": {
                "args": ["SYMBOLIC_BV_1024"],
                "in_vectsize": 1024,
                "out_vectsize": 512,
                "lanesize": 1024,
                "in_precision": 32,
                "out_precision": 16,
                "in_vectsize_index": None,
                "out_vectsize_index": None,
                "in_lanesize_index": None,
                "out_lanesize_index": None,
                "in_precision_index": None,
                "out_precision_index": None,
                "arg_permute_map": [0],
                "Signedness": 1,
                "Cost": "None",
                "SIMD": "True",
                "Extensions": "[]",
            },
        },
        "semantics": [
            '"(define (srs_to_v32int16 acc)"',
            '"(define dst"',
            '"(apply concat"',
            '"(for/list ([%i (reverse (range 0 32 1))])"',
            '"(define %low1 (* 32 %i))"',
            '"(define %high1 (+ %low1 (- 32 1)))"',
            '"(define %o (extract 15 0 (extract %high1 %low1 acc)))"',
            '"%o"',
            '")"',
            '")"',
            '")"',
            '"dst "',
            '")"',
        ],
    },
    "mac_elem_32": {
        "target_instructions": {
            "mac_elem_32": {
                "args": ["SYMBOLIC_BV_512", "SYMBOLIC_BV_512", "SYMBOLIC_BV_1024"],
                "in_vectsize": 512,
                "out_vectsize": 1024,
                "lanesize": 512,
                "in_precision": 16,
                "out_precision": 32,
                "in_vectsize_index": None,
                "out_vectsize_index": None,
                "in_lanesize_index": None,
                "out_lanesize_index": None,
                "in_precision_index": None,
                "out_precision_index": None,
                "arg_permute_map": [],
                "Signedness": 1,
                "Cost": "None",
                "SIMD": "True",
                "Extensions": "[]",
            },
        },
        "semantics": [
            '"(define (mac_elem_32 a b c)"',
            '"(define dst"',
            '"(apply concat"',
            '"(for/list ([%i (reverse (range 0 32 1))])"',
            '"(define %low1 (* 16 %i))"',
            '"(define %high1 (+ %low1 (- 16 1)))"',
            '"(define %ext_a (sign-extend (extract %high1 %low1 a) (bitvector 32)))"',
            '"(define %low2 (* 16 %i))"',
            '"(define %high2 (+ %low2 (- 16 1)))"',
            '"(define %ext_b (sign-extend (extract %high2 %low2 b) (bitvector 32)))"',
            '"(define %low3 (* 32 %i))"',
            '"(define %high3 (+ %low3 (- 32 1)))"',
            '"(define %ext_c (extract %high3 %low3 c))"',
            '"(define %o (bvadd %ext_c (bvmul %ext_a %ext_b)))"',
            '"%o"',
            '")"',
            '")"',
            '")"',
            '"dst"',
            '")"',
        ],
    },
    "mul_conv_16x4_conf_v16acc64": {
        "target_instructions": {
            "mul_conv_16x4_conf_v16acc64": {
                "args": [
                    "SYMBOLIC_BV_512",
                    "SYMBOLIC_BV_512",
                    "16",
                    "4",
                    "32",
                    "16",
                    "16",
                    "64",
                ],
                "in_vectsize": 512,
                "out_vectsize": 1024,
                "lanesize": 32,
                "in_precision": 16,
                "out_precision": 64,
                "in_vectsize_index": 4,
                "out_vectsize_index": 5,
                "in_lanesize_index": 4,
                "out_lanesize_index": 5,
                "in_precision_index": 6,
                "out_precision_index": 7,
                "arg_permute_map": [0, 1, -1, -1, -1, -1, -1, -1],
                "Signedness": 0,
                "Cost": "None",
                "SIMD": "True",
                "Extensions": "[]",
            },
            "mul_conv_16x4_v16acc64": {
                "args": [
                    "SYMBOLIC_BV_512",
                    "SYMBOLIC_BV_512",
                    "16",
                    "4",
                    "32",
                    "16",
                    "16",
                    "64",
                ],
                "in_vectsize": 512,
                "out_vectsize": 1024,
                "lanesize": 32,
                "in_precision": 16,
                "out_precision": 64,
                "in_vectsize_index": 4,
                "out_vectsize_index": 5,
                "in_lanesize_index": 4,
                "out_lanesize_index": 5,
                "in_precision_index": 6,
                "out_precision_index": 7,
                "arg_permute_map": [0, 1, -1, -1, -1, -1, -1, -1],
                "Signedness": 0,
                "Cost": "None",
                "SIMD": "True",
                "Extensions": "[]",
            },
            "mul_conv_32x8_conf_v32acc32": {
                "args": [
                    "SYMBOLIC_BV_512",
                    "SYMBOLIC_BV_512",
                    "32",
                    "8",
                    "64",
                    "32",
                    "8",
                    "32",
                ],
                "in_vectsize": 512,
                "out_vectsize": 1024,
                "lanesize": 64,
                "in_precision": 8,
                "out_precision": 32,
                "in_vectsize_index": 4,
                "out_vectsize_index": 5,
                "in_lanesize_index": 4,
                "out_lanesize_index": 5,
                "in_precision_index": 6,
                "out_precision_index": 7,
                "arg_permute_map": [0, 1, -1, -1, -1, -1, -1, -1],
                "Signedness": 0,
                "Cost": "None",
                "SIMD": "True",
                "Extensions": "[]",
            },
            "mul_conv_32x8_v32acc32": {
                "args": [
                    "SYMBOLIC_BV_512",
                    "SYMBOLIC_BV_512",
                    "32",
                    "8",
                    "64",
                    "32",
                    "8",
                    "32",
                ],
                "in_vectsize": 512,
                "out_vectsize": 1024,
                "lanesize": 64,
                "in_precision": 8,
                "out_precision": 32,
                "in_vectsize_index": 4,
                "out_vectsize_index": 5,
                "in_lanesize_index": 4,
                "out_lanesize_index": 5,
                "in_precision_index": 6,
                "out_precision_index": 7,
                "arg_permute_map": [0, 1, -1, -1, -1, -1, -1, -1],
                "Signedness": 0,
                "Cost": "None",
                "SIMD": "True",
                "Extensions": "[]",
            },
            "mul_conv_4x4_8ch_conf_v32acc32": {
                "args": [
                    "SYMBOLIC_BV_512",
                    "SYMBOLIC_BV_512",
                    "4",
                    "4",
                    "64",
                    "32",
                    "8",
                    "32",
                ],
                "in_vectsize": 512,
                "out_vectsize": 1024,
                "lanesize": 64,
                "in_precision": 8,
                "out_precision": 32,
                "in_vectsize_index": 4,
                "out_vectsize_index": 5,
                "in_lanesize_index": 4,
                "out_lanesize_index": 5,
                "in_precision_index": 6,
                "out_precision_index": 7,
                "arg_permute_map": [0, 1, -1, -1, -1, -1, -1, -1],
                "Signedness": 0,
                "Cost": "None",
                "SIMD": "True",
                "Extensions": "[]",
            },
            "mul_conv_4x4_8ch_v32acc32": {
                "args": [
                    "SYMBOLIC_BV_512",
                    "SYMBOLIC_BV_512",
                    "4",
                    "4",
                    "64",
                    "32",
                    "8",
                    "32",
                ],
                "in_vectsize": 512,
                "out_vectsize": 1024,
                "lanesize": 64,
                "in_precision": 8,
                "out_precision": 32,
                "in_vectsize_index": 4,
                "out_vectsize_index": 5,
                "in_lanesize_index": 4,
                "out_lanesize_index": 5,
                "in_precision_index": 6,
                "out_precision_index": 7,
                "arg_permute_map": [0, 1, -1, -1, -1, -1, -1, -1],
                "Signedness": 0,
                "Cost": "None",
                "SIMD": "True",
                "Extensions": "[]",
            },
            "mul_conv_8x8_4ch_conf_v32acc32": {
                "args": [
                    "SYMBOLIC_BV_512",
                    "SYMBOLIC_BV_512",
                    "8",
                    "8",
                    "64",
                    "32",
                    "8",
                    "32",
                ],
                "in_vectsize": 512,
                "out_vectsize": 1024,
                "lanesize": 64,
                "in_precision": 8,
                "out_precision": 32,
                "in_vectsize_index": 4,
                "out_vectsize_index": 5,
                "in_lanesize_index": 4,
                "out_lanesize_index": 5,
                "in_precision_index": 6,
                "out_precision_index": 7,
                "arg_permute_map": [0, 1, -1, -1, -1, -1, -1, -1],
                "Signedness": 0,
                "Cost": "None",
                "SIMD": "True",
                "Extensions": "[]",
            },
            "mul_conv_8x8_4ch_v32acc32": {
                "args": [
                    "SYMBOLIC_BV_512",
                    "SYMBOLIC_BV_512",
                    "8",
                    "8",
                    "64",
                    "32",
                    "8",
                    "32",
                ],
                "in_vectsize": 512,
                "out_vectsize": 1024,
                "lanesize": 64,
                "in_precision": 8,
                "out_precision": 32,
                "in_vectsize_index": 4,
                "out_vectsize_index": 5,
                "in_lanesize_index": 4,
                "out_lanesize_index": 5,
                "in_precision_index": 6,
                "out_precision_index": 7,
                "arg_permute_map": [0, 1, -1, -1, -1, -1, -1, -1],
                "Signedness": 0,
                "Cost": "None",
                "SIMD": "True",
                "Extensions": "[]",
            },
        },
        "semantics": [
            '"(define (mul_conv_16x4_conf_v16acc64 matA matB m n in_lanesize lanesize indatasize outdatasize) "',
            '"(define dst"',
            '"(apply concat"',
            '"(for/list ([%i (reverse (range 0 m 1))])"',
            '"(define res"',
            '"(apply bvadd"',
            '"(for/list ([%j (reverse (range 0 n 1))])"',
            '"(define %aLo1 (* indatasize (+ %i %j)))"',
            '"(define %aHi1 (+ %aLo1 (- indatasize 1)))"',
            '"(define %bLo1 (* indatasize %j))"',
            '"(define %bHi1 (+ %bLo1 (- indatasize 1)))"',
            '"(define %ext_a1 (sign-extend (extract %aHi1 %aLo1 matA) (bitvector outdatasize)))"',
            '"(define %ext_b1 (sign-extend (extract %bHi1 %bLo1 matB) (bitvector outdatasize)))"',
            '"(define %elem (bvmul %ext_a1 %ext_b1))"',
            '"%elem"',
            '")"',
            '")"',
            '")"',
            '"res"',
            '")"',
            '")"',
            '")"',
            '"dst"',
            '")"',
        ],
    },
    "shift_v16int32": {
        "target_instructions": {
            "shift_v16int32": {
                "args": [
                    "SYMBOLIC_BV_512",
                    "SYMBOLIC_BV_512",
                    "SYMBOLIC_BV_32",
                    "16",
                    "32",
                ],
                "in_vectsize": 512,
                "out_vectsize": 512,
                "lanesize": 16,
                "in_precision": 32,
                "out_precision": 32,
                "in_vectsize_index": 3,
                "out_vectsize_index": 3,
                "in_lanesize_index": 3,
                "out_lanesize_index": 3,
                "in_precision_index": 4,
                "out_precision_index": 4,
                "arg_permute_map": [0, 1, 2, -1, -1],
                "Signedness": 1,
                "Cost": "None",
                "SIMD": "True",
                "Extensions": "[]",
            },
            "shift_v16uint32": {
                "args": [
                    "SYMBOLIC_BV_512",
                    "SYMBOLIC_BV_512",
                    "SYMBOLIC_BV_32",
                    "16",
                    "32",
                ],
                "in_vectsize": 512,
                "out_vectsize": 512,
                "lanesize": 16,
                "in_precision": 32,
                "out_precision": 32,
                "in_vectsize_index": 3,
                "out_vectsize_index": 3,
                "in_lanesize_index": 3,
                "out_lanesize_index": 3,
                "in_precision_index": 4,
                "out_precision_index": 4,
                "arg_permute_map": [0, 1, 2, -1, -1],
                "Signedness": 0,
                "Cost": "None",
                "SIMD": "True",
                "Extensions": "[]",
            },
            "shift_v32int16": {
                "args": [
                    "SYMBOLIC_BV_512",
                    "SYMBOLIC_BV_512",
                    "SYMBOLIC_BV_32",
                    "32",
                    "16",
                ],
                "in_vectsize": 512,
                "out_vectsize": 512,
                "lanesize": 32,
                "in_precision": 16,
                "out_precision": 16,
                "in_vectsize_index": 3,
                "out_vectsize_index": 3,
                "in_lanesize_index": 3,
                "out_lanesize_index": 3,
                "in_precision_index": 4,
                "out_precision_index": 4,
                "arg_permute_map": [0, 1, 2, -1, -1],
                "Signedness": 1,
                "Cost": "None",
                "SIMD": "True",
                "Extensions": "[]",
            },
            "shift_v32uint16": {
                "args": [
                    "SYMBOLIC_BV_512",
                    "SYMBOLIC_BV_512",
                    "SYMBOLIC_BV_32",
                    "32",
                    "16",
                ],
                "in_vectsize": 512,
                "out_vectsize": 512,
                "lanesize": 32,
                "in_precision": 16,
                "out_precision": 16,
                "in_vectsize_index": 3,
                "out_vectsize_index": 3,
                "in_lanesize_index": 3,
                "out_lanesize_index": 3,
                "in_precision_index": 4,
                "out_precision_index": 4,
                "arg_permute_map": [0, 1, 2, -1, -1],
                "Signedness": 0,
                "Cost": "None",
                "SIMD": "True",
                "Extensions": "[]",
            },
            "shift_v64int8": {
                "args": [
                    "SYMBOLIC_BV_512",
                    "SYMBOLIC_BV_512",
                    "SYMBOLIC_BV_32",
                    "64",
                    "8",
                ],
                "in_vectsize": 512,
                "out_vectsize": 512,
                "lanesize": 64,
                "in_precision": 8,
                "out_precision": 8,
                "in_vectsize_index": 3,
                "out_vectsize_index": 3,
                "in_lanesize_index": 3,
                "out_lanesize_index": 3,
                "in_precision_index": 4,
                "out_precision_index": 4,
                "arg_permute_map": [0, 1, 2, -1, -1],
                "Signedness": 1,
                "Cost": "None",
                "SIMD": "True",
                "Extensions": "[]",
            },
            "shift_v64uint8": {
                "args": [
                    "SYMBOLIC_BV_512",
                    "SYMBOLIC_BV_512",
                    "SYMBOLIC_BV_32",
                    "64",
                    "8",
                ],
                "in_vectsize": 512,
                "out_vectsize": 512,
                "lanesize": 64,
                "in_precision": 8,
                "out_precision": 8,
                "in_vectsize_index": 3,
                "out_vectsize_index": 3,
                "in_lanesize_index": 3,
                "out_lanesize_index": 3,
                "in_precision_index": 4,
                "out_precision_index": 4,
                "arg_permute_map": [0, 1, 2, -1, -1],
                "Signedness": 0,
                "Cost": "None",
                "SIMD": "True",
                "Extensions": "[]",
            },
        },
        "semantics": [
            '"(define (shift_v16int32 a b shift %lanesize %datasize)"',
            '"(define dst (extract (+ (- (* %lanesize %datasize) 1) (* %datasize shift)) (* %datasize shift) (concat a b)))"',
            '"dst"',
            '")"',
        ],
    },
    "shuffle_v128int4_lo": {
        "target_instructions": {
            "shuffle_v128int4_lo": {
                "args": ["SYMBOLIC_BV_512", "SYMBOLIC_BV_512", "128", "4"],
                "in_vectsize": 512,
                "out_vectsize": 512,
                "lanesize": 128,
                "in_precision": 4,
                "out_precision": 4,
                "in_vectsize_index": 2,
                "out_vectsize_index": 2,
                "in_lanesize_index": 2,
                "out_lanesize_index": 2,
                "in_precision_index": 3,
                "out_precision_index": 3,
                "arg_permute_map": [0, 1, -1, -1],
                "Signedness": 0,
                "Cost": "None",
                "SIMD": "True",
                "Extensions": "[]",
            },
            "shuffle_v128uint4_lo": {
                "args": ["SYMBOLIC_BV_512", "SYMBOLIC_BV_512", "128", "4"],
                "in_vectsize": 512,
                "out_vectsize": 512,
                "lanesize": 128,
                "in_precision": 4,
                "out_precision": 4,
                "in_vectsize_index": 2,
                "out_vectsize_index": 2,
                "in_lanesize_index": 2,
                "out_lanesize_index": 2,
                "in_precision_index": 3,
                "out_precision_index": 3,
                "arg_permute_map": [0, 1, -1, -1],
                "Signedness": 0,
                "Cost": "None",
                "SIMD": "True",
                "Extensions": "[]",
            },
            "shuffle_v16int32_lo": {
                "args": ["SYMBOLIC_BV_512", "SYMBOLIC_BV_512", "16", "32"],
                "in_vectsize": 512,
                "out_vectsize": 512,
                "lanesize": 16,
                "in_precision": 32,
                "out_precision": 32,
                "in_vectsize_index": 2,
                "out_vectsize_index": 2,
                "in_lanesize_index": 2,
                "out_lanesize_index": 2,
                "in_precision_index": 3,
                "out_precision_index": 3,
                "arg_permute_map": [0, 1, -1, -1],
                "Signedness": 0,
                "Cost": "None",
                "SIMD": "True",
                "Extensions": "[]",
            },
            "shuffle_v16uint32_lo": {
                "args": ["SYMBOLIC_BV_512", "SYMBOLIC_BV_512", "16", "32"],
                "in_vectsize": 512,
                "out_vectsize": 512,
                "lanesize": 16,
                "in_precision": 32,
                "out_precision": 32,
                "in_vectsize_index": 2,
                "out_vectsize_index": 2,
                "in_lanesize_index": 2,
                "out_lanesize_index": 2,
                "in_precision_index": 3,
                "out_precision_index": 3,
                "arg_permute_map": [0, 1, -1, -1],
                "Signedness": 0,
                "Cost": "None",
                "SIMD": "True",
                "Extensions": "[]",
            },
            "shuffle_v32int16_lo": {
                "args": ["SYMBOLIC_BV_512", "SYMBOLIC_BV_512", "32", "16"],
                "in_vectsize": 512,
                "out_vectsize": 512,
                "lanesize": 32,
                "in_precision": 16,
                "out_precision": 16,
                "in_vectsize_index": 2,
                "out_vectsize_index": 2,
                "in_lanesize_index": 2,
                "out_lanesize_index": 2,
                "in_precision_index": 3,
                "out_precision_index": 3,
                "arg_permute_map": [0, 1, -1, -1],
                "Signedness": 0,
                "Cost": "None",
                "SIMD": "True",
                "Extensions": "[]",
            },
            "shuffle_v32uint16_lo": {
                "args": ["SYMBOLIC_BV_512", "SYMBOLIC_BV_512", "32", "16"],
                "in_vectsize": 512,
                "out_vectsize": 512,
                "lanesize": 32,
                "in_precision": 16,
                "out_precision": 16,
                "in_vectsize_index": 2,
                "out_vectsize_index": 2,
                "in_lanesize_index": 2,
                "out_lanesize_index": 2,
                "in_precision_index": 3,
                "out_precision_index": 3,
                "arg_permute_map": [0, 1, -1, -1],
                "Signedness": 0,
                "Cost": "None",
                "SIMD": "True",
                "Extensions": "[]",
            },
            "shuffle_v64int8_lo": {
                "args": ["SYMBOLIC_BV_512", "SYMBOLIC_BV_512", "64", "8"],
                "in_vectsize": 512,
                "out_vectsize": 512,
                "lanesize": 64,
                "in_precision": 8,
                "out_precision": 8,
                "in_vectsize_index": 2,
                "out_vectsize_index": 2,
                "in_lanesize_index": 2,
                "out_lanesize_index": 2,
                "in_precision_index": 3,
                "out_precision_index": 3,
                "arg_permute_map": [0, 1, -1, -1],
                "Signedness": 0,
                "Cost": "None",
                "SIMD": "True",
                "Extensions": "[]",
            },
            "shuffle_v64uint8_lo": {
                "args": ["SYMBOLIC_BV_512", "SYMBOLIC_BV_512", "64", "8"],
                "in_vectsize": 512,
                "out_vectsize": 512,
                "lanesize": 64,
                "in_precision": 8,
                "out_precision": 8,
                "in_vectsize_index": 2,
                "out_vectsize_index": 2,
                "in_lanesize_index": 2,
                "out_lanesize_index": 2,
                "in_precision_index": 3,
                "out_precision_index": 3,
                "arg_permute_map": [0, 1, -1, -1],
                "Signedness": 0,
                "Cost": "None",
                "SIMD": "True",
                "Extensions": "[]",
            },
        },
        "semantics": [
            '"(define (shuffle_v128int4_lo arg0 arg1 %lanesize %indatasize)"',
            '"(define dst"',
            '"(apply concat"',
            '"(for/list ([%inner.it (reverse (range 0 %lanesize 1))])"',
            '"(define %low (* %indatasize %inner.it))"',
            '"(define %high (+ %inner.it (- %indatasize 1)))"',
            '"(define %a (extract %high %low arg0))"',
            '"(define %b (extract %high %low arg1))"',
            '"(concat %a %b))))"',
            '"(extract (- (* %lanesize %indatasize) 1) 0 dst))"',
        ],
    },
    "shuffle_v128int4_hi": {
        "target_instructions": {
            "shuffle_v128int4_hi": {
                "args": ["SYMBOLIC_BV_512", "SYMBOLIC_BV_512", "128", "4"],
                "in_vectsize": 512,
                "out_vectsize": 512,
                "lanesize": 128,
                "in_precision": 4,
                "out_precision": 4,
                "in_vectsize_index": 2,
                "out_vectsize_index": 2,
                "in_lanesize_index": 2,
                "out_lanesize_index": 2,
                "in_precision_index": 3,
                "out_precision_index": 3,
                "arg_permute_map": [0, 1, -1, -1],
                "Signedness": 0,
                "Cost": "None",
                "SIMD": "True",
                "Extensions": "[]",
            },
            "shuffle_v128uint4_hi": {
                "args": ["SYMBOLIC_BV_512", "SYMBOLIC_BV_512", "128", "4"],
                "in_vectsize": 512,
                "out_vectsize": 512,
                "lanesize": 128,
                "in_precision": 4,
                "out_precision": 4,
                "in_vectsize_index": 2,
                "out_vectsize_index": 2,
                "in_lanesize_index": 2,
                "out_lanesize_index": 2,
                "in_precision_index": 3,
                "out_precision_index": 3,
                "arg_permute_map": [0, 1, -1, -1],
                "Signedness": 0,
                "Cost": "None",
                "SIMD": "True",
                "Extensions": "[]",
            },
            "shuffle_v16int32_hi": {
                "args": ["SYMBOLIC_BV_512", "SYMBOLIC_BV_512", "16", "32"],
                "in_vectsize": 512,
                "out_vectsize": 512,
                "lanesize": 16,
                "in_precision": 32,
                "out_precision": 32,
                "in_vectsize_index": 2,
                "out_vectsize_index": 2,
                "in_lanesize_index": 2,
                "out_lanesize_index": 2,
                "in_precision_index": 3,
                "out_precision_index": 3,
                "arg_permute_map": [0, 1, -1, -1],
                "Signedness": 0,
                "Cost": "None",
                "SIMD": "True",
                "Extensions": "[]",
            },
            "shuffle_v16uint32_hi": {
                "args": ["SYMBOLIC_BV_512", "SYMBOLIC_BV_512", "16", "32"],
                "in_vectsize": 512,
                "out_vectsize": 512,
                "lanesize": 16,
                "in_precision": 32,
                "out_precision": 32,
                "in_vectsize_index": 2,
                "out_vectsize_index": 2,
                "in_lanesize_index": 2,
                "out_lanesize_index": 2,
                "in_precision_index": 3,
                "out_precision_index": 3,
                "arg_permute_map": [0, 1, -1, -1],
                "Signedness": 0,
                "Cost": "None",
                "SIMD": "True",
                "Extensions": "[]",
            },
            "shuffle_v32int16_hi": {
                "args": ["SYMBOLIC_BV_512", "SYMBOLIC_BV_512", "32", "16"],
                "in_vectsize": 512,
                "out_vectsize": 512,
                "lanesize": 32,
                "in_precision": 16,
                "out_precision": 16,
                "in_vectsize_index": 2,
                "out_vectsize_index": 2,
                "in_lanesize_index": 2,
                "out_lanesize_index": 2,
                "in_precision_index": 3,
                "out_precision_index": 3,
                "arg_permute_map": [0, 1, -1, -1],
                "Signedness": 0,
                "Cost": "None",
                "SIMD": "True",
                "Extensions": "[]",
            },
            "shuffle_v32uint16_hi": {
                "args": ["SYMBOLIC_BV_512", "SYMBOLIC_BV_512", "32", "16"],
                "in_vectsize": 512,
                "out_vectsize": 512,
                "lanesize": 32,
                "in_precision": 16,
                "out_precision": 16,
                "in_vectsize_index": 2,
                "out_vectsize_index": 2,
                "in_lanesize_index": 2,
                "out_lanesize_index": 2,
                "in_precision_index": 3,
                "out_precision_index": 3,
                "arg_permute_map": [0, 1, -1, -1],
                "Signedness": 0,
                "Cost": "None",
                "SIMD": "True",
                "Extensions": "[]",
            },
            "shuffle_v64int8_hi": {
                "args": ["SYMBOLIC_BV_512", "SYMBOLIC_BV_512", "64", "8"],
                "in_vectsize": 512,
                "out_vectsize": 512,
                "lanesize": 64,
                "in_precision": 8,
                "out_precision": 8,
                "in_vectsize_index": 2,
                "out_vectsize_index": 2,
                "in_lanesize_index": 2,
                "out_lanesize_index": 2,
                "in_precision_index": 3,
                "out_precision_index": 3,
                "arg_permute_map": [0, 1, -1, -1],
                "Signedness": 0,
                "Cost": "None",
                "SIMD": "True",
                "Extensions": "[]",
            },
            "shuffle_v64uint8_hi": {
                "args": ["SYMBOLIC_BV_512", "SYMBOLIC_BV_512", "64", "8"],
                "in_vectsize": 512,
                "out_vectsize": 512,
                "lanesize": 64,
                "in_precision": 8,
                "out_precision": 8,
                "in_vectsize_index": 2,
                "out_vectsize_index": 2,
                "in_lanesize_index": 2,
                "out_lanesize_index": 2,
                "in_precision_index": 3,
                "out_precision_index": 3,
                "arg_permute_map": [0, 1, -1, -1],
                "Signedness": 0,
                "Cost": "None",
                "SIMD": "True",
                "Extensions": "[]",
            },
        },
        "semantics": [
            '"(define (shuffle_v128int4_hi arg0 arg1 %lanesize %indatasize)"',
            '"(define dst"',
            '"(apply concat"',
            '"(for/list ([%inner.it (reverse (range 0 %lanesize 1))])"',
            '"(define %low (* %indatasize %inner.it))"',
            '"(define %high (+ %inner.it (- %indatasize 1)))"',
            '"(define %a (extract %high %low arg0))"',
            '"(define %b (extract %high %low arg1))"',
            '"(concat %a %b))))"',
            '"(extract (- (* 2 (* %lanesize %indatasize)) 1) (* %lanesize %indatasize) dst))"',
        ],
    },
    "add_v16acc64": {
        "target_instructions": {
            "add_v16acc64": {
                "args": ["SYMBOLIC_BV_1024", "SYMBOLIC_BV_1024", "16", "64"],
                "in_vectsize": 1024,
                "out_vectsize": 1024,
                "lanesize": 16,
                "in_precision": 64,
                "out_precision": 64,
                "in_vectsize_index": 2,
                "out_vectsize_index": 2,
                "in_lanesize_index": 2,
                "out_lanesize_index": 2,
                "in_precision_index": 3,
                "out_precision_index": 3,
                "arg_permute_map": [0, 1, -1, -1],
                "Signedness": 1,
                "Cost": "None",
                "SIMD": "True",
                "Extensions": "[]",
            },
            "add_v16int32": {
                "args": ["SYMBOLIC_BV_512", "SYMBOLIC_BV_512", "16", "32"],
                "in_vectsize": 512,
                "out_vectsize": 512,
                "lanesize": 16,
                "in_precision": 32,
                "out_precision": 32,
                "in_vectsize_index": 2,
                "out_vectsize_index": 2,
                "in_lanesize_index": 2,
                "out_lanesize_index": 2,
                "in_precision_index": 3,
                "out_precision_index": 3,
                "arg_permute_map": [0, 1, -1, -1],
                "Signedness": 1,
                "Cost": "None",
                "SIMD": "True",
                "Extensions": "[]",
            },
            "add_v16uint32": {
                "args": ["SYMBOLIC_BV_512", "SYMBOLIC_BV_512", "16", "32"],
                "in_vectsize": 512,
                "out_vectsize": 512,
                "lanesize": 16,
                "in_precision": 32,
                "out_precision": 32,
                "in_vectsize_index": 2,
                "out_vectsize_index": 2,
                "in_lanesize_index": 2,
                "out_lanesize_index": 2,
                "in_precision_index": 3,
                "out_precision_index": 3,
                "arg_permute_map": [0, 1, -1, -1],
                "Signedness": 0,
                "Cost": "None",
                "SIMD": "True",
                "Extensions": "[]",
            },
            "add_v32acc32": {
                "args": ["SYMBOLIC_BV_1024", "SYMBOLIC_BV_1024", "32", "32"],
                "in_vectsize": 1024,
                "out_vectsize": 1024,
                "lanesize": 32,
                "in_precision": 32,
                "out_precision": 32,
                "in_vectsize_index": 2,
                "out_vectsize_index": 2,
                "in_lanesize_index": 2,
                "out_lanesize_index": 2,
                "in_precision_index": 3,
                "out_precision_index": 3,
                "arg_permute_map": [0, 1, -1, -1],
                "Signedness": 1,
                "Cost": "None",
                "SIMD": "True",
                "Extensions": "[]",
            },
            "add_v32int16": {
                "args": ["SYMBOLIC_BV_512", "SYMBOLIC_BV_512", "32", "16"],
                "in_vectsize": 512,
                "out_vectsize": 512,
                "lanesize": 32,
                "in_precision": 16,
                "out_precision": 16,
                "in_vectsize_index": 2,
                "out_vectsize_index": 2,
                "in_lanesize_index": 2,
                "out_lanesize_index": 2,
                "in_precision_index": 3,
                "out_precision_index": 3,
                "arg_permute_map": [0, 1, -1, -1],
                "Signedness": 1,
                "Cost": "None",
                "SIMD": "True",
                "Extensions": "[]",
            },
            "add_v32uint16": {
                "args": ["SYMBOLIC_BV_512", "SYMBOLIC_BV_512", "32", "16"],
                "in_vectsize": 512,
                "out_vectsize": 512,
                "lanesize": 32,
                "in_precision": 16,
                "out_precision": 16,
                "in_vectsize_index": 2,
                "out_vectsize_index": 2,
                "in_lanesize_index": 2,
                "out_lanesize_index": 2,
                "in_precision_index": 3,
                "out_precision_index": 3,
                "arg_permute_map": [0, 1, -1, -1],
                "Signedness": 0,
                "Cost": "None",
                "SIMD": "True",
                "Extensions": "[]",
            },
            "add_v64int8": {
                "args": ["SYMBOLIC_BV_512", "SYMBOLIC_BV_512", "64", "8"],
                "in_vectsize": 512,
                "out_vectsize": 512,
                "lanesize": 64,
                "in_precision": 8,
                "out_precision": 8,
                "in_vectsize_index": 2,
                "out_vectsize_index": 2,
                "in_lanesize_index": 2,
                "out_lanesize_index": 2,
                "in_precision_index": 3,
                "out_precision_index": 3,
                "arg_permute_map": [0, 1, -1, -1],
                "Signedness": 1,
                "Cost": "None",
                "SIMD": "True",
                "Extensions": "[]",
            },
            "add_v64uint8": {
                "args": ["SYMBOLIC_BV_512", "SYMBOLIC_BV_512", "64", "8"],
                "in_vectsize": 512,
                "out_vectsize": 512,
                "lanesize": 64,
                "in_precision": 8,
                "out_precision": 8,
                "in_vectsize_index": 2,
                "out_vectsize_index": 2,
                "in_lanesize_index": 2,
                "out_lanesize_index": 2,
                "in_precision_index": 3,
                "out_precision_index": 3,
                "arg_permute_map": [0, 1, -1, -1],
                "Signedness": 0,
                "Cost": "None",
                "SIMD": "True",
                "Extensions": "[]",
            },
        },
        "semantics": [
            '"(define (add_v16acc64 arg0 arg1 %lanesize %datasize)"',
            '"(define dst"',
            '"(apply concat"',
            '"(for/list ([%i (range 0 %lanesize 1)])"',
            '"(define %low1 (* %datasize %i))"',
            '"(define %high1 (+ %low1 (- %datasize 1)))"',
            '"(define %ext_xbuff (extract %high1 %low1 arg0))"',
            '"(define %low2 (* %datasize %i))"',
            '"(define %high2 (+ %low2 (- %datasize 1)))"',
            '"(define %ext_ybuff (extract %high2 %low2 arg1))"',
            '"(define %o (bvadd %ext_xbuff %ext_ybuff))"',
            '"%o"',
            '")"',
            '")"',
            '")"',
            '"dst"',
            '")"',
        ],
    },
    "mul_elem_16_2_v16acc64": {
        "target_instructions": {
            "mul_elem_16_2_v16acc64": {
                "args": ["SYMBOLIC_BV_512", "SYMBOLIC_BV_512", "16", "16", "64"],
                "in_vectsize": 512,
                "out_vectsize": 1024,
                "lanesize": 32,
                "in_precision": 16,
                "out_precision": 64,
                "in_vectsize_index": 2,
                "out_vectsize_index": 2,
                "in_lanesize_index": 2,
                "out_lanesize_index": 2,
                "in_precision_index": 3,
                "out_precision_index": 4,
                "arg_permute_map": [0, 1, -1, -1, -1],
                "Signedness": 0,
                "Cost": "None",
                "SIMD": "True",
                "Extensions": "[]",
            },
            "mul_elem_32_2_v32acc32": {
                "args": ["SYMBOLIC_BV_512", "SYMBOLIC_BV_512", "32", "8", "32"],
                "in_vectsize": 512,
                "out_vectsize": 1024,
                "lanesize": 64,
                "in_precision": 8,
                "out_precision": 32,
                "in_vectsize_index": 2,
                "out_vectsize_index": 2,
                "in_lanesize_index": 2,
                "out_lanesize_index": 2,
                "in_precision_index": 3,
                "out_precision_index": 4,
                "arg_permute_map": [0, 1, -1, -1, -1],
                "Signedness": 0,
                "Cost": "None",
                "SIMD": "True",
                "Extensions": "[]",
            },
            "mul_elem_32_v32acc32": {
                "args": ["SYMBOLIC_BV_512", "SYMBOLIC_BV_512", "32", "16", "32"],
                "in_vectsize": 512,
                "out_vectsize": 1024,
                "lanesize": 32,
                "in_precision": 16,
                "out_precision": 32,
                "in_vectsize_index": 2,
                "out_vectsize_index": 2,
                "in_lanesize_index": 2,
                "out_lanesize_index": 2,
                "in_precision_index": 3,
                "out_precision_index": 4,
                "arg_permute_map": [0, 1, -1, -1, -1],
                "Signedness": 0,
                "Cost": "None",
                "SIMD": "True",
                "Extensions": "[]",
            },
        },
        "semantics": [
            '"(define (mul_elem_16_2_v16acc64 arg0 arg1 %lanesize %indatasize %outdatasize)"',
            '"(define dst"',
            '"(apply concat"',
            '"(for/list ([%i (reverse (range 0 %lanesize 1))])"',
            '"(define %low1 (* %indatasize %i))"',
            '"(define %high1 (+ %low1 (- %indatasize 1)))"',
            '"(define %ext_a (sign-extend (extract %high1 %low1 arg0) (bitvector %outdatasize)))"',
            '"(define %low2 (* %indatasize %i))"',
            '"(define %high2 (+ %low2 (- %indatasize 1)))"',
            '"(define %ext_b (sign-extend (extract %high2 %low2 arg1) (bitvector %outdatasize)))"',
            '"(define %o (bvmul %ext_a %ext_b))"',
            '"%o"',
            '")"',
            '")"',
            '")"',
            '"dst"',
            '")"',
        ],
    },
    "mul_elem_16_2_conf_v16acc64": {
        "target_instructions": {
            "mul_elem_16_2_conf_v16acc64": {
                "args": [
                    "SYMBOLIC_BV_512",
                    "SYMBOLIC_BV_512",
                    "SYMBOLIC_BV_32",
                    "16",
                    "16",
                    "64",
                ],
                "in_vectsize": 512,
                "out_vectsize": 1024,
                "lanesize": 32,
                "in_precision": 16,
                "out_precision": 64,
                "in_vectsize_index": 2,
                "out_vectsize_index": 2,
                "in_lanesize_index": 2,
                "out_lanesize_index": 2,
                "in_precision_index": 3,
                "out_precision_index": 4,
                "arg_permute_map": [0, 1, 2, -1, -1, -1],
                "Signedness": 0,
                "Cost": "None",
                "SIMD": "True",
                "Extensions": "[]",
            },
            "mul_elem_32_2_conf_v32acc32": {
                "args": [
                    "SYMBOLIC_BV_512",
                    "SYMBOLIC_BV_512",
                    "SYMBOLIC_BV_32",
                    "32",
                    "8",
                    "32",
                ],
                "in_vectsize": 512,
                "out_vectsize": 1024,
                "lanesize": 64,
                "in_precision": 8,
                "out_precision": 32,
                "in_vectsize_index": 2,
                "out_vectsize_index": 2,
                "in_lanesize_index": 2,
                "out_lanesize_index": 2,
                "in_precision_index": 3,
                "out_precision_index": 4,
                "arg_permute_map": [0, 1, 2, -1, -1, -1],
                "Signedness": 0,
                "Cost": "None",
                "SIMD": "True",
                "Extensions": "[]",
            },
            "mul_elem_32_conf_v32acc32": {
                "args": [
                    "SYMBOLIC_BV_512",
                    "SYMBOLIC_BV_512",
                    "SYMBOLIC_BV_32",
                    "32",
                    "16",
                    "32",
                ],
                "in_vectsize": 512,
                "out_vectsize": 1024,
                "lanesize": 32,
                "in_precision": 16,
                "out_precision": 32,
                "in_vectsize_index": 2,
                "out_vectsize_index": 2,
                "in_lanesize_index": 2,
                "out_lanesize_index": 2,
                "in_precision_index": 3,
                "out_precision_index": 4,
                "arg_permute_map": [0, 1, 2, -1, -1, -1],
                "Signedness": 0,
                "Cost": "None",
                "SIMD": "True",
                "Extensions": "[]",
            },
        },
        "semantics": [
            '"(define (mul_elem_16_2_conf_v16acc64 arg0 arg1 int_sub %lanesize %indatasize %outdatasize)"',
            '"(define dst"',
            '"(apply concat"',
            '"(for/list ([%i (reverse (range 0 %lanesize 1))])"',
            '"(define %low1 (* %indatasize %i))"',
            '"(define %high1 (+ %low1 (- %indatasize 1)))"',
            '"(define %ext_a (sign-extend (extract %high1 %low1 arg0) (bitvector %outdatasize)))"',
            '"(define %low2 (* %indatasize %i))"',
            '"(define %high2 (+ %low2 (- %indatasize 1)))"',
            '"(define %ext_b (sign-extend (extract %high2 %low2 arg1) (bitvector %outdatasize)))"',
            '"(define %o (bvmul %ext_a %ext_b))"',
            '"(if (bveq (extract (+ %i 0) %i int_sub) (bv #b1 1)) (bvneg %o) %o)"',
            '")"',
            '")"',
            '")"',
            '"dst"',
            '")"',
        ],
    },
    "sub_v16acc64": {
        "target_instructions": {
            "sub_v16acc64": {
                "args": ["SYMBOLIC_BV_1024", "SYMBOLIC_BV_1024", "16", "64"],
                "in_vectsize": 1024,
                "out_vectsize": 1024,
                "lanesize": 16,
                "in_precision": 64,
                "out_precision": 64,
                "in_vectsize_index": 2,
                "out_vectsize_index": 2,
                "in_lanesize_index": 2,
                "out_lanesize_index": 2,
                "in_precision_index": 3,
                "out_precision_index": 3,
                "arg_permute_map": [0, 1, -1, -1],
                "Signedness": 1,
                "Cost": "None",
                "SIMD": "True",
                "Extensions": "[]",
            },
            "sub_v16int32": {
                "args": ["SYMBOLIC_BV_512", "SYMBOLIC_BV_512", "16", "32"],
                "in_vectsize": 512,
                "out_vectsize": 512,
                "lanesize": 16,
                "in_precision": 32,
                "out_precision": 32,
                "in_vectsize_index": 2,
                "out_vectsize_index": 2,
                "in_lanesize_index": 2,
                "out_lanesize_index": 2,
                "in_precision_index": 3,
                "out_precision_index": 3,
                "arg_permute_map": [0, 1, -1, -1],
                "Signedness": 1,
                "Cost": "None",
                "SIMD": "True",
                "Extensions": "[]",
            },
            "sub_v16uint32": {
                "args": ["SYMBOLIC_BV_512", "SYMBOLIC_BV_512", "16", "32"],
                "in_vectsize": 512,
                "out_vectsize": 512,
                "lanesize": 16,
                "in_precision": 32,
                "out_precision": 32,
                "in_vectsize_index": 2,
                "out_vectsize_index": 2,
                "in_lanesize_index": 2,
                "out_lanesize_index": 2,
                "in_precision_index": 3,
                "out_precision_index": 3,
                "arg_permute_map": [0, 1, -1, -1],
                "Signedness": 0,
                "Cost": "None",
                "SIMD": "True",
                "Extensions": "[]",
            },
            "sub_v32acc32": {
                "args": ["SYMBOLIC_BV_1024", "SYMBOLIC_BV_1024", "32", "32"],
                "in_vectsize": 1024,
                "out_vectsize": 1024,
                "lanesize": 32,
                "in_precision": 32,
                "out_precision": 32,
                "in_vectsize_index": 2,
                "out_vectsize_index": 2,
                "in_lanesize_index": 2,
                "out_lanesize_index": 2,
                "in_precision_index": 3,
                "out_precision_index": 3,
                "arg_permute_map": [0, 1, -1, -1],
                "Signedness": 1,
                "Cost": "None",
                "SIMD": "True",
                "Extensions": "[]",
            },
            "sub_v32int16": {
                "args": ["SYMBOLIC_BV_512", "SYMBOLIC_BV_512", "32", "16"],
                "in_vectsize": 512,
                "out_vectsize": 512,
                "lanesize": 32,
                "in_precision": 16,
                "out_precision": 16,
                "in_vectsize_index": 2,
                "out_vectsize_index": 2,
                "in_lanesize_index": 2,
                "out_lanesize_index": 2,
                "in_precision_index": 3,
                "out_precision_index": 3,
                "arg_permute_map": [0, 1, -1, -1],
                "Signedness": 1,
                "Cost": "None",
                "SIMD": "True",
                "Extensions": "[]",
            },
            "sub_v32uint16": {
                "args": ["SYMBOLIC_BV_512", "SYMBOLIC_BV_512", "32", "16"],
                "in_vectsize": 512,
                "out_vectsize": 512,
                "lanesize": 32,
                "in_precision": 16,
                "out_precision": 16,
                "in_vectsize_index": 2,
                "out_vectsize_index": 2,
                "in_lanesize_index": 2,
                "out_lanesize_index": 2,
                "in_precision_index": 3,
                "out_precision_index": 3,
                "arg_permute_map": [0, 1, -1, -1],
                "Signedness": 0,
                "Cost": "None",
                "SIMD": "True",
                "Extensions": "[]",
            },
            "sub_v64int8": {
                "args": ["SYMBOLIC_BV_512", "SYMBOLIC_BV_512", "64", "8"],
                "in_vectsize": 512,
                "out_vectsize": 512,
                "lanesize": 64,
                "in_precision": 8,
                "out_precision": 8,
                "in_vectsize_index": 2,
                "out_vectsize_index": 2,
                "in_lanesize_index": 2,
                "out_lanesize_index": 2,
                "in_precision_index": 3,
                "out_precision_index": 3,
                "arg_permute_map": [0, 1, -1, -1],
                "Signedness": 1,
                "Cost": "None",
                "SIMD": "True",
                "Extensions": "[]",
            },
            "sub_v64uint8": {
                "args": ["SYMBOLIC_BV_512", "SYMBOLIC_BV_512", "64", "8"],
                "in_vectsize": 512,
                "out_vectsize": 512,
                "lanesize": 64,
                "in_precision": 8,
                "out_precision": 8,
                "in_vectsize_index": 2,
                "out_vectsize_index": 2,
                "in_lanesize_index": 2,
                "out_lanesize_index": 2,
                "in_precision_index": 3,
                "out_precision_index": 3,
                "arg_permute_map": [0, 1, -1, -1],
                "Signedness": 0,
                "Cost": "None",
                "SIMD": "True",
                "Extensions": "[]",
            },
        },
        "semantics": [
            '"(define (sub_v16acc64 arg0 arg1 %lanesize %datasize)"',
            '"(define dst"',
            '"(apply concat"',
            '"(for/list ([%i (range 0 %lanesize 1)])"',
            '"(define %low1 (* %datasize %i))"',
            '"(define %high1 (+ %low1 (- %datasize 1)))"',
            '"(define %ext_xbuff (extract %high1 %low1 arg0))"',
            '"(define %low2 (* %datasize %i))"',
            '"(define %high2 (+ %low2 (- %datasize 1)))"',
            '"(define %ext_ybuff (extract %high2 %low2 arg1))"',
            '"(define %o (bvsub %ext_xbuff %ext_ybuff))"',
            '"%o"',
            '")"',
            '")"',
            '")"',
            '"dst"',
            '")"',
        ],
    },
}
