# ============================== Hydride File =================================
# Part of the Hydride Compiler Infrastructure.
# ============================== Hydride File =================================
aie_sema = {
	"aieml-eltwiseadd"  : { 
    "target_instructions" : {		
  	"add_v16acc64" : {
   	 "args": ["SYMBOLIC_BV_1024", "SYMBOLIC_BV_1024", "16", "64"],
                "in_vectsize": 1024,
                "out_vectsize": 1024,
                "lanesize": 16,
                "in_precision": 64,
                "out_precision": 64,
                "in_vectsize_index": None,
                "out_vectsize_index": None,
                "in_lanesize_index": None,
                "out_lanesize_index": None,
                "in_precision_index": None,
                "out_precision_index": None,
                "arg_permute_map": [0, 1, -1, -1],
                "Signedness": 1,
                "Cost": "None",
                "SIMD": "True",
                "Extensions": "[]",
  },		
  	"add_v16int32" : {
   	 "args": ["SYMBOLIC_BV_512", "SYMBOLIC_BV_512", "16", "32"],
                "in_vectsize": 512,
                "out_vectsize": 512,
                "lanesize": 16,
                "in_precision": 32,
                "out_precision": 32,
                "in_vectsize_index": None,
                "out_vectsize_index": None,
                "in_lanesize_index": None,
                "out_lanesize_index": None,
                "in_precision_index": None,
                "out_precision_index": None,
                "arg_permute_map": [0, 1, -1, -1],
                "Signedness": 1,
                "Cost": "None",
                "SIMD": "True",
                "Extensions": "[]",
  },		
  	"add_v16uint32" : {
   	 "args": ["SYMBOLIC_BV_512", "SYMBOLIC_BV_512", "16", "32"],
                "in_vectsize": 512,
                "out_vectsize": 512,
                "lanesize": 16,
                "in_precision": 32,
                "out_precision": 32,
                "in_vectsize_index": None,
                "out_vectsize_index": None,
                "in_lanesize_index": None,
                "out_lanesize_index": None,
                "in_precision_index": None,
                "out_precision_index": None,
                "arg_permute_map": [0, 1, -1, -1],
                "Signedness": 0,
                "Cost": "None",
                "SIMD": "True",
                "Extensions": "[]",
  },		
  	"add_v32acc32" : {
   	 "args": ["SYMBOLIC_BV_1024", "SYMBOLIC_BV_1024", "32", "32"],
                "in_vectsize": 1024,
                "out_vectsize": 1024,
                "lanesize": 32,
                "in_precision": 32,
                "out_precision": 32,
                "in_vectsize_index": None,
                "out_vectsize_index": None,
                "in_lanesize_index": None,
                "out_lanesize_index": None,
                "in_precision_index": None,
                "out_precision_index": None,
                "arg_permute_map": [0, 1, -1, -1],
                "Signedness": 1,
                "Cost": "None",
                "SIMD": "True",
                "Extensions": "[]",
  },		
  	"add_v32int16" : {
   	 "args": ["SYMBOLIC_BV_512", "SYMBOLIC_BV_512", "32", "16"],
                "in_vectsize": 512,
                "out_vectsize": 512,
                "lanesize": 32,
                "in_precision": 16,
                "out_precision": 16,
                "in_vectsize_index": None,
                "out_vectsize_index": None,
                "in_lanesize_index": None,
                "out_lanesize_index": None,
                "in_precision_index": None,
                "out_precision_index": None,
                "arg_permute_map": [0, 1, -1, -1],
                "Signedness": 1,
                "Cost": "None",
                "SIMD": "True",
                "Extensions": "[]",
  },		
  	"add_v32uint16" : {
   	 "args": ["SYMBOLIC_BV_512", "SYMBOLIC_BV_512", "32", "16"],
                "in_vectsize": 512,
                "out_vectsize": 512,
                "lanesize": 32,
                "in_precision": 16,
                "out_precision": 16,
                "in_vectsize_index": None,
                "out_vectsize_index": None,
                "in_lanesize_index": None,
                "out_lanesize_index": None,
                "in_precision_index": None,
                "out_precision_index": None,
                "arg_permute_map": [0, 1, -1, -1],
                "Signedness": 0,
                "Cost": "None",
                "SIMD": "True",
                "Extensions": "[]",
  },		
  	"add_v64int8" : {
   	 "args": ["SYMBOLIC_BV_512", "SYMBOLIC_BV_512", "64", "8"],
                "in_vectsize": 512,
                "out_vectsize": 512,
                "lanesize": 64,
                "in_precision": 8,
                "out_precision": 8,
                "in_vectsize_index": None,
                "out_vectsize_index": None,
                "in_lanesize_index": None,
                "out_lanesize_index": None,
                "in_precision_index": None,
                "out_precision_index": None,
                "arg_permute_map": [0, 1, -1, -1],
                "Signedness": 1,
                "Cost": "None",
                "SIMD": "True",
                "Extensions": "[]",
  },		
  	"add_v64uint8" : {
   	 "args": ["SYMBOLIC_BV_512", "SYMBOLIC_BV_512", "64", "8"],
                "in_vectsize": 512,
                "out_vectsize": 512,
                "lanesize": 64,
                "in_precision": 8,
                "out_precision": 8,
                "in_vectsize_index": None,
                "out_vectsize_index": None,
                "in_lanesize_index": None,
                "out_lanesize_index": None,
                "in_precision_index": None,
                "out_precision_index": None,
                "arg_permute_map": [0, 1, -1, -1],
                "Signedness": 0,
                "Cost": "None",
                "SIMD": "True",
                "Extensions": "[]",
  },
}, "semantics": [
        '"(define aieml-eltwiseadd ( arg0 arg1 %lanesize %datasize)"',
        '"(define dst"',
        '"(apply concat"',
        '"(for/list ([%i (range 0 %lanesize 1)])"',
        '"(define %low1 (* %datasize %i))"',
        '"(define %high1 (+ %low1 (- %datasize 1)))"',
        '"(define %ext_xbuff (extract %high1 %low1 arg0))"',
        '"(define %low2 (* %datasize %i))"',
        '"(define %high2 (+ %low2 (- %datasize 1)))"',
        '"(define %ext_ybuff (extract %high2 %low2 arg1))"',
        '"(define %o (bvadd %ext_xbuff %ext_ybuff))"',
        '"%o"',
        '")"',
        '")"',
        '")"',
        '"dst"',
        '")"',
    ]
}
}