
# This class is responsible for tracking all the 
# information that is generated by the legalizer generator.

class LegalizerInfo:
  # Map target instructions to the semantics
  inst_to_sema_map = dict()

  # List of the unique semantics 
  unique_sema_list = list()

  # Map DSL instructions to target instructions
  dsl_to_insts_map = dict()

  # Map Tensor DSL instruction to its corresponding intrinsic
  dsl_to_intrinsic_map = dict()

  # Map intrinsics to the target isntructions
  intrinsic_to_inst_map = dict()
