;#============================== Hydride File =================================
;#
;# Part of the Hydride Compiler Infrastructure.
;# <Placeholder for license information>
;#
;#=============================================================================
;#
;# Do NOT modify this file. It is automatically generated.
;#
;#=============================================================================

#lang rosette
(require rosette/lib/synthax)
(require rosette/lib/angelic)
(require racket/pretty)
(require rosette/lib/destruct)
(require rosette/solver/smt/boolector)

(require hydride/utils/bvops)
(require hydride/utils/misc)


(require hydride/ir/hydride/definition)

(require hydride/ir/arm/semantics)
(require hydride/ir/arm/definition)
(require hydride/ir/arm/length)


(provide (all-defined-out))
;; ================================================================================
;;                                DSL Binder
;; ================================================================================
(define (arm:bind-expr prog env)
 (destruct prog
	[(dim-x id) (dim-x id)]
	[(dim-y id) (dim-y id)]
	[(idx-i id) (idx-i id)]
	[(idx-j id) (idx-j id)]
	[(reg id) (vector-ref-bv env id)]
	[(lit v) (lit v)]
	[(idx-add i1 i2) (idx-add i1 i2)]
	[(idx-mul i1 i2) (idx-mul i1 i2)]
	[ (vector-two-input-swizzle_dsl v0 v1 num_2 prec_i_o num_4 num_5 num_6 num_7 num_8)
		(vector-two-input-swizzle_dsl (arm:bind-expr v0 env) (arm:bind-expr v1 env) (arm:bind-expr num_2 env) 
		 (arm:bind-expr prec_i_o env) (arm:bind-expr num_4 env) (arm:bind-expr num_5 env) 
		 (arm:bind-expr num_6 env) (arm:bind-expr num_7 env) (arm:bind-expr num_8 env))
	]
	[ (interleave-vectors_dsl v0 v1 size_i_o prec_i_o)
		(interleave-vectors_dsl (arm:bind-expr v0 env) (arm:bind-expr v1 env) (arm:bind-expr size_i_o env) 
		 (arm:bind-expr prec_i_o env))
	]
	[ (interleave-vector_dsl v0 size_i_o prec_i_o)
		(interleave-vector_dsl (arm:bind-expr v0 env) (arm:bind-expr size_i_o env) (arm:bind-expr prec_i_o env))
	]
	[ (deinterleave-vector_dsl v0 size_i_o prec_i_o)
		(deinterleave-vector_dsl (arm:bind-expr v0 env) (arm:bind-expr size_i_o env) (arm:bind-expr prec_i_o env))
	]
	[ (llvm_shuffle_vectors_dsl v0 v1 num_2 prec_i_o v4 num_5)
		(llvm_shuffle_vectors_dsl (arm:bind-expr v0 env) (arm:bind-expr v1 env) (arm:bind-expr num_2 env) 
		 (arm:bind-expr prec_i_o env) (arm:bind-expr v4 env) (arm:bind-expr num_5 env))
	]
	[ (llvm-vect-add_dsl v0 v1 num_2 prec_i_o)
		(llvm-vect-add_dsl (arm:bind-expr v0 env) (arm:bind-expr v1 env) (arm:bind-expr num_2 env) 
		 (arm:bind-expr prec_i_o env))
	]
	[ (llvm-vect-sub_dsl v0 v1 num_2 prec_i_o)
		(llvm-vect-sub_dsl (arm:bind-expr v0 env) (arm:bind-expr v1 env) (arm:bind-expr num_2 env) 
		 (arm:bind-expr prec_i_o env))
	]
	[ (llvm-vect-mul_dsl v0 v1 num_2 prec_i_o)
		(llvm-vect-mul_dsl (arm:bind-expr v0 env) (arm:bind-expr v1 env) (arm:bind-expr num_2 env) 
		 (arm:bind-expr prec_i_o env))
	]
	[ (llvm-vect-sdiv_dsl v0 v1 num_2 prec_i_o)
		(llvm-vect-sdiv_dsl (arm:bind-expr v0 env) (arm:bind-expr v1 env) (arm:bind-expr num_2 env) 
		 (arm:bind-expr prec_i_o env))
	]
	[ (llvm-vect-udiv_dsl v0 v1 num_2 prec_i_o)
		(llvm-vect-udiv_dsl (arm:bind-expr v0 env) (arm:bind-expr v1 env) (arm:bind-expr num_2 env) 
		 (arm:bind-expr prec_i_o env))
	]
	[ (llvm-zext_dsl v0 size_i size_o)
		(llvm-zext_dsl (arm:bind-expr v0 env) (arm:bind-expr size_i env) (arm:bind-expr size_o env))
	]
	[ (scalar_splat_dsl v0 size_i size_o)
		(scalar_splat_dsl (arm:bind-expr v0 env) (arm:bind-expr size_i env) (arm:bind-expr size_o env))
	]
	[ (vpmin_u32_dsl v0 v1 size_i_o num_3 num_4 num_5 prec_o num_7 num_8 num_9 num_10 num_11 num_12 prec_i num_14)
		(vpmin_u32_dsl (arm:bind-expr v0 env) (arm:bind-expr v1 env) (arm:bind-expr size_i_o env) 
		 (arm:bind-expr num_3 env) (arm:bind-expr num_4 env) (arm:bind-expr num_5 env) 
		 (arm:bind-expr prec_o env) (arm:bind-expr num_7 env) (arm:bind-expr num_8 env) 
		 (arm:bind-expr num_9 env) (arm:bind-expr num_10 env) (arm:bind-expr num_11 env) 
		 (arm:bind-expr num_12 env) (arm:bind-expr prec_i env) (arm:bind-expr num_14 env))
	]
	[ (vqdmulhq_n_s32_dsl vc_0 v1 v2 size_i_o num_4 num_5 num_6 prec_i_o num_8 num_9 num_10 num_11)
		(vqdmulhq_n_s32_dsl (arm:bind-expr vc_0 env) (arm:bind-expr v1 env) (arm:bind-expr v2 env) 
		 (arm:bind-expr size_i_o env) (arm:bind-expr num_4 env) (arm:bind-expr num_5 env) 
		 (arm:bind-expr num_6 env) (arm:bind-expr prec_i_o env) (arm:bind-expr num_8 env) 
		 (arm:bind-expr num_9 env) (arm:bind-expr num_10 env) (arm:bind-expr num_11 env))
	]
	[ (vrshrn_n_s64_dsl vc_0 vc_1 v2 v3 size_i_o num_5 num_6 num_7 prec_o num_9 num_10 num_11 num_12 num_13 num_14 prec_i num_16)
		(vrshrn_n_s64_dsl (arm:bind-expr vc_0 env) (arm:bind-expr vc_1 env) (arm:bind-expr v2 env) 
		 (arm:bind-expr v3 env) (arm:bind-expr size_i_o env) (arm:bind-expr num_5 env) 
		 (arm:bind-expr num_6 env) (arm:bind-expr num_7 env) (arm:bind-expr prec_o env) 
		 (arm:bind-expr num_9 env) (arm:bind-expr num_10 env) (arm:bind-expr num_11 env) 
		 (arm:bind-expr num_12 env) (arm:bind-expr num_13 env) (arm:bind-expr num_14 env) 
		 (arm:bind-expr prec_i env) (arm:bind-expr num_16 env))
	]
	[ (vpaddq_u8_dsl vc_0 v1 v2 size_i prec_i_o num_5 num_6 num_7 num_8 num_9 num_10 num_11)
		(vpaddq_u8_dsl (arm:bind-expr vc_0 env) (arm:bind-expr v1 env) (arm:bind-expr v2 env) 
		 (arm:bind-expr size_i env) (arm:bind-expr prec_i_o env) (arm:bind-expr num_5 env) 
		 (arm:bind-expr num_6 env) (arm:bind-expr num_7 env) (arm:bind-expr num_8 env) 
		 (arm:bind-expr num_9 env) (arm:bind-expr num_10 env) (arm:bind-expr num_11 env))
	]
	[ (vqdmlsl_n_s32_dsl vc_0 v1 v2 v3 size_i_o num_5 num_6 num_7 prec_i num_9 num_10 prec_o num_12 num_13 num_14)
		(vqdmlsl_n_s32_dsl (arm:bind-expr vc_0 env) (arm:bind-expr v1 env) (arm:bind-expr v2 env) 
		 (arm:bind-expr v3 env) (arm:bind-expr size_i_o env) (arm:bind-expr num_5 env) 
		 (arm:bind-expr num_6 env) (arm:bind-expr num_7 env) (arm:bind-expr prec_i env) 
		 (arm:bind-expr num_9 env) (arm:bind-expr num_10 env) (arm:bind-expr prec_o env) 
		 (arm:bind-expr num_12 env) (arm:bind-expr num_13 env) (arm:bind-expr num_14 env))
	]
	[ (vqdmlal_high_s16_dsl vc_0 v1 v2 v3 size_i_o num_5 num_6 num_7 prec_i_o num_9 num_10 num_11 num_12 num_13)
		(vqdmlal_high_s16_dsl (arm:bind-expr vc_0 env) (arm:bind-expr v1 env) (arm:bind-expr v2 env) 
		 (arm:bind-expr v3 env) (arm:bind-expr size_i_o env) (arm:bind-expr num_5 env) 
		 (arm:bind-expr num_6 env) (arm:bind-expr num_7 env) (arm:bind-expr prec_i_o env) 
		 (arm:bind-expr num_9 env) (arm:bind-expr num_10 env) (arm:bind-expr num_11 env) 
		 (arm:bind-expr num_12 env) (arm:bind-expr num_13 env))
	]
	[ (vget_high_u64_dsl v0 size_i_o num_2 num_3 num_4 prec_i_o num_6 num_7)
		(vget_high_u64_dsl (arm:bind-expr v0 env) (arm:bind-expr size_i_o env) (arm:bind-expr num_2 env) 
		 (arm:bind-expr num_3 env) (arm:bind-expr num_4 env) (arm:bind-expr prec_i_o env) 
		 (arm:bind-expr num_6 env) (arm:bind-expr num_7 env))
	]
	[ (vabal_high_u32_dsl v0 v1 v2 size_i_o num_4 num_5 num_6 prec_i_o num_8 num_9 num_10 num_11 num_12 num_13 num_14 num_15 num_16)
		(vabal_high_u32_dsl (arm:bind-expr v0 env) (arm:bind-expr v1 env) (arm:bind-expr v2 env) 
		 (arm:bind-expr size_i_o env) (arm:bind-expr num_4 env) (arm:bind-expr num_5 env) 
		 (arm:bind-expr num_6 env) (arm:bind-expr prec_i_o env) (arm:bind-expr num_8 env) 
		 (arm:bind-expr num_9 env) (arm:bind-expr num_10 env) (arm:bind-expr num_11 env) 
		 (arm:bind-expr num_12 env) (arm:bind-expr num_13 env) (arm:bind-expr num_14 env) 
		 (arm:bind-expr num_15 env) (arm:bind-expr num_16 env))
	]
	[ (vqdmull_s16_dsl vc_0 v1 v2 size_i_o num_4 num_5 num_6 prec_i prec_o num_9 num_10 num_11)
		(vqdmull_s16_dsl (arm:bind-expr vc_0 env) (arm:bind-expr v1 env) (arm:bind-expr v2 env) 
		 (arm:bind-expr size_i_o env) (arm:bind-expr num_4 env) (arm:bind-expr num_5 env) 
		 (arm:bind-expr num_6 env) (arm:bind-expr prec_i env) (arm:bind-expr prec_o env) 
		 (arm:bind-expr num_9 env) (arm:bind-expr num_10 env) (arm:bind-expr num_11 env))
	]
	[ (vqrshrnd_n_u64_dsl vc_0 vc_1 v2 v3 size_i_o num_5 num_6 num_7 prec_o num_9 num_10 num_11 num_12 num_13 num_14 prec_i num_16)
		(vqrshrnd_n_u64_dsl (arm:bind-expr vc_0 env) (arm:bind-expr vc_1 env) (arm:bind-expr v2 env) 
		 (arm:bind-expr v3 env) (arm:bind-expr size_i_o env) (arm:bind-expr num_5 env) 
		 (arm:bind-expr num_6 env) (arm:bind-expr num_7 env) (arm:bind-expr prec_o env) 
		 (arm:bind-expr num_9 env) (arm:bind-expr num_10 env) (arm:bind-expr num_11 env) 
		 (arm:bind-expr num_12 env) (arm:bind-expr num_13 env) (arm:bind-expr num_14 env) 
		 (arm:bind-expr prec_i env) (arm:bind-expr num_16 env))
	]
	[ (vqmovn_u64_dsl v0 size_i_o num_2 num_3 num_4 prec_o num_6 num_7 num_8 prec_i num_10)
		(vqmovn_u64_dsl (arm:bind-expr v0 env) (arm:bind-expr size_i_o env) (arm:bind-expr num_2 env) 
		 (arm:bind-expr num_3 env) (arm:bind-expr num_4 env) (arm:bind-expr prec_o env) 
		 (arm:bind-expr num_6 env) (arm:bind-expr num_7 env) (arm:bind-expr num_8 env) 
		 (arm:bind-expr prec_i env) (arm:bind-expr num_10 env))
	]
	[ (vqneg_s32_dsl v0 size_i_o num_2 num_3 num_4 prec_i_o num_6 num_7 num_8)
		(vqneg_s32_dsl (arm:bind-expr v0 env) (arm:bind-expr size_i_o env) (arm:bind-expr num_2 env) 
		 (arm:bind-expr num_3 env) (arm:bind-expr num_4 env) (arm:bind-expr prec_i_o env) 
		 (arm:bind-expr num_6 env) (arm:bind-expr num_7 env) (arm:bind-expr num_8 env))
	]
	[ (vqdmlsl_s32_dsl vc_0 v1 v2 v3 size_i_o num_5 num_6 num_7 prec_i prec_o num_10 num_11 num_12 num_13)
		(vqdmlsl_s32_dsl (arm:bind-expr vc_0 env) (arm:bind-expr v1 env) (arm:bind-expr v2 env) 
		 (arm:bind-expr v3 env) (arm:bind-expr size_i_o env) (arm:bind-expr num_5 env) 
		 (arm:bind-expr num_6 env) (arm:bind-expr num_7 env) (arm:bind-expr prec_i env) 
		 (arm:bind-expr prec_o env) (arm:bind-expr num_10 env) (arm:bind-expr num_11 env) 
		 (arm:bind-expr num_12 env) (arm:bind-expr num_13 env))
	]
	[ (vaba_u8_dsl v0 v1 v2 size_i_o num_4 num_5 num_6 prec_i_o num_8 num_9 num_10 num_11 num_12 num_13 num_14)
		(vaba_u8_dsl (arm:bind-expr v0 env) (arm:bind-expr v1 env) (arm:bind-expr v2 env) 
		 (arm:bind-expr size_i_o env) (arm:bind-expr num_4 env) (arm:bind-expr num_5 env) 
		 (arm:bind-expr num_6 env) (arm:bind-expr prec_i_o env) (arm:bind-expr num_8 env) 
		 (arm:bind-expr num_9 env) (arm:bind-expr num_10 env) (arm:bind-expr num_11 env) 
		 (arm:bind-expr num_12 env) (arm:bind-expr num_13 env) (arm:bind-expr num_14 env))
	]
	[ (vmlal_n_u32_dsl v0 v1 v2 size_i_o num_4 num_5 num_6 prec_i num_8 num_9 prec_o num_11 num_12 num_13 num_14)
		(vmlal_n_u32_dsl (arm:bind-expr v0 env) (arm:bind-expr v1 env) (arm:bind-expr v2 env) 
		 (arm:bind-expr size_i_o env) (arm:bind-expr num_4 env) (arm:bind-expr num_5 env) 
		 (arm:bind-expr num_6 env) (arm:bind-expr prec_i env) (arm:bind-expr num_8 env) 
		 (arm:bind-expr num_9 env) (arm:bind-expr prec_o env) (arm:bind-expr num_11 env) 
		 (arm:bind-expr num_12 env) (arm:bind-expr num_13 env) (arm:bind-expr num_14 env))
	]
	[ (vpadalq_u8_dsl v0 v1 size_i_o num_3 num_4 num_5 prec_i prec_o num_8 num_9 num_10 num_11 num_12 num_13 num_14 num_15 num_16 num_17 num_18)
		(vpadalq_u8_dsl (arm:bind-expr v0 env) (arm:bind-expr v1 env) (arm:bind-expr size_i_o env) 
		 (arm:bind-expr num_3 env) (arm:bind-expr num_4 env) (arm:bind-expr num_5 env) 
		 (arm:bind-expr prec_i env) (arm:bind-expr prec_o env) (arm:bind-expr num_8 env) 
		 (arm:bind-expr num_9 env) (arm:bind-expr num_10 env) (arm:bind-expr num_11 env) 
		 (arm:bind-expr num_12 env) (arm:bind-expr num_13 env) (arm:bind-expr num_14 env) 
		 (arm:bind-expr num_15 env) (arm:bind-expr num_16 env) (arm:bind-expr num_17 env) 
		 (arm:bind-expr num_18 env))
	]
	[ (vtrn2_s8_dsl v0 v1 size_i_o num_3 num_4 num_5 prec_i_o num_7 num_8 num_9 num_10)
		(vtrn2_s8_dsl (arm:bind-expr v0 env) (arm:bind-expr v1 env) (arm:bind-expr size_i_o env) 
		 (arm:bind-expr num_3 env) (arm:bind-expr num_4 env) (arm:bind-expr num_5 env) 
		 (arm:bind-expr prec_i_o env) (arm:bind-expr num_7 env) (arm:bind-expr num_8 env) 
		 (arm:bind-expr num_9 env) (arm:bind-expr num_10 env))
	]
	[ (vmull_n_s32_dsl v0 v1 size_i_o num_3 num_4 num_5 prec_i num_7 num_8 prec_o num_10 num_11 num_12)
		(vmull_n_s32_dsl (arm:bind-expr v0 env) (arm:bind-expr v1 env) (arm:bind-expr size_i_o env) 
		 (arm:bind-expr num_3 env) (arm:bind-expr num_4 env) (arm:bind-expr num_5 env) 
		 (arm:bind-expr prec_i env) (arm:bind-expr num_7 env) (arm:bind-expr num_8 env) 
		 (arm:bind-expr prec_o env) (arm:bind-expr num_10 env) (arm:bind-expr num_11 env) 
		 (arm:bind-expr num_12 env))
	]
	[ (vqshlq_s32_dsl v0 v1 size_i_o num_3 num_4 num_5 prec_i_o num_7 num_8 num_9 num_10)
		(vqshlq_s32_dsl (arm:bind-expr v0 env) (arm:bind-expr v1 env) (arm:bind-expr size_i_o env) 
		 (arm:bind-expr num_3 env) (arm:bind-expr num_4 env) (arm:bind-expr num_5 env) 
		 (arm:bind-expr prec_i_o env) (arm:bind-expr num_7 env) (arm:bind-expr num_8 env) 
		 (arm:bind-expr num_9 env) (arm:bind-expr num_10 env))
	]
	[ (vqabsq_s64_dsl v0 size_i_o num_2 num_3 num_4 prec_i_o num_6 num_7 num_8)
		(vqabsq_s64_dsl (arm:bind-expr v0 env) (arm:bind-expr size_i_o env) (arm:bind-expr num_2 env) 
		 (arm:bind-expr num_3 env) (arm:bind-expr num_4 env) (arm:bind-expr prec_i_o env) 
		 (arm:bind-expr num_6 env) (arm:bind-expr num_7 env) (arm:bind-expr num_8 env))
	]
	[ (vmlsl_high_n_s32_dsl v0 v1 v2 size_i_o num_4 num_5 num_6 prec_i_o num_8 num_9 num_10 num_11 num_12 num_13 num_14)
		(vmlsl_high_n_s32_dsl (arm:bind-expr v0 env) (arm:bind-expr v1 env) (arm:bind-expr v2 env) 
		 (arm:bind-expr size_i_o env) (arm:bind-expr num_4 env) (arm:bind-expr num_5 env) 
		 (arm:bind-expr num_6 env) (arm:bind-expr prec_i_o env) (arm:bind-expr num_8 env) 
		 (arm:bind-expr num_9 env) (arm:bind-expr num_10 env) (arm:bind-expr num_11 env) 
		 (arm:bind-expr num_12 env) (arm:bind-expr num_13 env) (arm:bind-expr num_14 env))
	]
	[ (vclez_s8_dsl vc_0 vc_1 vc_2 v3 size_i_o num_5 num_6 num_7 prec_i_o num_9)
		(vclez_s8_dsl (arm:bind-expr vc_0 env) (arm:bind-expr vc_1 env) (arm:bind-expr vc_2 env) 
		 (arm:bind-expr v3 env) (arm:bind-expr size_i_o env) (arm:bind-expr num_5 env) 
		 (arm:bind-expr num_6 env) (arm:bind-expr num_7 env) (arm:bind-expr prec_i_o env) 
		 (arm:bind-expr num_9 env))
	]
	[ (vqdmull_n_s16_dsl vc_0 v1 v2 size_i_o num_4 num_5 num_6 prec_i num_8 num_9 prec_o num_11 num_12)
		(vqdmull_n_s16_dsl (arm:bind-expr vc_0 env) (arm:bind-expr v1 env) (arm:bind-expr v2 env) 
		 (arm:bind-expr size_i_o env) (arm:bind-expr num_4 env) (arm:bind-expr num_5 env) 
		 (arm:bind-expr num_6 env) (arm:bind-expr prec_i env) (arm:bind-expr num_8 env) 
		 (arm:bind-expr num_9 env) (arm:bind-expr prec_o env) (arm:bind-expr num_11 env) 
		 (arm:bind-expr num_12 env))
	]
	[ (vsubhn_u32_dsl v0 v1 size_i_o num_3 num_4 num_5 prec_o num_7 num_8 prec_i num_10)
		(vsubhn_u32_dsl (arm:bind-expr v0 env) (arm:bind-expr v1 env) (arm:bind-expr size_i_o env) 
		 (arm:bind-expr num_3 env) (arm:bind-expr num_4 env) (arm:bind-expr num_5 env) 
		 (arm:bind-expr prec_o env) (arm:bind-expr num_7 env) (arm:bind-expr num_8 env) 
		 (arm:bind-expr prec_i env) (arm:bind-expr num_10 env))
	]
	[ (vmla_n_u32_dsl v0 v1 v2 size_i_o num_4 num_5 num_6 prec_i_o num_8 num_9 num_10 num_11 num_12)
		(vmla_n_u32_dsl (arm:bind-expr v0 env) (arm:bind-expr v1 env) (arm:bind-expr v2 env) 
		 (arm:bind-expr size_i_o env) (arm:bind-expr num_4 env) (arm:bind-expr num_5 env) 
		 (arm:bind-expr num_6 env) (arm:bind-expr prec_i_o env) (arm:bind-expr num_8 env) 
		 (arm:bind-expr num_9 env) (arm:bind-expr num_10 env) (arm:bind-expr num_11 env) 
		 (arm:bind-expr num_12 env))
	]
	[ (vmls_n_s16_dsl v0 v1 v2 size_i_o num_4 num_5 num_6 prec_i_o num_8 num_9 num_10 num_11 num_12)
		(vmls_n_s16_dsl (arm:bind-expr v0 env) (arm:bind-expr v1 env) (arm:bind-expr v2 env) 
		 (arm:bind-expr size_i_o env) (arm:bind-expr num_4 env) (arm:bind-expr num_5 env) 
		 (arm:bind-expr num_6 env) (arm:bind-expr prec_i_o env) (arm:bind-expr num_8 env) 
		 (arm:bind-expr num_9 env) (arm:bind-expr num_10 env) (arm:bind-expr num_11 env) 
		 (arm:bind-expr num_12 env))
	]
	[ (vmlsl_n_s32_dsl v0 v1 v2 size_i_o num_4 num_5 num_6 prec_i num_8 num_9 prec_o num_11 num_12 num_13 num_14)
		(vmlsl_n_s32_dsl (arm:bind-expr v0 env) (arm:bind-expr v1 env) (arm:bind-expr v2 env) 
		 (arm:bind-expr size_i_o env) (arm:bind-expr num_4 env) (arm:bind-expr num_5 env) 
		 (arm:bind-expr num_6 env) (arm:bind-expr prec_i env) (arm:bind-expr num_8 env) 
		 (arm:bind-expr num_9 env) (arm:bind-expr prec_o env) (arm:bind-expr num_11 env) 
		 (arm:bind-expr num_12 env) (arm:bind-expr num_13 env) (arm:bind-expr num_14 env))
	]
	[ (vmlsq_n_u32_dsl v0 v1 v2 size_i_o num_4 num_5 num_6 prec_i_o num_8 num_9 num_10 num_11 num_12)
		(vmlsq_n_u32_dsl (arm:bind-expr v0 env) (arm:bind-expr v1 env) (arm:bind-expr v2 env) 
		 (arm:bind-expr size_i_o env) (arm:bind-expr num_4 env) (arm:bind-expr num_5 env) 
		 (arm:bind-expr num_6 env) (arm:bind-expr prec_i_o env) (arm:bind-expr num_8 env) 
		 (arm:bind-expr num_9 env) (arm:bind-expr num_10 env) (arm:bind-expr num_11 env) 
		 (arm:bind-expr num_12 env))
	]
	[ (vqdmlal_n_s32_dsl vc_0 v1 v2 v3 size_i_o num_5 num_6 num_7 prec_i num_9 num_10 prec_o num_12 num_13 num_14)
		(vqdmlal_n_s32_dsl (arm:bind-expr vc_0 env) (arm:bind-expr v1 env) (arm:bind-expr v2 env) 
		 (arm:bind-expr v3 env) (arm:bind-expr size_i_o env) (arm:bind-expr num_5 env) 
		 (arm:bind-expr num_6 env) (arm:bind-expr num_7 env) (arm:bind-expr prec_i env) 
		 (arm:bind-expr num_9 env) (arm:bind-expr num_10 env) (arm:bind-expr prec_o env) 
		 (arm:bind-expr num_12 env) (arm:bind-expr num_13 env) (arm:bind-expr num_14 env))
	]
	[ (vaddw_u8_dsl v0 v1 size_i_o num_3 num_4 num_5 num_6 prec_i_o num_8 num_9 num_10 num_11 num_12 num_13 num_14)
		(vaddw_u8_dsl (arm:bind-expr v0 env) (arm:bind-expr v1 env) (arm:bind-expr size_i_o env) 
		 (arm:bind-expr num_3 env) (arm:bind-expr num_4 env) (arm:bind-expr num_5 env) 
		 (arm:bind-expr num_6 env) (arm:bind-expr prec_i_o env) (arm:bind-expr num_8 env) 
		 (arm:bind-expr num_9 env) (arm:bind-expr num_10 env) (arm:bind-expr num_11 env) 
		 (arm:bind-expr num_12 env) (arm:bind-expr num_13 env) (arm:bind-expr num_14 env))
	]
	[ (vrsra_n_u64_dsl vc_0 vc_1 v2 v3 v4 size_i_o num_6 num_7 num_8 prec_i_o num_10 num_11 num_12 num_13 num_14 num_15 num_16)
		(vrsra_n_u64_dsl (arm:bind-expr vc_0 env) (arm:bind-expr vc_1 env) (arm:bind-expr v2 env) 
		 (arm:bind-expr v3 env) (arm:bind-expr v4 env) (arm:bind-expr size_i_o env) 
		 (arm:bind-expr num_6 env) (arm:bind-expr num_7 env) (arm:bind-expr num_8 env) 
		 (arm:bind-expr prec_i_o env) (arm:bind-expr num_10 env) (arm:bind-expr num_11 env) 
		 (arm:bind-expr num_12 env) (arm:bind-expr num_13 env) (arm:bind-expr num_14 env) 
		 (arm:bind-expr num_15 env) (arm:bind-expr num_16 env))
	]
	[ (vqshrn_n_u32_dsl v0 v1 size_i_o num_3 num_4 num_5 prec_o num_7 num_8 num_9 prec_i num_11)
		(vqshrn_n_u32_dsl (arm:bind-expr v0 env) (arm:bind-expr v1 env) (arm:bind-expr size_i_o env) 
		 (arm:bind-expr num_3 env) (arm:bind-expr num_4 env) (arm:bind-expr num_5 env) 
		 (arm:bind-expr prec_o env) (arm:bind-expr num_7 env) (arm:bind-expr num_8 env) 
		 (arm:bind-expr num_9 env) (arm:bind-expr prec_i env) (arm:bind-expr num_11 env))
	]
	[ (vqshrnd_n_u64_dsl v0 v1 size_i_o num_3 num_4 num_5 prec_o num_7 prec_i num_9)
		(vqshrnd_n_u64_dsl (arm:bind-expr v0 env) (arm:bind-expr v1 env) (arm:bind-expr size_i_o env) 
		 (arm:bind-expr num_3 env) (arm:bind-expr num_4 env) (arm:bind-expr num_5 env) 
		 (arm:bind-expr prec_o env) (arm:bind-expr num_7 env) (arm:bind-expr prec_i env) 
		 (arm:bind-expr num_9 env))
	]
	[ (vshl_s8_dsl v0 v1 size_i_o num_3 num_4 num_5 prec_i_o num_7 num_8 num_9 num_10)
		(vshl_s8_dsl (arm:bind-expr v0 env) (arm:bind-expr v1 env) (arm:bind-expr size_i_o env) 
		 (arm:bind-expr num_3 env) (arm:bind-expr num_4 env) (arm:bind-expr num_5 env) 
		 (arm:bind-expr prec_i_o env) (arm:bind-expr num_7 env) (arm:bind-expr num_8 env) 
		 (arm:bind-expr num_9 env) (arm:bind-expr num_10 env))
	]
	[ (vpaddlq_s32_dsl vc_0 v1 size_i_o num_3 num_4 num_5 prec_i prec_o num_8 num_9 num_10 num_11 num_12 num_13 num_14 num_15 num_16 num_17 num_18)
		(vpaddlq_s32_dsl (arm:bind-expr vc_0 env) (arm:bind-expr v1 env) (arm:bind-expr size_i_o env) 
		 (arm:bind-expr num_3 env) (arm:bind-expr num_4 env) (arm:bind-expr num_5 env) 
		 (arm:bind-expr prec_i env) (arm:bind-expr prec_o env) (arm:bind-expr num_8 env) 
		 (arm:bind-expr num_9 env) (arm:bind-expr num_10 env) (arm:bind-expr num_11 env) 
		 (arm:bind-expr num_12 env) (arm:bind-expr num_13 env) (arm:bind-expr num_14 env) 
		 (arm:bind-expr num_15 env) (arm:bind-expr num_16 env) (arm:bind-expr num_17 env) 
		 (arm:bind-expr num_18 env))
	]
	[ (vshrn_n_s32_dsl v0 v1 size_i_o num_3 num_4 num_5 prec_o num_7 num_8 num_9 prec_i num_11)
		(vshrn_n_s32_dsl (arm:bind-expr v0 env) (arm:bind-expr v1 env) (arm:bind-expr size_i_o env) 
		 (arm:bind-expr num_3 env) (arm:bind-expr num_4 env) (arm:bind-expr num_5 env) 
		 (arm:bind-expr prec_o env) (arm:bind-expr num_7 env) (arm:bind-expr num_8 env) 
		 (arm:bind-expr num_9 env) (arm:bind-expr prec_i env) (arm:bind-expr num_11 env))
	]
	[ (vshrn_n_u64_dsl v0 v1 size_i_o num_3 num_4 num_5 prec_o num_7 prec_i num_9)
		(vshrn_n_u64_dsl (arm:bind-expr v0 env) (arm:bind-expr v1 env) (arm:bind-expr size_i_o env) 
		 (arm:bind-expr num_3 env) (arm:bind-expr num_4 env) (arm:bind-expr num_5 env) 
		 (arm:bind-expr prec_o env) (arm:bind-expr num_7 env) (arm:bind-expr prec_i env) 
		 (arm:bind-expr num_9 env))
	]
	[ (vqshrn_n_s16_dsl v0 v1 size_i_o num_3 num_4 num_5 prec_o num_7 num_8 num_9 prec_i num_11)
		(vqshrn_n_s16_dsl (arm:bind-expr v0 env) (arm:bind-expr v1 env) (arm:bind-expr size_i_o env) 
		 (arm:bind-expr num_3 env) (arm:bind-expr num_4 env) (arm:bind-expr num_5 env) 
		 (arm:bind-expr prec_o env) (arm:bind-expr num_7 env) (arm:bind-expr num_8 env) 
		 (arm:bind-expr num_9 env) (arm:bind-expr prec_i env) (arm:bind-expr num_11 env))
	]
	[ (vceqzq_s8_dsl vc_0 v1 vc_2 vc_3 size_i_o num_5 num_6 num_7 prec_i_o)
		(vceqzq_s8_dsl (arm:bind-expr vc_0 env) (arm:bind-expr v1 env) (arm:bind-expr vc_2 env) 
		 (arm:bind-expr vc_3 env) (arm:bind-expr size_i_o env) (arm:bind-expr num_5 env) 
		 (arm:bind-expr num_6 env) (arm:bind-expr num_7 env) (arm:bind-expr prec_i_o env))
	]
	[ (vmla_n_u16_dsl v0 v1 v2 size_i_o num_4 num_5 num_6 prec_i_o num_8 num_9 num_10 num_11 num_12)
		(vmla_n_u16_dsl (arm:bind-expr v0 env) (arm:bind-expr v1 env) (arm:bind-expr v2 env) 
		 (arm:bind-expr size_i_o env) (arm:bind-expr num_4 env) (arm:bind-expr num_5 env) 
		 (arm:bind-expr num_6 env) (arm:bind-expr prec_i_o env) (arm:bind-expr num_8 env) 
		 (arm:bind-expr num_9 env) (arm:bind-expr num_10 env) (arm:bind-expr num_11 env) 
		 (arm:bind-expr num_12 env))
	]
	[ (vqshlu_n_s64_dsl v0 v1 size_i_o num_3 num_4 num_5 prec_i_o num_7 num_8 num_9 num_10)
		(vqshlu_n_s64_dsl (arm:bind-expr v0 env) (arm:bind-expr v1 env) (arm:bind-expr size_i_o env) 
		 (arm:bind-expr num_3 env) (arm:bind-expr num_4 env) (arm:bind-expr num_5 env) 
		 (arm:bind-expr prec_i_o env) (arm:bind-expr num_7 env) (arm:bind-expr num_8 env) 
		 (arm:bind-expr num_9 env) (arm:bind-expr num_10 env))
	]
	[ (vabdl_high_u8_dsl vc_0 v1 v2 size_o num_4 num_5 num_6 prec_o num_8 num_9 num_10 num_11 num_12 num_13 num_14 num_15 num_16)
		(vabdl_high_u8_dsl (arm:bind-expr vc_0 env) (arm:bind-expr v1 env) (arm:bind-expr v2 env) 
		 (arm:bind-expr size_o env) (arm:bind-expr num_4 env) (arm:bind-expr num_5 env) 
		 (arm:bind-expr num_6 env) (arm:bind-expr prec_o env) (arm:bind-expr num_8 env) 
		 (arm:bind-expr num_9 env) (arm:bind-expr num_10 env) (arm:bind-expr num_11 env) 
		 (arm:bind-expr num_12 env) (arm:bind-expr num_13 env) (arm:bind-expr num_14 env) 
		 (arm:bind-expr num_15 env) (arm:bind-expr num_16 env))
	]
	[ (vmlal_high_n_u32_dsl v0 v1 v2 size_i_o num_4 num_5 num_6 prec_i_o num_8 num_9 num_10 num_11 num_12 num_13 num_14)
		(vmlal_high_n_u32_dsl (arm:bind-expr v0 env) (arm:bind-expr v1 env) (arm:bind-expr v2 env) 
		 (arm:bind-expr size_i_o env) (arm:bind-expr num_4 env) (arm:bind-expr num_5 env) 
		 (arm:bind-expr num_6 env) (arm:bind-expr prec_i_o env) (arm:bind-expr num_8 env) 
		 (arm:bind-expr num_9 env) (arm:bind-expr num_10 env) (arm:bind-expr num_11 env) 
		 (arm:bind-expr num_12 env) (arm:bind-expr num_13 env) (arm:bind-expr num_14 env))
	]
	[ (vmovn_s16_dsl v0 size_i_o num_2 num_3 num_4 prec_i_o num_6)
		(vmovn_s16_dsl (arm:bind-expr v0 env) (arm:bind-expr size_i_o env) (arm:bind-expr num_2 env) 
		 (arm:bind-expr num_3 env) (arm:bind-expr num_4 env) (arm:bind-expr prec_i_o env) 
		 (arm:bind-expr num_6 env))
	]
	[ (vqrdmulhq_n_s32_dsl vc_0 vc_1 v2 v3 size_i_o num_5 num_6 num_7 prec_i_o num_9 num_10 num_11 num_12 num_13 num_14 num_15)
		(vqrdmulhq_n_s32_dsl (arm:bind-expr vc_0 env) (arm:bind-expr vc_1 env) (arm:bind-expr v2 env) 
		 (arm:bind-expr v3 env) (arm:bind-expr size_i_o env) (arm:bind-expr num_5 env) 
		 (arm:bind-expr num_6 env) (arm:bind-expr num_7 env) (arm:bind-expr prec_i_o env) 
		 (arm:bind-expr num_9 env) (arm:bind-expr num_10 env) (arm:bind-expr num_11 env) 
		 (arm:bind-expr num_12 env) (arm:bind-expr num_13 env) (arm:bind-expr num_14 env) 
		 (arm:bind-expr num_15 env))
	]
	[ (vshll_n_s8_dsl v0 v1 size_i_o num_3 num_4 num_5 prec_i prec_o num_8 num_9 num_10 num_11)
		(vshll_n_s8_dsl (arm:bind-expr v0 env) (arm:bind-expr v1 env) (arm:bind-expr size_i_o env) 
		 (arm:bind-expr num_3 env) (arm:bind-expr num_4 env) (arm:bind-expr num_5 env) 
		 (arm:bind-expr prec_i env) (arm:bind-expr prec_o env) (arm:bind-expr num_8 env) 
		 (arm:bind-expr num_9 env) (arm:bind-expr num_10 env) (arm:bind-expr num_11 env))
	]
	[ (vaddhn_u32_dsl v0 v1 size_i_o num_3 num_4 num_5 prec_o num_7 num_8 prec_i num_10)
		(vaddhn_u32_dsl (arm:bind-expr v0 env) (arm:bind-expr v1 env) (arm:bind-expr size_i_o env) 
		 (arm:bind-expr num_3 env) (arm:bind-expr num_4 env) (arm:bind-expr num_5 env) 
		 (arm:bind-expr prec_o env) (arm:bind-expr num_7 env) (arm:bind-expr num_8 env) 
		 (arm:bind-expr prec_i env) (arm:bind-expr num_10 env))
	]
	[ (vqdmlal_high_n_s16_dsl vc_0 v1 v2 v3 size_i_o num_5 num_6 num_7 prec_i_o num_9 num_10 num_11 num_12 num_13 num_14)
		(vqdmlal_high_n_s16_dsl (arm:bind-expr vc_0 env) (arm:bind-expr v1 env) (arm:bind-expr v2 env) 
		 (arm:bind-expr v3 env) (arm:bind-expr size_i_o env) (arm:bind-expr num_5 env) 
		 (arm:bind-expr num_6 env) (arm:bind-expr num_7 env) (arm:bind-expr prec_i_o env) 
		 (arm:bind-expr num_9 env) (arm:bind-expr num_10 env) (arm:bind-expr num_11 env) 
		 (arm:bind-expr num_12 env) (arm:bind-expr num_13 env) (arm:bind-expr num_14 env))
	]
	[ (vmovl_s32_dsl v0 size_i_o num_2 num_3 num_4 prec_i prec_o num_7 num_8 num_9 num_10)
		(vmovl_s32_dsl (arm:bind-expr v0 env) (arm:bind-expr size_i_o env) (arm:bind-expr num_2 env) 
		 (arm:bind-expr num_3 env) (arm:bind-expr num_4 env) (arm:bind-expr prec_i env) 
		 (arm:bind-expr prec_o env) (arm:bind-expr num_7 env) (arm:bind-expr num_8 env) 
		 (arm:bind-expr num_9 env) (arm:bind-expr num_10 env))
	]
	[ (vtrn1_s32_dsl v0 v1 size_i_o num_3 num_4 num_5 prec_i_o num_7 num_8 num_9 num_10)
		(vtrn1_s32_dsl (arm:bind-expr v0 env) (arm:bind-expr v1 env) (arm:bind-expr size_i_o env) 
		 (arm:bind-expr num_3 env) (arm:bind-expr num_4 env) (arm:bind-expr num_5 env) 
		 (arm:bind-expr prec_i_o env) (arm:bind-expr num_7 env) (arm:bind-expr num_8 env) 
		 (arm:bind-expr num_9 env) (arm:bind-expr num_10 env))
	]
	[ (vmul_u32_dsl v0 v1 size_i_o num_3 num_4 num_5 prec_i_o num_7 num_8 num_9 num_10)
		(vmul_u32_dsl (arm:bind-expr v0 env) (arm:bind-expr v1 env) (arm:bind-expr size_i_o env) 
		 (arm:bind-expr num_3 env) (arm:bind-expr num_4 env) (arm:bind-expr num_5 env) 
		 (arm:bind-expr prec_i_o env) (arm:bind-expr num_7 env) (arm:bind-expr num_8 env) 
		 (arm:bind-expr num_9 env) (arm:bind-expr num_10 env))
	]
	[ (vmlal_high_n_u16_dsl v0 v1 v2 size_i_o num_4 num_5 num_6 prec_i_o num_8 num_9 num_10 num_11 num_12 num_13 num_14)
		(vmlal_high_n_u16_dsl (arm:bind-expr v0 env) (arm:bind-expr v1 env) (arm:bind-expr v2 env) 
		 (arm:bind-expr size_i_o env) (arm:bind-expr num_4 env) (arm:bind-expr num_5 env) 
		 (arm:bind-expr num_6 env) (arm:bind-expr prec_i_o env) (arm:bind-expr num_8 env) 
		 (arm:bind-expr num_9 env) (arm:bind-expr num_10 env) (arm:bind-expr num_11 env) 
		 (arm:bind-expr num_12 env) (arm:bind-expr num_13 env) (arm:bind-expr num_14 env))
	]
	[ (vrshrq_n_u16_dsl vc_0 vc_1 vc_2 v3 v4 size_i_o num_6 num_7 num_8 prec_i_o num_10 num_11 num_12 num_13 num_14 num_15)
		(vrshrq_n_u16_dsl (arm:bind-expr vc_0 env) (arm:bind-expr vc_1 env) (arm:bind-expr vc_2 env) 
		 (arm:bind-expr v3 env) (arm:bind-expr v4 env) (arm:bind-expr size_i_o env) 
		 (arm:bind-expr num_6 env) (arm:bind-expr num_7 env) (arm:bind-expr num_8 env) 
		 (arm:bind-expr prec_i_o env) (arm:bind-expr num_10 env) (arm:bind-expr num_11 env) 
		 (arm:bind-expr num_12 env) (arm:bind-expr num_13 env) (arm:bind-expr num_14 env) 
		 (arm:bind-expr num_15 env))
	]
	[ (vcltz_s32_dsl vc_0 vc_1 vc_2 v3 size_i_o num_5 num_6 num_7 prec_i_o num_9)
		(vcltz_s32_dsl (arm:bind-expr vc_0 env) (arm:bind-expr vc_1 env) (arm:bind-expr vc_2 env) 
		 (arm:bind-expr v3 env) (arm:bind-expr size_i_o env) (arm:bind-expr num_5 env) 
		 (arm:bind-expr num_6 env) (arm:bind-expr num_7 env) (arm:bind-expr prec_i_o env) 
		 (arm:bind-expr num_9 env))
	]
	[ (vqdmlsl_high_n_s16_dsl vc_0 v1 v2 v3 size_i_o num_5 num_6 num_7 prec_i_o num_9 num_10 num_11 num_12 num_13 num_14)
		(vqdmlsl_high_n_s16_dsl (arm:bind-expr vc_0 env) (arm:bind-expr v1 env) (arm:bind-expr v2 env) 
		 (arm:bind-expr v3 env) (arm:bind-expr size_i_o env) (arm:bind-expr num_5 env) 
		 (arm:bind-expr num_6 env) (arm:bind-expr num_7 env) (arm:bind-expr prec_i_o env) 
		 (arm:bind-expr num_9 env) (arm:bind-expr num_10 env) (arm:bind-expr num_11 env) 
		 (arm:bind-expr num_12 env) (arm:bind-expr num_13 env) (arm:bind-expr num_14 env))
	]
	[ (vrsra_n_s32_dsl vc_0 vc_1 v2 v3 v4 size_i_o num_6 num_7 num_8 prec_i_o num_10 num_11 num_12 num_13 num_14 num_15)
		(vrsra_n_s32_dsl (arm:bind-expr vc_0 env) (arm:bind-expr vc_1 env) (arm:bind-expr v2 env) 
		 (arm:bind-expr v3 env) (arm:bind-expr v4 env) (arm:bind-expr size_i_o env) 
		 (arm:bind-expr num_6 env) (arm:bind-expr num_7 env) (arm:bind-expr num_8 env) 
		 (arm:bind-expr prec_i_o env) (arm:bind-expr num_10 env) (arm:bind-expr num_11 env) 
		 (arm:bind-expr num_12 env) (arm:bind-expr num_13 env) (arm:bind-expr num_14 env) 
		 (arm:bind-expr num_15 env))
	]
	[ (vabal_u16_dsl v0 v1 v2 size_i_o num_4 num_5 num_6 prec_i prec_o num_9 num_10 num_11 num_12 num_13 num_14 num_15 num_16)
		(vabal_u16_dsl (arm:bind-expr v0 env) (arm:bind-expr v1 env) (arm:bind-expr v2 env) 
		 (arm:bind-expr size_i_o env) (arm:bind-expr num_4 env) (arm:bind-expr num_5 env) 
		 (arm:bind-expr num_6 env) (arm:bind-expr prec_i env) (arm:bind-expr prec_o env) 
		 (arm:bind-expr num_9 env) (arm:bind-expr num_10 env) (arm:bind-expr num_11 env) 
		 (arm:bind-expr num_12 env) (arm:bind-expr num_13 env) (arm:bind-expr num_14 env) 
		 (arm:bind-expr num_15 env) (arm:bind-expr num_16 env))
	]
	[ (vmull_high_n_s16_dsl v0 v1 size_o num_3 num_4 num_5 prec_o num_7 num_8 num_9 num_10 num_11 num_12)
		(vmull_high_n_s16_dsl (arm:bind-expr v0 env) (arm:bind-expr v1 env) (arm:bind-expr size_o env) 
		 (arm:bind-expr num_3 env) (arm:bind-expr num_4 env) (arm:bind-expr num_5 env) 
		 (arm:bind-expr prec_o env) (arm:bind-expr num_7 env) (arm:bind-expr num_8 env) 
		 (arm:bind-expr num_9 env) (arm:bind-expr num_10 env) (arm:bind-expr num_11 env) 
		 (arm:bind-expr num_12 env))
	]
	[ (vget_low_u8_dsl v0 size_i_o num_2 num_3 num_4 prec_i_o num_6)
		(vget_low_u8_dsl (arm:bind-expr v0 env) (arm:bind-expr size_i_o env) (arm:bind-expr num_2 env) 
		 (arm:bind-expr num_3 env) (arm:bind-expr num_4 env) (arm:bind-expr prec_i_o env) 
		 (arm:bind-expr num_6 env))
	]
	[ (vsraq_n_u64_dsl v0 v1 v2 size_i_o num_4 num_5 num_6 prec_i_o num_8 num_9)
		(vsraq_n_u64_dsl (arm:bind-expr v0 env) (arm:bind-expr v1 env) (arm:bind-expr v2 env) 
		 (arm:bind-expr size_i_o env) (arm:bind-expr num_4 env) (arm:bind-expr num_5 env) 
		 (arm:bind-expr num_6 env) (arm:bind-expr prec_i_o env) (arm:bind-expr num_8 env) 
		 (arm:bind-expr num_9 env))
	]
	[ (vmlal_high_u16_dsl v0 v1 v2 size_i_o num_4 num_5 num_6 prec_i_o num_8 num_9 num_10 num_11 num_12 num_13 num_14)
		(vmlal_high_u16_dsl (arm:bind-expr v0 env) (arm:bind-expr v1 env) (arm:bind-expr v2 env) 
		 (arm:bind-expr size_i_o env) (arm:bind-expr num_4 env) (arm:bind-expr num_5 env) 
		 (arm:bind-expr num_6 env) (arm:bind-expr prec_i_o env) (arm:bind-expr num_8 env) 
		 (arm:bind-expr num_9 env) (arm:bind-expr num_10 env) (arm:bind-expr num_11 env) 
		 (arm:bind-expr num_12 env) (arm:bind-expr num_13 env) (arm:bind-expr num_14 env))
	]
	[ (vmull_u32_dsl v0 v1 size_i_o num_3 num_4 num_5 prec_i prec_o num_8 num_9 num_10 num_11 num_12)
		(vmull_u32_dsl (arm:bind-expr v0 env) (arm:bind-expr v1 env) (arm:bind-expr size_i_o env) 
		 (arm:bind-expr num_3 env) (arm:bind-expr num_4 env) (arm:bind-expr num_5 env) 
		 (arm:bind-expr prec_i env) (arm:bind-expr prec_o env) (arm:bind-expr num_8 env) 
		 (arm:bind-expr num_9 env) (arm:bind-expr num_10 env) (arm:bind-expr num_11 env) 
		 (arm:bind-expr num_12 env))
	]
	[ (vrsra_n_u8_dsl vc_0 vc_1 v2 v3 v4 size_i_o num_6 num_7 num_8 prec_i_o num_10 num_11 num_12 num_13 num_14 num_15)
		(vrsra_n_u8_dsl (arm:bind-expr vc_0 env) (arm:bind-expr vc_1 env) (arm:bind-expr v2 env) 
		 (arm:bind-expr v3 env) (arm:bind-expr v4 env) (arm:bind-expr size_i_o env) 
		 (arm:bind-expr num_6 env) (arm:bind-expr num_7 env) (arm:bind-expr num_8 env) 
		 (arm:bind-expr prec_i_o env) (arm:bind-expr num_10 env) (arm:bind-expr num_11 env) 
		 (arm:bind-expr num_12 env) (arm:bind-expr num_13 env) (arm:bind-expr num_14 env) 
		 (arm:bind-expr num_15 env))
	]
	[ (vmul_n_u32_dsl v0 v1 size_i_o num_3 num_4 num_5 prec_i_o num_7 num_8 num_9 num_10)
		(vmul_n_u32_dsl (arm:bind-expr v0 env) (arm:bind-expr v1 env) (arm:bind-expr size_i_o env) 
		 (arm:bind-expr num_3 env) (arm:bind-expr num_4 env) (arm:bind-expr num_5 env) 
		 (arm:bind-expr prec_i_o env) (arm:bind-expr num_7 env) (arm:bind-expr num_8 env) 
		 (arm:bind-expr num_9 env) (arm:bind-expr num_10 env))
	]
	[ (vqrdmulh_s32_dsl vc_0 vc_1 v2 v3 size_i_o num_5 num_6 num_7 prec_i_o num_9 num_10 num_11 num_12 num_13 num_14 num_15)
		(vqrdmulh_s32_dsl (arm:bind-expr vc_0 env) (arm:bind-expr vc_1 env) (arm:bind-expr v2 env) 
		 (arm:bind-expr v3 env) (arm:bind-expr size_i_o env) (arm:bind-expr num_5 env) 
		 (arm:bind-expr num_6 env) (arm:bind-expr num_7 env) (arm:bind-expr prec_i_o env) 
		 (arm:bind-expr num_9 env) (arm:bind-expr num_10 env) (arm:bind-expr num_11 env) 
		 (arm:bind-expr num_12 env) (arm:bind-expr num_13 env) (arm:bind-expr num_14 env) 
		 (arm:bind-expr num_15 env))
	]
	[ (vqrshrun_n_s64_dsl vc_0 vc_1 v2 v3 size_i_o num_5 num_6 num_7 prec_o num_9 num_10 num_11 num_12 num_13 num_14 prec_i num_16)
		(vqrshrun_n_s64_dsl (arm:bind-expr vc_0 env) (arm:bind-expr vc_1 env) (arm:bind-expr v2 env) 
		 (arm:bind-expr v3 env) (arm:bind-expr size_i_o env) (arm:bind-expr num_5 env) 
		 (arm:bind-expr num_6 env) (arm:bind-expr num_7 env) (arm:bind-expr prec_o env) 
		 (arm:bind-expr num_9 env) (arm:bind-expr num_10 env) (arm:bind-expr num_11 env) 
		 (arm:bind-expr num_12 env) (arm:bind-expr num_13 env) (arm:bind-expr num_14 env) 
		 (arm:bind-expr prec_i env) (arm:bind-expr num_16 env))
	]
	[ (vmlal_n_u16_dsl v0 v1 v2 size_i_o num_4 num_5 num_6 prec_i num_8 num_9 prec_o num_11 num_12 num_13 num_14)
		(vmlal_n_u16_dsl (arm:bind-expr v0 env) (arm:bind-expr v1 env) (arm:bind-expr v2 env) 
		 (arm:bind-expr size_i_o env) (arm:bind-expr num_4 env) (arm:bind-expr num_5 env) 
		 (arm:bind-expr num_6 env) (arm:bind-expr prec_i env) (arm:bind-expr num_8 env) 
		 (arm:bind-expr num_9 env) (arm:bind-expr prec_o env) (arm:bind-expr num_11 env) 
		 (arm:bind-expr num_12 env) (arm:bind-expr num_13 env) (arm:bind-expr num_14 env))
	]
	[ (vrsubhn_u16_dsl vc_0 v1 v2 size_i_o num_4 num_5 num_6 prec_o num_8 num_9 num_10 prec_i num_12)
		(vrsubhn_u16_dsl (arm:bind-expr vc_0 env) (arm:bind-expr v1 env) (arm:bind-expr v2 env) 
		 (arm:bind-expr size_i_o env) (arm:bind-expr num_4 env) (arm:bind-expr num_5 env) 
		 (arm:bind-expr num_6 env) (arm:bind-expr prec_o env) (arm:bind-expr num_8 env) 
		 (arm:bind-expr num_9 env) (arm:bind-expr num_10 env) (arm:bind-expr prec_i env) 
		 (arm:bind-expr num_12 env))
	]
	[ (vaddw_high_u32_dsl v0 v1 size_i_o num_3 num_4 num_5 prec_i_o num_7 num_8 num_9 num_10 num_11 num_12 num_13 num_14)
		(vaddw_high_u32_dsl (arm:bind-expr v0 env) (arm:bind-expr v1 env) (arm:bind-expr size_i_o env) 
		 (arm:bind-expr num_3 env) (arm:bind-expr num_4 env) (arm:bind-expr num_5 env) 
		 (arm:bind-expr prec_i_o env) (arm:bind-expr num_7 env) (arm:bind-expr num_8 env) 
		 (arm:bind-expr num_9 env) (arm:bind-expr num_10 env) (arm:bind-expr num_11 env) 
		 (arm:bind-expr num_12 env) (arm:bind-expr num_13 env) (arm:bind-expr num_14 env))
	]
	[ (vqrdmulhq_n_s16_dsl vc_0 vc_1 v2 v3 size_i_o num_5 num_6 num_7 prec_i_o num_9 num_10 num_11 num_12 num_13 num_14 num_15)
		(vqrdmulhq_n_s16_dsl (arm:bind-expr vc_0 env) (arm:bind-expr vc_1 env) (arm:bind-expr v2 env) 
		 (arm:bind-expr v3 env) (arm:bind-expr size_i_o env) (arm:bind-expr num_5 env) 
		 (arm:bind-expr num_6 env) (arm:bind-expr num_7 env) (arm:bind-expr prec_i_o env) 
		 (arm:bind-expr num_9 env) (arm:bind-expr num_10 env) (arm:bind-expr num_11 env) 
		 (arm:bind-expr num_12 env) (arm:bind-expr num_13 env) (arm:bind-expr num_14 env) 
		 (arm:bind-expr num_15 env))
	]
	[ (vqrdmulhq_s16_dsl vc_0 vc_1 v2 v3 size_i_o num_5 num_6 num_7 prec_i_o num_9 num_10 num_11 num_12 num_13 num_14 num_15)
		(vqrdmulhq_s16_dsl (arm:bind-expr vc_0 env) (arm:bind-expr vc_1 env) (arm:bind-expr v2 env) 
		 (arm:bind-expr v3 env) (arm:bind-expr size_i_o env) (arm:bind-expr num_5 env) 
		 (arm:bind-expr num_6 env) (arm:bind-expr num_7 env) (arm:bind-expr prec_i_o env) 
		 (arm:bind-expr num_9 env) (arm:bind-expr num_10 env) (arm:bind-expr num_11 env) 
		 (arm:bind-expr num_12 env) (arm:bind-expr num_13 env) (arm:bind-expr num_14 env) 
		 (arm:bind-expr num_15 env))
	]
	[ (vrshld_s64_dsl vc_0 vc_1 v2 v3 size_i_o num_5 num_6 num_7 prec_i_o num_9 num_10 num_11 num_12 num_13 num_14 num_15)
		(vrshld_s64_dsl (arm:bind-expr vc_0 env) (arm:bind-expr vc_1 env) (arm:bind-expr v2 env) 
		 (arm:bind-expr v3 env) (arm:bind-expr size_i_o env) (arm:bind-expr num_5 env) 
		 (arm:bind-expr num_6 env) (arm:bind-expr num_7 env) (arm:bind-expr prec_i_o env) 
		 (arm:bind-expr num_9 env) (arm:bind-expr num_10 env) (arm:bind-expr num_11 env) 
		 (arm:bind-expr num_12 env) (arm:bind-expr num_13 env) (arm:bind-expr num_14 env) 
		 (arm:bind-expr num_15 env))
	]
	[ (vqdmull_n_s32_dsl vc_0 v1 v2 size_i_o num_4 num_5 num_6 prec_i num_8 num_9 prec_o num_11 num_12)
		(vqdmull_n_s32_dsl (arm:bind-expr vc_0 env) (arm:bind-expr v1 env) (arm:bind-expr v2 env) 
		 (arm:bind-expr size_i_o env) (arm:bind-expr num_4 env) (arm:bind-expr num_5 env) 
		 (arm:bind-expr num_6 env) (arm:bind-expr prec_i env) (arm:bind-expr num_8 env) 
		 (arm:bind-expr num_9 env) (arm:bind-expr prec_o env) (arm:bind-expr num_11 env) 
		 (arm:bind-expr num_12 env))
	]
	[ (vraddhn_u64_dsl vc_0 v1 v2 size_i_o num_4 num_5 num_6 prec_o num_8 num_9 num_10 prec_i num_12)
		(vraddhn_u64_dsl (arm:bind-expr vc_0 env) (arm:bind-expr v1 env) (arm:bind-expr v2 env) 
		 (arm:bind-expr size_i_o env) (arm:bind-expr num_4 env) (arm:bind-expr num_5 env) 
		 (arm:bind-expr num_6 env) (arm:bind-expr prec_o env) (arm:bind-expr num_8 env) 
		 (arm:bind-expr num_9 env) (arm:bind-expr num_10 env) (arm:bind-expr prec_i env) 
		 (arm:bind-expr num_12 env))
	]
	[ (vshr_n_u64_dsl vc_0 v1 v2 size_i_o num_4 num_5 num_6 prec_i_o num_8 num_9)
		(vshr_n_u64_dsl (arm:bind-expr vc_0 env) (arm:bind-expr v1 env) (arm:bind-expr v2 env) 
		 (arm:bind-expr size_i_o env) (arm:bind-expr num_4 env) (arm:bind-expr num_5 env) 
		 (arm:bind-expr num_6 env) (arm:bind-expr prec_i_o env) (arm:bind-expr num_8 env) 
		 (arm:bind-expr num_9 env))
	]
	[ (vabs_s32_dsl v0 size_i_o num_2 num_3 num_4 prec_i_o num_6 num_7 num_8)
		(vabs_s32_dsl (arm:bind-expr v0 env) (arm:bind-expr size_i_o env) (arm:bind-expr num_2 env) 
		 (arm:bind-expr num_3 env) (arm:bind-expr num_4 env) (arm:bind-expr prec_i_o env) 
		 (arm:bind-expr num_6 env) (arm:bind-expr num_7 env) (arm:bind-expr num_8 env))
	]
	[ (vqdmlsl_high_n_s32_dsl vc_0 v1 v2 v3 size_i_o num_5 num_6 num_7 prec_i_o num_9 num_10 num_11 num_12 num_13 num_14)
		(vqdmlsl_high_n_s32_dsl (arm:bind-expr vc_0 env) (arm:bind-expr v1 env) (arm:bind-expr v2 env) 
		 (arm:bind-expr v3 env) (arm:bind-expr size_i_o env) (arm:bind-expr num_5 env) 
		 (arm:bind-expr num_6 env) (arm:bind-expr num_7 env) (arm:bind-expr prec_i_o env) 
		 (arm:bind-expr num_9 env) (arm:bind-expr num_10 env) (arm:bind-expr num_11 env) 
		 (arm:bind-expr num_12 env) (arm:bind-expr num_13 env) (arm:bind-expr num_14 env))
	]
	[ (vmull_high_n_s32_dsl v0 v1 size_o num_3 num_4 num_5 prec_o num_7 num_8 num_9 num_10 num_11 num_12)
		(vmull_high_n_s32_dsl (arm:bind-expr v0 env) (arm:bind-expr v1 env) (arm:bind-expr size_o env) 
		 (arm:bind-expr num_3 env) (arm:bind-expr num_4 env) (arm:bind-expr num_5 env) 
		 (arm:bind-expr prec_o env) (arm:bind-expr num_7 env) (arm:bind-expr num_8 env) 
		 (arm:bind-expr num_9 env) (arm:bind-expr num_10 env) (arm:bind-expr num_11 env) 
		 (arm:bind-expr num_12 env))
	]
	[ (vqdmulhh_s16_dsl vc_0 v1 v2 size_i_o num_4 num_5 num_6 prec_i_o num_8 num_9 num_10 num_11)
		(vqdmulhh_s16_dsl (arm:bind-expr vc_0 env) (arm:bind-expr v1 env) (arm:bind-expr v2 env) 
		 (arm:bind-expr size_i_o env) (arm:bind-expr num_4 env) (arm:bind-expr num_5 env) 
		 (arm:bind-expr num_6 env) (arm:bind-expr prec_i_o env) (arm:bind-expr num_8 env) 
		 (arm:bind-expr num_9 env) (arm:bind-expr num_10 env) (arm:bind-expr num_11 env))
	]
	[ (vsraq_n_s64_dsl v0 v1 v2 size_i_o num_4 num_5 num_6 prec_i_o num_8 num_9)
		(vsraq_n_s64_dsl (arm:bind-expr v0 env) (arm:bind-expr v1 env) (arm:bind-expr v2 env) 
		 (arm:bind-expr size_i_o env) (arm:bind-expr num_4 env) (arm:bind-expr num_5 env) 
		 (arm:bind-expr num_6 env) (arm:bind-expr prec_i_o env) (arm:bind-expr num_8 env) 
		 (arm:bind-expr num_9 env))
	]
	[ (vsqadds_u32_dsl v0 v1 size_i_o num_3 num_4 num_5 prec_i_o num_7 num_8 num_9 num_10 num_11 num_12)
		(vsqadds_u32_dsl (arm:bind-expr v0 env) (arm:bind-expr v1 env) (arm:bind-expr size_i_o env) 
		 (arm:bind-expr num_3 env) (arm:bind-expr num_4 env) (arm:bind-expr num_5 env) 
		 (arm:bind-expr prec_i_o env) (arm:bind-expr num_7 env) (arm:bind-expr num_8 env) 
		 (arm:bind-expr num_9 env) (arm:bind-expr num_10 env) (arm:bind-expr num_11 env) 
		 (arm:bind-expr num_12 env))
	]
	[ (vabal_high_s16_dsl v0 v1 v2 size_i_o num_4 num_5 num_6 prec_i_o num_8 num_9 num_10 num_11 num_12 num_13 num_14 num_15 num_16)
		(vabal_high_s16_dsl (arm:bind-expr v0 env) (arm:bind-expr v1 env) (arm:bind-expr v2 env) 
		 (arm:bind-expr size_i_o env) (arm:bind-expr num_4 env) (arm:bind-expr num_5 env) 
		 (arm:bind-expr num_6 env) (arm:bind-expr prec_i_o env) (arm:bind-expr num_8 env) 
		 (arm:bind-expr num_9 env) (arm:bind-expr num_10 env) (arm:bind-expr num_11 env) 
		 (arm:bind-expr num_12 env) (arm:bind-expr num_13 env) (arm:bind-expr num_14 env) 
		 (arm:bind-expr num_15 env) (arm:bind-expr num_16 env))
	]
	[ (vqdmlal_high_n_s32_dsl vc_0 v1 v2 v3 size_i_o num_5 num_6 num_7 prec_i_o num_9 num_10 num_11 num_12 num_13 num_14)
		(vqdmlal_high_n_s32_dsl (arm:bind-expr vc_0 env) (arm:bind-expr v1 env) (arm:bind-expr v2 env) 
		 (arm:bind-expr v3 env) (arm:bind-expr size_i_o env) (arm:bind-expr num_5 env) 
		 (arm:bind-expr num_6 env) (arm:bind-expr num_7 env) (arm:bind-expr prec_i_o env) 
		 (arm:bind-expr num_9 env) (arm:bind-expr num_10 env) (arm:bind-expr num_11 env) 
		 (arm:bind-expr num_12 env) (arm:bind-expr num_13 env) (arm:bind-expr num_14 env))
	]
	[ (vqdmlsl_high_s16_dsl vc_0 v1 v2 v3 size_i_o num_5 num_6 num_7 prec_i_o num_9 num_10 num_11 num_12 num_13)
		(vqdmlsl_high_s16_dsl (arm:bind-expr vc_0 env) (arm:bind-expr v1 env) (arm:bind-expr v2 env) 
		 (arm:bind-expr v3 env) (arm:bind-expr size_i_o env) (arm:bind-expr num_5 env) 
		 (arm:bind-expr num_6 env) (arm:bind-expr num_7 env) (arm:bind-expr prec_i_o env) 
		 (arm:bind-expr num_9 env) (arm:bind-expr num_10 env) (arm:bind-expr num_11 env) 
		 (arm:bind-expr num_12 env) (arm:bind-expr num_13 env))
	]
	[ (vaddl_high_s8_dsl v0 v1 size_o num_3 num_4 num_5 prec_o num_7 num_8 num_9 num_10 num_11 num_12 num_13 num_14)
		(vaddl_high_s8_dsl (arm:bind-expr v0 env) (arm:bind-expr v1 env) (arm:bind-expr size_o env) 
		 (arm:bind-expr num_3 env) (arm:bind-expr num_4 env) (arm:bind-expr num_5 env) 
		 (arm:bind-expr prec_o env) (arm:bind-expr num_7 env) (arm:bind-expr num_8 env) 
		 (arm:bind-expr num_9 env) (arm:bind-expr num_10 env) (arm:bind-expr num_11 env) 
		 (arm:bind-expr num_12 env) (arm:bind-expr num_13 env) (arm:bind-expr num_14 env))
	]
	[ (vqdmlal_n_s16_dsl vc_0 v1 v2 v3 size_i_o num_5 num_6 num_7 prec_i num_9 num_10 prec_o num_12 num_13 num_14)
		(vqdmlal_n_s16_dsl (arm:bind-expr vc_0 env) (arm:bind-expr v1 env) (arm:bind-expr v2 env) 
		 (arm:bind-expr v3 env) (arm:bind-expr size_i_o env) (arm:bind-expr num_5 env) 
		 (arm:bind-expr num_6 env) (arm:bind-expr num_7 env) (arm:bind-expr prec_i env) 
		 (arm:bind-expr num_9 env) (arm:bind-expr num_10 env) (arm:bind-expr prec_o env) 
		 (arm:bind-expr num_12 env) (arm:bind-expr num_13 env) (arm:bind-expr num_14 env))
	]
	[ (vmul_n_s16_dsl v0 v1 size_i_o num_3 num_4 num_5 prec_i_o num_7 num_8 num_9 num_10)
		(vmul_n_s16_dsl (arm:bind-expr v0 env) (arm:bind-expr v1 env) (arm:bind-expr size_i_o env) 
		 (arm:bind-expr num_3 env) (arm:bind-expr num_4 env) (arm:bind-expr num_5 env) 
		 (arm:bind-expr prec_i_o env) (arm:bind-expr num_7 env) (arm:bind-expr num_8 env) 
		 (arm:bind-expr num_9 env) (arm:bind-expr num_10 env))
	]
	[ (vabdl_s8_dsl vc_0 v1 v2 size_i_o num_4 num_5 num_6 prec_i prec_o num_9 num_10 num_11 num_12 num_13 num_14 num_15 num_16)
		(vabdl_s8_dsl (arm:bind-expr vc_0 env) (arm:bind-expr v1 env) (arm:bind-expr v2 env) 
		 (arm:bind-expr size_i_o env) (arm:bind-expr num_4 env) (arm:bind-expr num_5 env) 
		 (arm:bind-expr num_6 env) (arm:bind-expr prec_i env) (arm:bind-expr prec_o env) 
		 (arm:bind-expr num_9 env) (arm:bind-expr num_10 env) (arm:bind-expr num_11 env) 
		 (arm:bind-expr num_12 env) (arm:bind-expr num_13 env) (arm:bind-expr num_14 env) 
		 (arm:bind-expr num_15 env) (arm:bind-expr num_16 env))
	]
	[ (vcombine_u16_dsl v0 v1 size_i_o num_3 num_4 num_5 prec_i prec_o num_8)
		(vcombine_u16_dsl (arm:bind-expr v0 env) (arm:bind-expr v1 env) (arm:bind-expr size_i_o env) 
		 (arm:bind-expr num_3 env) (arm:bind-expr num_4 env) (arm:bind-expr num_5 env) 
		 (arm:bind-expr prec_i env) (arm:bind-expr prec_o env) (arm:bind-expr num_8 env))
	]
	[ (vmlsl_high_u16_dsl v0 v1 v2 size_i_o num_4 num_5 num_6 prec_i_o num_8 num_9 num_10 num_11 num_12 num_13 num_14)
		(vmlsl_high_u16_dsl (arm:bind-expr v0 env) (arm:bind-expr v1 env) (arm:bind-expr v2 env) 
		 (arm:bind-expr size_i_o env) (arm:bind-expr num_4 env) (arm:bind-expr num_5 env) 
		 (arm:bind-expr num_6 env) (arm:bind-expr prec_i_o env) (arm:bind-expr num_8 env) 
		 (arm:bind-expr num_9 env) (arm:bind-expr num_10 env) (arm:bind-expr num_11 env) 
		 (arm:bind-expr num_12 env) (arm:bind-expr num_13 env) (arm:bind-expr num_14 env))
	]
	[ (vuqaddq_s8_dsl v0 v1 size_i_o num_3 num_4 num_5 prec_i_o num_7 num_8 num_9 num_10 num_11 num_12)
		(vuqaddq_s8_dsl (arm:bind-expr v0 env) (arm:bind-expr v1 env) (arm:bind-expr size_i_o env) 
		 (arm:bind-expr num_3 env) (arm:bind-expr num_4 env) (arm:bind-expr num_5 env) 
		 (arm:bind-expr prec_i_o env) (arm:bind-expr num_7 env) (arm:bind-expr num_8 env) 
		 (arm:bind-expr num_9 env) (arm:bind-expr num_10 env) (arm:bind-expr num_11 env) 
		 (arm:bind-expr num_12 env))
	]
	[ (vabal_high_u8_dsl v0 v1 v2 size_i_o num_4 num_5 num_6 prec_i_o num_8 num_9 num_10 num_11 num_12 num_13 num_14 num_15 num_16)
		(vabal_high_u8_dsl (arm:bind-expr v0 env) (arm:bind-expr v1 env) (arm:bind-expr v2 env) 
		 (arm:bind-expr size_i_o env) (arm:bind-expr num_4 env) (arm:bind-expr num_5 env) 
		 (arm:bind-expr num_6 env) (arm:bind-expr prec_i_o env) (arm:bind-expr num_8 env) 
		 (arm:bind-expr num_9 env) (arm:bind-expr num_10 env) (arm:bind-expr num_11 env) 
		 (arm:bind-expr num_12 env) (arm:bind-expr num_13 env) (arm:bind-expr num_14 env) 
		 (arm:bind-expr num_15 env) (arm:bind-expr num_16 env))
	]
	[ (vsqadd_u64_dsl v0 v1 size_i_o num_3 num_4 num_5 prec_i_o num_7 num_8 num_9 num_10 num_11 num_12)
		(vsqadd_u64_dsl (arm:bind-expr v0 env) (arm:bind-expr v1 env) (arm:bind-expr size_i_o env) 
		 (arm:bind-expr num_3 env) (arm:bind-expr num_4 env) (arm:bind-expr num_5 env) 
		 (arm:bind-expr prec_i_o env) (arm:bind-expr num_7 env) (arm:bind-expr num_8 env) 
		 (arm:bind-expr num_9 env) (arm:bind-expr num_10 env) (arm:bind-expr num_11 env) 
		 (arm:bind-expr num_12 env))
	]
	[ (vqdmull_high_s16_dsl vc_0 v1 v2 size_o num_4 num_5 num_6 prec_o num_8 num_9 num_10 num_11)
		(vqdmull_high_s16_dsl (arm:bind-expr vc_0 env) (arm:bind-expr v1 env) (arm:bind-expr v2 env) 
		 (arm:bind-expr size_o env) (arm:bind-expr num_4 env) (arm:bind-expr num_5 env) 
		 (arm:bind-expr num_6 env) (arm:bind-expr prec_o env) (arm:bind-expr num_8 env) 
		 (arm:bind-expr num_9 env) (arm:bind-expr num_10 env) (arm:bind-expr num_11 env))
	]
	[ (vqrshrns_n_u32_dsl vc_0 vc_1 v2 v3 size_i_o num_5 num_6 num_7 prec_o num_9 num_10 num_11 num_12 num_13 prec_i num_15)
		(vqrshrns_n_u32_dsl (arm:bind-expr vc_0 env) (arm:bind-expr vc_1 env) (arm:bind-expr v2 env) 
		 (arm:bind-expr v3 env) (arm:bind-expr size_i_o env) (arm:bind-expr num_5 env) 
		 (arm:bind-expr num_6 env) (arm:bind-expr num_7 env) (arm:bind-expr prec_o env) 
		 (arm:bind-expr num_9 env) (arm:bind-expr num_10 env) (arm:bind-expr num_11 env) 
		 (arm:bind-expr num_12 env) (arm:bind-expr num_13 env) (arm:bind-expr prec_i env) 
		 (arm:bind-expr num_15 env))
	]
	[ (vqrshrnh_n_s16_dsl vc_0 vc_1 v2 v3 size_i_o num_5 num_6 num_7 prec_o num_9 num_10 num_11 num_12 num_13 prec_i num_15)
		(vqrshrnh_n_s16_dsl (arm:bind-expr vc_0 env) (arm:bind-expr vc_1 env) (arm:bind-expr v2 env) 
		 (arm:bind-expr v3 env) (arm:bind-expr size_i_o env) (arm:bind-expr num_5 env) 
		 (arm:bind-expr num_6 env) (arm:bind-expr num_7 env) (arm:bind-expr prec_o env) 
		 (arm:bind-expr num_9 env) (arm:bind-expr num_10 env) (arm:bind-expr num_11 env) 
		 (arm:bind-expr num_12 env) (arm:bind-expr num_13 env) (arm:bind-expr prec_i env) 
		 (arm:bind-expr num_15 env))
	]
	[ (vsra_n_s64_dsl v0 v1 v2 size_i_o num_4 num_5 num_6 prec_i_o num_8 num_9)
		(vsra_n_s64_dsl (arm:bind-expr v0 env) (arm:bind-expr v1 env) (arm:bind-expr v2 env) 
		 (arm:bind-expr size_i_o env) (arm:bind-expr num_4 env) (arm:bind-expr num_5 env) 
		 (arm:bind-expr num_6 env) (arm:bind-expr prec_i_o env) (arm:bind-expr num_8 env) 
		 (arm:bind-expr num_9 env))
	]
	[ (vabal_s8_dsl v0 v1 v2 size_i_o num_4 num_5 num_6 prec_i prec_o num_9 num_10 num_11 num_12 num_13 num_14 num_15 num_16)
		(vabal_s8_dsl (arm:bind-expr v0 env) (arm:bind-expr v1 env) (arm:bind-expr v2 env) 
		 (arm:bind-expr size_i_o env) (arm:bind-expr num_4 env) (arm:bind-expr num_5 env) 
		 (arm:bind-expr num_6 env) (arm:bind-expr prec_i env) (arm:bind-expr prec_o env) 
		 (arm:bind-expr num_9 env) (arm:bind-expr num_10 env) (arm:bind-expr num_11 env) 
		 (arm:bind-expr num_12 env) (arm:bind-expr num_13 env) (arm:bind-expr num_14 env) 
		 (arm:bind-expr num_15 env) (arm:bind-expr num_16 env))
	]
	[ (vceqq_u16_dsl v0 v1 vc_2 vc_3 size_i_o num_5 num_6 num_7 prec_i_o)
		(vceqq_u16_dsl (arm:bind-expr v0 env) (arm:bind-expr v1 env) (arm:bind-expr vc_2 env) 
		 (arm:bind-expr vc_3 env) (arm:bind-expr size_i_o env) (arm:bind-expr num_5 env) 
		 (arm:bind-expr num_6 env) (arm:bind-expr num_7 env) (arm:bind-expr prec_i_o env))
	]
	[ (vaddl_s32_dsl v0 v1 size_i_o num_3 num_4 num_5 prec_i prec_o num_8 num_9 num_10 num_11 num_12 num_13 num_14)
		(vaddl_s32_dsl (arm:bind-expr v0 env) (arm:bind-expr v1 env) (arm:bind-expr size_i_o env) 
		 (arm:bind-expr num_3 env) (arm:bind-expr num_4 env) (arm:bind-expr num_5 env) 
		 (arm:bind-expr prec_i env) (arm:bind-expr prec_o env) (arm:bind-expr num_8 env) 
		 (arm:bind-expr num_9 env) (arm:bind-expr num_10 env) (arm:bind-expr num_11 env) 
		 (arm:bind-expr num_12 env) (arm:bind-expr num_13 env) (arm:bind-expr num_14 env))
	]
	[ (vmull_high_s16_dsl v0 v1 size_o num_3 num_4 num_5 prec_o num_7 num_8 num_9 num_10 num_11 num_12)
		(vmull_high_s16_dsl (arm:bind-expr v0 env) (arm:bind-expr v1 env) (arm:bind-expr size_o env) 
		 (arm:bind-expr num_3 env) (arm:bind-expr num_4 env) (arm:bind-expr num_5 env) 
		 (arm:bind-expr prec_o env) (arm:bind-expr num_7 env) (arm:bind-expr num_8 env) 
		 (arm:bind-expr num_9 env) (arm:bind-expr num_10 env) (arm:bind-expr num_11 env) 
		 (arm:bind-expr num_12 env))
	]
	[ (vabal_s32_dsl v0 v1 v2 size_i_o num_4 num_5 num_6 prec_i prec_o num_9 num_10 num_11 num_12 num_13 num_14 num_15 num_16)
		(vabal_s32_dsl (arm:bind-expr v0 env) (arm:bind-expr v1 env) (arm:bind-expr v2 env) 
		 (arm:bind-expr size_i_o env) (arm:bind-expr num_4 env) (arm:bind-expr num_5 env) 
		 (arm:bind-expr num_6 env) (arm:bind-expr prec_i env) (arm:bind-expr prec_o env) 
		 (arm:bind-expr num_9 env) (arm:bind-expr num_10 env) (arm:bind-expr num_11 env) 
		 (arm:bind-expr num_12 env) (arm:bind-expr num_13 env) (arm:bind-expr num_14 env) 
		 (arm:bind-expr num_15 env) (arm:bind-expr num_16 env))
	]
	[ (vzip1q_u32_dsl v0 v1 size_i_o num_3 num_4 num_5 prec_i_o num_7 num_8 num_9 num_10)
		(vzip1q_u32_dsl (arm:bind-expr v0 env) (arm:bind-expr v1 env) (arm:bind-expr size_i_o env) 
		 (arm:bind-expr num_3 env) (arm:bind-expr num_4 env) (arm:bind-expr num_5 env) 
		 (arm:bind-expr prec_i_o env) (arm:bind-expr num_7 env) (arm:bind-expr num_8 env) 
		 (arm:bind-expr num_9 env) (arm:bind-expr num_10 env))
	]
	[ (vmlsl_u32_dsl v0 v1 v2 size_i_o num_4 num_5 num_6 prec_i prec_o num_9 num_10 num_11 num_12 num_13 num_14)
		(vmlsl_u32_dsl (arm:bind-expr v0 env) (arm:bind-expr v1 env) (arm:bind-expr v2 env) 
		 (arm:bind-expr size_i_o env) (arm:bind-expr num_4 env) (arm:bind-expr num_5 env) 
		 (arm:bind-expr num_6 env) (arm:bind-expr prec_i env) (arm:bind-expr prec_o env) 
		 (arm:bind-expr num_9 env) (arm:bind-expr num_10 env) (arm:bind-expr num_11 env) 
		 (arm:bind-expr num_12 env) (arm:bind-expr num_13 env) (arm:bind-expr num_14 env))
	]
	[ (vqdmulh_n_s16_dsl vc_0 v1 v2 size_i_o num_4 num_5 num_6 prec_i_o num_8 num_9 num_10 num_11)
		(vqdmulh_n_s16_dsl (arm:bind-expr vc_0 env) (arm:bind-expr v1 env) (arm:bind-expr v2 env) 
		 (arm:bind-expr size_i_o env) (arm:bind-expr num_4 env) (arm:bind-expr num_5 env) 
		 (arm:bind-expr num_6 env) (arm:bind-expr prec_i_o env) (arm:bind-expr num_8 env) 
		 (arm:bind-expr num_9 env) (arm:bind-expr num_10 env) (arm:bind-expr num_11 env))
	]
	[ (vrhadd_s16_dsl vc_0 v1 v2 size_i_o num_4 num_5 num_6 prec_i_o num_8 num_9 num_10 num_11 num_12 num_13 num_14)
		(vrhadd_s16_dsl (arm:bind-expr vc_0 env) (arm:bind-expr v1 env) (arm:bind-expr v2 env) 
		 (arm:bind-expr size_i_o env) (arm:bind-expr num_4 env) (arm:bind-expr num_5 env) 
		 (arm:bind-expr num_6 env) (arm:bind-expr prec_i_o env) (arm:bind-expr num_8 env) 
		 (arm:bind-expr num_9 env) (arm:bind-expr num_10 env) (arm:bind-expr num_11 env) 
		 (arm:bind-expr num_12 env) (arm:bind-expr num_13 env) (arm:bind-expr num_14 env))
	]
	[ (vrshrd_n_s64_dsl vc_0 vc_1 vc_2 v3 v4 size_i_o num_6 num_7 num_8 prec_i_o num_10 num_11 num_12 num_13 num_14 num_15 num_16)
		(vrshrd_n_s64_dsl (arm:bind-expr vc_0 env) (arm:bind-expr vc_1 env) (arm:bind-expr vc_2 env) 
		 (arm:bind-expr v3 env) (arm:bind-expr v4 env) (arm:bind-expr size_i_o env) 
		 (arm:bind-expr num_6 env) (arm:bind-expr num_7 env) (arm:bind-expr num_8 env) 
		 (arm:bind-expr prec_i_o env) (arm:bind-expr num_10 env) (arm:bind-expr num_11 env) 
		 (arm:bind-expr num_12 env) (arm:bind-expr num_13 env) (arm:bind-expr num_14 env) 
		 (arm:bind-expr num_15 env) (arm:bind-expr num_16 env))
	]
	[ (vuzp1q_u8_dsl v0 v1 size_i_o num_3 num_4 num_5 prec_i_o num_7)
		(vuzp1q_u8_dsl (arm:bind-expr v0 env) (arm:bind-expr v1 env) (arm:bind-expr size_i_o env) 
		 (arm:bind-expr num_3 env) (arm:bind-expr num_4 env) (arm:bind-expr num_5 env) 
		 (arm:bind-expr prec_i_o env) (arm:bind-expr num_7 env))
	]
	[ (vhsub_u16_dsl v0 v1 size_i_o num_3 num_4 num_5 prec_i_o num_7 num_8 num_9 num_10 num_11 num_12)
		(vhsub_u16_dsl (arm:bind-expr v0 env) (arm:bind-expr v1 env) (arm:bind-expr size_i_o env) 
		 (arm:bind-expr num_3 env) (arm:bind-expr num_4 env) (arm:bind-expr num_5 env) 
		 (arm:bind-expr prec_i_o env) (arm:bind-expr num_7 env) (arm:bind-expr num_8 env) 
		 (arm:bind-expr num_9 env) (arm:bind-expr num_10 env) (arm:bind-expr num_11 env) 
		 (arm:bind-expr num_12 env))
	]
	[ (vqshlh_n_s16_dsl v0 v1 size_i_o num_3 num_4 num_5 prec_i_o num_7 num_8 num_9)
		(vqshlh_n_s16_dsl (arm:bind-expr v0 env) (arm:bind-expr v1 env) (arm:bind-expr size_i_o env) 
		 (arm:bind-expr num_3 env) (arm:bind-expr num_4 env) (arm:bind-expr num_5 env) 
		 (arm:bind-expr prec_i_o env) (arm:bind-expr num_7 env) (arm:bind-expr num_8 env) 
		 (arm:bind-expr num_9 env))
	]
	[ (vabdl_s16_dsl vc_0 v1 v2 size_i_o num_4 num_5 num_6 prec_i prec_o num_9 num_10 num_11 num_12 num_13 num_14 num_15 num_16)
		(vabdl_s16_dsl (arm:bind-expr vc_0 env) (arm:bind-expr v1 env) (arm:bind-expr v2 env) 
		 (arm:bind-expr size_i_o env) (arm:bind-expr num_4 env) (arm:bind-expr num_5 env) 
		 (arm:bind-expr num_6 env) (arm:bind-expr prec_i env) (arm:bind-expr prec_o env) 
		 (arm:bind-expr num_9 env) (arm:bind-expr num_10 env) (arm:bind-expr num_11 env) 
		 (arm:bind-expr num_12 env) (arm:bind-expr num_13 env) (arm:bind-expr num_14 env) 
		 (arm:bind-expr num_15 env) (arm:bind-expr num_16 env))
	]
	[ (vmovl_high_s8_dsl v0 size_o num_2 num_3 num_4 prec_o num_6 num_7 num_8 num_9 num_10)
		(vmovl_high_s8_dsl (arm:bind-expr v0 env) (arm:bind-expr size_o env) (arm:bind-expr num_2 env) 
		 (arm:bind-expr num_3 env) (arm:bind-expr num_4 env) (arm:bind-expr prec_o env) 
		 (arm:bind-expr num_6 env) (arm:bind-expr num_7 env) (arm:bind-expr num_8 env) 
		 (arm:bind-expr num_9 env) (arm:bind-expr num_10 env))
	]
	[ (vcgt_u32_dsl vc_0 vc_1 v2 v3 size_i_o num_5 num_6 num_7 prec_i_o num_9)
		(vcgt_u32_dsl (arm:bind-expr vc_0 env) (arm:bind-expr vc_1 env) (arm:bind-expr v2 env) 
		 (arm:bind-expr v3 env) (arm:bind-expr size_i_o env) (arm:bind-expr num_5 env) 
		 (arm:bind-expr num_6 env) (arm:bind-expr num_7 env) (arm:bind-expr prec_i_o env) 
		 (arm:bind-expr num_9 env))
	]
	[ (vrshr_n_u64_dsl vc_0 vc_1 vc_2 v3 v4 size_i_o num_6 num_7 num_8 prec_i_o num_10 num_11 num_12 num_13 num_14 num_15 num_16)
		(vrshr_n_u64_dsl (arm:bind-expr vc_0 env) (arm:bind-expr vc_1 env) (arm:bind-expr vc_2 env) 
		 (arm:bind-expr v3 env) (arm:bind-expr v4 env) (arm:bind-expr size_i_o env) 
		 (arm:bind-expr num_6 env) (arm:bind-expr num_7 env) (arm:bind-expr num_8 env) 
		 (arm:bind-expr prec_i_o env) (arm:bind-expr num_10 env) (arm:bind-expr num_11 env) 
		 (arm:bind-expr num_12 env) (arm:bind-expr num_13 env) (arm:bind-expr num_14 env) 
		 (arm:bind-expr num_15 env) (arm:bind-expr num_16 env))
	]
	[ (vqdmull_high_n_s16_dsl vc_0 v1 v2 size_o num_4 num_5 num_6 prec_o num_8 num_9 num_10 num_11 num_12)
		(vqdmull_high_n_s16_dsl (arm:bind-expr vc_0 env) (arm:bind-expr v1 env) (arm:bind-expr v2 env) 
		 (arm:bind-expr size_o env) (arm:bind-expr num_4 env) (arm:bind-expr num_5 env) 
		 (arm:bind-expr num_6 env) (arm:bind-expr prec_o env) (arm:bind-expr num_8 env) 
		 (arm:bind-expr num_9 env) (arm:bind-expr num_10 env) (arm:bind-expr num_11 env) 
		 (arm:bind-expr num_12 env))
	]
	[ (vsraq_n_s32_dsl v0 v1 v2 size_i_o num_4 num_5 num_6 prec_i_o num_8 num_9 num_10 num_11)
		(vsraq_n_s32_dsl (arm:bind-expr v0 env) (arm:bind-expr v1 env) (arm:bind-expr v2 env) 
		 (arm:bind-expr size_i_o env) (arm:bind-expr num_4 env) (arm:bind-expr num_5 env) 
		 (arm:bind-expr num_6 env) (arm:bind-expr prec_i_o env) (arm:bind-expr num_8 env) 
		 (arm:bind-expr num_9 env) (arm:bind-expr num_10 env) (arm:bind-expr num_11 env))
	]
	[ (vabdl_high_s16_dsl vc_0 v1 v2 size_o num_4 num_5 num_6 prec_o num_8 num_9 num_10 num_11 num_12 num_13 num_14 num_15 num_16)
		(vabdl_high_s16_dsl (arm:bind-expr vc_0 env) (arm:bind-expr v1 env) (arm:bind-expr v2 env) 
		 (arm:bind-expr size_o env) (arm:bind-expr num_4 env) (arm:bind-expr num_5 env) 
		 (arm:bind-expr num_6 env) (arm:bind-expr prec_o env) (arm:bind-expr num_8 env) 
		 (arm:bind-expr num_9 env) (arm:bind-expr num_10 env) (arm:bind-expr num_11 env) 
		 (arm:bind-expr num_12 env) (arm:bind-expr num_13 env) (arm:bind-expr num_14 env) 
		 (arm:bind-expr num_15 env) (arm:bind-expr num_16 env))
	]
	[ (vmlsq_s32_dsl v0 v1 v2 size_i_o num_4 num_5 num_6 prec_i_o num_8 num_9 num_10 num_11 num_12)
		(vmlsq_s32_dsl (arm:bind-expr v0 env) (arm:bind-expr v1 env) (arm:bind-expr v2 env) 
		 (arm:bind-expr size_i_o env) (arm:bind-expr num_4 env) (arm:bind-expr num_5 env) 
		 (arm:bind-expr num_6 env) (arm:bind-expr prec_i_o env) (arm:bind-expr num_8 env) 
		 (arm:bind-expr num_9 env) (arm:bind-expr num_10 env) (arm:bind-expr num_11 env) 
		 (arm:bind-expr num_12 env))
	]
	[ (vabdq_s32_dsl vc_0 v1 v2 size_i_o num_4 num_5 num_6 prec_i_o num_8 num_9 num_10 num_11 num_12 num_13 num_14)
		(vabdq_s32_dsl (arm:bind-expr vc_0 env) (arm:bind-expr v1 env) (arm:bind-expr v2 env) 
		 (arm:bind-expr size_i_o env) (arm:bind-expr num_4 env) (arm:bind-expr num_5 env) 
		 (arm:bind-expr num_6 env) (arm:bind-expr prec_i_o env) (arm:bind-expr num_8 env) 
		 (arm:bind-expr num_9 env) (arm:bind-expr num_10 env) (arm:bind-expr num_11 env) 
		 (arm:bind-expr num_12 env) (arm:bind-expr num_13 env) (arm:bind-expr num_14 env))
	]
	[ (vpmaxq_s32_dsl v0 v1 size_i_o num_3 num_4 num_5 prec_o num_7 num_8 num_9 num_10 num_11 num_12 prec_i num_14)
		(vpmaxq_s32_dsl (arm:bind-expr v0 env) (arm:bind-expr v1 env) (arm:bind-expr size_i_o env) 
		 (arm:bind-expr num_3 env) (arm:bind-expr num_4 env) (arm:bind-expr num_5 env) 
		 (arm:bind-expr prec_o env) (arm:bind-expr num_7 env) (arm:bind-expr num_8 env) 
		 (arm:bind-expr num_9 env) (arm:bind-expr num_10 env) (arm:bind-expr num_11 env) 
		 (arm:bind-expr num_12 env) (arm:bind-expr prec_i env) (arm:bind-expr num_14 env))
	]
	[ (vshrq_n_u8_dsl vc_0 v1 v2 size_i_o num_4 num_5 num_6 prec_i_o num_8 num_9 num_10 num_11)
		(vshrq_n_u8_dsl (arm:bind-expr vc_0 env) (arm:bind-expr v1 env) (arm:bind-expr v2 env) 
		 (arm:bind-expr size_i_o env) (arm:bind-expr num_4 env) (arm:bind-expr num_5 env) 
		 (arm:bind-expr num_6 env) (arm:bind-expr prec_i_o env) (arm:bind-expr num_8 env) 
		 (arm:bind-expr num_9 env) (arm:bind-expr num_10 env) (arm:bind-expr num_11 env))
	]
	[ (vqdmlal_s32_dsl vc_0 v1 v2 v3 size_i_o num_5 num_6 num_7 prec_i prec_o num_10 num_11 num_12 num_13)
		(vqdmlal_s32_dsl (arm:bind-expr vc_0 env) (arm:bind-expr v1 env) (arm:bind-expr v2 env) 
		 (arm:bind-expr v3 env) (arm:bind-expr size_i_o env) (arm:bind-expr num_5 env) 
		 (arm:bind-expr num_6 env) (arm:bind-expr num_7 env) (arm:bind-expr prec_i env) 
		 (arm:bind-expr prec_o env) (arm:bind-expr num_10 env) (arm:bind-expr num_11 env) 
		 (arm:bind-expr num_12 env) (arm:bind-expr num_13 env))
	]
	[ (vshr_n_s16_dsl vc_0 v1 v2 size_i_o num_4 num_5 num_6 prec_i_o num_8 num_9 num_10 num_11)
		(vshr_n_s16_dsl (arm:bind-expr vc_0 env) (arm:bind-expr v1 env) (arm:bind-expr v2 env) 
		 (arm:bind-expr size_i_o env) (arm:bind-expr num_4 env) (arm:bind-expr num_5 env) 
		 (arm:bind-expr num_6 env) (arm:bind-expr prec_i_o env) (arm:bind-expr num_8 env) 
		 (arm:bind-expr num_9 env) (arm:bind-expr num_10 env) (arm:bind-expr num_11 env))
	]
	[ (vrshr_n_s32_dsl vc_0 vc_1 vc_2 v3 v4 size_i_o num_6 num_7 num_8 prec_i_o num_10 num_11 num_12 num_13 num_14 num_15)
		(vrshr_n_s32_dsl (arm:bind-expr vc_0 env) (arm:bind-expr vc_1 env) (arm:bind-expr vc_2 env) 
		 (arm:bind-expr v3 env) (arm:bind-expr v4 env) (arm:bind-expr size_i_o env) 
		 (arm:bind-expr num_6 env) (arm:bind-expr num_7 env) (arm:bind-expr num_8 env) 
		 (arm:bind-expr prec_i_o env) (arm:bind-expr num_10 env) (arm:bind-expr num_11 env) 
		 (arm:bind-expr num_12 env) (arm:bind-expr num_13 env) (arm:bind-expr num_14 env) 
		 (arm:bind-expr num_15 env))
	]
	[ (vadd_u16_dsl v0 v1 size_i_o num_3 num_4 num_5 prec_i_o num_7)
		(vadd_u16_dsl (arm:bind-expr v0 env) (arm:bind-expr v1 env) (arm:bind-expr size_i_o env) 
		 (arm:bind-expr num_3 env) (arm:bind-expr num_4 env) (arm:bind-expr num_5 env) 
		 (arm:bind-expr prec_i_o env) (arm:bind-expr num_7 env))
	]
	[ (vuqaddq_s16_dsl v0 v1 size_i_o num_3 num_4 num_5 prec_i_o num_7 num_8 num_9 num_10 num_11 num_12)
		(vuqaddq_s16_dsl (arm:bind-expr v0 env) (arm:bind-expr v1 env) (arm:bind-expr size_i_o env) 
		 (arm:bind-expr num_3 env) (arm:bind-expr num_4 env) (arm:bind-expr num_5 env) 
		 (arm:bind-expr prec_i_o env) (arm:bind-expr num_7 env) (arm:bind-expr num_8 env) 
		 (arm:bind-expr num_9 env) (arm:bind-expr num_10 env) (arm:bind-expr num_11 env) 
		 (arm:bind-expr num_12 env))
	]
	[ (vtst_u64_dsl vc_0 vc_1 v2 v3 size_i_o num_5 num_6 num_7 prec_i_o)
		(vtst_u64_dsl (arm:bind-expr vc_0 env) (arm:bind-expr vc_1 env) (arm:bind-expr v2 env) 
		 (arm:bind-expr v3 env) (arm:bind-expr size_i_o env) (arm:bind-expr num_5 env) 
		 (arm:bind-expr num_6 env) (arm:bind-expr num_7 env) (arm:bind-expr prec_i_o env))
	]
	[ (vnegq_s64_dsl v0 size_i_o num_2 num_3 num_4 prec_i_o num_6 num_7 num_8)
		(vnegq_s64_dsl (arm:bind-expr v0 env) (arm:bind-expr size_i_o env) (arm:bind-expr num_2 env) 
		 (arm:bind-expr num_3 env) (arm:bind-expr num_4 env) (arm:bind-expr prec_i_o env) 
		 (arm:bind-expr num_6 env) (arm:bind-expr num_7 env) (arm:bind-expr num_8 env))
	]
	[ (vqdmull_high_n_s32_dsl vc_0 v1 v2 size_o num_4 num_5 num_6 prec_o num_8 num_9 num_10 num_11 num_12)
		(vqdmull_high_n_s32_dsl (arm:bind-expr vc_0 env) (arm:bind-expr v1 env) (arm:bind-expr v2 env) 
		 (arm:bind-expr size_o env) (arm:bind-expr num_4 env) (arm:bind-expr num_5 env) 
		 (arm:bind-expr num_6 env) (arm:bind-expr prec_o env) (arm:bind-expr num_8 env) 
		 (arm:bind-expr num_9 env) (arm:bind-expr num_10 env) (arm:bind-expr num_11 env) 
		 (arm:bind-expr num_12 env))
	]
	[ (vmull_n_s16_dsl v0 v1 size_i_o num_3 num_4 num_5 prec_i num_7 num_8 prec_o num_10 num_11 num_12)
		(vmull_n_s16_dsl (arm:bind-expr v0 env) (arm:bind-expr v1 env) (arm:bind-expr size_i_o env) 
		 (arm:bind-expr num_3 env) (arm:bind-expr num_4 env) (arm:bind-expr num_5 env) 
		 (arm:bind-expr prec_i env) (arm:bind-expr num_7 env) (arm:bind-expr num_8 env) 
		 (arm:bind-expr prec_o env) (arm:bind-expr num_10 env) (arm:bind-expr num_11 env) 
		 (arm:bind-expr num_12 env))
	]
	[ (vrsra_n_s64_dsl vc_0 vc_1 v2 v3 v4 size_i_o num_6 num_7 num_8 prec_i_o num_10 num_11 num_12 num_13 num_14 num_15 num_16)
		(vrsra_n_s64_dsl (arm:bind-expr vc_0 env) (arm:bind-expr vc_1 env) (arm:bind-expr v2 env) 
		 (arm:bind-expr v3 env) (arm:bind-expr v4 env) (arm:bind-expr size_i_o env) 
		 (arm:bind-expr num_6 env) (arm:bind-expr num_7 env) (arm:bind-expr num_8 env) 
		 (arm:bind-expr prec_i_o env) (arm:bind-expr num_10 env) (arm:bind-expr num_11 env) 
		 (arm:bind-expr num_12 env) (arm:bind-expr num_13 env) (arm:bind-expr num_14 env) 
		 (arm:bind-expr num_15 env) (arm:bind-expr num_16 env))
	]
	[ (vabdl_u32_dsl vc_0 v1 v2 size_i_o num_4 num_5 num_6 prec_i prec_o num_9 num_10 num_11 num_12 num_13 num_14 num_15 num_16)
		(vabdl_u32_dsl (arm:bind-expr vc_0 env) (arm:bind-expr v1 env) (arm:bind-expr v2 env) 
		 (arm:bind-expr size_i_o env) (arm:bind-expr num_4 env) (arm:bind-expr num_5 env) 
		 (arm:bind-expr num_6 env) (arm:bind-expr prec_i env) (arm:bind-expr prec_o env) 
		 (arm:bind-expr num_9 env) (arm:bind-expr num_10 env) (arm:bind-expr num_11 env) 
		 (arm:bind-expr num_12 env) (arm:bind-expr num_13 env) (arm:bind-expr num_14 env) 
		 (arm:bind-expr num_15 env) (arm:bind-expr num_16 env))
	]
	[ (vabdl_high_u32_dsl vc_0 v1 v2 size_o num_4 num_5 num_6 prec_o num_8 num_9 num_10 num_11 num_12 num_13 num_14 num_15 num_16)
		(vabdl_high_u32_dsl (arm:bind-expr vc_0 env) (arm:bind-expr v1 env) (arm:bind-expr v2 env) 
		 (arm:bind-expr size_o env) (arm:bind-expr num_4 env) (arm:bind-expr num_5 env) 
		 (arm:bind-expr num_6 env) (arm:bind-expr prec_o env) (arm:bind-expr num_8 env) 
		 (arm:bind-expr num_9 env) (arm:bind-expr num_10 env) (arm:bind-expr num_11 env) 
		 (arm:bind-expr num_12 env) (arm:bind-expr num_13 env) (arm:bind-expr num_14 env) 
		 (arm:bind-expr num_15 env) (arm:bind-expr num_16 env))
	]
	[ (vsubl_s8_dsl v0 v1 size_i_o num_3 num_4 num_5 prec_i prec_o num_8 num_9 num_10 num_11 num_12 num_13 num_14)
		(vsubl_s8_dsl (arm:bind-expr v0 env) (arm:bind-expr v1 env) (arm:bind-expr size_i_o env) 
		 (arm:bind-expr num_3 env) (arm:bind-expr num_4 env) (arm:bind-expr num_5 env) 
		 (arm:bind-expr prec_i env) (arm:bind-expr prec_o env) (arm:bind-expr num_8 env) 
		 (arm:bind-expr num_9 env) (arm:bind-expr num_10 env) (arm:bind-expr num_11 env) 
		 (arm:bind-expr num_12 env) (arm:bind-expr num_13 env) (arm:bind-expr num_14 env))
	]
	[ (vsubl_high_u16_dsl v0 v1 size_o num_3 num_4 num_5 prec_o num_7 num_8 num_9 num_10 num_11 num_12 num_13 num_14)
		(vsubl_high_u16_dsl (arm:bind-expr v0 env) (arm:bind-expr v1 env) (arm:bind-expr size_o env) 
		 (arm:bind-expr num_3 env) (arm:bind-expr num_4 env) (arm:bind-expr num_5 env) 
		 (arm:bind-expr prec_o env) (arm:bind-expr num_7 env) (arm:bind-expr num_8 env) 
		 (arm:bind-expr num_9 env) (arm:bind-expr num_10 env) (arm:bind-expr num_11 env) 
		 (arm:bind-expr num_12 env) (arm:bind-expr num_13 env) (arm:bind-expr num_14 env))
	]
	[ (vsubw_s8_dsl v0 v1 size_i_o num_3 num_4 num_5 num_6 prec_i_o num_8 num_9 num_10 num_11 num_12 num_13 num_14)
		(vsubw_s8_dsl (arm:bind-expr v0 env) (arm:bind-expr v1 env) (arm:bind-expr size_i_o env) 
		 (arm:bind-expr num_3 env) (arm:bind-expr num_4 env) (arm:bind-expr num_5 env) 
		 (arm:bind-expr num_6 env) (arm:bind-expr prec_i_o env) (arm:bind-expr num_8 env) 
		 (arm:bind-expr num_9 env) (arm:bind-expr num_10 env) (arm:bind-expr num_11 env) 
		 (arm:bind-expr num_12 env) (arm:bind-expr num_13 env) (arm:bind-expr num_14 env))
	]
	[ (vsubw_high_u16_dsl v0 v1 size_i_o num_3 num_4 num_5 prec_i_o num_7 num_8 num_9 num_10 num_11 num_12 num_13 num_14)
		(vsubw_high_u16_dsl (arm:bind-expr v0 env) (arm:bind-expr v1 env) (arm:bind-expr size_i_o env) 
		 (arm:bind-expr num_3 env) (arm:bind-expr num_4 env) (arm:bind-expr num_5 env) 
		 (arm:bind-expr prec_i_o env) (arm:bind-expr num_7 env) (arm:bind-expr num_8 env) 
		 (arm:bind-expr num_9 env) (arm:bind-expr num_10 env) (arm:bind-expr num_11 env) 
		 (arm:bind-expr num_12 env) (arm:bind-expr num_13 env) (arm:bind-expr num_14 env))
	]
	[ (vmov_n_u16_dsl v0 size_o num_2 num_3 num_4 prec_o)
		(vmov_n_u16_dsl (arm:bind-expr v0 env) (arm:bind-expr size_o env) (arm:bind-expr num_2 env) 
		 (arm:bind-expr num_3 env) (arm:bind-expr num_4 env) (arm:bind-expr prec_o env))
	]
	[ (vmin_u32_dsl v0 v1 size_i_o num_3 num_4 num_5 prec_i_o num_7 num_8)
		(vmin_u32_dsl (arm:bind-expr v0 env) (arm:bind-expr v1 env) (arm:bind-expr size_i_o env) 
		 (arm:bind-expr num_3 env) (arm:bind-expr num_4 env) (arm:bind-expr num_5 env) 
		 (arm:bind-expr prec_i_o env) (arm:bind-expr num_7 env) (arm:bind-expr num_8 env))
	]
	[ (vrshrn_n_s16_dsl vc_0 vc_1 v2 v3 size_i_o num_5 num_6 num_7 prec_o num_9 num_10 num_11 num_12 num_13 prec_i num_15)
		(vrshrn_n_s16_dsl (arm:bind-expr vc_0 env) (arm:bind-expr vc_1 env) (arm:bind-expr v2 env) 
		 (arm:bind-expr v3 env) (arm:bind-expr size_i_o env) (arm:bind-expr num_5 env) 
		 (arm:bind-expr num_6 env) (arm:bind-expr num_7 env) (arm:bind-expr prec_o env) 
		 (arm:bind-expr num_9 env) (arm:bind-expr num_10 env) (arm:bind-expr num_11 env) 
		 (arm:bind-expr num_12 env) (arm:bind-expr num_13 env) (arm:bind-expr prec_i env) 
		 (arm:bind-expr num_15 env))
	]
	[ (vmlsl_high_n_u16_dsl v0 v1 v2 size_i_o num_4 num_5 num_6 prec_i_o num_8 num_9 num_10 num_11 num_12 num_13 num_14)
		(vmlsl_high_n_u16_dsl (arm:bind-expr v0 env) (arm:bind-expr v1 env) (arm:bind-expr v2 env) 
		 (arm:bind-expr size_i_o env) (arm:bind-expr num_4 env) (arm:bind-expr num_5 env) 
		 (arm:bind-expr num_6 env) (arm:bind-expr prec_i_o env) (arm:bind-expr num_8 env) 
		 (arm:bind-expr num_9 env) (arm:bind-expr num_10 env) (arm:bind-expr num_11 env) 
		 (arm:bind-expr num_12 env) (arm:bind-expr num_13 env) (arm:bind-expr num_14 env))
	]
	[ (vmlal_u8_dsl v0 v1 v2 size_i_o num_4 num_5 num_6 prec_i prec_o num_9 num_10 num_11 num_12 num_13 num_14)
		(vmlal_u8_dsl (arm:bind-expr v0 env) (arm:bind-expr v1 env) (arm:bind-expr v2 env) 
		 (arm:bind-expr size_i_o env) (arm:bind-expr num_4 env) (arm:bind-expr num_5 env) 
		 (arm:bind-expr num_6 env) (arm:bind-expr prec_i env) (arm:bind-expr prec_o env) 
		 (arm:bind-expr num_9 env) (arm:bind-expr num_10 env) (arm:bind-expr num_11 env) 
		 (arm:bind-expr num_12 env) (arm:bind-expr num_13 env) (arm:bind-expr num_14 env))
	]
	[ (vqdmlsl_n_s16_dsl vc_0 v1 v2 v3 size_i_o num_5 num_6 num_7 prec_i num_9 num_10 prec_o num_12 num_13 num_14)
		(vqdmlsl_n_s16_dsl (arm:bind-expr vc_0 env) (arm:bind-expr v1 env) (arm:bind-expr v2 env) 
		 (arm:bind-expr v3 env) (arm:bind-expr size_i_o env) (arm:bind-expr num_5 env) 
		 (arm:bind-expr num_6 env) (arm:bind-expr num_7 env) (arm:bind-expr prec_i env) 
		 (arm:bind-expr num_9 env) (arm:bind-expr num_10 env) (arm:bind-expr prec_o env) 
		 (arm:bind-expr num_12 env) (arm:bind-expr num_13 env) (arm:bind-expr num_14 env))
	]
	[ (vsraq_n_u8_dsl v0 v1 v2 size_i_o num_4 num_5 num_6 prec_i_o num_8 num_9 num_10 num_11)
		(vsraq_n_u8_dsl (arm:bind-expr v0 env) (arm:bind-expr v1 env) (arm:bind-expr v2 env) 
		 (arm:bind-expr size_i_o env) (arm:bind-expr num_4 env) (arm:bind-expr num_5 env) 
		 (arm:bind-expr num_6 env) (arm:bind-expr prec_i_o env) (arm:bind-expr num_8 env) 
		 (arm:bind-expr num_9 env) (arm:bind-expr num_10 env) (arm:bind-expr num_11 env))
	]
	[ (vmlaq_u32_dsl v0 v1 v2 size_i_o num_4 num_5 num_6 prec_i_o num_8 num_9 num_10 num_11 num_12)
		(vmlaq_u32_dsl (arm:bind-expr v0 env) (arm:bind-expr v1 env) (arm:bind-expr v2 env) 
		 (arm:bind-expr size_i_o env) (arm:bind-expr num_4 env) (arm:bind-expr num_5 env) 
		 (arm:bind-expr num_6 env) (arm:bind-expr prec_i_o env) (arm:bind-expr num_8 env) 
		 (arm:bind-expr num_9 env) (arm:bind-expr num_10 env) (arm:bind-expr num_11 env) 
		 (arm:bind-expr num_12 env))
	]
	[ (vmvn_s16_dsl v0 size_i_o num_2 num_3 num_4 prec_i_o)
		(vmvn_s16_dsl (arm:bind-expr v0 env) (arm:bind-expr size_i_o env) (arm:bind-expr num_2 env) 
		 (arm:bind-expr num_3 env) (arm:bind-expr num_4 env) (arm:bind-expr prec_i_o env))
	]
	[ (vuzp2_s16_dsl v0 v1 size_i_o num_3 num_4 num_5 prec_i_o num_7 num_8 num_9)
		(vuzp2_s16_dsl (arm:bind-expr v0 env) (arm:bind-expr v1 env) (arm:bind-expr size_i_o env) 
		 (arm:bind-expr num_3 env) (arm:bind-expr num_4 env) (arm:bind-expr num_5 env) 
		 (arm:bind-expr prec_i_o env) (arm:bind-expr num_7 env) (arm:bind-expr num_8 env) 
		 (arm:bind-expr num_9 env))
	]
	[ (vqrshld_s64_dsl vc_0 vc_1 v2 v3 size_i_o num_5 num_6 num_7 prec_i_o num_9 num_10 num_11 num_12 num_13 num_14 num_15)
		(vqrshld_s64_dsl (arm:bind-expr vc_0 env) (arm:bind-expr vc_1 env) (arm:bind-expr v2 env) 
		 (arm:bind-expr v3 env) (arm:bind-expr size_i_o env) (arm:bind-expr num_5 env) 
		 (arm:bind-expr num_6 env) (arm:bind-expr num_7 env) (arm:bind-expr prec_i_o env) 
		 (arm:bind-expr num_9 env) (arm:bind-expr num_10 env) (arm:bind-expr num_11 env) 
		 (arm:bind-expr num_12 env) (arm:bind-expr num_13 env) (arm:bind-expr num_14 env) 
		 (arm:bind-expr num_15 env))
	]
	[ (vzip2q_s64_dsl v0 v1 size_i_o num_3 num_4 num_5 prec_i_o num_7 num_8 num_9 num_10 num_11 num_12 num_13)
		(vzip2q_s64_dsl (arm:bind-expr v0 env) (arm:bind-expr v1 env) (arm:bind-expr size_i_o env) 
		 (arm:bind-expr num_3 env) (arm:bind-expr num_4 env) (arm:bind-expr num_5 env) 
		 (arm:bind-expr prec_i_o env) (arm:bind-expr num_7 env) (arm:bind-expr num_8 env) 
		 (arm:bind-expr num_9 env) (arm:bind-expr num_10 env) (arm:bind-expr num_11 env) 
		 (arm:bind-expr num_12 env) (arm:bind-expr num_13 env))
	]
	[ (vsubq_u32_dsl v0 v1 size_i_o num_3 num_4 num_5 prec_i_o num_7)
		(vsubq_u32_dsl (arm:bind-expr v0 env) (arm:bind-expr v1 env) (arm:bind-expr size_i_o env) 
		 (arm:bind-expr num_3 env) (arm:bind-expr num_4 env) (arm:bind-expr num_5 env) 
		 (arm:bind-expr prec_i_o env) (arm:bind-expr num_7 env))
	]
	[ (vqshrn_n_s64_dsl v0 v1 size_i_o num_3 num_4 num_5 prec_o num_7 prec_i num_9)
		(vqshrn_n_s64_dsl (arm:bind-expr v0 env) (arm:bind-expr v1 env) (arm:bind-expr size_i_o env) 
		 (arm:bind-expr num_3 env) (arm:bind-expr num_4 env) (arm:bind-expr num_5 env) 
		 (arm:bind-expr prec_o env) (arm:bind-expr num_7 env) (arm:bind-expr prec_i env) 
		 (arm:bind-expr num_9 env))
	]
	[ (vhadd_s32_dsl v0 v1 size_i_o num_3 num_4 num_5 prec_i_o num_7 num_8 num_9 num_10 num_11 num_12)
		(vhadd_s32_dsl (arm:bind-expr v0 env) (arm:bind-expr v1 env) (arm:bind-expr size_i_o env) 
		 (arm:bind-expr num_3 env) (arm:bind-expr num_4 env) (arm:bind-expr num_5 env) 
		 (arm:bind-expr prec_i_o env) (arm:bind-expr num_7 env) (arm:bind-expr num_8 env) 
		 (arm:bind-expr num_9 env) (arm:bind-expr num_10 env) (arm:bind-expr num_11 env) 
		 (arm:bind-expr num_12 env))
	]
	[ (vshll_high_n_s8_dsl v0 v1 size_o num_3 num_4 num_5 prec_o num_7 num_8 num_9 num_10 num_11)
		(vshll_high_n_s8_dsl (arm:bind-expr v0 env) (arm:bind-expr v1 env) (arm:bind-expr size_o env) 
		 (arm:bind-expr num_3 env) (arm:bind-expr num_4 env) (arm:bind-expr num_5 env) 
		 (arm:bind-expr prec_o env) (arm:bind-expr num_7 env) (arm:bind-expr num_8 env) 
		 (arm:bind-expr num_9 env) (arm:bind-expr num_10 env) (arm:bind-expr num_11 env))
	]
	[ (vdotq_s32_dsl v0 v1 v2 size_i prec_o num_5 num_6 prec_i num_8 num_9 num_10)
		(vdotq_s32_dsl (arm:bind-expr v0 env) (arm:bind-expr v1 env) (arm:bind-expr v2 env) 
		 (arm:bind-expr size_i env) (arm:bind-expr prec_o env) (arm:bind-expr num_5 env) 
		 (arm:bind-expr num_6 env) (arm:bind-expr prec_i env) (arm:bind-expr num_8 env) 
		 (arm:bind-expr num_9 env) (arm:bind-expr num_10 env))
	]
	[ (vmax_u8_dsl v0 v1 size_i_o num_3 num_4 num_5 prec_i_o num_7 num_8)
		(vmax_u8_dsl (arm:bind-expr v0 env) (arm:bind-expr v1 env) (arm:bind-expr size_i_o env) 
		 (arm:bind-expr num_3 env) (arm:bind-expr num_4 env) (arm:bind-expr num_5 env) 
		 (arm:bind-expr prec_i_o env) (arm:bind-expr num_7 env) (arm:bind-expr num_8 env))
	]
	[ (vmlsl_n_u16_dsl v0 v1 v2 size_i_o num_4 num_5 num_6 prec_i num_8 num_9 prec_o num_11 num_12 num_13 num_14)
		(vmlsl_n_u16_dsl (arm:bind-expr v0 env) (arm:bind-expr v1 env) (arm:bind-expr v2 env) 
		 (arm:bind-expr size_i_o env) (arm:bind-expr num_4 env) (arm:bind-expr num_5 env) 
		 (arm:bind-expr num_6 env) (arm:bind-expr prec_i env) (arm:bind-expr num_8 env) 
		 (arm:bind-expr num_9 env) (arm:bind-expr prec_o env) (arm:bind-expr num_11 env) 
		 (arm:bind-expr num_12 env) (arm:bind-expr num_13 env) (arm:bind-expr num_14 env))
	]
	[v v]
 )
)
;; ================================================================================

