;#============================== Hydride File =================================
;#
;# Part of the Hydride Compiler Infrastructure.
;# <Placeholder for license information>
;#
;#=============================================================================
;#
;# Do NOT modify this file. It is automatically generated.
;#
;#=============================================================================

#lang rosette
(require rosette/lib/synthax)
(require rosette/lib/angelic)
(require racket/pretty)
(require rosette/lib/destruct)
(require rosette/solver/smt/boolector)

(require hydride/utils/bvops)
(require hydride/utils/misc)


(require hydride/ir/hydride/definition)

(require hydride/ir/arm/semantics)
(require hydride/ir/arm/definition)
(require hydride/ir/arm/length)


(provide (all-defined-out))
;; ================================================================================
;;                                DSL Binder
;; ================================================================================
(define (arm:bind-expr prog env)
 (destruct prog
	[(dim-x id) (dim-x id)]
	[(dim-y id) (dim-y id)]
	[(idx-i id) (idx-i id)]
	[(idx-j id) (idx-j id)]
	[(reg id) (vector-ref-bv env id)]
	[(lit v) (lit v)]
	[(idx-add i1 i2) (idx-add i1 i2)]
	[(idx-mul i1 i2) (idx-mul i1 i2)]
	[ (vector-two-input-swizzle_dsl v0 v1 num_2 prec_i_o num_4 num_5 num_6 num_7 num_8)
		(vector-two-input-swizzle_dsl (arm:bind-expr v0 env) (arm:bind-expr v1 env) (arm:bind-expr num_2 env) 
		 (arm:bind-expr prec_i_o env) (arm:bind-expr num_4 env) (arm:bind-expr num_5 env) 
		 (arm:bind-expr num_6 env) (arm:bind-expr num_7 env) (arm:bind-expr num_8 env))
	]
	[ (interleave-vectors_dsl v0 v1 size_i_o prec_i_o)
		(interleave-vectors_dsl (arm:bind-expr v0 env) (arm:bind-expr v1 env) (arm:bind-expr size_i_o env) 
		 (arm:bind-expr prec_i_o env))
	]
	[ (interleave-vector_dsl v0 size_i_o prec_i_o)
		(interleave-vector_dsl (arm:bind-expr v0 env) (arm:bind-expr size_i_o env) (arm:bind-expr prec_i_o env))
	]
	[ (deinterleave-vector_dsl v0 size_i_o prec_i_o)
		(deinterleave-vector_dsl (arm:bind-expr v0 env) (arm:bind-expr size_i_o env) (arm:bind-expr prec_i_o env))
	]
	[ (llvm_shuffle_vectors_dsl v0 v1 num_2 prec_i_o v4 num_5)
		(llvm_shuffle_vectors_dsl (arm:bind-expr v0 env) (arm:bind-expr v1 env) (arm:bind-expr num_2 env) 
		 (arm:bind-expr prec_i_o env) (arm:bind-expr v4 env) (arm:bind-expr num_5 env))
	]
	[ (vraddhn_s32_dsl vc_0 v1 v2 size_i_o num_4 num_5 num_6 prec_o num_8 num_9 num_10 prec_i num_12)
		(vraddhn_s32_dsl (arm:bind-expr vc_0 env) (arm:bind-expr v1 env) (arm:bind-expr v2 env) 
		 (arm:bind-expr size_i_o env) (arm:bind-expr num_4 env) (arm:bind-expr num_5 env) 
		 (arm:bind-expr num_6 env) (arm:bind-expr prec_o env) (arm:bind-expr num_8 env) 
		 (arm:bind-expr num_9 env) (arm:bind-expr num_10 env) (arm:bind-expr prec_i env) 
		 (arm:bind-expr num_12 env))
	]
	[ (vmla_n_s32_dsl v0 v1 v2 size_i_o num_4 num_5 num_6 prec_i_o num_8 num_9 num_10 num_11)
		(vmla_n_s32_dsl (arm:bind-expr v0 env) (arm:bind-expr v1 env) (arm:bind-expr v2 env) 
		 (arm:bind-expr size_i_o env) (arm:bind-expr num_4 env) (arm:bind-expr num_5 env) 
		 (arm:bind-expr num_6 env) (arm:bind-expr prec_i_o env) (arm:bind-expr num_8 env) 
		 (arm:bind-expr num_9 env) (arm:bind-expr num_10 env) (arm:bind-expr num_11 env))
	]
	[ (vshl_s8_dsl vc_0 v1 v2 size_i_o num_4 num_5 num_6 prec_i_o num_8 num_9 num_10 num_11)
		(vshl_s8_dsl (arm:bind-expr vc_0 env) (arm:bind-expr v1 env) (arm:bind-expr v2 env) 
		 (arm:bind-expr size_i_o env) (arm:bind-expr num_4 env) (arm:bind-expr num_5 env) 
		 (arm:bind-expr num_6 env) (arm:bind-expr prec_i_o env) (arm:bind-expr num_8 env) 
		 (arm:bind-expr num_9 env) (arm:bind-expr num_10 env) (arm:bind-expr num_11 env))
	]
	[ (vsubw_high_u8_dsl v0 v1 size_i_o num_3 num_4 num_5 prec_i_o num_7 num_8 num_9 num_10 num_11 num_12)
		(vsubw_high_u8_dsl (arm:bind-expr v0 env) (arm:bind-expr v1 env) (arm:bind-expr size_i_o env) 
		 (arm:bind-expr num_3 env) (arm:bind-expr num_4 env) (arm:bind-expr num_5 env) 
		 (arm:bind-expr prec_i_o env) (arm:bind-expr num_7 env) (arm:bind-expr num_8 env) 
		 (arm:bind-expr num_9 env) (arm:bind-expr num_10 env) (arm:bind-expr num_11 env) 
		 (arm:bind-expr num_12 env))
	]
	[ (vmull_n_u16_dsl v0 v1 size_i_o num_3 num_4 num_5 prec_i num_7 prec_o num_9 num_10 num_11)
		(vmull_n_u16_dsl (arm:bind-expr v0 env) (arm:bind-expr v1 env) (arm:bind-expr size_i_o env) 
		 (arm:bind-expr num_3 env) (arm:bind-expr num_4 env) (arm:bind-expr num_5 env) 
		 (arm:bind-expr prec_i env) (arm:bind-expr num_7 env) (arm:bind-expr prec_o env) 
		 (arm:bind-expr num_9 env) (arm:bind-expr num_10 env) (arm:bind-expr num_11 env))
	]
	[ (vmlsl_high_n_s32_dsl v0 v1 v2 size_i_o num_4 num_5 num_6 prec_i_o num_8 num_9 num_10 num_11 num_12 num_13)
		(vmlsl_high_n_s32_dsl (arm:bind-expr v0 env) (arm:bind-expr v1 env) (arm:bind-expr v2 env) 
		 (arm:bind-expr size_i_o env) (arm:bind-expr num_4 env) (arm:bind-expr num_5 env) 
		 (arm:bind-expr num_6 env) (arm:bind-expr prec_i_o env) (arm:bind-expr num_8 env) 
		 (arm:bind-expr num_9 env) (arm:bind-expr num_10 env) (arm:bind-expr num_11 env) 
		 (arm:bind-expr num_12 env) (arm:bind-expr num_13 env))
	]
	[ (vmlaq_n_u16_dsl v0 v1 v2 size_i_o num_4 num_5 num_6 prec_i_o num_8 num_9 num_10 num_11)
		(vmlaq_n_u16_dsl (arm:bind-expr v0 env) (arm:bind-expr v1 env) (arm:bind-expr v2 env) 
		 (arm:bind-expr size_i_o env) (arm:bind-expr num_4 env) (arm:bind-expr num_5 env) 
		 (arm:bind-expr num_6 env) (arm:bind-expr prec_i_o env) (arm:bind-expr num_8 env) 
		 (arm:bind-expr num_9 env) (arm:bind-expr num_10 env) (arm:bind-expr num_11 env))
	]
	[ (vaddl_high_s16_dsl v0 v1 size_o num_3 num_4 num_5 prec_o num_7 num_8 num_9 num_10 num_11 num_12)
		(vaddl_high_s16_dsl (arm:bind-expr v0 env) (arm:bind-expr v1 env) (arm:bind-expr size_o env) 
		 (arm:bind-expr num_3 env) (arm:bind-expr num_4 env) (arm:bind-expr num_5 env) 
		 (arm:bind-expr prec_o env) (arm:bind-expr num_7 env) (arm:bind-expr num_8 env) 
		 (arm:bind-expr num_9 env) (arm:bind-expr num_10 env) (arm:bind-expr num_11 env) 
		 (arm:bind-expr num_12 env))
	]
	[ (vqsub_u8_dsl v0 v1 size_i_o num_3 num_4 num_5 prec_i_o num_7 num_8 num_9 num_10)
		(vqsub_u8_dsl (arm:bind-expr v0 env) (arm:bind-expr v1 env) (arm:bind-expr size_i_o env) 
		 (arm:bind-expr num_3 env) (arm:bind-expr num_4 env) (arm:bind-expr num_5 env) 
		 (arm:bind-expr prec_i_o env) (arm:bind-expr num_7 env) (arm:bind-expr num_8 env) 
		 (arm:bind-expr num_9 env) (arm:bind-expr num_10 env))
	]
	[ (vpminq_s32_dsl v0 v1 size_i_o num_3 num_4 num_5 prec_o num_7 num_8 num_9 num_10 num_11 num_12 num_13 num_14 prec_i num_16)
		(vpminq_s32_dsl (arm:bind-expr v0 env) (arm:bind-expr v1 env) (arm:bind-expr size_i_o env) 
		 (arm:bind-expr num_3 env) (arm:bind-expr num_4 env) (arm:bind-expr num_5 env) 
		 (arm:bind-expr prec_o env) (arm:bind-expr num_7 env) (arm:bind-expr num_8 env) 
		 (arm:bind-expr num_9 env) (arm:bind-expr num_10 env) (arm:bind-expr num_11 env) 
		 (arm:bind-expr num_12 env) (arm:bind-expr num_13 env) (arm:bind-expr num_14 env) 
		 (arm:bind-expr prec_i env) (arm:bind-expr num_16 env))
	]
	[ (vqdmull_n_s16_dsl vc_0 v1 v2 size_i_o num_4 num_5 num_6 prec_i num_8 prec_o num_10 num_11 num_12)
		(vqdmull_n_s16_dsl (arm:bind-expr vc_0 env) (arm:bind-expr v1 env) (arm:bind-expr v2 env) 
		 (arm:bind-expr size_i_o env) (arm:bind-expr num_4 env) (arm:bind-expr num_5 env) 
		 (arm:bind-expr num_6 env) (arm:bind-expr prec_i env) (arm:bind-expr num_8 env) 
		 (arm:bind-expr prec_o env) (arm:bind-expr num_10 env) (arm:bind-expr num_11 env) 
		 (arm:bind-expr num_12 env))
	]
	[ (vuqaddq_s8_dsl v0 v1 size_i_o num_3 num_4 num_5 prec_i_o num_7 num_8 num_9 num_10)
		(vuqaddq_s8_dsl (arm:bind-expr v0 env) (arm:bind-expr v1 env) (arm:bind-expr size_i_o env) 
		 (arm:bind-expr num_3 env) (arm:bind-expr num_4 env) (arm:bind-expr num_5 env) 
		 (arm:bind-expr prec_i_o env) (arm:bind-expr num_7 env) (arm:bind-expr num_8 env) 
		 (arm:bind-expr num_9 env) (arm:bind-expr num_10 env))
	]
	[ (vcgtzq_s64_dsl vc_0 vc_1 vc_2 v3 size_i_o num_5 num_6 num_7 prec_i_o num_9 num_10)
		(vcgtzq_s64_dsl (arm:bind-expr vc_0 env) (arm:bind-expr vc_1 env) (arm:bind-expr vc_2 env) 
		 (arm:bind-expr v3 env) (arm:bind-expr size_i_o env) (arm:bind-expr num_5 env) 
		 (arm:bind-expr num_6 env) (arm:bind-expr num_7 env) (arm:bind-expr prec_i_o env) 
		 (arm:bind-expr num_9 env) (arm:bind-expr num_10 env))
	]
	[ (vrshlq_s8_dsl vc_0 vc_1 v2 v3 size_i_o num_5 num_6 num_7 prec_i_o num_9 num_10 num_11 num_12 num_13)
		(vrshlq_s8_dsl (arm:bind-expr vc_0 env) (arm:bind-expr vc_1 env) (arm:bind-expr v2 env) 
		 (arm:bind-expr v3 env) (arm:bind-expr size_i_o env) (arm:bind-expr num_5 env) 
		 (arm:bind-expr num_6 env) (arm:bind-expr num_7 env) (arm:bind-expr prec_i_o env) 
		 (arm:bind-expr num_9 env) (arm:bind-expr num_10 env) (arm:bind-expr num_11 env) 
		 (arm:bind-expr num_12 env) (arm:bind-expr num_13 env))
	]
	[ (vqdmulhq_n_s32_dsl vc_0 vc_1 vc_2 v3 v4 size_i_o num_6 num_7 num_8 prec_i_o num_10 num_11 num_12 num_13)
		(vqdmulhq_n_s32_dsl (arm:bind-expr vc_0 env) (arm:bind-expr vc_1 env) (arm:bind-expr vc_2 env) 
		 (arm:bind-expr v3 env) (arm:bind-expr v4 env) (arm:bind-expr size_i_o env) 
		 (arm:bind-expr num_6 env) (arm:bind-expr num_7 env) (arm:bind-expr num_8 env) 
		 (arm:bind-expr prec_i_o env) (arm:bind-expr num_10 env) (arm:bind-expr num_11 env) 
		 (arm:bind-expr num_12 env) (arm:bind-expr num_13 env))
	]
	[ (vqabs_s8_dsl v0 size_i_o num_2 num_3 num_4 prec_i_o num_6 num_7)
		(vqabs_s8_dsl (arm:bind-expr v0 env) (arm:bind-expr size_i_o env) (arm:bind-expr num_2 env) 
		 (arm:bind-expr num_3 env) (arm:bind-expr num_4 env) (arm:bind-expr prec_i_o env) 
		 (arm:bind-expr num_6 env) (arm:bind-expr num_7 env))
	]
	[ (vmovn_u64_dsl v0 size_i_o num_2 num_3 num_4 prec_i_o num_6)
		(vmovn_u64_dsl (arm:bind-expr v0 env) (arm:bind-expr size_i_o env) (arm:bind-expr num_2 env) 
		 (arm:bind-expr num_3 env) (arm:bind-expr num_4 env) (arm:bind-expr prec_i_o env) 
		 (arm:bind-expr num_6 env))
	]
	[ (vabd_u16_dsl vc_0 v1 v2 size_i_o num_4 num_5 num_6 prec_i_o num_8 num_9 num_10 num_11 num_12)
		(vabd_u16_dsl (arm:bind-expr vc_0 env) (arm:bind-expr v1 env) (arm:bind-expr v2 env) 
		 (arm:bind-expr size_i_o env) (arm:bind-expr num_4 env) (arm:bind-expr num_5 env) 
		 (arm:bind-expr num_6 env) (arm:bind-expr prec_i_o env) (arm:bind-expr num_8 env) 
		 (arm:bind-expr num_9 env) (arm:bind-expr num_10 env) (arm:bind-expr num_11 env) 
		 (arm:bind-expr num_12 env))
	]
	[ (vqdmlals_s32_dsl vc_0 v1 v2 v3 size_i_o num_5 num_6 num_7 prec_i prec_o num_10 num_11 num_12 num_13 num_14 num_15 num_16 num_17 num_18)
		(vqdmlals_s32_dsl (arm:bind-expr vc_0 env) (arm:bind-expr v1 env) (arm:bind-expr v2 env) 
		 (arm:bind-expr v3 env) (arm:bind-expr size_i_o env) (arm:bind-expr num_5 env) 
		 (arm:bind-expr num_6 env) (arm:bind-expr num_7 env) (arm:bind-expr prec_i env) 
		 (arm:bind-expr prec_o env) (arm:bind-expr num_10 env) (arm:bind-expr num_11 env) 
		 (arm:bind-expr num_12 env) (arm:bind-expr num_13 env) (arm:bind-expr num_14 env) 
		 (arm:bind-expr num_15 env) (arm:bind-expr num_16 env) (arm:bind-expr num_17 env) 
		 (arm:bind-expr num_18 env))
	]
	[ (vmul_n_s32_dsl v0 v1 size_i_o num_3 num_4 num_5 prec_i_o num_7 num_8 num_9)
		(vmul_n_s32_dsl (arm:bind-expr v0 env) (arm:bind-expr v1 env) (arm:bind-expr size_i_o env) 
		 (arm:bind-expr num_3 env) (arm:bind-expr num_4 env) (arm:bind-expr num_5 env) 
		 (arm:bind-expr prec_i_o env) (arm:bind-expr num_7 env) (arm:bind-expr num_8 env) 
		 (arm:bind-expr num_9 env))
	]
	[ (vsubl_s8_dsl v0 v1 size_i_o num_3 num_4 num_5 prec_i prec_o num_8 num_9 num_10 num_11 num_12)
		(vsubl_s8_dsl (arm:bind-expr v0 env) (arm:bind-expr v1 env) (arm:bind-expr size_i_o env) 
		 (arm:bind-expr num_3 env) (arm:bind-expr num_4 env) (arm:bind-expr num_5 env) 
		 (arm:bind-expr prec_i env) (arm:bind-expr prec_o env) (arm:bind-expr num_8 env) 
		 (arm:bind-expr num_9 env) (arm:bind-expr num_10 env) (arm:bind-expr num_11 env) 
		 (arm:bind-expr num_12 env))
	]
	[ (vshll_high_n_u8_dsl v0 v1 size_o num_3 num_4 num_5 prec_o num_7 num_8 num_9 num_10)
		(vshll_high_n_u8_dsl (arm:bind-expr v0 env) (arm:bind-expr v1 env) (arm:bind-expr size_o env) 
		 (arm:bind-expr num_3 env) (arm:bind-expr num_4 env) (arm:bind-expr num_5 env) 
		 (arm:bind-expr prec_o env) (arm:bind-expr num_7 env) (arm:bind-expr num_8 env) 
		 (arm:bind-expr num_9 env) (arm:bind-expr num_10 env))
	]
	[ (vmvnq_s8_dsl v0 size_i_o num_2 num_3 num_4 prec_i_o)
		(vmvnq_s8_dsl (arm:bind-expr v0 env) (arm:bind-expr size_i_o env) (arm:bind-expr num_2 env) 
		 (arm:bind-expr num_3 env) (arm:bind-expr num_4 env) (arm:bind-expr prec_i_o env))
	]
	[ (vsraq_n_s32_dsl vc_0 v1 v2 v3 size_i_o num_5 num_6 num_7 prec_i_o num_9 num_10 num_11 num_12)
		(vsraq_n_s32_dsl (arm:bind-expr vc_0 env) (arm:bind-expr v1 env) (arm:bind-expr v2 env) 
		 (arm:bind-expr v3 env) (arm:bind-expr size_i_o env) (arm:bind-expr num_5 env) 
		 (arm:bind-expr num_6 env) (arm:bind-expr num_7 env) (arm:bind-expr prec_i_o env) 
		 (arm:bind-expr num_9 env) (arm:bind-expr num_10 env) (arm:bind-expr num_11 env) 
		 (arm:bind-expr num_12 env))
	]
	[ (vqdmull_high_n_s32_dsl vc_0 v1 v2 size_o num_4 num_5 num_6 prec_o num_8 num_9 num_10 num_11 num_12)
		(vqdmull_high_n_s32_dsl (arm:bind-expr vc_0 env) (arm:bind-expr v1 env) (arm:bind-expr v2 env) 
		 (arm:bind-expr size_o env) (arm:bind-expr num_4 env) (arm:bind-expr num_5 env) 
		 (arm:bind-expr num_6 env) (arm:bind-expr prec_o env) (arm:bind-expr num_8 env) 
		 (arm:bind-expr num_9 env) (arm:bind-expr num_10 env) (arm:bind-expr num_11 env) 
		 (arm:bind-expr num_12 env))
	]
	[ (vsubhn_s32_dsl vc_0 v1 v2 size_i_o num_4 num_5 num_6 prec_o num_8 num_9 num_10 prec_i num_12)
		(vsubhn_s32_dsl (arm:bind-expr vc_0 env) (arm:bind-expr v1 env) (arm:bind-expr v2 env) 
		 (arm:bind-expr size_i_o env) (arm:bind-expr num_4 env) (arm:bind-expr num_5 env) 
		 (arm:bind-expr num_6 env) (arm:bind-expr prec_o env) (arm:bind-expr num_8 env) 
		 (arm:bind-expr num_9 env) (arm:bind-expr num_10 env) (arm:bind-expr prec_i env) 
		 (arm:bind-expr num_12 env))
	]
	[ (vclt_u32_dsl vc_0 vc_1 v2 v3 size_i_o num_5 num_6 num_7 prec_i_o num_9 num_10 num_11)
		(vclt_u32_dsl (arm:bind-expr vc_0 env) (arm:bind-expr vc_1 env) (arm:bind-expr v2 env) 
		 (arm:bind-expr v3 env) (arm:bind-expr size_i_o env) (arm:bind-expr num_5 env) 
		 (arm:bind-expr num_6 env) (arm:bind-expr num_7 env) (arm:bind-expr prec_i_o env) 
		 (arm:bind-expr num_9 env) (arm:bind-expr num_10 env) (arm:bind-expr num_11 env))
	]
	[ (vqmovn_s32_dsl v0 size_i_o num_2 num_3 num_4 prec_o num_6 num_7 prec_i num_9)
		(vqmovn_s32_dsl (arm:bind-expr v0 env) (arm:bind-expr size_i_o env) (arm:bind-expr num_2 env) 
		 (arm:bind-expr num_3 env) (arm:bind-expr num_4 env) (arm:bind-expr prec_o env) 
		 (arm:bind-expr num_6 env) (arm:bind-expr num_7 env) (arm:bind-expr prec_i env) 
		 (arm:bind-expr num_9 env))
	]
	[ (vqshlq_s64_dsl vc_0 v1 v2 size_i_o num_4 num_5 num_6 prec_i prec_o num_9 num_10 num_11 num_12 num_13)
		(vqshlq_s64_dsl (arm:bind-expr vc_0 env) (arm:bind-expr v1 env) (arm:bind-expr v2 env) 
		 (arm:bind-expr size_i_o env) (arm:bind-expr num_4 env) (arm:bind-expr num_5 env) 
		 (arm:bind-expr num_6 env) (arm:bind-expr prec_i env) (arm:bind-expr prec_o env) 
		 (arm:bind-expr num_9 env) (arm:bind-expr num_10 env) (arm:bind-expr num_11 env) 
		 (arm:bind-expr num_12 env) (arm:bind-expr num_13 env))
	]
	[ (vceqzq_s64_dsl v0 vc_1 vc_2 vc_3 size_i_o num_5 num_6 num_7 prec_i_o num_9)
		(vceqzq_s64_dsl (arm:bind-expr v0 env) (arm:bind-expr vc_1 env) (arm:bind-expr vc_2 env) 
		 (arm:bind-expr vc_3 env) (arm:bind-expr size_i_o env) (arm:bind-expr num_5 env) 
		 (arm:bind-expr num_6 env) (arm:bind-expr num_7 env) (arm:bind-expr prec_i_o env) 
		 (arm:bind-expr num_9 env))
	]
	[ (vmlal_s32_dsl v0 v1 v2 size_i_o num_4 num_5 num_6 prec_i prec_o num_9 num_10 num_11 num_12 num_13)
		(vmlal_s32_dsl (arm:bind-expr v0 env) (arm:bind-expr v1 env) (arm:bind-expr v2 env) 
		 (arm:bind-expr size_i_o env) (arm:bind-expr num_4 env) (arm:bind-expr num_5 env) 
		 (arm:bind-expr num_6 env) (arm:bind-expr prec_i env) (arm:bind-expr prec_o env) 
		 (arm:bind-expr num_9 env) (arm:bind-expr num_10 env) (arm:bind-expr num_11 env) 
		 (arm:bind-expr num_12 env) (arm:bind-expr num_13 env))
	]
	[ (vqdmlsl_high_n_s32_dsl vc_0 v1 v2 v3 size_i_o num_5 num_6 num_7 prec_i_o num_9 num_10 num_11 num_12 num_13 num_14 num_15 num_16 num_17 num_18)
		(vqdmlsl_high_n_s32_dsl (arm:bind-expr vc_0 env) (arm:bind-expr v1 env) (arm:bind-expr v2 env) 
		 (arm:bind-expr v3 env) (arm:bind-expr size_i_o env) (arm:bind-expr num_5 env) 
		 (arm:bind-expr num_6 env) (arm:bind-expr num_7 env) (arm:bind-expr prec_i_o env) 
		 (arm:bind-expr num_9 env) (arm:bind-expr num_10 env) (arm:bind-expr num_11 env) 
		 (arm:bind-expr num_12 env) (arm:bind-expr num_13 env) (arm:bind-expr num_14 env) 
		 (arm:bind-expr num_15 env) (arm:bind-expr num_16 env) (arm:bind-expr num_17 env) 
		 (arm:bind-expr num_18 env))
	]
	[ (vabdl_high_s8_dsl vc_0 v1 v2 size_o num_4 num_5 num_6 prec_o num_8 num_9 num_10 num_11 num_12 num_13 num_14)
		(vabdl_high_s8_dsl (arm:bind-expr vc_0 env) (arm:bind-expr v1 env) (arm:bind-expr v2 env) 
		 (arm:bind-expr size_o env) (arm:bind-expr num_4 env) (arm:bind-expr num_5 env) 
		 (arm:bind-expr num_6 env) (arm:bind-expr prec_o env) (arm:bind-expr num_8 env) 
		 (arm:bind-expr num_9 env) (arm:bind-expr num_10 env) (arm:bind-expr num_11 env) 
		 (arm:bind-expr num_12 env) (arm:bind-expr num_13 env) (arm:bind-expr num_14 env))
	]
	[ (vmovq_n_u8_dsl v0 size_o num_2 num_3 num_4 prec_o)
		(vmovq_n_u8_dsl (arm:bind-expr v0 env) (arm:bind-expr size_o env) (arm:bind-expr num_2 env) 
		 (arm:bind-expr num_3 env) (arm:bind-expr num_4 env) (arm:bind-expr prec_o env))
	]
	[ (vrhaddq_s8_dsl vc_0 v1 v2 size_i_o num_4 num_5 num_6 prec_i_o num_8 num_9 num_10 num_11 num_12)
		(vrhaddq_s8_dsl (arm:bind-expr vc_0 env) (arm:bind-expr v1 env) (arm:bind-expr v2 env) 
		 (arm:bind-expr size_i_o env) (arm:bind-expr num_4 env) (arm:bind-expr num_5 env) 
		 (arm:bind-expr num_6 env) (arm:bind-expr prec_i_o env) (arm:bind-expr num_8 env) 
		 (arm:bind-expr num_9 env) (arm:bind-expr num_10 env) (arm:bind-expr num_11 env) 
		 (arm:bind-expr num_12 env))
	]
	[ (vtst_s8_dsl vc_0 vc_1 v2 v3 size_i_o num_5 num_6 num_7 prec_i_o)
		(vtst_s8_dsl (arm:bind-expr vc_0 env) (arm:bind-expr vc_1 env) (arm:bind-expr v2 env) 
		 (arm:bind-expr v3 env) (arm:bind-expr size_i_o env) (arm:bind-expr num_5 env) 
		 (arm:bind-expr num_6 env) (arm:bind-expr num_7 env) (arm:bind-expr prec_i_o env))
	]
	[ (vmovl_high_u16_dsl vc_0 v1 size_o num_3 num_4 num_5 prec_o num_7 num_8 num_9 num_10)
		(vmovl_high_u16_dsl (arm:bind-expr vc_0 env) (arm:bind-expr v1 env) (arm:bind-expr size_o env) 
		 (arm:bind-expr num_3 env) (arm:bind-expr num_4 env) (arm:bind-expr num_5 env) 
		 (arm:bind-expr prec_o env) (arm:bind-expr num_7 env) (arm:bind-expr num_8 env) 
		 (arm:bind-expr num_9 env) (arm:bind-expr num_10 env))
	]
	[ (vqdmlal_high_n_s32_dsl vc_0 v1 v2 v3 size_i_o num_5 num_6 num_7 prec_i_o num_9 num_10 num_11 num_12 num_13 num_14 num_15 num_16 num_17 num_18)
		(vqdmlal_high_n_s32_dsl (arm:bind-expr vc_0 env) (arm:bind-expr v1 env) (arm:bind-expr v2 env) 
		 (arm:bind-expr v3 env) (arm:bind-expr size_i_o env) (arm:bind-expr num_5 env) 
		 (arm:bind-expr num_6 env) (arm:bind-expr num_7 env) (arm:bind-expr prec_i_o env) 
		 (arm:bind-expr num_9 env) (arm:bind-expr num_10 env) (arm:bind-expr num_11 env) 
		 (arm:bind-expr num_12 env) (arm:bind-expr num_13 env) (arm:bind-expr num_14 env) 
		 (arm:bind-expr num_15 env) (arm:bind-expr num_16 env) (arm:bind-expr num_17 env) 
		 (arm:bind-expr num_18 env))
	]
	[ (vmls_n_s16_dsl v0 v1 v2 size_i_o num_4 num_5 num_6 prec_i_o num_8 num_9 num_10 num_11)
		(vmls_n_s16_dsl (arm:bind-expr v0 env) (arm:bind-expr v1 env) (arm:bind-expr v2 env) 
		 (arm:bind-expr size_i_o env) (arm:bind-expr num_4 env) (arm:bind-expr num_5 env) 
		 (arm:bind-expr num_6 env) (arm:bind-expr prec_i_o env) (arm:bind-expr num_8 env) 
		 (arm:bind-expr num_9 env) (arm:bind-expr num_10 env) (arm:bind-expr num_11 env))
	]
	[ (vcgt_u16_dsl vc_0 vc_1 v2 v3 size_i_o num_5 num_6 num_7 prec_i_o num_9 num_10 num_11)
		(vcgt_u16_dsl (arm:bind-expr vc_0 env) (arm:bind-expr vc_1 env) (arm:bind-expr v2 env) 
		 (arm:bind-expr v3 env) (arm:bind-expr size_i_o env) (arm:bind-expr num_5 env) 
		 (arm:bind-expr num_6 env) (arm:bind-expr num_7 env) (arm:bind-expr prec_i_o env) 
		 (arm:bind-expr num_9 env) (arm:bind-expr num_10 env) (arm:bind-expr num_11 env))
	]
	[ (vsub_s64_dsl v0 v1 size_i_o num_3 num_4 num_5 prec_i_o num_7)
		(vsub_s64_dsl (arm:bind-expr v0 env) (arm:bind-expr v1 env) (arm:bind-expr size_i_o env) 
		 (arm:bind-expr num_3 env) (arm:bind-expr num_4 env) (arm:bind-expr num_5 env) 
		 (arm:bind-expr prec_i_o env) (arm:bind-expr num_7 env))
	]
	[ (vceq_s8_dsl v0 vc_1 v2 vc_3 size_i_o num_5 num_6 num_7 prec_i_o)
		(vceq_s8_dsl (arm:bind-expr v0 env) (arm:bind-expr vc_1 env) (arm:bind-expr v2 env) 
		 (arm:bind-expr vc_3 env) (arm:bind-expr size_i_o env) (arm:bind-expr num_5 env) 
		 (arm:bind-expr num_6 env) (arm:bind-expr num_7 env) (arm:bind-expr prec_i_o env))
	]
	[ (vmlaq_s32_dsl v0 v1 v2 size_i_o num_4 num_5 num_6 prec_i_o num_8 num_9 num_10 num_11)
		(vmlaq_s32_dsl (arm:bind-expr v0 env) (arm:bind-expr v1 env) (arm:bind-expr v2 env) 
		 (arm:bind-expr size_i_o env) (arm:bind-expr num_4 env) (arm:bind-expr num_5 env) 
		 (arm:bind-expr num_6 env) (arm:bind-expr prec_i_o env) (arm:bind-expr num_8 env) 
		 (arm:bind-expr num_9 env) (arm:bind-expr num_10 env) (arm:bind-expr num_11 env))
	]
	[ (vqdmull_high_s32_dsl vc_0 v1 v2 size_o num_4 num_5 num_6 prec_o num_8 num_9 num_10 num_11 num_12)
		(vqdmull_high_s32_dsl (arm:bind-expr vc_0 env) (arm:bind-expr v1 env) (arm:bind-expr v2 env) 
		 (arm:bind-expr size_o env) (arm:bind-expr num_4 env) (arm:bind-expr num_5 env) 
		 (arm:bind-expr num_6 env) (arm:bind-expr prec_o env) (arm:bind-expr num_8 env) 
		 (arm:bind-expr num_9 env) (arm:bind-expr num_10 env) (arm:bind-expr num_11 env) 
		 (arm:bind-expr num_12 env))
	]
	[ (vabdl_s8_dsl vc_0 v1 v2 size_i_o num_4 num_5 num_6 prec_i prec_o num_9 num_10 num_11 num_12 num_13 num_14)
		(vabdl_s8_dsl (arm:bind-expr vc_0 env) (arm:bind-expr v1 env) (arm:bind-expr v2 env) 
		 (arm:bind-expr size_i_o env) (arm:bind-expr num_4 env) (arm:bind-expr num_5 env) 
		 (arm:bind-expr num_6 env) (arm:bind-expr prec_i env) (arm:bind-expr prec_o env) 
		 (arm:bind-expr num_9 env) (arm:bind-expr num_10 env) (arm:bind-expr num_11 env) 
		 (arm:bind-expr num_12 env) (arm:bind-expr num_13 env) (arm:bind-expr num_14 env))
	]
	[ (vmlsl_n_s32_dsl v0 v1 v2 size_i_o num_4 num_5 num_6 prec_i num_8 prec_o num_10 num_11 num_12 num_13)
		(vmlsl_n_s32_dsl (arm:bind-expr v0 env) (arm:bind-expr v1 env) (arm:bind-expr v2 env) 
		 (arm:bind-expr size_i_o env) (arm:bind-expr num_4 env) (arm:bind-expr num_5 env) 
		 (arm:bind-expr num_6 env) (arm:bind-expr prec_i env) (arm:bind-expr num_8 env) 
		 (arm:bind-expr prec_o env) (arm:bind-expr num_10 env) (arm:bind-expr num_11 env) 
		 (arm:bind-expr num_12 env) (arm:bind-expr num_13 env))
	]
	[ (vmlsl_high_u32_dsl v0 v1 v2 size_i_o num_4 num_5 num_6 prec_i_o num_8 num_9 num_10 num_11 num_12 num_13)
		(vmlsl_high_u32_dsl (arm:bind-expr v0 env) (arm:bind-expr v1 env) (arm:bind-expr v2 env) 
		 (arm:bind-expr size_i_o env) (arm:bind-expr num_4 env) (arm:bind-expr num_5 env) 
		 (arm:bind-expr num_6 env) (arm:bind-expr prec_i_o env) (arm:bind-expr num_8 env) 
		 (arm:bind-expr num_9 env) (arm:bind-expr num_10 env) (arm:bind-expr num_11 env) 
		 (arm:bind-expr num_12 env) (arm:bind-expr num_13 env))
	]
	[ (vrsra_n_s8_dsl vc_0 vc_1 v2 v3 v4 size_i_o num_6 num_7 num_8 prec_i_o num_10 num_11 num_12 num_13 num_14)
		(vrsra_n_s8_dsl (arm:bind-expr vc_0 env) (arm:bind-expr vc_1 env) (arm:bind-expr v2 env) 
		 (arm:bind-expr v3 env) (arm:bind-expr v4 env) (arm:bind-expr size_i_o env) 
		 (arm:bind-expr num_6 env) (arm:bind-expr num_7 env) (arm:bind-expr num_8 env) 
		 (arm:bind-expr prec_i_o env) (arm:bind-expr num_10 env) (arm:bind-expr num_11 env) 
		 (arm:bind-expr num_12 env) (arm:bind-expr num_13 env) (arm:bind-expr num_14 env))
	]
	[ (vadd_u64_dsl v0 v1 size_i_o num_3 num_4 num_5 prec_i_o num_7)
		(vadd_u64_dsl (arm:bind-expr v0 env) (arm:bind-expr v1 env) (arm:bind-expr size_i_o env) 
		 (arm:bind-expr num_3 env) (arm:bind-expr num_4 env) (arm:bind-expr num_5 env) 
		 (arm:bind-expr prec_i_o env) (arm:bind-expr num_7 env))
	]
	[ (vmull_n_s32_dsl v0 v1 size_i_o num_3 num_4 num_5 prec_i num_7 prec_o num_9 num_10 num_11)
		(vmull_n_s32_dsl (arm:bind-expr v0 env) (arm:bind-expr v1 env) (arm:bind-expr size_i_o env) 
		 (arm:bind-expr num_3 env) (arm:bind-expr num_4 env) (arm:bind-expr num_5 env) 
		 (arm:bind-expr prec_i env) (arm:bind-expr num_7 env) (arm:bind-expr prec_o env) 
		 (arm:bind-expr num_9 env) (arm:bind-expr num_10 env) (arm:bind-expr num_11 env))
	]
	[ (vhadd_u8_dsl v0 v1 size_i_o num_3 num_4 num_5 prec_i_o num_7 num_8 num_9 num_10)
		(vhadd_u8_dsl (arm:bind-expr v0 env) (arm:bind-expr v1 env) (arm:bind-expr size_i_o env) 
		 (arm:bind-expr num_3 env) (arm:bind-expr num_4 env) (arm:bind-expr num_5 env) 
		 (arm:bind-expr prec_i_o env) (arm:bind-expr num_7 env) (arm:bind-expr num_8 env) 
		 (arm:bind-expr num_9 env) (arm:bind-expr num_10 env))
	]
	[ (vaddw_high_s32_dsl v0 v1 size_i_o num_3 num_4 num_5 prec_i_o num_7 num_8 num_9 num_10 num_11 num_12)
		(vaddw_high_s32_dsl (arm:bind-expr v0 env) (arm:bind-expr v1 env) (arm:bind-expr size_i_o env) 
		 (arm:bind-expr num_3 env) (arm:bind-expr num_4 env) (arm:bind-expr num_5 env) 
		 (arm:bind-expr prec_i_o env) (arm:bind-expr num_7 env) (arm:bind-expr num_8 env) 
		 (arm:bind-expr num_9 env) (arm:bind-expr num_10 env) (arm:bind-expr num_11 env) 
		 (arm:bind-expr num_12 env))
	]
	[ (vtrn1_u16_dsl v0 v1 size_i_o num_3 num_4 num_5 num_6 num_7 num_8 prec_i_o num_10 num_11 num_12 num_13 num_14)
		(vtrn1_u16_dsl (arm:bind-expr v0 env) (arm:bind-expr v1 env) (arm:bind-expr size_i_o env) 
		 (arm:bind-expr num_3 env) (arm:bind-expr num_4 env) (arm:bind-expr num_5 env) 
		 (arm:bind-expr num_6 env) (arm:bind-expr num_7 env) (arm:bind-expr num_8 env) 
		 (arm:bind-expr prec_i_o env) (arm:bind-expr num_10 env) (arm:bind-expr num_11 env) 
		 (arm:bind-expr num_12 env) (arm:bind-expr num_13 env) (arm:bind-expr num_14 env))
	]
	[ (vrshl_s32_dsl vc_0 vc_1 v2 v3 size_i_o num_5 num_6 num_7 prec_i prec_o num_10 num_11 num_12 num_13 num_14 num_15)
		(vrshl_s32_dsl (arm:bind-expr vc_0 env) (arm:bind-expr vc_1 env) (arm:bind-expr v2 env) 
		 (arm:bind-expr v3 env) (arm:bind-expr size_i_o env) (arm:bind-expr num_5 env) 
		 (arm:bind-expr num_6 env) (arm:bind-expr num_7 env) (arm:bind-expr prec_i env) 
		 (arm:bind-expr prec_o env) (arm:bind-expr num_10 env) (arm:bind-expr num_11 env) 
		 (arm:bind-expr num_12 env) (arm:bind-expr num_13 env) (arm:bind-expr num_14 env) 
		 (arm:bind-expr num_15 env))
	]
	[ (vmull_u32_dsl v0 v1 size_i_o num_3 num_4 num_5 prec_i prec_o num_8 num_9 num_10 num_11)
		(vmull_u32_dsl (arm:bind-expr v0 env) (arm:bind-expr v1 env) (arm:bind-expr size_i_o env) 
		 (arm:bind-expr num_3 env) (arm:bind-expr num_4 env) (arm:bind-expr num_5 env) 
		 (arm:bind-expr prec_i env) (arm:bind-expr prec_o env) (arm:bind-expr num_8 env) 
		 (arm:bind-expr num_9 env) (arm:bind-expr num_10 env) (arm:bind-expr num_11 env))
	]
	[ (vsra_n_u8_dsl vc_0 v1 v2 v3 size_i_o num_5 num_6 num_7 prec_i_o num_9 num_10 num_11 num_12)
		(vsra_n_u8_dsl (arm:bind-expr vc_0 env) (arm:bind-expr v1 env) (arm:bind-expr v2 env) 
		 (arm:bind-expr v3 env) (arm:bind-expr size_i_o env) (arm:bind-expr num_5 env) 
		 (arm:bind-expr num_6 env) (arm:bind-expr num_7 env) (arm:bind-expr prec_i_o env) 
		 (arm:bind-expr num_9 env) (arm:bind-expr num_10 env) (arm:bind-expr num_11 env) 
		 (arm:bind-expr num_12 env))
	]
	[ (vqdmull_s32_dsl vc_0 v1 v2 size_i_o num_4 num_5 num_6 prec_i prec_o num_9 num_10 num_11 num_12)
		(vqdmull_s32_dsl (arm:bind-expr vc_0 env) (arm:bind-expr v1 env) (arm:bind-expr v2 env) 
		 (arm:bind-expr size_i_o env) (arm:bind-expr num_4 env) (arm:bind-expr num_5 env) 
		 (arm:bind-expr num_6 env) (arm:bind-expr prec_i env) (arm:bind-expr prec_o env) 
		 (arm:bind-expr num_9 env) (arm:bind-expr num_10 env) (arm:bind-expr num_11 env) 
		 (arm:bind-expr num_12 env))
	]
	[ (vmaxq_u16_dsl v0 v1 size_i_o num_3 num_4 num_5 prec_i_o num_7 num_8 num_9 num_10)
		(vmaxq_u16_dsl (arm:bind-expr v0 env) (arm:bind-expr v1 env) (arm:bind-expr size_i_o env) 
		 (arm:bind-expr num_3 env) (arm:bind-expr num_4 env) (arm:bind-expr num_5 env) 
		 (arm:bind-expr prec_i_o env) (arm:bind-expr num_7 env) (arm:bind-expr num_8 env) 
		 (arm:bind-expr num_9 env) (arm:bind-expr num_10 env))
	]
	[ (vshll_n_u16_dsl v0 v1 size_i_o num_3 num_4 num_5 prec_i prec_o num_8 num_9 num_10)
		(vshll_n_u16_dsl (arm:bind-expr v0 env) (arm:bind-expr v1 env) (arm:bind-expr size_i_o env) 
		 (arm:bind-expr num_3 env) (arm:bind-expr num_4 env) (arm:bind-expr num_5 env) 
		 (arm:bind-expr prec_i env) (arm:bind-expr prec_o env) (arm:bind-expr num_8 env) 
		 (arm:bind-expr num_9 env) (arm:bind-expr num_10 env))
	]
	[ (vzip1_s32_dsl v0 v1 size_i_o num_3 num_4 num_5 num_6 num_7 num_8 prec_i_o num_10 num_11 num_12 num_13)
		(vzip1_s32_dsl (arm:bind-expr v0 env) (arm:bind-expr v1 env) (arm:bind-expr size_i_o env) 
		 (arm:bind-expr num_3 env) (arm:bind-expr num_4 env) (arm:bind-expr num_5 env) 
		 (arm:bind-expr num_6 env) (arm:bind-expr num_7 env) (arm:bind-expr num_8 env) 
		 (arm:bind-expr prec_i_o env) (arm:bind-expr num_10 env) (arm:bind-expr num_11 env) 
		 (arm:bind-expr num_12 env) (arm:bind-expr num_13 env))
	]
	[ (vcgeq_u32_dsl vc_0 vc_1 v2 v3 size_i_o num_5 num_6 num_7 prec_i_o num_9 num_10 num_11)
		(vcgeq_u32_dsl (arm:bind-expr vc_0 env) (arm:bind-expr vc_1 env) (arm:bind-expr v2 env) 
		 (arm:bind-expr v3 env) (arm:bind-expr size_i_o env) (arm:bind-expr num_5 env) 
		 (arm:bind-expr num_6 env) (arm:bind-expr num_7 env) (arm:bind-expr prec_i_o env) 
		 (arm:bind-expr num_9 env) (arm:bind-expr num_10 env) (arm:bind-expr num_11 env))
	]
	[ (vqdmlal_high_n_s16_dsl vc_0 v1 v2 v3 size_i_o num_5 num_6 num_7 prec_i_o num_9 num_10 num_11 num_12 num_13 num_14 num_15 num_16 num_17 num_18)
		(vqdmlal_high_n_s16_dsl (arm:bind-expr vc_0 env) (arm:bind-expr v1 env) (arm:bind-expr v2 env) 
		 (arm:bind-expr v3 env) (arm:bind-expr size_i_o env) (arm:bind-expr num_5 env) 
		 (arm:bind-expr num_6 env) (arm:bind-expr num_7 env) (arm:bind-expr prec_i_o env) 
		 (arm:bind-expr num_9 env) (arm:bind-expr num_10 env) (arm:bind-expr num_11 env) 
		 (arm:bind-expr num_12 env) (arm:bind-expr num_13 env) (arm:bind-expr num_14 env) 
		 (arm:bind-expr num_15 env) (arm:bind-expr num_16 env) (arm:bind-expr num_17 env) 
		 (arm:bind-expr num_18 env))
	]
	[ (vqneg_s32_dsl v0 size_i_o num_2 num_3 num_4 prec_i_o num_6 num_7)
		(vqneg_s32_dsl (arm:bind-expr v0 env) (arm:bind-expr size_i_o env) (arm:bind-expr num_2 env) 
		 (arm:bind-expr num_3 env) (arm:bind-expr num_4 env) (arm:bind-expr prec_i_o env) 
		 (arm:bind-expr num_6 env) (arm:bind-expr num_7 env))
	]
	[ (vqdmlsl_n_s16_dsl vc_0 v1 v2 v3 size_i_o num_5 num_6 num_7 prec_i num_9 prec_o num_11 num_12 num_13 num_14 num_15 num_16 num_17 num_18)
		(vqdmlsl_n_s16_dsl (arm:bind-expr vc_0 env) (arm:bind-expr v1 env) (arm:bind-expr v2 env) 
		 (arm:bind-expr v3 env) (arm:bind-expr size_i_o env) (arm:bind-expr num_5 env) 
		 (arm:bind-expr num_6 env) (arm:bind-expr num_7 env) (arm:bind-expr prec_i env) 
		 (arm:bind-expr num_9 env) (arm:bind-expr prec_o env) (arm:bind-expr num_11 env) 
		 (arm:bind-expr num_12 env) (arm:bind-expr num_13 env) (arm:bind-expr num_14 env) 
		 (arm:bind-expr num_15 env) (arm:bind-expr num_16 env) (arm:bind-expr num_17 env) 
		 (arm:bind-expr num_18 env))
	]
	[ (vmulq_u8_dsl v0 v1 size_i_o num_3 num_4 num_5 prec_i_o num_7 num_8 num_9)
		(vmulq_u8_dsl (arm:bind-expr v0 env) (arm:bind-expr v1 env) (arm:bind-expr size_i_o env) 
		 (arm:bind-expr num_3 env) (arm:bind-expr num_4 env) (arm:bind-expr num_5 env) 
		 (arm:bind-expr prec_i_o env) (arm:bind-expr num_7 env) (arm:bind-expr num_8 env) 
		 (arm:bind-expr num_9 env))
	]
	[ (vtrn2_s32_dsl v0 v1 size_i_o num_3 num_4 num_5 num_6 num_7 num_8 prec_i_o num_10 num_11 num_12 num_13 num_14 num_15 num_16)
		(vtrn2_s32_dsl (arm:bind-expr v0 env) (arm:bind-expr v1 env) (arm:bind-expr size_i_o env) 
		 (arm:bind-expr num_3 env) (arm:bind-expr num_4 env) (arm:bind-expr num_5 env) 
		 (arm:bind-expr num_6 env) (arm:bind-expr num_7 env) (arm:bind-expr num_8 env) 
		 (arm:bind-expr prec_i_o env) (arm:bind-expr num_10 env) (arm:bind-expr num_11 env) 
		 (arm:bind-expr num_12 env) (arm:bind-expr num_13 env) (arm:bind-expr num_14 env) 
		 (arm:bind-expr num_15 env) (arm:bind-expr num_16 env))
	]
	[ (vcltz_s32_dsl vc_0 vc_1 vc_2 v3 size_i_o num_5 num_6 num_7 prec_i_o num_9 num_10)
		(vcltz_s32_dsl (arm:bind-expr vc_0 env) (arm:bind-expr vc_1 env) (arm:bind-expr vc_2 env) 
		 (arm:bind-expr v3 env) (arm:bind-expr size_i_o env) (arm:bind-expr num_5 env) 
		 (arm:bind-expr num_6 env) (arm:bind-expr num_7 env) (arm:bind-expr prec_i_o env) 
		 (arm:bind-expr num_9 env) (arm:bind-expr num_10 env))
	]
	[ (vqdmlsl_high_s32_dsl vc_0 v1 v2 v3 size_i_o num_5 num_6 num_7 prec_i_o num_9 num_10 num_11 num_12 num_13 num_14 num_15 num_16 num_17 num_18)
		(vqdmlsl_high_s32_dsl (arm:bind-expr vc_0 env) (arm:bind-expr v1 env) (arm:bind-expr v2 env) 
		 (arm:bind-expr v3 env) (arm:bind-expr size_i_o env) (arm:bind-expr num_5 env) 
		 (arm:bind-expr num_6 env) (arm:bind-expr num_7 env) (arm:bind-expr prec_i_o env) 
		 (arm:bind-expr num_9 env) (arm:bind-expr num_10 env) (arm:bind-expr num_11 env) 
		 (arm:bind-expr num_12 env) (arm:bind-expr num_13 env) (arm:bind-expr num_14 env) 
		 (arm:bind-expr num_15 env) (arm:bind-expr num_16 env) (arm:bind-expr num_17 env) 
		 (arm:bind-expr num_18 env))
	]
	[ (vqdmulh_s16_dsl vc_0 vc_1 vc_2 v3 v4 size_i_o num_6 num_7 num_8 prec_i_o num_10 num_11 num_12 num_13)
		(vqdmulh_s16_dsl (arm:bind-expr vc_0 env) (arm:bind-expr vc_1 env) (arm:bind-expr vc_2 env) 
		 (arm:bind-expr v3 env) (arm:bind-expr v4 env) (arm:bind-expr size_i_o env) 
		 (arm:bind-expr num_6 env) (arm:bind-expr num_7 env) (arm:bind-expr num_8 env) 
		 (arm:bind-expr prec_i_o env) (arm:bind-expr num_10 env) (arm:bind-expr num_11 env) 
		 (arm:bind-expr num_12 env) (arm:bind-expr num_13 env))
	]
	[ (vqdmlsl_high_n_s16_dsl vc_0 v1 v2 v3 size_i_o num_5 num_6 num_7 prec_i_o num_9 num_10 num_11 num_12 num_13 num_14 num_15 num_16 num_17 num_18)
		(vqdmlsl_high_n_s16_dsl (arm:bind-expr vc_0 env) (arm:bind-expr v1 env) (arm:bind-expr v2 env) 
		 (arm:bind-expr v3 env) (arm:bind-expr size_i_o env) (arm:bind-expr num_5 env) 
		 (arm:bind-expr num_6 env) (arm:bind-expr num_7 env) (arm:bind-expr prec_i_o env) 
		 (arm:bind-expr num_9 env) (arm:bind-expr num_10 env) (arm:bind-expr num_11 env) 
		 (arm:bind-expr num_12 env) (arm:bind-expr num_13 env) (arm:bind-expr num_14 env) 
		 (arm:bind-expr num_15 env) (arm:bind-expr num_16 env) (arm:bind-expr num_17 env) 
		 (arm:bind-expr num_18 env))
	]
	[ (vmlsl_high_n_s16_dsl v0 v1 v2 size_i_o num_4 num_5 num_6 prec_i_o num_8 num_9 num_10 num_11 num_12 num_13)
		(vmlsl_high_n_s16_dsl (arm:bind-expr v0 env) (arm:bind-expr v1 env) (arm:bind-expr v2 env) 
		 (arm:bind-expr size_i_o env) (arm:bind-expr num_4 env) (arm:bind-expr num_5 env) 
		 (arm:bind-expr num_6 env) (arm:bind-expr prec_i_o env) (arm:bind-expr num_8 env) 
		 (arm:bind-expr num_9 env) (arm:bind-expr num_10 env) (arm:bind-expr num_11 env) 
		 (arm:bind-expr num_12 env) (arm:bind-expr num_13 env))
	]
	[ (vpaddq_u64_dsl vc_0 v1 v2 size_i prec_i_o num_5 num_6 num_7 num_8 num_9 num_10 num_11)
		(vpaddq_u64_dsl (arm:bind-expr vc_0 env) (arm:bind-expr v1 env) (arm:bind-expr v2 env) 
		 (arm:bind-expr size_i env) (arm:bind-expr prec_i_o env) (arm:bind-expr num_5 env) 
		 (arm:bind-expr num_6 env) (arm:bind-expr num_7 env) (arm:bind-expr num_8 env) 
		 (arm:bind-expr num_9 env) (arm:bind-expr num_10 env) (arm:bind-expr num_11 env))
	]
	[ (vmull_high_n_s16_dsl v0 v1 size_o num_3 num_4 num_5 prec_o num_7 num_8 num_9 num_10 num_11)
		(vmull_high_n_s16_dsl (arm:bind-expr v0 env) (arm:bind-expr v1 env) (arm:bind-expr size_o env) 
		 (arm:bind-expr num_3 env) (arm:bind-expr num_4 env) (arm:bind-expr num_5 env) 
		 (arm:bind-expr prec_o env) (arm:bind-expr num_7 env) (arm:bind-expr num_8 env) 
		 (arm:bind-expr num_9 env) (arm:bind-expr num_10 env) (arm:bind-expr num_11 env))
	]
	[ (vqrshlq_s16_dsl vc_0 vc_1 v2 v3 size_i_o num_5 num_6 num_7 prec_i prec_o num_10 num_11 num_12 num_13 num_14 num_15)
		(vqrshlq_s16_dsl (arm:bind-expr vc_0 env) (arm:bind-expr vc_1 env) (arm:bind-expr v2 env) 
		 (arm:bind-expr v3 env) (arm:bind-expr size_i_o env) (arm:bind-expr num_5 env) 
		 (arm:bind-expr num_6 env) (arm:bind-expr num_7 env) (arm:bind-expr prec_i env) 
		 (arm:bind-expr prec_o env) (arm:bind-expr num_10 env) (arm:bind-expr num_11 env) 
		 (arm:bind-expr num_12 env) (arm:bind-expr num_13 env) (arm:bind-expr num_14 env) 
		 (arm:bind-expr num_15 env))
	]
	[ (vmlal_n_u32_dsl v0 v1 v2 size_i_o num_4 num_5 num_6 prec_i num_8 prec_o num_10 num_11 num_12 num_13)
		(vmlal_n_u32_dsl (arm:bind-expr v0 env) (arm:bind-expr v1 env) (arm:bind-expr v2 env) 
		 (arm:bind-expr size_i_o env) (arm:bind-expr num_4 env) (arm:bind-expr num_5 env) 
		 (arm:bind-expr num_6 env) (arm:bind-expr prec_i env) (arm:bind-expr num_8 env) 
		 (arm:bind-expr prec_o env) (arm:bind-expr num_10 env) (arm:bind-expr num_11 env) 
		 (arm:bind-expr num_12 env) (arm:bind-expr num_13 env))
	]
	[ (vmlsq_u16_dsl v0 v1 v2 size_i_o num_4 num_5 num_6 prec_i_o num_8 num_9 num_10 num_11)
		(vmlsq_u16_dsl (arm:bind-expr v0 env) (arm:bind-expr v1 env) (arm:bind-expr v2 env) 
		 (arm:bind-expr size_i_o env) (arm:bind-expr num_4 env) (arm:bind-expr num_5 env) 
		 (arm:bind-expr num_6 env) (arm:bind-expr prec_i_o env) (arm:bind-expr num_8 env) 
		 (arm:bind-expr num_9 env) (arm:bind-expr num_10 env) (arm:bind-expr num_11 env))
	]
	[ (vqshl_u8_dsl vc_0 v1 v2 size_i_o num_4 num_5 num_6 prec_i_o num_8 num_9 num_10 num_11)
		(vqshl_u8_dsl (arm:bind-expr vc_0 env) (arm:bind-expr v1 env) (arm:bind-expr v2 env) 
		 (arm:bind-expr size_i_o env) (arm:bind-expr num_4 env) (arm:bind-expr num_5 env) 
		 (arm:bind-expr num_6 env) (arm:bind-expr prec_i_o env) (arm:bind-expr num_8 env) 
		 (arm:bind-expr num_9 env) (arm:bind-expr num_10 env) (arm:bind-expr num_11 env))
	]
	[ (vuzp2_s16_dsl v0 v1 size_i_o num_3 num_4 num_5 prec_i_o num_7 num_8 num_9)
		(vuzp2_s16_dsl (arm:bind-expr v0 env) (arm:bind-expr v1 env) (arm:bind-expr size_i_o env) 
		 (arm:bind-expr num_3 env) (arm:bind-expr num_4 env) (arm:bind-expr num_5 env) 
		 (arm:bind-expr prec_i_o env) (arm:bind-expr num_7 env) (arm:bind-expr num_8 env) 
		 (arm:bind-expr num_9 env))
	]
	[ (vclezq_s8_dsl vc_0 vc_1 vc_2 v3 size_i_o num_5 num_6 num_7 prec_i_o num_9 num_10)
		(vclezq_s8_dsl (arm:bind-expr vc_0 env) (arm:bind-expr vc_1 env) (arm:bind-expr vc_2 env) 
		 (arm:bind-expr v3 env) (arm:bind-expr size_i_o env) (arm:bind-expr num_5 env) 
		 (arm:bind-expr num_6 env) (arm:bind-expr num_7 env) (arm:bind-expr prec_i_o env) 
		 (arm:bind-expr num_9 env) (arm:bind-expr num_10 env))
	]
	[ (vqrshl_u8_dsl vc_0 vc_1 v2 v3 size_i_o num_5 num_6 num_7 prec_i_o num_9 num_10 num_11 num_12 num_13)
		(vqrshl_u8_dsl (arm:bind-expr vc_0 env) (arm:bind-expr vc_1 env) (arm:bind-expr v2 env) 
		 (arm:bind-expr v3 env) (arm:bind-expr size_i_o env) (arm:bind-expr num_5 env) 
		 (arm:bind-expr num_6 env) (arm:bind-expr num_7 env) (arm:bind-expr prec_i_o env) 
		 (arm:bind-expr num_9 env) (arm:bind-expr num_10 env) (arm:bind-expr num_11 env) 
		 (arm:bind-expr num_12 env) (arm:bind-expr num_13 env))
	]
	[ (vhsubq_u16_dsl v0 v1 size_i_o num_3 num_4 num_5 prec_i_o num_7 num_8 num_9 num_10)
		(vhsubq_u16_dsl (arm:bind-expr v0 env) (arm:bind-expr v1 env) (arm:bind-expr size_i_o env) 
		 (arm:bind-expr num_3 env) (arm:bind-expr num_4 env) (arm:bind-expr num_5 env) 
		 (arm:bind-expr prec_i_o env) (arm:bind-expr num_7 env) (arm:bind-expr num_8 env) 
		 (arm:bind-expr num_9 env) (arm:bind-expr num_10 env))
	]
	[ (vmlal_n_s16_dsl v0 v1 v2 size_i_o num_4 num_5 num_6 prec_i num_8 prec_o num_10 num_11 num_12 num_13)
		(vmlal_n_s16_dsl (arm:bind-expr v0 env) (arm:bind-expr v1 env) (arm:bind-expr v2 env) 
		 (arm:bind-expr size_i_o env) (arm:bind-expr num_4 env) (arm:bind-expr num_5 env) 
		 (arm:bind-expr num_6 env) (arm:bind-expr prec_i env) (arm:bind-expr num_8 env) 
		 (arm:bind-expr prec_o env) (arm:bind-expr num_10 env) (arm:bind-expr num_11 env) 
		 (arm:bind-expr num_12 env) (arm:bind-expr num_13 env))
	]
	[ (vuzp1_u16_dsl v0 v1 size_i_o num_3 num_4 num_5 prec_i_o num_7)
		(vuzp1_u16_dsl (arm:bind-expr v0 env) (arm:bind-expr v1 env) (arm:bind-expr size_i_o env) 
		 (arm:bind-expr num_3 env) (arm:bind-expr num_4 env) (arm:bind-expr num_5 env) 
		 (arm:bind-expr prec_i_o env) (arm:bind-expr num_7 env))
	]
	[ (vqdmulhq_n_s16_dsl vc_0 vc_1 vc_2 v3 v4 size_i_o num_6 num_7 num_8 prec_i_o num_10 num_11 num_12 num_13)
		(vqdmulhq_n_s16_dsl (arm:bind-expr vc_0 env) (arm:bind-expr vc_1 env) (arm:bind-expr vc_2 env) 
		 (arm:bind-expr v3 env) (arm:bind-expr v4 env) (arm:bind-expr size_i_o env) 
		 (arm:bind-expr num_6 env) (arm:bind-expr num_7 env) (arm:bind-expr num_8 env) 
		 (arm:bind-expr prec_i_o env) (arm:bind-expr num_10 env) (arm:bind-expr num_11 env) 
		 (arm:bind-expr num_12 env) (arm:bind-expr num_13 env))
	]
	[ (vshl_u16_dsl vc_0 v1 v2 size_i_o num_4 num_5 num_6 prec_i prec_o num_9 num_10 num_11 num_12 num_13)
		(vshl_u16_dsl (arm:bind-expr vc_0 env) (arm:bind-expr v1 env) (arm:bind-expr v2 env) 
		 (arm:bind-expr size_i_o env) (arm:bind-expr num_4 env) (arm:bind-expr num_5 env) 
		 (arm:bind-expr num_6 env) (arm:bind-expr prec_i env) (arm:bind-expr prec_o env) 
		 (arm:bind-expr num_9 env) (arm:bind-expr num_10 env) (arm:bind-expr num_11 env) 
		 (arm:bind-expr num_12 env) (arm:bind-expr num_13 env))
	]
	[ (vabs_s32_dsl v0 size_i_o num_2 num_3 num_4 prec_i_o num_6 num_7)
		(vabs_s32_dsl (arm:bind-expr v0 env) (arm:bind-expr size_i_o env) (arm:bind-expr num_2 env) 
		 (arm:bind-expr num_3 env) (arm:bind-expr num_4 env) (arm:bind-expr prec_i_o env) 
		 (arm:bind-expr num_6 env) (arm:bind-expr num_7 env))
	]
	[ (vaddl_u8_dsl v0 v1 size_i_o num_3 num_4 num_5 prec_i prec_o num_8 num_9 num_10 num_11 num_12)
		(vaddl_u8_dsl (arm:bind-expr v0 env) (arm:bind-expr v1 env) (arm:bind-expr size_i_o env) 
		 (arm:bind-expr num_3 env) (arm:bind-expr num_4 env) (arm:bind-expr num_5 env) 
		 (arm:bind-expr prec_i env) (arm:bind-expr prec_o env) (arm:bind-expr num_8 env) 
		 (arm:bind-expr num_9 env) (arm:bind-expr num_10 env) (arm:bind-expr num_11 env) 
		 (arm:bind-expr num_12 env))
	]
	[ (vqdmull_high_n_s16_dsl vc_0 v1 v2 size_o num_4 num_5 num_6 prec_o num_8 num_9 num_10 num_11 num_12)
		(vqdmull_high_n_s16_dsl (arm:bind-expr vc_0 env) (arm:bind-expr v1 env) (arm:bind-expr v2 env) 
		 (arm:bind-expr size_o env) (arm:bind-expr num_4 env) (arm:bind-expr num_5 env) 
		 (arm:bind-expr num_6 env) (arm:bind-expr prec_o env) (arm:bind-expr num_8 env) 
		 (arm:bind-expr num_9 env) (arm:bind-expr num_10 env) (arm:bind-expr num_11 env) 
		 (arm:bind-expr num_12 env))
	]
	[ (vneg_s8_dsl v0 size_i_o num_2 num_3 num_4 prec_i_o num_6 num_7)
		(vneg_s8_dsl (arm:bind-expr v0 env) (arm:bind-expr size_i_o env) (arm:bind-expr num_2 env) 
		 (arm:bind-expr num_3 env) (arm:bind-expr num_4 env) (arm:bind-expr prec_i_o env) 
		 (arm:bind-expr num_6 env) (arm:bind-expr num_7 env))
	]
	[ (vqdmlsls_s32_dsl vc_0 v1 v2 v3 size_i_o num_5 num_6 num_7 prec_i prec_o num_10 num_11 num_12 num_13 num_14 num_15 num_16 num_17 num_18)
		(vqdmlsls_s32_dsl (arm:bind-expr vc_0 env) (arm:bind-expr v1 env) (arm:bind-expr v2 env) 
		 (arm:bind-expr v3 env) (arm:bind-expr size_i_o env) (arm:bind-expr num_5 env) 
		 (arm:bind-expr num_6 env) (arm:bind-expr num_7 env) (arm:bind-expr prec_i env) 
		 (arm:bind-expr prec_o env) (arm:bind-expr num_10 env) (arm:bind-expr num_11 env) 
		 (arm:bind-expr num_12 env) (arm:bind-expr num_13 env) (arm:bind-expr num_14 env) 
		 (arm:bind-expr num_15 env) (arm:bind-expr num_16 env) (arm:bind-expr num_17 env) 
		 (arm:bind-expr num_18 env))
	]
	[ (vmull_high_n_u32_dsl v0 v1 size_o num_3 num_4 num_5 prec_o num_7 num_8 num_9 num_10 num_11)
		(vmull_high_n_u32_dsl (arm:bind-expr v0 env) (arm:bind-expr v1 env) (arm:bind-expr size_o env) 
		 (arm:bind-expr num_3 env) (arm:bind-expr num_4 env) (arm:bind-expr num_5 env) 
		 (arm:bind-expr prec_o env) (arm:bind-expr num_7 env) (arm:bind-expr num_8 env) 
		 (arm:bind-expr num_9 env) (arm:bind-expr num_10 env) (arm:bind-expr num_11 env))
	]
	[ (vpmax_u32_dsl v0 v1 size_i_o num_3 num_4 num_5 prec_o num_7 num_8 num_9 num_10 num_11 num_12 num_13 num_14 prec_i num_16)
		(vpmax_u32_dsl (arm:bind-expr v0 env) (arm:bind-expr v1 env) (arm:bind-expr size_i_o env) 
		 (arm:bind-expr num_3 env) (arm:bind-expr num_4 env) (arm:bind-expr num_5 env) 
		 (arm:bind-expr prec_o env) (arm:bind-expr num_7 env) (arm:bind-expr num_8 env) 
		 (arm:bind-expr num_9 env) (arm:bind-expr num_10 env) (arm:bind-expr num_11 env) 
		 (arm:bind-expr num_12 env) (arm:bind-expr num_13 env) (arm:bind-expr num_14 env) 
		 (arm:bind-expr prec_i env) (arm:bind-expr num_16 env))
	]
	[ (vqdmull_n_s32_dsl vc_0 v1 v2 size_i_o num_4 num_5 num_6 prec_i num_8 prec_o num_10 num_11 num_12)
		(vqdmull_n_s32_dsl (arm:bind-expr vc_0 env) (arm:bind-expr v1 env) (arm:bind-expr v2 env) 
		 (arm:bind-expr size_i_o env) (arm:bind-expr num_4 env) (arm:bind-expr num_5 env) 
		 (arm:bind-expr num_6 env) (arm:bind-expr prec_i env) (arm:bind-expr num_8 env) 
		 (arm:bind-expr prec_o env) (arm:bind-expr num_10 env) (arm:bind-expr num_11 env) 
		 (arm:bind-expr num_12 env))
	]
	[ (vsubw_s8_dsl v0 v1 size_i_o num_3 num_4 num_5 num_6 prec_i_o num_8 num_9 num_10 num_11 num_12)
		(vsubw_s8_dsl (arm:bind-expr v0 env) (arm:bind-expr v1 env) (arm:bind-expr size_i_o env) 
		 (arm:bind-expr num_3 env) (arm:bind-expr num_4 env) (arm:bind-expr num_5 env) 
		 (arm:bind-expr num_6 env) (arm:bind-expr prec_i_o env) (arm:bind-expr num_8 env) 
		 (arm:bind-expr num_9 env) (arm:bind-expr num_10 env) (arm:bind-expr num_11 env) 
		 (arm:bind-expr num_12 env))
	]
	[ (vrsra_n_u8_dsl vc_0 vc_1 v2 v3 v4 size_i_o num_6 num_7 num_8 prec_i_o num_10 num_11 num_12 num_13 num_14)
		(vrsra_n_u8_dsl (arm:bind-expr vc_0 env) (arm:bind-expr vc_1 env) (arm:bind-expr v2 env) 
		 (arm:bind-expr v3 env) (arm:bind-expr v4 env) (arm:bind-expr size_i_o env) 
		 (arm:bind-expr num_6 env) (arm:bind-expr num_7 env) (arm:bind-expr num_8 env) 
		 (arm:bind-expr prec_i_o env) (arm:bind-expr num_10 env) (arm:bind-expr num_11 env) 
		 (arm:bind-expr num_12 env) (arm:bind-expr num_13 env) (arm:bind-expr num_14 env))
	]
	[ (vcle_s64_dsl vc_0 vc_1 v2 v3 size_i_o num_5 num_6 num_7 prec_i_o num_9 num_10 num_11)
		(vcle_s64_dsl (arm:bind-expr vc_0 env) (arm:bind-expr vc_1 env) (arm:bind-expr v2 env) 
		 (arm:bind-expr v3 env) (arm:bind-expr size_i_o env) (arm:bind-expr num_5 env) 
		 (arm:bind-expr num_6 env) (arm:bind-expr num_7 env) (arm:bind-expr prec_i_o env) 
		 (arm:bind-expr num_9 env) (arm:bind-expr num_10 env) (arm:bind-expr num_11 env))
	]
	[ (vsubl_high_s16_dsl v0 v1 size_o num_3 num_4 num_5 prec_o num_7 num_8 num_9 num_10 num_11 num_12)
		(vsubl_high_s16_dsl (arm:bind-expr v0 env) (arm:bind-expr v1 env) (arm:bind-expr size_o env) 
		 (arm:bind-expr num_3 env) (arm:bind-expr num_4 env) (arm:bind-expr num_5 env) 
		 (arm:bind-expr prec_o env) (arm:bind-expr num_7 env) (arm:bind-expr num_8 env) 
		 (arm:bind-expr num_9 env) (arm:bind-expr num_10 env) (arm:bind-expr num_11 env) 
		 (arm:bind-expr num_12 env))
	]
	[ (vqadd_u64_dsl v0 v1 size_i_o num_3 num_4 num_5 prec_i_o num_7 num_8 num_9 num_10)
		(vqadd_u64_dsl (arm:bind-expr v0 env) (arm:bind-expr v1 env) (arm:bind-expr size_i_o env) 
		 (arm:bind-expr num_3 env) (arm:bind-expr num_4 env) (arm:bind-expr num_5 env) 
		 (arm:bind-expr prec_i_o env) (arm:bind-expr num_7 env) (arm:bind-expr num_8 env) 
		 (arm:bind-expr num_9 env) (arm:bind-expr num_10 env))
	]
	[ (vqdmlal_n_s16_dsl vc_0 v1 v2 v3 size_i_o num_5 num_6 num_7 prec_i num_9 prec_o num_11 num_12 num_13 num_14 num_15 num_16 num_17 num_18)
		(vqdmlal_n_s16_dsl (arm:bind-expr vc_0 env) (arm:bind-expr v1 env) (arm:bind-expr v2 env) 
		 (arm:bind-expr v3 env) (arm:bind-expr size_i_o env) (arm:bind-expr num_5 env) 
		 (arm:bind-expr num_6 env) (arm:bind-expr num_7 env) (arm:bind-expr prec_i env) 
		 (arm:bind-expr num_9 env) (arm:bind-expr prec_o env) (arm:bind-expr num_11 env) 
		 (arm:bind-expr num_12 env) (arm:bind-expr num_13 env) (arm:bind-expr num_14 env) 
		 (arm:bind-expr num_15 env) (arm:bind-expr num_16 env) (arm:bind-expr num_17 env) 
		 (arm:bind-expr num_18 env))
	]
	[ (vqdmlsl_n_s32_dsl vc_0 v1 v2 v3 size_i_o num_5 num_6 num_7 prec_i num_9 prec_o num_11 num_12 num_13 num_14 num_15 num_16 num_17 num_18)
		(vqdmlsl_n_s32_dsl (arm:bind-expr vc_0 env) (arm:bind-expr v1 env) (arm:bind-expr v2 env) 
		 (arm:bind-expr v3 env) (arm:bind-expr size_i_o env) (arm:bind-expr num_5 env) 
		 (arm:bind-expr num_6 env) (arm:bind-expr num_7 env) (arm:bind-expr prec_i env) 
		 (arm:bind-expr num_9 env) (arm:bind-expr prec_o env) (arm:bind-expr num_11 env) 
		 (arm:bind-expr num_12 env) (arm:bind-expr num_13 env) (arm:bind-expr num_14 env) 
		 (arm:bind-expr num_15 env) (arm:bind-expr num_16 env) (arm:bind-expr num_17 env) 
		 (arm:bind-expr num_18 env))
	]
	[ (vmlsl_n_u16_dsl v0 v1 v2 size_i_o num_4 num_5 num_6 prec_i num_8 prec_o num_10 num_11 num_12 num_13)
		(vmlsl_n_u16_dsl (arm:bind-expr v0 env) (arm:bind-expr v1 env) (arm:bind-expr v2 env) 
		 (arm:bind-expr size_i_o env) (arm:bind-expr num_4 env) (arm:bind-expr num_5 env) 
		 (arm:bind-expr num_6 env) (arm:bind-expr prec_i env) (arm:bind-expr num_8 env) 
		 (arm:bind-expr prec_o env) (arm:bind-expr num_10 env) (arm:bind-expr num_11 env) 
		 (arm:bind-expr num_12 env) (arm:bind-expr num_13 env))
	]
	[ (vminq_u16_dsl v0 v1 size_i_o num_3 num_4 num_5 prec_i_o num_7 num_8 num_9 num_10)
		(vminq_u16_dsl (arm:bind-expr v0 env) (arm:bind-expr v1 env) (arm:bind-expr size_i_o env) 
		 (arm:bind-expr num_3 env) (arm:bind-expr num_4 env) (arm:bind-expr num_5 env) 
		 (arm:bind-expr prec_i_o env) (arm:bind-expr num_7 env) (arm:bind-expr num_8 env) 
		 (arm:bind-expr num_9 env) (arm:bind-expr num_10 env))
	]
	[ (vmlsl_u16_dsl v0 v1 v2 size_i_o num_4 num_5 num_6 prec_i prec_o num_9 num_10 num_11 num_12 num_13)
		(vmlsl_u16_dsl (arm:bind-expr v0 env) (arm:bind-expr v1 env) (arm:bind-expr v2 env) 
		 (arm:bind-expr size_i_o env) (arm:bind-expr num_4 env) (arm:bind-expr num_5 env) 
		 (arm:bind-expr num_6 env) (arm:bind-expr prec_i env) (arm:bind-expr prec_o env) 
		 (arm:bind-expr num_9 env) (arm:bind-expr num_10 env) (arm:bind-expr num_11 env) 
		 (arm:bind-expr num_12 env) (arm:bind-expr num_13 env))
	]
	[ (vcgez_s16_dsl vc_0 vc_1 vc_2 v3 size_i_o num_5 num_6 num_7 prec_i_o num_9 num_10)
		(vcgez_s16_dsl (arm:bind-expr vc_0 env) (arm:bind-expr vc_1 env) (arm:bind-expr vc_2 env) 
		 (arm:bind-expr v3 env) (arm:bind-expr size_i_o env) (arm:bind-expr num_5 env) 
		 (arm:bind-expr num_6 env) (arm:bind-expr num_7 env) (arm:bind-expr prec_i_o env) 
		 (arm:bind-expr num_9 env) (arm:bind-expr num_10 env))
	]
	[ (vmulq_n_s16_dsl v0 v1 size_i_o num_3 num_4 num_5 prec_i_o num_7 num_8 num_9)
		(vmulq_n_s16_dsl (arm:bind-expr v0 env) (arm:bind-expr v1 env) (arm:bind-expr size_i_o env) 
		 (arm:bind-expr num_3 env) (arm:bind-expr num_4 env) (arm:bind-expr num_5 env) 
		 (arm:bind-expr prec_i_o env) (arm:bind-expr num_7 env) (arm:bind-expr num_8 env) 
		 (arm:bind-expr num_9 env))
	]
	[ (vmlal_high_s8_dsl v0 v1 v2 size_i_o num_4 num_5 num_6 prec_i_o num_8 num_9 num_10 num_11 num_12 num_13)
		(vmlal_high_s8_dsl (arm:bind-expr v0 env) (arm:bind-expr v1 env) (arm:bind-expr v2 env) 
		 (arm:bind-expr size_i_o env) (arm:bind-expr num_4 env) (arm:bind-expr num_5 env) 
		 (arm:bind-expr num_6 env) (arm:bind-expr prec_i_o env) (arm:bind-expr num_8 env) 
		 (arm:bind-expr num_9 env) (arm:bind-expr num_10 env) (arm:bind-expr num_11 env) 
		 (arm:bind-expr num_12 env) (arm:bind-expr num_13 env))
	]
	[ (vqdmlal_n_s32_dsl vc_0 v1 v2 v3 size_i_o num_5 num_6 num_7 prec_i num_9 prec_o num_11 num_12 num_13 num_14 num_15 num_16 num_17 num_18)
		(vqdmlal_n_s32_dsl (arm:bind-expr vc_0 env) (arm:bind-expr v1 env) (arm:bind-expr v2 env) 
		 (arm:bind-expr v3 env) (arm:bind-expr size_i_o env) (arm:bind-expr num_5 env) 
		 (arm:bind-expr num_6 env) (arm:bind-expr num_7 env) (arm:bind-expr prec_i env) 
		 (arm:bind-expr num_9 env) (arm:bind-expr prec_o env) (arm:bind-expr num_11 env) 
		 (arm:bind-expr num_12 env) (arm:bind-expr num_13 env) (arm:bind-expr num_14 env) 
		 (arm:bind-expr num_15 env) (arm:bind-expr num_16 env) (arm:bind-expr num_17 env) 
		 (arm:bind-expr num_18 env))
	]
	[ (vqdmlal_high_s16_dsl vc_0 v1 v2 v3 size_i_o num_5 num_6 num_7 prec_i_o num_9 num_10 num_11 num_12 num_13 num_14 num_15 num_16 num_17 num_18)
		(vqdmlal_high_s16_dsl (arm:bind-expr vc_0 env) (arm:bind-expr v1 env) (arm:bind-expr v2 env) 
		 (arm:bind-expr v3 env) (arm:bind-expr size_i_o env) (arm:bind-expr num_5 env) 
		 (arm:bind-expr num_6 env) (arm:bind-expr num_7 env) (arm:bind-expr prec_i_o env) 
		 (arm:bind-expr num_9 env) (arm:bind-expr num_10 env) (arm:bind-expr num_11 env) 
		 (arm:bind-expr num_12 env) (arm:bind-expr num_13 env) (arm:bind-expr num_14 env) 
		 (arm:bind-expr num_15 env) (arm:bind-expr num_16 env) (arm:bind-expr num_17 env) 
		 (arm:bind-expr num_18 env))
	]
	[ (vmull_high_u8_dsl v0 v1 size_o num_3 num_4 num_5 prec_o num_7 num_8 num_9 num_10 num_11)
		(vmull_high_u8_dsl (arm:bind-expr v0 env) (arm:bind-expr v1 env) (arm:bind-expr size_o env) 
		 (arm:bind-expr num_3 env) (arm:bind-expr num_4 env) (arm:bind-expr num_5 env) 
		 (arm:bind-expr prec_o env) (arm:bind-expr num_7 env) (arm:bind-expr num_8 env) 
		 (arm:bind-expr num_9 env) (arm:bind-expr num_10 env) (arm:bind-expr num_11 env))
	]
	[ (vmls_n_s32_dsl v0 v1 v2 size_i_o num_4 num_5 num_6 prec_i_o num_8 num_9 num_10 num_11)
		(vmls_n_s32_dsl (arm:bind-expr v0 env) (arm:bind-expr v1 env) (arm:bind-expr v2 env) 
		 (arm:bind-expr size_i_o env) (arm:bind-expr num_4 env) (arm:bind-expr num_5 env) 
		 (arm:bind-expr num_6 env) (arm:bind-expr prec_i_o env) (arm:bind-expr num_8 env) 
		 (arm:bind-expr num_9 env) (arm:bind-expr num_10 env) (arm:bind-expr num_11 env))
	]
	[ (vaddw_s16_dsl v0 v1 size_i_o num_3 num_4 num_5 num_6 prec_i_o num_8 num_9 num_10 num_11 num_12)
		(vaddw_s16_dsl (arm:bind-expr v0 env) (arm:bind-expr v1 env) (arm:bind-expr size_i_o env) 
		 (arm:bind-expr num_3 env) (arm:bind-expr num_4 env) (arm:bind-expr num_5 env) 
		 (arm:bind-expr num_6 env) (arm:bind-expr prec_i_o env) (arm:bind-expr num_8 env) 
		 (arm:bind-expr num_9 env) (arm:bind-expr num_10 env) (arm:bind-expr num_11 env) 
		 (arm:bind-expr num_12 env))
	]
	[ (vmlal_high_n_u32_dsl v0 v1 v2 size_i_o num_4 num_5 num_6 prec_i_o num_8 num_9 num_10 num_11 num_12 num_13)
		(vmlal_high_n_u32_dsl (arm:bind-expr v0 env) (arm:bind-expr v1 env) (arm:bind-expr v2 env) 
		 (arm:bind-expr size_i_o env) (arm:bind-expr num_4 env) (arm:bind-expr num_5 env) 
		 (arm:bind-expr num_6 env) (arm:bind-expr prec_i_o env) (arm:bind-expr num_8 env) 
		 (arm:bind-expr num_9 env) (arm:bind-expr num_10 env) (arm:bind-expr num_11 env) 
		 (arm:bind-expr num_12 env) (arm:bind-expr num_13 env))
	]
	[ (vmovl_u16_dsl vc_0 v1 size_i_o num_3 num_4 num_5 prec_i prec_o num_8 num_9 num_10)
		(vmovl_u16_dsl (arm:bind-expr vc_0 env) (arm:bind-expr v1 env) (arm:bind-expr size_i_o env) 
		 (arm:bind-expr num_3 env) (arm:bind-expr num_4 env) (arm:bind-expr num_5 env) 
		 (arm:bind-expr prec_i env) (arm:bind-expr prec_o env) (arm:bind-expr num_8 env) 
		 (arm:bind-expr num_9 env) (arm:bind-expr num_10 env))
	]
	[ (vzip2_s8_dsl v0 v1 size_i_o num_3 num_4 num_5 num_6 num_7 num_8 prec_i_o num_10 num_11 num_12 num_13 num_14 num_15 num_16 num_17 num_18 num_19)
		(vzip2_s8_dsl (arm:bind-expr v0 env) (arm:bind-expr v1 env) (arm:bind-expr size_i_o env) 
		 (arm:bind-expr num_3 env) (arm:bind-expr num_4 env) (arm:bind-expr num_5 env) 
		 (arm:bind-expr num_6 env) (arm:bind-expr num_7 env) (arm:bind-expr num_8 env) 
		 (arm:bind-expr prec_i_o env) (arm:bind-expr num_10 env) (arm:bind-expr num_11 env) 
		 (arm:bind-expr num_12 env) (arm:bind-expr num_13 env) (arm:bind-expr num_14 env) 
		 (arm:bind-expr num_15 env) (arm:bind-expr num_16 env) (arm:bind-expr num_17 env) 
		 (arm:bind-expr num_18 env) (arm:bind-expr num_19 env))
	]
	[ (vqshlb_n_s8_dsl v0 v1 size_i_o num_3 num_4 num_5 prec_i_o num_7 num_8)
		(vqshlb_n_s8_dsl (arm:bind-expr v0 env) (arm:bind-expr v1 env) (arm:bind-expr size_i_o env) 
		 (arm:bind-expr num_3 env) (arm:bind-expr num_4 env) (arm:bind-expr num_5 env) 
		 (arm:bind-expr prec_i_o env) (arm:bind-expr num_7 env) (arm:bind-expr num_8 env))
	]
	[ (vmlal_high_n_s16_dsl v0 v1 v2 size_i_o num_4 num_5 num_6 prec_i_o num_8 num_9 num_10 num_11 num_12 num_13)
		(vmlal_high_n_s16_dsl (arm:bind-expr v0 env) (arm:bind-expr v1 env) (arm:bind-expr v2 env) 
		 (arm:bind-expr size_i_o env) (arm:bind-expr num_4 env) (arm:bind-expr num_5 env) 
		 (arm:bind-expr num_6 env) (arm:bind-expr prec_i_o env) (arm:bind-expr num_8 env) 
		 (arm:bind-expr num_9 env) (arm:bind-expr num_10 env) (arm:bind-expr num_11 env) 
		 (arm:bind-expr num_12 env) (arm:bind-expr num_13 env))
	]
	[v v]
 )
)
;; ================================================================================

