#============================== Hydride File =================================
#
# Part of the Hydride Compiler Infrastructure. 
# <Placeholder for license information> 
#
#=============================================================================
#
# Do NOT modify this file. It is automatically generated. 
#
#=============================================================================




semantcs = {

          "vpmin_u16" : {
            "target_instructions" : {
              "vpmin_u16" : {
                  "args" : ["SYMBOLIC_BV_64","SYMBOLIC_BV_64","64","64","0","64","16","0","0","0","16","16","1","8","0","16","2"],
                  "in_vectsize" : 128,
                  "out_vectsize" : 64,
                  "lanesize" : 64,
                  "in_precision" : 16,
                  "out_precision" : 16,
                  "in_vectsize_index" : 2,
                  "out_vectsize_index" : 2,
                  "lanesize_index" : 3,
                  "in_precision_index" : 15,
                  "out_precision_index" : 6,
                  "arg_permute_map" : [0,1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1],
                  "Signedness" : 0,
                  "Cost" : "None",
                  "SIMD" : "True",
                  "Extensions" : "None",
      },
        
              "vpminq_u16" : {
                  "args" : ["SYMBOLIC_BV_128","SYMBOLIC_BV_128","128","128","0","128","16","0","0","0","16","16","1","8","0","16","2"],
                  "in_vectsize" : 256,
                  "out_vectsize" : 128,
                  "lanesize" : 128,
                  "in_precision" : 16,
                  "out_precision" : 16,
                  "in_vectsize_index" : 2,
                  "out_vectsize_index" : 2,
                  "lanesize_index" : 3,
                  "in_precision_index" : 15,
                  "out_precision_index" : 6,
                  "arg_permute_map" : [0,1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1],
                  "Signedness" : 0,
                  "Cost" : "None",
                  "SIMD" : "True",
                  "Extensions" : "None",
      },
        
              "vpmin_s8" : {
                  "args" : ["SYMBOLIC_BV_64","SYMBOLIC_BV_64","64","64","0","64","8","0","1","1","8","8","1","4","1","8","2"],
                  "in_vectsize" : 128,
                  "out_vectsize" : 64,
                  "lanesize" : 64,
                  "in_precision" : 8,
                  "out_precision" : 8,
                  "in_vectsize_index" : 2,
                  "out_vectsize_index" : 2,
                  "lanesize_index" : 3,
                  "in_precision_index" : 15,
                  "out_precision_index" : 6,
                  "arg_permute_map" : [0,1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1],
                  "Signedness" : 1,
                  "Cost" : "None",
                  "SIMD" : "True",
                  "Extensions" : "None",
      },
        
              "vpminq_u8" : {
                  "args" : ["SYMBOLIC_BV_128","SYMBOLIC_BV_128","128","128","0","128","8","0","0","0","8","8","1","4","0","8","2"],
                  "in_vectsize" : 256,
                  "out_vectsize" : 128,
                  "lanesize" : 128,
                  "in_precision" : 8,
                  "out_precision" : 8,
                  "in_vectsize_index" : 2,
                  "out_vectsize_index" : 2,
                  "lanesize_index" : 3,
                  "in_precision_index" : 15,
                  "out_precision_index" : 6,
                  "arg_permute_map" : [0,1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1],
                  "Signedness" : 0,
                  "Cost" : "None",
                  "SIMD" : "True",
                  "Extensions" : "None",
      },
        
              "vpminq_u32" : {
                  "args" : ["SYMBOLIC_BV_128","SYMBOLIC_BV_128","128","128","0","128","32","0","0","0","32","32","1","16","0","32","2"],
                  "in_vectsize" : 256,
                  "out_vectsize" : 128,
                  "lanesize" : 128,
                  "in_precision" : 32,
                  "out_precision" : 32,
                  "in_vectsize_index" : 2,
                  "out_vectsize_index" : 2,
                  "lanesize_index" : 3,
                  "in_precision_index" : 15,
                  "out_precision_index" : 6,
                  "arg_permute_map" : [0,1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1],
                  "Signedness" : 0,
                  "Cost" : "None",
                  "SIMD" : "True",
                  "Extensions" : "None",
      },
        
              "vpminq_s16" : {
                  "args" : ["SYMBOLIC_BV_128","SYMBOLIC_BV_128","128","128","0","128","16","0","1","1","16","16","1","8","1","16","2"],
                  "in_vectsize" : 256,
                  "out_vectsize" : 128,
                  "lanesize" : 128,
                  "in_precision" : 16,
                  "out_precision" : 16,
                  "in_vectsize_index" : 2,
                  "out_vectsize_index" : 2,
                  "lanesize_index" : 3,
                  "in_precision_index" : 15,
                  "out_precision_index" : 6,
                  "arg_permute_map" : [0,1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1],
                  "Signedness" : 1,
                  "Cost" : "None",
                  "SIMD" : "True",
                  "Extensions" : "None",
      },
        
              "vpminq_s32" : {
                  "args" : ["SYMBOLIC_BV_128","SYMBOLIC_BV_128","128","128","0","128","32","0","1","1","32","32","1","16","1","32","2"],
                  "in_vectsize" : 256,
                  "out_vectsize" : 128,
                  "lanesize" : 128,
                  "in_precision" : 32,
                  "out_precision" : 32,
                  "in_vectsize_index" : 2,
                  "out_vectsize_index" : 2,
                  "lanesize_index" : 3,
                  "in_precision_index" : 15,
                  "out_precision_index" : 6,
                  "arg_permute_map" : [0,1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1],
                  "Signedness" : 1,
                  "Cost" : "None",
                  "SIMD" : "True",
                  "Extensions" : "None",
      },
        
              "vpmin_u32" : {
                  "args" : ["SYMBOLIC_BV_64","SYMBOLIC_BV_64","64","64","0","64","32","0","0","0","32","32","1","16","0","32","2"],
                  "in_vectsize" : 128,
                  "out_vectsize" : 64,
                  "lanesize" : 64,
                  "in_precision" : 32,
                  "out_precision" : 32,
                  "in_vectsize_index" : 2,
                  "out_vectsize_index" : 2,
                  "lanesize_index" : 3,
                  "in_precision_index" : 15,
                  "out_precision_index" : 6,
                  "arg_permute_map" : [0,1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1],
                  "Signedness" : 0,
                  "Cost" : "None",
                  "SIMD" : "True",
                  "Extensions" : "None",
      },
        
              "vpminq_s8" : {
                  "args" : ["SYMBOLIC_BV_128","SYMBOLIC_BV_128","128","128","0","128","8","0","1","1","8","8","1","4","1","8","2"],
                  "in_vectsize" : 256,
                  "out_vectsize" : 128,
                  "lanesize" : 128,
                  "in_precision" : 8,
                  "out_precision" : 8,
                  "in_vectsize_index" : 2,
                  "out_vectsize_index" : 2,
                  "lanesize_index" : 3,
                  "in_precision_index" : 15,
                  "out_precision_index" : 6,
                  "arg_permute_map" : [0,1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1],
                  "Signedness" : 1,
                  "Cost" : "None",
                  "SIMD" : "True",
                  "Extensions" : "None",
      },
        
              "vpmin_s16" : {
                  "args" : ["SYMBOLIC_BV_64","SYMBOLIC_BV_64","64","64","0","64","16","0","1","1","16","16","1","8","1","16","2"],
                  "in_vectsize" : 128,
                  "out_vectsize" : 64,
                  "lanesize" : 64,
                  "in_precision" : 16,
                  "out_precision" : 16,
                  "in_vectsize_index" : 2,
                  "out_vectsize_index" : 2,
                  "lanesize_index" : 3,
                  "in_precision_index" : 15,
                  "out_precision_index" : 6,
                  "arg_permute_map" : [0,1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1],
                  "Signedness" : 1,
                  "Cost" : "None",
                  "SIMD" : "True",
                  "Extensions" : "None",
      },
        
              "vpmin_u8" : {
                  "args" : ["SYMBOLIC_BV_64","SYMBOLIC_BV_64","64","64","0","64","8","0","0","0","8","8","1","4","0","8","2"],
                  "in_vectsize" : 128,
                  "out_vectsize" : 64,
                  "lanesize" : 64,
                  "in_precision" : 8,
                  "out_precision" : 8,
                  "in_vectsize_index" : 2,
                  "out_vectsize_index" : 2,
                  "lanesize_index" : 3,
                  "in_precision_index" : 15,
                  "out_precision_index" : 6,
                  "arg_permute_map" : [0,1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1],
                  "Signedness" : 0,
                  "Cost" : "None",
                  "SIMD" : "True",
                  "Extensions" : "None",
      },
        
              "vpmin_s32" : {
                  "args" : ["SYMBOLIC_BV_64","SYMBOLIC_BV_64","64","64","0","64","32","0","1","1","32","32","1","16","1","32","2"],
                  "in_vectsize" : 128,
                  "out_vectsize" : 64,
                  "lanesize" : 64,
                  "in_precision" : 32,
                  "out_precision" : 32,
                  "in_vectsize_index" : 2,
                  "out_vectsize_index" : 2,
                  "lanesize_index" : 3,
                  "in_precision_index" : 15,
                  "out_precision_index" : 6,
                  "arg_permute_map" : [0,1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1],
                  "Signedness" : 1,
                  "Cost" : "None",
                  "SIMD" : "True",
                  "Extensions" : "None",
      },
        },
            "semantics" : ['"(define (vpmin_u16  a b %vectsize0 %outerlanesize0 %innerlaneoffset0 %innerlanesize0 %elemsize0 %arg0 %arg1 %arg2 %arg3 %arg4 %arg5 %arg6 %arg7 %arg8 %arg9 )"', '"(define %1 (concat b a))"', '"(define result"', '"(apply"', '"concat"', '"(for/list ([%outer.it (reverse (range 0 %vectsize0 %outerlanesize0))])"', '" (apply"', '" concat"', '" (for/list ([e0.new (reverse (range %innerlaneoffset0 %innerlanesize0 %elemsize0))])"', '"  (define %4.new0 (*  e0.new  %arg9))"', '"  (define %lastidx3 (-  %arg8  1))"', '"  (define %8 (+  %4.new0  %lastidx3))"', '"  (define %9 (extract  %8 %4.new0 %1))"', '"  (define %10.ab0 (bvsizeext  %9 192 %arg7))"', '"  (define %11.new0 (/  e0.new  %arg6))"', '"  (define %12 (+  %11.new0  %arg5))"', '"  (define %13 (*  %12  %arg4))"', '"  (define %lastidx2 (-  %arg3  1))"', '"  (define %18 (+  %13  %lastidx2))"', '"  (define %19 (extract  %18 %13 %1))"', '"  (define %20.ab0 (bvsizeext  %19 192 %arg2))"', '"  (define %21.ab0 (bvmin %10.ab0 %20.ab0 %arg1 ))"', '"  (define %lastidx1 (-  %elemsize0  1))"', '"  (define %highidx0 (+  %lastidx1  %arg0))"', '"  (define %28 (extract  %highidx0 %arg0 %21.ab0))"', '"  %28"', '" )"', '" )"', '")"', '")"', '")"', '"result)"', '""'], 
      },
        
          "vpmaxq_u16" : {
            "target_instructions" : {
              "vpmaxq_u16" : {
                  "args" : ["SYMBOLIC_BV_128","SYMBOLIC_BV_128","128","128","0","128","16","0","0","0","16","16","1","8","0","16","2"],
                  "in_vectsize" : 256,
                  "out_vectsize" : 128,
                  "lanesize" : 128,
                  "in_precision" : 16,
                  "out_precision" : 16,
                  "in_vectsize_index" : 2,
                  "out_vectsize_index" : 2,
                  "lanesize_index" : 3,
                  "in_precision_index" : 15,
                  "out_precision_index" : 6,
                  "arg_permute_map" : [0,1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1],
                  "Signedness" : 0,
                  "Cost" : "None",
                  "SIMD" : "True",
                  "Extensions" : "None",
      },
        
              "vpmax_u32" : {
                  "args" : ["SYMBOLIC_BV_64","SYMBOLIC_BV_64","64","64","0","64","32","0","0","0","32","32","1","16","0","32","2"],
                  "in_vectsize" : 128,
                  "out_vectsize" : 64,
                  "lanesize" : 64,
                  "in_precision" : 32,
                  "out_precision" : 32,
                  "in_vectsize_index" : 2,
                  "out_vectsize_index" : 2,
                  "lanesize_index" : 3,
                  "in_precision_index" : 15,
                  "out_precision_index" : 6,
                  "arg_permute_map" : [0,1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1],
                  "Signedness" : 0,
                  "Cost" : "None",
                  "SIMD" : "True",
                  "Extensions" : "None",
      },
        
              "vpmax_s16" : {
                  "args" : ["SYMBOLIC_BV_64","SYMBOLIC_BV_64","64","64","0","64","16","0","1","1","16","16","1","8","1","16","2"],
                  "in_vectsize" : 128,
                  "out_vectsize" : 64,
                  "lanesize" : 64,
                  "in_precision" : 16,
                  "out_precision" : 16,
                  "in_vectsize_index" : 2,
                  "out_vectsize_index" : 2,
                  "lanesize_index" : 3,
                  "in_precision_index" : 15,
                  "out_precision_index" : 6,
                  "arg_permute_map" : [0,1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1],
                  "Signedness" : 1,
                  "Cost" : "None",
                  "SIMD" : "True",
                  "Extensions" : "None",
      },
        
              "vpmaxq_u32" : {
                  "args" : ["SYMBOLIC_BV_128","SYMBOLIC_BV_128","128","128","0","128","32","0","0","0","32","32","1","16","0","32","2"],
                  "in_vectsize" : 256,
                  "out_vectsize" : 128,
                  "lanesize" : 128,
                  "in_precision" : 32,
                  "out_precision" : 32,
                  "in_vectsize_index" : 2,
                  "out_vectsize_index" : 2,
                  "lanesize_index" : 3,
                  "in_precision_index" : 15,
                  "out_precision_index" : 6,
                  "arg_permute_map" : [0,1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1],
                  "Signedness" : 0,
                  "Cost" : "None",
                  "SIMD" : "True",
                  "Extensions" : "None",
      },
        
              "vpmax_s8" : {
                  "args" : ["SYMBOLIC_BV_64","SYMBOLIC_BV_64","64","64","0","64","8","0","1","1","8","8","1","4","1","8","2"],
                  "in_vectsize" : 128,
                  "out_vectsize" : 64,
                  "lanesize" : 64,
                  "in_precision" : 8,
                  "out_precision" : 8,
                  "in_vectsize_index" : 2,
                  "out_vectsize_index" : 2,
                  "lanesize_index" : 3,
                  "in_precision_index" : 15,
                  "out_precision_index" : 6,
                  "arg_permute_map" : [0,1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1],
                  "Signedness" : 1,
                  "Cost" : "None",
                  "SIMD" : "True",
                  "Extensions" : "None",
      },
        
              "vpmaxq_u8" : {
                  "args" : ["SYMBOLIC_BV_128","SYMBOLIC_BV_128","128","128","0","128","8","0","0","0","8","8","1","4","0","8","2"],
                  "in_vectsize" : 256,
                  "out_vectsize" : 128,
                  "lanesize" : 128,
                  "in_precision" : 8,
                  "out_precision" : 8,
                  "in_vectsize_index" : 2,
                  "out_vectsize_index" : 2,
                  "lanesize_index" : 3,
                  "in_precision_index" : 15,
                  "out_precision_index" : 6,
                  "arg_permute_map" : [0,1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1],
                  "Signedness" : 0,
                  "Cost" : "None",
                  "SIMD" : "True",
                  "Extensions" : "None",
      },
        
              "vpmaxq_s32" : {
                  "args" : ["SYMBOLIC_BV_128","SYMBOLIC_BV_128","128","128","0","128","32","0","1","1","32","32","1","16","1","32","2"],
                  "in_vectsize" : 256,
                  "out_vectsize" : 128,
                  "lanesize" : 128,
                  "in_precision" : 32,
                  "out_precision" : 32,
                  "in_vectsize_index" : 2,
                  "out_vectsize_index" : 2,
                  "lanesize_index" : 3,
                  "in_precision_index" : 15,
                  "out_precision_index" : 6,
                  "arg_permute_map" : [0,1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1],
                  "Signedness" : 1,
                  "Cost" : "None",
                  "SIMD" : "True",
                  "Extensions" : "None",
      },
        
              "vpmax_u16" : {
                  "args" : ["SYMBOLIC_BV_64","SYMBOLIC_BV_64","64","64","0","64","16","0","0","0","16","16","1","8","0","16","2"],
                  "in_vectsize" : 128,
                  "out_vectsize" : 64,
                  "lanesize" : 64,
                  "in_precision" : 16,
                  "out_precision" : 16,
                  "in_vectsize_index" : 2,
                  "out_vectsize_index" : 2,
                  "lanesize_index" : 3,
                  "in_precision_index" : 15,
                  "out_precision_index" : 6,
                  "arg_permute_map" : [0,1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1],
                  "Signedness" : 0,
                  "Cost" : "None",
                  "SIMD" : "True",
                  "Extensions" : "None",
      },
        
              "vpmaxq_s8" : {
                  "args" : ["SYMBOLIC_BV_128","SYMBOLIC_BV_128","128","128","0","128","8","0","1","1","8","8","1","4","1","8","2"],
                  "in_vectsize" : 256,
                  "out_vectsize" : 128,
                  "lanesize" : 128,
                  "in_precision" : 8,
                  "out_precision" : 8,
                  "in_vectsize_index" : 2,
                  "out_vectsize_index" : 2,
                  "lanesize_index" : 3,
                  "in_precision_index" : 15,
                  "out_precision_index" : 6,
                  "arg_permute_map" : [0,1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1],
                  "Signedness" : 1,
                  "Cost" : "None",
                  "SIMD" : "True",
                  "Extensions" : "None",
      },
        
              "vpmax_u8" : {
                  "args" : ["SYMBOLIC_BV_64","SYMBOLIC_BV_64","64","64","0","64","8","0","0","0","8","8","1","4","0","8","2"],
                  "in_vectsize" : 128,
                  "out_vectsize" : 64,
                  "lanesize" : 64,
                  "in_precision" : 8,
                  "out_precision" : 8,
                  "in_vectsize_index" : 2,
                  "out_vectsize_index" : 2,
                  "lanesize_index" : 3,
                  "in_precision_index" : 15,
                  "out_precision_index" : 6,
                  "arg_permute_map" : [0,1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1],
                  "Signedness" : 0,
                  "Cost" : "None",
                  "SIMD" : "True",
                  "Extensions" : "None",
      },
        
              "vpmaxq_s16" : {
                  "args" : ["SYMBOLIC_BV_128","SYMBOLIC_BV_128","128","128","0","128","16","0","1","1","16","16","1","8","1","16","2"],
                  "in_vectsize" : 256,
                  "out_vectsize" : 128,
                  "lanesize" : 128,
                  "in_precision" : 16,
                  "out_precision" : 16,
                  "in_vectsize_index" : 2,
                  "out_vectsize_index" : 2,
                  "lanesize_index" : 3,
                  "in_precision_index" : 15,
                  "out_precision_index" : 6,
                  "arg_permute_map" : [0,1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1],
                  "Signedness" : 1,
                  "Cost" : "None",
                  "SIMD" : "True",
                  "Extensions" : "None",
      },
        
              "vpmax_s32" : {
                  "args" : ["SYMBOLIC_BV_64","SYMBOLIC_BV_64","64","64","0","64","32","0","1","1","32","32","1","16","1","32","2"],
                  "in_vectsize" : 128,
                  "out_vectsize" : 64,
                  "lanesize" : 64,
                  "in_precision" : 32,
                  "out_precision" : 32,
                  "in_vectsize_index" : 2,
                  "out_vectsize_index" : 2,
                  "lanesize_index" : 3,
                  "in_precision_index" : 15,
                  "out_precision_index" : 6,
                  "arg_permute_map" : [0,1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1],
                  "Signedness" : 1,
                  "Cost" : "None",
                  "SIMD" : "True",
                  "Extensions" : "None",
      },
        },
            "semantics" : ['"(define (vpmaxq_u16  a b %vectsize0 %outerlanesize0 %innerlaneoffset0 %innerlanesize0 %elemsize0 %arg0 %arg1 %arg2 %arg3 %arg4 %arg5 %arg6 %arg7 %arg8 %arg9 )"', '"(define %1 (concat b a))"', '"(define result"', '"(apply"', '"concat"', '"(for/list ([%outer.it (reverse (range 0 %vectsize0 %outerlanesize0))])"', '" (apply"', '" concat"', '" (for/list ([e0.new (reverse (range %innerlaneoffset0 %innerlanesize0 %elemsize0))])"', '"  (define %4.new0 (*  e0.new  %arg9))"', '"  (define %lastidx3 (-  %arg8  1))"', '"  (define %8 (+  %4.new0  %lastidx3))"', '"  (define %9 (extract  %8 %4.new0 %1))"', '"  (define %10.ab0 (bvsizeext  %9 192 %arg7))"', '"  (define %11.new0 (/  e0.new  %arg6))"', '"  (define %12 (+  %11.new0  %arg5))"', '"  (define %13 (*  %12  %arg4))"', '"  (define %lastidx2 (-  %arg3  1))"', '"  (define %18 (+  %13  %lastidx2))"', '"  (define %19 (extract  %18 %13 %1))"', '"  (define %20.ab0 (bvsizeext  %19 192 %arg2))"', '"  (define %22.ab0 (bvmax %10.ab0 %20.ab0 %arg1 ))"', '"  (define %lastidx1 (-  %elemsize0  1))"', '"  (define %highidx0 (+  %lastidx1  %arg0))"', '"  (define %28 (extract  %highidx0 %arg0 %22.ab0))"', '"  %28"', '" )"', '" )"', '")"', '")"', '")"', '"result)"', '""'], 
      },
        
          "vmaxq_u16" : {
            "target_instructions" : {
              "vmaxq_u16" : {
                  "args" : ["SYMBOLIC_BV_128","SYMBOLIC_BV_128","128","128","0","128","16","0","0","0","0"],
                  "in_vectsize" : 128,
                  "out_vectsize" : 128,
                  "lanesize" : 128,
                  "in_precision" : 16,
                  "out_precision" : 16,
                  "in_vectsize_index" : 2,
                  "out_vectsize_index" : 2,
                  "lanesize_index" : 3,
                  "in_precision_index" : 6,
                  "out_precision_index" : 6,
                  "arg_permute_map" : [0,1,-1,-1,-1,-1,-1,-1,-1,-1,-1],
                  "Signedness" : 0,
                  "Cost" : "None",
                  "SIMD" : "True",
                  "Extensions" : "None",
      },
        
              "vmaxq_s16" : {
                  "args" : ["SYMBOLIC_BV_128","SYMBOLIC_BV_128","128","128","0","128","16","0","1","1","1"],
                  "in_vectsize" : 128,
                  "out_vectsize" : 128,
                  "lanesize" : 128,
                  "in_precision" : 16,
                  "out_precision" : 16,
                  "in_vectsize_index" : 2,
                  "out_vectsize_index" : 2,
                  "lanesize_index" : 3,
                  "in_precision_index" : 6,
                  "out_precision_index" : 6,
                  "arg_permute_map" : [0,1,-1,-1,-1,-1,-1,-1,-1,-1,-1],
                  "Signedness" : 1,
                  "Cost" : "None",
                  "SIMD" : "True",
                  "Extensions" : "None",
      },
        
              "vmax_u32" : {
                  "args" : ["SYMBOLIC_BV_64","SYMBOLIC_BV_64","64","64","0","64","32","0","0","0","0"],
                  "in_vectsize" : 64,
                  "out_vectsize" : 64,
                  "lanesize" : 64,
                  "in_precision" : 32,
                  "out_precision" : 32,
                  "in_vectsize_index" : 2,
                  "out_vectsize_index" : 2,
                  "lanesize_index" : 3,
                  "in_precision_index" : 6,
                  "out_precision_index" : 6,
                  "arg_permute_map" : [0,1,-1,-1,-1,-1,-1,-1,-1,-1,-1],
                  "Signedness" : 0,
                  "Cost" : "None",
                  "SIMD" : "True",
                  "Extensions" : "None",
      },
        
              "vmax_s16" : {
                  "args" : ["SYMBOLIC_BV_64","SYMBOLIC_BV_64","64","64","0","64","16","0","1","1","1"],
                  "in_vectsize" : 64,
                  "out_vectsize" : 64,
                  "lanesize" : 64,
                  "in_precision" : 16,
                  "out_precision" : 16,
                  "in_vectsize_index" : 2,
                  "out_vectsize_index" : 2,
                  "lanesize_index" : 3,
                  "in_precision_index" : 6,
                  "out_precision_index" : 6,
                  "arg_permute_map" : [0,1,-1,-1,-1,-1,-1,-1,-1,-1,-1],
                  "Signedness" : 1,
                  "Cost" : "None",
                  "SIMD" : "True",
                  "Extensions" : "None",
      },
        
              "vmax_u16" : {
                  "args" : ["SYMBOLIC_BV_64","SYMBOLIC_BV_64","64","64","0","64","16","0","0","0","0"],
                  "in_vectsize" : 64,
                  "out_vectsize" : 64,
                  "lanesize" : 64,
                  "in_precision" : 16,
                  "out_precision" : 16,
                  "in_vectsize_index" : 2,
                  "out_vectsize_index" : 2,
                  "lanesize_index" : 3,
                  "in_precision_index" : 6,
                  "out_precision_index" : 6,
                  "arg_permute_map" : [0,1,-1,-1,-1,-1,-1,-1,-1,-1,-1],
                  "Signedness" : 0,
                  "Cost" : "None",
                  "SIMD" : "True",
                  "Extensions" : "None",
      },
        
              "vmax_u8" : {
                  "args" : ["SYMBOLIC_BV_64","SYMBOLIC_BV_64","64","64","0","64","8","0","0","0","0"],
                  "in_vectsize" : 64,
                  "out_vectsize" : 64,
                  "lanesize" : 64,
                  "in_precision" : 8,
                  "out_precision" : 8,
                  "in_vectsize_index" : 2,
                  "out_vectsize_index" : 2,
                  "lanesize_index" : 3,
                  "in_precision_index" : 6,
                  "out_precision_index" : 6,
                  "arg_permute_map" : [0,1,-1,-1,-1,-1,-1,-1,-1,-1,-1],
                  "Signedness" : 0,
                  "Cost" : "None",
                  "SIMD" : "True",
                  "Extensions" : "None",
      },
        
              "vmaxq_u8" : {
                  "args" : ["SYMBOLIC_BV_128","SYMBOLIC_BV_128","128","128","0","128","8","0","0","0","0"],
                  "in_vectsize" : 128,
                  "out_vectsize" : 128,
                  "lanesize" : 128,
                  "in_precision" : 8,
                  "out_precision" : 8,
                  "in_vectsize_index" : 2,
                  "out_vectsize_index" : 2,
                  "lanesize_index" : 3,
                  "in_precision_index" : 6,
                  "out_precision_index" : 6,
                  "arg_permute_map" : [0,1,-1,-1,-1,-1,-1,-1,-1,-1,-1],
                  "Signedness" : 0,
                  "Cost" : "None",
                  "SIMD" : "True",
                  "Extensions" : "None",
      },
        
              "vmaxq_s8" : {
                  "args" : ["SYMBOLIC_BV_128","SYMBOLIC_BV_128","128","128","0","128","8","0","1","1","1"],
                  "in_vectsize" : 128,
                  "out_vectsize" : 128,
                  "lanesize" : 128,
                  "in_precision" : 8,
                  "out_precision" : 8,
                  "in_vectsize_index" : 2,
                  "out_vectsize_index" : 2,
                  "lanesize_index" : 3,
                  "in_precision_index" : 6,
                  "out_precision_index" : 6,
                  "arg_permute_map" : [0,1,-1,-1,-1,-1,-1,-1,-1,-1,-1],
                  "Signedness" : 1,
                  "Cost" : "None",
                  "SIMD" : "True",
                  "Extensions" : "None",
      },
        
              "vmaxq_u32" : {
                  "args" : ["SYMBOLIC_BV_128","SYMBOLIC_BV_128","128","128","0","128","32","0","0","0","0"],
                  "in_vectsize" : 128,
                  "out_vectsize" : 128,
                  "lanesize" : 128,
                  "in_precision" : 32,
                  "out_precision" : 32,
                  "in_vectsize_index" : 2,
                  "out_vectsize_index" : 2,
                  "lanesize_index" : 3,
                  "in_precision_index" : 6,
                  "out_precision_index" : 6,
                  "arg_permute_map" : [0,1,-1,-1,-1,-1,-1,-1,-1,-1,-1],
                  "Signedness" : 0,
                  "Cost" : "None",
                  "SIMD" : "True",
                  "Extensions" : "None",
      },
        
              "vmaxq_s32" : {
                  "args" : ["SYMBOLIC_BV_128","SYMBOLIC_BV_128","128","128","0","128","32","0","1","1","1"],
                  "in_vectsize" : 128,
                  "out_vectsize" : 128,
                  "lanesize" : 128,
                  "in_precision" : 32,
                  "out_precision" : 32,
                  "in_vectsize_index" : 2,
                  "out_vectsize_index" : 2,
                  "lanesize_index" : 3,
                  "in_precision_index" : 6,
                  "out_precision_index" : 6,
                  "arg_permute_map" : [0,1,-1,-1,-1,-1,-1,-1,-1,-1,-1],
                  "Signedness" : 1,
                  "Cost" : "None",
                  "SIMD" : "True",
                  "Extensions" : "None",
      },
        
              "vmax_s32" : {
                  "args" : ["SYMBOLIC_BV_64","SYMBOLIC_BV_64","64","64","0","64","32","0","1","1","1"],
                  "in_vectsize" : 64,
                  "out_vectsize" : 64,
                  "lanesize" : 64,
                  "in_precision" : 32,
                  "out_precision" : 32,
                  "in_vectsize_index" : 2,
                  "out_vectsize_index" : 2,
                  "lanesize_index" : 3,
                  "in_precision_index" : 6,
                  "out_precision_index" : 6,
                  "arg_permute_map" : [0,1,-1,-1,-1,-1,-1,-1,-1,-1,-1],
                  "Signedness" : 1,
                  "Cost" : "None",
                  "SIMD" : "True",
                  "Extensions" : "None",
      },
        
              "vmax_s8" : {
                  "args" : ["SYMBOLIC_BV_64","SYMBOLIC_BV_64","64","64","0","64","8","0","1","1","1"],
                  "in_vectsize" : 64,
                  "out_vectsize" : 64,
                  "lanesize" : 64,
                  "in_precision" : 8,
                  "out_precision" : 8,
                  "in_vectsize_index" : 2,
                  "out_vectsize_index" : 2,
                  "lanesize_index" : 3,
                  "in_precision_index" : 6,
                  "out_precision_index" : 6,
                  "arg_permute_map" : [0,1,-1,-1,-1,-1,-1,-1,-1,-1,-1],
                  "Signedness" : 1,
                  "Cost" : "None",
                  "SIMD" : "True",
                  "Extensions" : "None",
      },
        },
            "semantics" : ['"(define (vmaxq_u16  a b %vectsize0 %outerlanesize0 %innerlaneoffset0 %innerlanesize0 %elemsize0 %arg0 %arg1 %arg2 %arg3 )"', '"(define result"', '"(apply"', '"concat"', '"(for/list ([%outer.it (reverse (range 0 %vectsize0 %outerlanesize0))])"', '" (apply"', '" concat"', '" (for/list ([e0.new (reverse (range %innerlaneoffset0 %innerlanesize0 %elemsize0))])"', '"  (define %lastidx0 (-  %elemsize0  1))"', '"  (define %4 (+  e0.new  %lastidx0))"', '"  (define %5 (extract  %4 e0.new a))"', '"  (define %6.ab0 (bvsizeext  %5 192 %arg3))"', '"  (define %11 (extract  %4 e0.new b))"', '"  (define %12.ab0 (bvsizeext  %11 192 %arg2))"', '"  (define %14.ab0 (bvmax %6.ab0 %12.ab0 %arg1 ))"', '"  (define %lastidx1 (-  %elemsize0  1))"', '"  (define %highidx0 (+  %lastidx1  %arg0))"', '"  (define %20 (extract  %highidx0 %arg0 %14.ab0))"', '"  %20"', '" )"', '" )"', '")"', '")"', '")"', '"result)"', '""'], 
      },
        
          "vminq_s8" : {
            "target_instructions" : {
              "vminq_s8" : {
                  "args" : ["SYMBOLIC_BV_128","SYMBOLIC_BV_128","128","128","0","128","8","0","1","1","1"],
                  "in_vectsize" : 128,
                  "out_vectsize" : 128,
                  "lanesize" : 128,
                  "in_precision" : 8,
                  "out_precision" : 8,
                  "in_vectsize_index" : 2,
                  "out_vectsize_index" : 2,
                  "lanesize_index" : 3,
                  "in_precision_index" : 6,
                  "out_precision_index" : 6,
                  "arg_permute_map" : [0,1,-1,-1,-1,-1,-1,-1,-1,-1,-1],
                  "Signedness" : 1,
                  "Cost" : "None",
                  "SIMD" : "True",
                  "Extensions" : "None",
      },
        
              "vmin_s8" : {
                  "args" : ["SYMBOLIC_BV_64","SYMBOLIC_BV_64","64","64","0","64","8","0","1","1","1"],
                  "in_vectsize" : 64,
                  "out_vectsize" : 64,
                  "lanesize" : 64,
                  "in_precision" : 8,
                  "out_precision" : 8,
                  "in_vectsize_index" : 2,
                  "out_vectsize_index" : 2,
                  "lanesize_index" : 3,
                  "in_precision_index" : 6,
                  "out_precision_index" : 6,
                  "arg_permute_map" : [0,1,-1,-1,-1,-1,-1,-1,-1,-1,-1],
                  "Signedness" : 1,
                  "Cost" : "None",
                  "SIMD" : "True",
                  "Extensions" : "None",
      },
        
              "vmin_u16" : {
                  "args" : ["SYMBOLIC_BV_64","SYMBOLIC_BV_64","64","64","0","64","16","0","0","0","0"],
                  "in_vectsize" : 64,
                  "out_vectsize" : 64,
                  "lanesize" : 64,
                  "in_precision" : 16,
                  "out_precision" : 16,
                  "in_vectsize_index" : 2,
                  "out_vectsize_index" : 2,
                  "lanesize_index" : 3,
                  "in_precision_index" : 6,
                  "out_precision_index" : 6,
                  "arg_permute_map" : [0,1,-1,-1,-1,-1,-1,-1,-1,-1,-1],
                  "Signedness" : 0,
                  "Cost" : "None",
                  "SIMD" : "True",
                  "Extensions" : "None",
      },
        
              "vmin_s32" : {
                  "args" : ["SYMBOLIC_BV_64","SYMBOLIC_BV_64","64","64","0","64","32","0","1","1","1"],
                  "in_vectsize" : 64,
                  "out_vectsize" : 64,
                  "lanesize" : 64,
                  "in_precision" : 32,
                  "out_precision" : 32,
                  "in_vectsize_index" : 2,
                  "out_vectsize_index" : 2,
                  "lanesize_index" : 3,
                  "in_precision_index" : 6,
                  "out_precision_index" : 6,
                  "arg_permute_map" : [0,1,-1,-1,-1,-1,-1,-1,-1,-1,-1],
                  "Signedness" : 1,
                  "Cost" : "None",
                  "SIMD" : "True",
                  "Extensions" : "None",
      },
        
              "vminq_u32" : {
                  "args" : ["SYMBOLIC_BV_128","SYMBOLIC_BV_128","128","128","0","128","32","0","0","0","0"],
                  "in_vectsize" : 128,
                  "out_vectsize" : 128,
                  "lanesize" : 128,
                  "in_precision" : 32,
                  "out_precision" : 32,
                  "in_vectsize_index" : 2,
                  "out_vectsize_index" : 2,
                  "lanesize_index" : 3,
                  "in_precision_index" : 6,
                  "out_precision_index" : 6,
                  "arg_permute_map" : [0,1,-1,-1,-1,-1,-1,-1,-1,-1,-1],
                  "Signedness" : 0,
                  "Cost" : "None",
                  "SIMD" : "True",
                  "Extensions" : "None",
      },
        
              "vminq_u16" : {
                  "args" : ["SYMBOLIC_BV_128","SYMBOLIC_BV_128","128","128","0","128","16","0","0","0","0"],
                  "in_vectsize" : 128,
                  "out_vectsize" : 128,
                  "lanesize" : 128,
                  "in_precision" : 16,
                  "out_precision" : 16,
                  "in_vectsize_index" : 2,
                  "out_vectsize_index" : 2,
                  "lanesize_index" : 3,
                  "in_precision_index" : 6,
                  "out_precision_index" : 6,
                  "arg_permute_map" : [0,1,-1,-1,-1,-1,-1,-1,-1,-1,-1],
                  "Signedness" : 0,
                  "Cost" : "None",
                  "SIMD" : "True",
                  "Extensions" : "None",
      },
        
              "vmin_u32" : {
                  "args" : ["SYMBOLIC_BV_64","SYMBOLIC_BV_64","64","64","0","64","32","0","0","0","0"],
                  "in_vectsize" : 64,
                  "out_vectsize" : 64,
                  "lanesize" : 64,
                  "in_precision" : 32,
                  "out_precision" : 32,
                  "in_vectsize_index" : 2,
                  "out_vectsize_index" : 2,
                  "lanesize_index" : 3,
                  "in_precision_index" : 6,
                  "out_precision_index" : 6,
                  "arg_permute_map" : [0,1,-1,-1,-1,-1,-1,-1,-1,-1,-1],
                  "Signedness" : 0,
                  "Cost" : "None",
                  "SIMD" : "True",
                  "Extensions" : "None",
      },
        
              "vmin_s16" : {
                  "args" : ["SYMBOLIC_BV_64","SYMBOLIC_BV_64","64","64","0","64","16","0","1","1","1"],
                  "in_vectsize" : 64,
                  "out_vectsize" : 64,
                  "lanesize" : 64,
                  "in_precision" : 16,
                  "out_precision" : 16,
                  "in_vectsize_index" : 2,
                  "out_vectsize_index" : 2,
                  "lanesize_index" : 3,
                  "in_precision_index" : 6,
                  "out_precision_index" : 6,
                  "arg_permute_map" : [0,1,-1,-1,-1,-1,-1,-1,-1,-1,-1],
                  "Signedness" : 1,
                  "Cost" : "None",
                  "SIMD" : "True",
                  "Extensions" : "None",
      },
        
              "vminq_s32" : {
                  "args" : ["SYMBOLIC_BV_128","SYMBOLIC_BV_128","128","128","0","128","32","0","1","1","1"],
                  "in_vectsize" : 128,
                  "out_vectsize" : 128,
                  "lanesize" : 128,
                  "in_precision" : 32,
                  "out_precision" : 32,
                  "in_vectsize_index" : 2,
                  "out_vectsize_index" : 2,
                  "lanesize_index" : 3,
                  "in_precision_index" : 6,
                  "out_precision_index" : 6,
                  "arg_permute_map" : [0,1,-1,-1,-1,-1,-1,-1,-1,-1,-1],
                  "Signedness" : 1,
                  "Cost" : "None",
                  "SIMD" : "True",
                  "Extensions" : "None",
      },
        
              "vmin_u8" : {
                  "args" : ["SYMBOLIC_BV_64","SYMBOLIC_BV_64","64","64","0","64","8","0","0","0","0"],
                  "in_vectsize" : 64,
                  "out_vectsize" : 64,
                  "lanesize" : 64,
                  "in_precision" : 8,
                  "out_precision" : 8,
                  "in_vectsize_index" : 2,
                  "out_vectsize_index" : 2,
                  "lanesize_index" : 3,
                  "in_precision_index" : 6,
                  "out_precision_index" : 6,
                  "arg_permute_map" : [0,1,-1,-1,-1,-1,-1,-1,-1,-1,-1],
                  "Signedness" : 0,
                  "Cost" : "None",
                  "SIMD" : "True",
                  "Extensions" : "None",
      },
        
              "vminq_s16" : {
                  "args" : ["SYMBOLIC_BV_128","SYMBOLIC_BV_128","128","128","0","128","16","0","1","1","1"],
                  "in_vectsize" : 128,
                  "out_vectsize" : 128,
                  "lanesize" : 128,
                  "in_precision" : 16,
                  "out_precision" : 16,
                  "in_vectsize_index" : 2,
                  "out_vectsize_index" : 2,
                  "lanesize_index" : 3,
                  "in_precision_index" : 6,
                  "out_precision_index" : 6,
                  "arg_permute_map" : [0,1,-1,-1,-1,-1,-1,-1,-1,-1,-1],
                  "Signedness" : 1,
                  "Cost" : "None",
                  "SIMD" : "True",
                  "Extensions" : "None",
      },
        
              "vminq_u8" : {
                  "args" : ["SYMBOLIC_BV_128","SYMBOLIC_BV_128","128","128","0","128","8","0","0","0","0"],
                  "in_vectsize" : 128,
                  "out_vectsize" : 128,
                  "lanesize" : 128,
                  "in_precision" : 8,
                  "out_precision" : 8,
                  "in_vectsize_index" : 2,
                  "out_vectsize_index" : 2,
                  "lanesize_index" : 3,
                  "in_precision_index" : 6,
                  "out_precision_index" : 6,
                  "arg_permute_map" : [0,1,-1,-1,-1,-1,-1,-1,-1,-1,-1],
                  "Signedness" : 0,
                  "Cost" : "None",
                  "SIMD" : "True",
                  "Extensions" : "None",
      },
        },
            "semantics" : ['"(define (vminq_s8  a b %vectsize0 %outerlanesize0 %innerlaneoffset0 %innerlanesize0 %elemsize0 %arg0 %arg1 %arg2 %arg3 )"', '"(define result"', '"(apply"', '"concat"', '"(for/list ([%outer.it (reverse (range 0 %vectsize0 %outerlanesize0))])"', '" (apply"', '" concat"', '" (for/list ([e0.new (reverse (range %innerlaneoffset0 %innerlanesize0 %elemsize0))])"', '"  (define %lastidx0 (-  %elemsize0  1))"', '"  (define %4 (+  e0.new  %lastidx0))"', '"  (define %5 (extract  %4 e0.new a))"', '"  (define %6.ab0 (bvsizeext  %5 192 %arg3))"', '"  (define %11 (extract  %4 e0.new b))"', '"  (define %12.ab0 (bvsizeext  %11 192 %arg2))"', '"  (define %13.ab0 (bvmin %6.ab0 %12.ab0 %arg1 ))"', '"  (define %lastidx1 (-  %elemsize0  1))"', '"  (define %highidx0 (+  %lastidx1  %arg0))"', '"  (define %20 (extract  %highidx0 %arg0 %13.ab0))"', '"  %20"', '" )"', '" )"', '")"', '")"', '")"', '"result)"', '""'], 
      },
        }
