python3 ../run_synth.py --grammar tensor_grammar_8bit_specialized_shufl2.rkt tensor_8bit.spec -v --iterations 10 --depth 4
#python3 ../run_synth.py --grammar tensor_grammar_8bit_specialized_shufl.rkt tensor_8bit.spec -v --iterations 10 --depth 4
#python3 ../run_synth.py --grammar tensor_grammar_8bit_full2.rkt tensor_8bit.spec -v --iterations 10 --depth 3
#python3 ../run_synth.py --grammar tensor_grammar_8bit_shufl2.rkt tensor_8bit.spec -v --iterations 10 --depth 3
#python3 ../run_synth.py --grammar tensor_grammar_8bit_shufl.rkt tensor_8bit.spec -v --iterations 10 --depth 3
#python3 ../run_synth.py --grammar tensor_grammar_8bit.rkt tensor_8bit.spec -v --iterations 10 --depth 3
#python3 ../run_synth.py --grammar tensor_grammar_8bit_full.rkt tensor_8bit.spec -v --iterations 10 --depth 3
#python3 ../run_synth.py --grammar tensor_grammar_8bit_simd.rkt tensor_8bit.spec -v --iterations 10 --depth 3
#python3 ../run_synth.py --grammar tensor_grammar_8bit_reduce.rkt tensor_8bit.spec -v --iterations 10 --depth 3
#python3 ../run_synth.py --grammar tensor_grammar_32bit.rkt tensor_32bit.spec -v --iterations 10 --depth 3
